### ISSUE TITLE
AIRR and MiAIRR logo...

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#1]
Hi Ahmad,

Not sure if the Minimal Standard group is using GIT issues to track things. Hoping so 8-)

Were you the one who created the MiAIRR logo - I love using the receptor graphic in the acronym... Awesome...

I have just one suggestion. Should we use the receptor graphic as the "big I" in AIRR rather than the "little i"  MiAIRR??? I think that would be a VERY cool logo for AIRR in general!

Brian

**Comment by ahmadchan** [comment]
Hi Brian,

Thanks for your feedback. I changed the logo  as per your suggestion https://github.com/airr-community/airr-standards/commit/fa5e3b7260c3f2054c7f591691e58943932c5341#diff-ad1bf83151c04083a9e94acdc3954e3e 

However, most of the people (in today's call) liked this one https://github.com/airr-community/airr-standards/blob/master/Images/miairr.png. 

Thanks

**Comment by bcorrie** [comment]
I can see why - it looks like it says MYAIRR as well as MiAIRR 8-)

It makes sense to use your original for the MiAIRR logo...

It might make sense to use the second version, without the "Mi" as the 
general AIRR logo...

Brian

**Comment by BusseChristian** [comment]
I think this should be a decision by the whole group. Otherwise I share some of the concerns raised in the last call in regards to "T vs. B" and spelling.

**Comment by ahmadchan** [comment]
@BusseChristian  here is the link of MiAIRR eps format logo 

https://github.com/airr-community/airr-standards/blob/master/Images/miairr_logo.eps

**Comment by BusseChristian** [comment]
Thanks!

**Comment by BusseChristian** [comment]
Hy @ahmadchan

Sorry, I just realized that the EPS only contains the picture as bitmap, not as vector graphic. What is the original format you have the logo in?

**Comment by BusseChristian** [comment]
Original file is a bitmap, no vectorized version available. Removed EPS and SVG in commit 9fb397b2be9b0e9d35c3f9868fe2de7443650ed7.

**Comment by bcorrie** [comment]
Hi Christian,

I have Adobe Illustrator originals for the iReceptor/AIRR logo 8-) The nice "receptor" graphic is embeded with iReceptor in various ways, but with the Illustrator file I am sure you can extract it...

I can provide them to you if you like, but we need to resolve the who is using what logo issue.

Brian
