### ISSUE TITLE
"ng_template" field name contains unit

### ISSUE THREAD

**Issue by BusseChristian** [airr-community/airr-standards#10]
The field name `ng_template`, which refers to the `Template amount` item (line 58), contains a unit in its name (ng). I consider this a bad practice, as the unit should be part of the data/value, not of the key.

**Comment by schristley** [comment]
How about `template_amount` field name?

**Comment by BusseChristian** [comment]
Ok, done (commit [a475816](https://github.com/airr-community/airr-standards/commit/a475816f76953d654c45043696bb618fe8d66205)).
