### ISSUE TITLE
Convert examples into proper test framework for python library.

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#100]
There was mention of a few python unit testing frameworks. We should create a skeleton with one so can start adding tests.

**Comment by javh** [comment]
I'm partial to vanilla `unittest.TestCase` tests because they render pretty in PyCharm.

**Comment by schristley** [comment]
I'm not gonna be able to do this before the release. If you want to take a stab at it @javh that's cool, but I think its okay to have this for the next release.

**Comment by javh** [comment]
@schristley, gotcha. I'm unlikely to have time as well. So unless anyone volunteers for this in the next couple of days, then I say we bump it to the next release.

**Comment by javh** [comment]
Skeleton added in #112 with not intention of finishing before release.

**Comment by schristley** [comment]
We have a unit test framework now
