### ISSUE TITLE
R API Package Tasks

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#101]
Dropped the beginnings of the R package into the `R-package` branch.  This is just a brainstorming and task list issue for myself, @ssnn-airr, and any who wants to contribute. :)

TODO:

- [x] Unit tests. Use `testthat`.
- [x] Simple vignette. Use `rmarkdown` and `knitr`. (#120)
- [x] Build API doc. I plan to use [markr](https://bitbucket.org/javh/markr). Need to see if the markdown import into sphinx is sufficient or if I need to add rst conversion to `markr`.
- [x] Document the package build process. Building the package and rebuilding the docs.
- [x] read/write functions probably need more validation checks.
- [x] make sure "roundtrip" of booleans behaves well. Ie, "T", "TRUE", to TRUE and back again.

**Comment by javh** [comment]
Merged into master in #102.  Gonna leave the `R-package` branch in place for a bit though as a working branch.

**Comment by ssnn-airr** [comment]
Related to #96 . Should we use 'required' instead of 'mandatory' for consistency here? https://github.com/airr-community/airr-standards/blob/2694efdca44525221ade0f569a0d36d07176c45f/lang/R/R/Schema.R#L22-L39

**Comment by javh** [comment]
Probably. This is how it was in the python package, so I kept the naming consistent. However, I think the python name was from an old structure and we could probably change it to `required` as well.

@schristley and @laserson, any insight on `mandatory` vs `required`?

**Comment by schristley** [comment]
`mandatory` was from the old original spec before we moved to OpenAPI. The OpenAPI keyword is `required`.

**Comment by javh** [comment]
Okay, let's change it then. I'll fix the python package and docs.

**Comment by ssnn-airr** [comment]
required it is

**Comment by javh** [comment]
I attempted to plug the markr output directly into the existing docs using recommonmark. It didn't go well.  I'm going to have to add a sphinx compatible implementation to markr. Which will be time consuming.

I think all we really have is docs and unit tests though, aside from making sure the small bit of validation code in there is okay. @ssnn-airr, are you okay with focusing on the unit tests and the vignette? And I'll deal with the sphinx docs?

**Comment by ssnn-airr** [comment]
Yes, very ok.

**Comment by javh** [comment]
R library docs are up.

**Comment by javh** [comment]
Last bit is done in #128.
