### ISSUE TITLE
Whole vs. partial sequences is ambiguous

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#11]
The "Whole vs. partial sequences" is typed as a boolean but it is ambiguous what a "YES" or "NO" signifies. Either the field can be changed to be a question, like "Whole sequences?", but then may be confusing what "not whole" means. Better maybe to make it a controlled vocabulary string (whole|partial).

**Comment by ahmadchan** [comment]
I agree, its bit ambiguous. We can even introduce "whole" and "partial" as controlled vocablaries. In this way the field name will go as. "Sequence Type"

**Comment by BusseChristian** [comment]
We need a clear definition what a "complete" sequence is. A paired-end read that overlaps? Amplicons that contains FR1-to-J?

**Comment by frubelt** [comment]
Agree
Sequence spanning the entire FR1-to-J region. 

It doesn't have to be paired end if the read length is long enough. Not even a amplicon if is e.g. directly sequencing the mRNA (or gDNA).

**Comment by BusseChristian** [comment]
Ok, agreed. So let's do some nit-picking:
To be considered "complete", a sequence MUST
1. include the first V segment codon that encodes the mature polypeptide chain (i.e. _after_ the leader sequence)
2. include the last complete codon of the J segment (i.e. 1 bp 5' of the J->C splice site).
3. provide sequence information for all positions between 1) and 2).

Open points: What if the sequence of 1. and 2. is primer templated?

**Comment by frubelt** [comment]
Sounds good! I would accept the primer at this point, even this is not perfect. Exclude this regions as primer template is maybe to to much to ask for now.   ?

**Comment by BusseChristian** [comment]
Well, that's what we got `forward_PCR_primer_target_location` and `reverse_PCR_primer_target_location` for 😃 So people can clip if they wanted to.

**Comment by skleinstein** [comment]
I would not accept as full length if primer is in the V and/or J. Can't
trust the SHM patterns in this case, or any potential SNPs. We usually
exclude such regions from the analysis. Other than that, I like the 3 point
definition.

-Steve...

**Comment by BusseChristian** [comment]
For people coming from the cloning side, "complete" usually implies 1.-3., but they often do not care about the templated regions (which do not carry a lot of SHM in the end). But I understand that for some analysis types it will be important to know this status. So should we stay with 1.-3. but make this an enumerated field (instead of boolean): `no`, `yes, templated`, `yes, untemplated`?

**Comment by BusseChristian** [comment]
Fixed in commit [4a67875](https://github.com/airr-community/airr-standards/commit/4a67875299ac2e946be7a2cafcc01b514b39cf11).
