### ISSUE TITLE
How to indicate xenografted or transgenic animals

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#137]
MiAIRR currently assumes that all entries in a record pertain to the same `species`, which is defined in data set 1. As `species` will be `required` (#96) and restricted by a species taxonomy (most likely NCBITAXON, #97) we need a mechanism to describe subjects that cannot be clearly assigned to a single species. Two examples of such a subject would be:

* Animals containing complete human immunoglobulin loci as transgenes. Note that it is not possible to unambiguously infer the species from `target_locus` as the gene symbol does often not contain this information. Therefore the sequence information could be wrongly interpreted as host sequences.

* Chimeric animals that have been grafted with human bone marrow (and potentially other tissues). Here also additional fields like `cell_subset` would be affected.

One solution would be to introduce a "species prefix" for the fields involved. However, as this changes MiAIRR, it a slightly bigger decision.

**Comment by bussec** [comment]
Re-opening as PR #260 was not merged.

**Comment by scharch** [comment]
I believe this is done

**Comment by scharch** [comment]
Nope, #614 was never merged...
