### ISSUE TITLE
Test Windows output of python reference library

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#138]
Need to verify the output of the python reference library looks correct in Windows, because of funny interactions between the universal newline modifications that `open()` and `csv.DictWriter()` do independently. If there's a blank line between rows, then just adding `lineterminator='\n'` to the `csv.DictWriter()` init should be sufficient. I think.

**Comment by schristley** [comment]
What about using the `U` flag to open? https://docs.python.org/3/library/functions.html#open

**Comment by javh** [comment]
Naw, if we have the problem, then adding `U` won't help. `U` is deprecated and default. 

It has to do with the csv writer adding it's own line endings based of `os.linesep`. On Windows, `csv` it'll append `\r\n` to the end of line, but then `open` will try to be clever and replace `\n` with `\r\n` as well, making the EOL `\r\r\n` (Mac EOL + Windows EOL).

**Comment by javh** [comment]
Seems fine on Win10 with the `lineterminator='\n'` change.
