### ISSUE TITLE
Potential additions to the Rearrangement spec

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#139]
From feedback on the manuscript, here are some additional fields to discuss for the next release of the Rearrangement schema:

- [ ] 1. A way to record the species of the V, J , D segments.
- [ ] 2. Clarity on if they using a global vs local alignments.
- [ ] 3. A place to enter the numbering scheme you are using. (It seems to assume IMGT, but doesn’t require it.)
- [ ] 4. The Deletion count in nucleotides from the V 3’, 5’ and 3’ D, and 5’J. (Although this could be in the Cigar string if you did a global alignment rather than a local alignment.)
- [ ] 5. An annotation for the Leader Sequence.
- [ ] 6. A way to annotate V-gene Conversion
- [x] 7. A way to annotate D-D recombination.

**Comment by bussec** [comment]
@javh, my two cents on this:

- (1) Is this related to #137 or do you just need a `species` field that is independent of the MiAIRR record?
- (7) We currently have neither a MiAIRR nor an GenBank specification on for this. I assume this should be included there as well. Will this be restricted to any of the three possible loci (_IGH_, _TRB_, _TRD_)?

**Comment by javh** [comment]
Sorry, these were copy-paste from an email conversation to make sure we discuss them. I neglected some details and my personal opinions.

1. Yes, I think this relates directly to #137. I think for the vast majority of use cases the existing MiAIRR `species` tag in the metadata should suffice, combined with the flexibility in gene call nomenclature. Ie, just not restricting people from using gene names like "Homo sapiens IGHV1-69*01".
2. I don't think we need to mandate this. Most aligners do semi-global, and some of the coordinate fields don't make a lot of sense outside that context, but they are optional. This is something we can just add to the technical metadata, such as the numbering scheme, software versions, alignment tool, etc.
3. I'm inclined to make it a *required* metadata field.
4. These can already be derived from `*_germline_start`, `*_germline_end` or the CIGAR strings if they include the tail `N` operators. However, that's all optional and this information is biological, so I think some optional fields similar to the N/P fields would be good additions. Eg, `v3_deletion`, etc.
5. This is encompassed be the V segment data, but I think there's good reasons to add optional leader fields to analyze them separately. We'll just need some more fields that start with `L` or `U` - I prefer `U` just because lowercase `L` is hard to distinguish from other characters.
6. I don't have enough experience with such data to know now to implement this, but I think we should do it. We need some example use cases.
7. Well, hopefully the implementation is flexible enough that it doesn't need to be restricted. I assume *IGH*, *TRB* and *TRD* are the only cases where it would pop up, but we don't want to force people to put light chains and heavy chains in separate files. The IMGT/HighV-QUEST is the only aligner, that I'm aware of, that supports this, but I think the output is a a bit cumbersome.

**Comment by schristley** [comment]
Epitope fields. This was brought up a awhile ago but wasn't followed through on.

**Comment by bussec** [comment]
With the addition of the various `d2_*` fields to the `Rearrangement` object, we can tick of (7).

**Comment by javh** [comment]
Much of this hasn't made it into the schema, but if it hasn't been asked for in 3 years, I'm guess it isn't needed. Closing.
