### ISSUE TITLE
Mapping to BioSample attributes still incomplete

### ISSUE THREAD

**Issue by BusseChristian** [airr-community/airr-standards#14]
Updated the ODS table in the devel branch [[here](https://github.com/airr-community/airr-standards/commit/0fae4f795566bc6fce85583a6aafc482600c676e)]. We are still lacking a full and non-ambiguous 1:1 mapping between the MiAIRR items, the NCBI-defined attributes and the AIRR-custom keywords in the submission templates.

**Comment by ahmadchan** [comment]
Can you please  change the format of this file? I can not open it on my MAC. CSV or XLS would be fine.

**Comment by BusseChristian** [comment]
ODS is LibreOffice spreadsheet format.
Converted to XLS.

**Comment by ahmadchan** [comment]
@BusseChristian I have added the available NCBI BP and BS mapping into the table. You can pull that to the branch

**Comment by ahmadchan** [comment]
@BusseChristian  Can you please check it now?

**Comment by BusseChristian** [comment]
Got it. I now update the field names from the current MiAIRR template and tried to assign your mappings accordingly. However, there were several element that I could not map, which I now put into a separate column. Could you please have a look again?

**Comment by ahmadchan** [comment]
However, there were several element that I could not map, which I now put into a separate column. Could you please have a look again?
@BusseChristian 
-In which column and file? BioSample integeration?

**Comment by BusseChristian** [comment]
File: MiAIRR-Elements_NCBI_mapping.xls

Columns L-M contain the current keywords/attributes from the NCBI BioSample documentation, the AIRR_BioSample template and the respective comments. Everything that is not green still needs some kind of fixing. Red lines do not yet have a valid mapping.

All the keywords you entered in the last iteration for which I could not find an identical correlate were moved to column H.

The SRA integration looks pretty good, so lets focus on BioSample right now.

**Comment by ahmadchan** [comment]
I tried to map the remaining elements and annotated the fields with "review and approve if done ".  We probably need a short meeting to look over the mapping file, finalize and update the templates.

**Comment by BusseChristian** [comment]
Added MiAIRR-to-BioSample table in commit 512ba4b0a622bc65a65d0f6cb4801eeead5f46cd.
