### ISSUE TITLE
Remove "Minimal Standards" team

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#140]
We currently have a `Minimal Standards` Github team which - in terms of members - is a subset of the `Standards` team. I could not find any special privileges to any of the five repos that would be granted to the team members (@laserson, @ahmadchan, @schristley, @frubelt and myself), which would not also be granted via the `Standards` team. Thus I consider it to be a remnant of the repo merger.

Does anyone have any objections against removing this team?

**Comment by schristley** [comment]
No objection. I had the same thought awhile ago but didn't follow through.

**Comment by bussec** [comment]
Done.
