### ISSUE TITLE
indicating release dates to NCBI in CEDAR metadata

### ISSUE THREAD

**Issue by graybeal** [airr-community/airr-standards#143]
In the CEDAR template there is only one field to indicate "Expected Release Date", and it has no impact on whether the submission is made public or not. I'm not sure what its purpose is (any thoughts?).

There are 2-3 different submission types created by the template: BioProject (if it doesn't already exist); BioSample; and SRA. The latter 2 can each have multiple instances. 

NCBI interpretation of release dates is complicated; they release 'parent' items like BioProject if the (any!) BioSample or SRA submission is released.

For simplicity we propose a optional single release date for the whole CEDAR collection, which may include any number of BioSample or SRA submissions. The release date field would be at the top of the template. 

Is this agreeable? 

If not, we could add release dates to each section, but we would not add code to check that no unexpected consequence will ensue. (We can document the understood behavior in the help text for each release date though.

**Comment by bussec** [comment]
Yes, I agree this is the best solution as the outcome of setting the release date will be obvious to everyone.

**Comment by graybeal** [comment]
OK, we will implement it as I proposed. I believe (based on testing) we can just change add that field to the current template and the (two or three) existing in-progress instances will pick up the changes gracefully.

We also will change the documentation of the existing Expected Release Data attribute in the BioSample part to make clear that is not used for setting any of the release dates in NCBI.
