### ISSUE TITLE
Info object in airr-schema.yaml?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#147]
I'm thinking of adding a simple Info object into the yaml file that has a description, version, URL, etc. Essentially stuff that was in the [original schema](https://github.com/airr-community/airr-formats/blob/master/specs/rearrangements.yaml) from long ago.

I realize this becomes another version and etc. to maintain but I think it might be useful for tools that use the schema but don't use a reference library (or can access the underlying git info)

**Comment by javh** [comment]
Seems like a good idea, though it'll be tricky to maintain between versions. Ie, when the schema has been changed but the repo hasn't been tagged, then the version label in the file will be "behind" unless we do some sort of devel version marker. We use x.y.z.999 version numbers for this, but updating this is easily forgotten. Might be something we could enforce through Travis though? Or some way to do this with versioneer?

**Comment by schristley** [comment]
I'm thinking the version would only be for the schema and not for software, so just X.Y. When a PR changes the schema, it updates to X.Y+1. You are right though that the URL needs to point to a repo tag which doesn't exist yet. I suppose it could point to master and then be changed with the release, or maybe leave the URL blank.

**Comment by schristley** [comment]
Versioneer gives a git commit version with commits beyond a repo tag, so asking the python library for its version is gonna give something akin to your x.y.z.999. Not the end of the world if the (in development) library gives a version different from the schema, I suppose here at least you can ask the schema directly for its version separate from the software.
