### ISSUE TITLE
MiAIRR Cell Subset field - request additional option

### ISSUE THREAD

**Issue by ahmadchan** [airr-community/airr-standards#152]
I am helping a person from the NCBI to submit AIRR compliant data and he reported the following issue to me through email.

> Hi Ahmed,
> 
> I’m trying to use the web-based MiAIRR metadata tool to get my data prepped for repository submission. It was going ok but I ran into an issue with the Cell Subset field under Processing. There’s an option called B cell, which I could use, but it doesn’t really differentiate my samples as they are all B cells, just different types (Naïve, memory, GC, etc). The field won’t accept anything typed in (eg. Naïve B cell) that is not part of the drop down list. I type it in, hit OK, but whatever I just typed disappears. It seems from the help I could type in whatever I wanted, but wanted to check with you.
> 
> Thanks for your help,
> 

I reported this issue to the CEDAR team https://github.com/metadatacenter/cedar-project/issues/870. They suggested I should I also discuss this issue to AIRR standards team as well. Following is the CEDAR team reply

> Per John:
> 
> We'll have to check what help suggests this, as the suggestion is incorrect. For controlled terms, users may only choose from among the options defined by the template.
> 
> You may want to refer this ticket to the metadata working group, since they can recommend a change to the selected terms.

Any thoughts?

**Comment by lgcowell** [comment]
Does CEDAR not allow selection from Cell ontology subtypes of lymphocyte?

— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by ahmadchan** [comment]
Its using the cell ontology. I found naive T cell but not Naive B cell in the drop down.

**Comment by schristley** [comment]
The [purl](http://purl.obolibrary.org/obo/CL_0000788) is slow to load or gets an error.

**Comment by bussec** [comment]
I just had a look again at CL and as @schristley already pointed out, [`B cell`](http://purl.obolibrary.org/obo/CL_0000236) exists in CL as node for several common subpopulations. Therefore this issue is not MiAIRR related.
Further note that the respective issue [870](https://github.com/metadatacenter/cedar-project/issues/870) at CEDAR has been closed, too.
