### ISSUE TITLE
integrate miairr.yaml with reference libraries

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#158]
The `miairr.yaml` file provides a number of MiAIRR-specific attributes that we decided to put in a separate file instead of as custom attributes in `airr-schema.yaml`. The reference libraries should load up `miairr.yaml` and have the attributes linked to the appropriate data elements as well as be made available to tools.

**Comment by schristley** [comment]
We might also consider re-visiting the idea of having these attributes in a separate file. If we finalize the study metadata schema and format, we might want to put these back into `airr-schema.yaml` as custom attributes on the fields.

**Comment by javh** [comment]
Discussed in #29. I'm cool with adding custom tags instead of having a separate yaml, but I'm also okay with two files.  The task of auto-generating the old TSV from the two yaml files is still open, but probably best to wait on that until we have a decision on how to format this information.

**Comment by javh** [comment]
The consensus opinion from the conference call is to merge the two files.

**Comment by schristley** [comment]
Basic integration is done.
