### ISSUE TITLE
Question around "Study Type" and study_description

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#163]
Again, some feedback from the iReceptor folk (Emily and myself)...

One comment is that the tag study_description doesn't align too well with the actual use of the field, as it is really a "study_type" or "study_design". This is a bit confusing...

From Emily:

"Currently MiAIRR has a semi-controlled vocabulary for this field, as do we. We treat this field as a simplistic "Cancer study" or "Healthy baseline study" entry point to explicitly state the general study type. [Others treat] it as a study description and detailed their entry further. Do we want a more detailed field on top of study_description? More detail holds merit."

When we say "others" above, when we are importing data from other research groups and ask them for the MiAIRR information, when they respond based on the tag name (which we provide in a spreadsheet for computational purposes) leads them to entering a lengthy description. This points to the confusion around the naming and also points out the benefit of having both.

Wondering if it might make sense to have a "study_design" field basically defined as "study_description" is defined now and then add a "study_description" field that is free text and is a more detailed description of the study from the research group???

@schristley I think VDJServer has a long text description of the study in "study_description", as this is what the MiAIRR YAML spec (v0.1.0) had when we froze this version of the API. This is also what we have received back on occasion in our MiAIRR metadata spreadsheet that we send out to people to fill in...

Brian

**Comment by schristley** [comment]
@bcorrie The `study_description` that we have in VDJServer is a long text description, generally the abstract for the publication. I think that field is VDJServer specific though, MiAIRR actually has a `study_type` field which is a controlled vocabulary term similar to what you mention but MiAIRR doesn't have a field for the long text description. I agree that `study_description` is useful but I'm not sure if it's "mandatory" from a minimal information perspective. That's something I suppose the MSWG can discuss.

**Comment by schristley** [comment]
@bcorrie my mistake, you are right that the MiAIRR field is called `study_description`, I got confused with the name which is "Study type". So I agree with you, `study_description` is probably not the best field name, `study_type` would be better, which leads to your question about whether a long text description for the study should be added to MiAIRR.

**Comment by bcorrie** [comment]
Doing an old issue check... 

Summary for this: MiAIRR "Study Type" (study_description) is a controlled vocabulary term that says "{"ontology": "NCIT", "top_node": "Study Design", "draft": true} with a description of "Generic study design" and an example of "Case-Control Study"

I think the question @schristley raised above is whether MiAIRR should:

1. Have a better field name (should study_description be study_type)?
2. Should MiAIRR have a more general "Study Description" field?

If we aren't going to change anything here, should we close this issue?

**Comment by bussec** [comment]
I cannot recall exactly why MiniStd decided against an more extensive free text description, but most likely we considered the combination of title, type and inclusion/exclusion criteria to be sufficient.

In general, I would be in favor of renaming the current `study_description` key to `study_type` as this would align well with the MiAIRR field name and the use of a controlled vocabulary to restrict potential values.

In addition, `study_description` could be added as new key. We would have to discuss whether ithis would still be considered "minimal information", though.

**Comment by schristley** [comment]
> In general, I would be in favor of renaming the current study_description key to study_type as this would align well with the MiAIRR field name and the use of a controlled vocabulary to restrict potential values.

I'm in favor of this renaming.

> In addition, study_description could be added as new key. We would have to discuss whether ithis would still be considered "minimal information", though.

I don't think its "minimal information". I've been copy/pasting the paper abstract to put in this field, as from a UI perspective it is nice to have a long description like that for users to read.

My recommendation is that we add the `study_description` fields, but mark it non-MIAIRR. This will reserve the name so repositories and however can utilize, but it doesn't seem mandatory for a MIAIRR submission.

**Comment by schristley** [comment]
@bcorrie @bussec I've committed a [change](https://github.com/airr-community/airr-standards/pull/182/commits/f0ef84a1cfcb4ad2045f67e48b3e3416f6d312bb) for this

**Comment by bussec** [comment]
Looks good, thanks!
