### ISSUE TITLE
Paired rearrangements and cell_id

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#165]
I think this is probably a quick answer, but I wanted to confirm. My understanding is that if you have a paired sequence the correct way in the DataRep schema is to have them have the same cell_id. Then to get both chains of a paired rearrangment you would search for rearrangements that had the same cell_id?

Is that correct?

We have a question from a user about paired TCR data. We currently don't have any paired TCR data in the iReceptor repository, but supposing we did, what would be the correct way to represent that at the rearrangement level.

Brian

**Comment by schristley** [comment]
Yes, that's correct. Note that cell_id is assigned by the user, so there is no guarantee of it being globally unique. You need repertoire_id and (possibly) rearrangement_set_id as additional keys to constrain the match.

**Comment by bcorrie** [comment]
Great, thanks - closing this...

**Comment by bussec** [comment]
With the wisdom of hindsight: See #169 and #206 => Use of `cell_id` to annotate chain linkage has been **deprecated**, instead an additional `paired_id` field was introduced (as single cell and chain pairing are not always associated).

**Comment by bussec** [comment]
With even more hindsight: Chain linkage on the level of a cell vs. on the level of a receptor has turned out to be different things, that should be handled accordingly. For a current proposal see https://github.com/airr-community/airr-standards/issues/273#issuecomment-568649516
