### ISSUE TITLE
Using validate method on RearrangementReader

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#166]
I am using the RearrangementReader class as follows:

       airr_data = airr.read_rearrangement(file_handle)
       if airr_data.validate():
                print("File", path, "is a valid AIRR TSV file")

When I do this with a TSV file generated with igblast's AIRR TSV generation, I get a set of messages that says: 

Warning: productive is not boolean for row # 1.
Warning: productive is not boolean for row # 1.
Warning: productive is not boolean for row # 1.
Warning: productive is not boolean for row # 1.
Warning: productive is not boolean for row # 1.
Warning: productive is not boolean for row # 1.

Indeed, the TSV file has no data for the productive field, so the warning is valid... The data is not boolean, it is empty. This implies I think that igblast is generating invalid AIRR TSV for this field, but that is not my main concern here...

I have two questions:

1) It seems like the row number in this message is incorrect, as I suspect there is the same error for each row in the file...
2) I would like to turn off the warnings in this case, as really all I care about is that the data is valid and I can live without the warnings. It seems like the default for the class is to be quiet, but I can't seem to stop this message from being printed and I don't see where in the code the error message is being generated...

Thoughts? 

Brian

**Comment by ssnn-airr** [comment]
Yes, I think `row_num = 1` inside `def validate(self)`, in `io.py`, doesn't get increased.
I am  going to check what the R package does in the same situation.

**Comment by bcorrie** [comment]
I used the pip install method, and it appears that I am an early adopter. My AIRR python version is 1.1.0 8-)

Let me upgrade and check if that fixes the problem...

**Comment by javh** [comment]
I was just about the mention that. :)

1. `airr.read_rearrangement` now takes a filename (string) instead of a file handle.
2. `io.RearrangementReader` doesn't have a validate method anymore in favor of the `validate=True` argument to `__init__`

We made a bunch of other changes to validation to address #142.  I'd check through the end of that issue for details on how the behavior differs.

**Comment by bcorrie** [comment]
Changed code to 1.2.1 - now working after updating my code to use new version...
