### ISSUE TITLE
validate_rearrangement bug/feature

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#168]
Testing some edge cases in our AIRR TSV repository loading code, and therefore the python AIRR TSV processing code (1.2.1), and I noticed what I think I would call a bug... When passed an empty file, the method crashes with the error below. Note that with a file with text in it (even if just a single " " character) or with a single column name (e.g. v_call) the method returns False. I would think that the method should probably return False with an empty file as well???  Looks like the CSV reader treats an empty file differently than a file with no column headers.

I know its an edge case, but thought I would raise it...

  File "/home/ubuntu/bcorrie/dataloading-mongo/scripts/airr_tsv.py", line 60, in processAIRRTSVFile
    if airr.validate_rearrangement(path):
  File "/opt/ireceptor/data/lib/python3.5/site-packages/airr/interface.py", line 175, in validate_rearrangement
    iter(reader)
  File "/opt/ireceptor/data/lib/python3.5/site-packages/airr/io.py", line 77, in __iter__
    self.schema.validate_header(self.dict_reader.fieldnames)
  File "/opt/ireceptor/data/lib/python3.5/site-packages/airr/schema.py", line 242, in validate_header
    missing_fields = [f for f in self.required if f not in header]
  File "/opt/ireceptor/data/lib/python3.5/site-packages/airr/schema.py", line 242, in <listcomp>
    missing_fields = [f for f in self.required if f not in header]
TypeError: argument of type 'NoneType' is not iterable

**Comment by javh** [comment]
I pushed the fix to master. Can you check that it's resolved?

**Comment by bcorrie** [comment]
Hi Jason,
We use the AIRR TSV library within a docker container, pulling from pypi. So we are using version 1.2.1 in all of our environments. It is non trivial for me to test outside of that... I suspect the change is a pretty minor one so if you test it locally I trust that it is fixed 8-)

The test case that I have is:

touch foo
Read in foo with the library... This crashes on 1.2.1 with the above error. If that passes, then I think you can close this issue.

**Comment by javh** [comment]
Okay, seems fine then:

```
$ touch foo.tsv
$ python3
>>> import airr
>>> foo = airr.read_rearrangement("foo.tsv", validate=True)
>>> for x in foo: print(x)
... 
Traceback (most recent call last):
    raise ValidationError('missing header')
airr.schema.ValidationError: missing header
```
