### ISSUE TITLE
Heavy and light chain at the metadata level?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#169]
Hello All,
I believe we have a mechanism for pairing heavy and light chain at the rearrangement level, this is the cell_id field. If two rearrangements with a repertoire are a paired heavy and light chain they should have the same cell_id (correct me if I am wrong).

My questions is more at the metadata/repertoire level. We have use cases where people are only interested in studies that have paired heavy/light chains (or alpha/beta). Is there a place in MiAIRR where it is noted whether or not a repertoire has this feature? It appears that the closest thing I can find is:

3 / process (nucl. acid)	Physical linkage of different loci	string	Controlled vocabulary	Describes the mode of linkage if a method was used which physically links nucleic acids derived from distinct loci in a single-cell context	IGH-IGK/IGL-head/head	physical_linkage

If this is the case, what would one expect to find in this value for the cases where:
1) There are no paired heavy/light chain data
2) There is paired data in the repertoire and it is paired (I am not sure I understand the meaning of the example given "IGH-IGK/IGL-head/head"

**Comment by bussec** [comment]
The keyword you are looking for is `single_cell`, which is a Boolean indicating whether single-cell compartmentalization has been performed. I agree that the current description should be clarified, as you could interpret it as only applying to flow cytometry (FC)-based isolation. The information that this field IMO should encode is the (at least temporary) existence of a single-cell context, which is a prerequisite for chain pairing.

The `physical_linkage` field you are referring to is for a subset of `single_cell`=`TRUE` techniques, which assemble the transcripts of both chains into a single DNA molecule, before breaking the the single-cell context again. However, neither classical FC-based workflows nor cell-barcoding platforms (e.g. 10X) do this.

**Comment by schristley** [comment]
Note that single cell isn't the only way to get paired chains, there are computational techniques and I thought there are other experimental techniques that aren't single cell, so it might be worthwhile to have an explicit paired chain flag that indicates this for a repertoire.

**Comment by laserson** [comment]
e.g., the PairSEQ technique can generate chain pairings without actually doing any single-cell compartmentalization.

**Comment by bcorrie** [comment]
We were discussing a similar issue...

Does that mean we would need something at the rearrangement level as well? That is, does there need to be a cell_id (for identifying many rearrangements that belong to one cell) and a paired_id (for identifying two rearrangements that are a heavy/light or alpha/beta chain pair). Or can a single ID be used for both. If so, I think this would mean that you would never need to know about a paired_id if you knew about the cell_id and vice versa. That is, if your from the same cell, you would never care about which rearrangement you are paired to??? And vice versa if you knew about your paired rearrangement, you would never care about which cell you belong to. The later case seems to be a bit of a stretch but I will leave that to the experts... 8-)

**Comment by laserson** [comment]
I would think a single `cell_id` should be sufficient.

**Comment by bussec** [comment]
@schristley, @laserson: Stochastic pairing (like PairSEQ) always relies on clonal expansion, non-expanded cells will not show up in more than one pool and thus cannot be paired.

I don't question that these approaches work (and most people are interested in expanded clones), but we should come to an agreement whether this level of processing is what we stil consider to be part of MiAIRR Set 6.

Otherwise the easiest option IMO would be to repurpose `physical_linkage` and convert it into a genuine `chain_linkage` field with an expanded vocabulary (it should probably still live somewhere in Set 3, though).

**Comment by laserson** [comment]
Perhaps we can instead add a flag like `is_paired` to specify that data was processed in a way that tries to compute pairings.

**Comment by bussec** [comment]
Yes, however that information would - in my understanding - be on the level of Set 6, where the "cell_id" already implies paired information. Or did you want it put it some else?

**Comment by schristley** [comment]
> Yes, however that information would - in my understanding - be on the level of Set 6, where the "cell_id" already implies paired information. Or did you want it put it some else?

This requires reading all of the rearrangement data to check if multiple rows have the same cell_id and thus are paired, which is computationally expensive. There isn't a simple query that asks if a study contains paired data without reading the rearrangement data. I'm not sure if such a field/flag would go into cell processing or the nucleic acid processing section, maybe na?

**Comment by laserson** [comment]
Wherever `single_cell` is that you mentioned, there could be another flag there for the paired data.

**Comment by javh** [comment]
This seems like a convenience (optional) field in `RearrangementSet` to me. Sounds like the need is for something to select datasets based on a boolean that could be populated from data in either `NucleicAcidProcessing` or `SoftwareProcessing`?

**Comment by nishmm** [comment]
> e.g., the PairSEQ technique can generate chain pairings without actually doing any single-cell compartmentalization.

> Perhaps we can instead add a flag like `is_paired` to specify that data was processed in a way that tries to compute pairings.

Hence, this flag (or alternative pair id) might be needed for each rearrangement record. Especially cases where heavy chain rearrangement (however incomplete) is determined from read 1 and light chain from the read 2 for linked library fragments (as in Georgiou's data).

**Comment by laserson** [comment]
I'm not opposed to a rearrangement-level `is_paired` flag. However, it does have a different meaning than an `is_paired` at the repertoire level, which would mean the dataset is processed to have pairs, but any given rearrangement may or may not have found a successful pairing.

**Comment by bcorrie** [comment]
Soooo, where have we landed with this... We want to load some paired Heavy/Light chain data into iReceptor's IPA repository so I mostly interested in getting a recommendation on what we should store in the existing fields of the MiAIRR standard.

For now, our approach will be to use cell_id at the rearrangement level to link two rearrangements that are a paired Heavy/Light chain.

Given the current state of MiAIRR, any suggestions on what repertoire metadata we should store in which fields? 8-) It doesn't sound like single_cell is appropriate unless single_cell sequencing was performed. 

Any recommendations as to what should go into physical_linkage? That seems like the only existing field that would be appropriate to store this data at the moment, no?

Advice?

**Comment by javh** [comment]
From the call:

+ We probably need an `pair_id` field in Rearrangement, whose population corresponds with `is_paired=True` (wherever we put that).

**Comment by bcorrie** [comment]
Hi All,
We discussed this at our group meeting, and it sounds like this would be sufficient. We are going to explore two different paired data sets and try to load them into iReceptor IPA assuming:

- is_paired: boolean that represents if the data set has at least some paired data (repertoire)
- single_cell: if the data is single_cell compartmentalized data (repertoire)
- pair_id: identifier for rearrangements that have a chain pairing, unique ID within the repertoire for each unique pair.
- cell_id: identifier for rearrangements that come from a single cell, unique ID within the repertoire for each unique cell.

Is that the correct interpretation. Note I don't specify which level of the repertoire metadata the is_paired and single_cell fields are at, because our repositories are flat...

**Comment by bcorrie** [comment]
Hi all (mostly @bussec and @schristley)

I don't think these have made it in to the current pull request... Should is_paired and pair_id be added?

**Comment by bussec** [comment]
Would there be any advantage over just trying complete #156 first and starting a new branch then for the respective changes?
Also, I am having second thoughts about `is_paired`. Not about the usefulness of this information, but whether it should be a key with a boolean value (as discussed before) or a value in a list of keywords pertaining to a dataset (as discussed in #174).

**Comment by laserson** [comment]
fyi, #156 is now merged

**Comment by bcorrie** [comment]
Can we close this issue given #174

**Comment by Zhemm** [comment]
Hello Everyone,

I’m looking for a large database for heavy chain and light chain of antibodies. Does anybody has any suggestions?

**Comment by javh** [comment]
@Zhemm, This isn't the appropriate place for that question. Try https://b-t.cr instead.

**Comment by Zhemm** [comment]
Thanks for your reply @javh!
