### ISSUE TITLE
Read the Docs webhook support

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#171]
I got an email notification about Read the Docs needing to switch to webhooks. I'm assuming that others (@javh?) did as well, since it seems like the new integration has been configured. I'm opening this issue just to document this fact. If it was fixed, please go ahead and mark this issue as resolved.

**Comment by javh** [comment]
Yeah, I got that email too.  I haven't addressed it yet. We have both the service and webhook configured right now (not sure why).  I think we just need to delete the service, test the webhook, and remake the webhook if it doesn't work.

We should see if the same applies to Travis, which is currently configured as a service as well.

**Comment by javh** [comment]
The existing webhooks seemed to be working. I deleted the Travis and RTD services, pushed to master, and check that both RTD and Travis triggered.  Seems fine.
