### ISSUE TITLE
Is there a MiAIRR field that differentiates T-cell and B-cell?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#174]
Hi All,
A quick question. Is there a single field in MiAIRR that would differentiate a repertoire as to whether it was a B-cell or T-cell specific repertoire? There are many ways to infer it, but is there a field that states this explicitly. Nothing is jumping out at me.

Brian

**Comment by javh** [comment]
NucleicAcidProcessing:pcr_target_locus or Rearrangement:locus

**Comment by schristley** [comment]
maybe `cell_subset`?

**Comment by bcorrie** [comment]
@javh I was looking for something along the lines of metadata at the repertoire level, so one can ask the question "which repertoires are targeted at B-cells?" Rearrangement:locus is the most explicit, but it is at the rearrangement level so can't directly help with the above question. One could compute this for each repertoire by looking at a rearrangement in each repertoire, but...

In the example in the Minimal Standard it says pcr_target_locus should be something like "Constant region vs. V region amplification" which doesn't help in this context. In our curation process, the pcr_target_locus is often something like CDR3, IGHV-D-J, V gene, etc. So again, not to sure that can be relied on to differentiate B-cell and T-cell data. Are we using this incorrectly? Should the example be clarified?

@schristley same for cell_subset. I think this is more hopeful, and what we were thinking one would use, but this is getting complicated. It would rely on the vocabulary used being able to differentiate easily. Our current set of cell_subsets in iReceptor are relatively extensive, and include things like "CD4, Naive CD8+ T cell, Treg, T follicular regulatory cells, ..." All of these are T-cell related but there is no obvious general pattern to ensure that you will get all T-cells with a single search across those names. We can't do something like a where clause "where cell_subset like "%T cell%", so the only way is to look at the entire list (which currently consists of 28 different cell subsets in iReceptor) and choose all of the ones that you think are T-cell related, hoping you don't miss any (one hopes that the user would know that CD4 is a T-cell cell_subset. I am guessing an ontology based vocabulary will help, but I doubt it will solve the naming problem above. I am guessing that the ontology might actually group the cell subsets under B-cell or T-cell, but we are not intending to use the whole ontology structure, just a controlled vocabulary from the cell ontology.

It is exactly this awkwardness that drove me to asking the question. If you want all the T-cell data sets, you have to click on 14 select buttons (half of the 28 cell_subsets) 8-)

In the current MiAIRR world, it appears that it is possible to infer T-cell vs B-cell from a bunch of different fields, but this feels like something that is very fundamental, and perhaps should be in the MiAIRR standard explicitly???

Thoughts?

**Comment by schristley** [comment]
> I am guessing an ontology based vocabulary will help, but I doubt it will solve the naming problem above. I am guessing that the ontology might actually group the cell subsets under B-cell or T-cell, but we are not intending to use the whole ontology structure, just a controlled vocabulary from the cell ontology.

That's correct, you should use the Cell Ontology to solve this problem. You are essentially asking the questions "`cell_subset` _isa_ T cell (CL_0000084)?" or "`cell_subset` _isa_ B cell (CL_0000236)?" While you don't need to include the whole Cell Ontology structure, you probably at a minimum want to use the leukocyte (CL_0000738) sub-tree.

The query can be performed in different ways. If you have the ontology structure local, then it's a matter of walking up the parent tree until you hit either T cell, B cell, or neither. If you are using an ontology lookup service like OLS, then you would search for the `cell_subset` term while restricting the search to the T cell or B cell sub-tree by using the `childrenOf` parameter.

https://www.ebi.ac.uk/ols/docs/api#search

**Comment by javh** [comment]
Hrm. I don't think that's the correct usage of `pcr_target_locus`, which is described in the schema as "Designation of the target locus according to standard gene nomencleature". So I see that as something like `IGHG1`, `IGHV1`, etc.  Pinging @bussec for clarification.

Isn't `Repertoire` just a container object for other objects? It could contain single or multiple loci data. I guess you could propagate the set of unique `locus` values in each `Repertoire.sequence_annotation.<Rearrangement>` up a level into an array at the `Repertoire` level...

**Comment by bcorrie** [comment]
> That's correct, you should use the Cell Ontology to solve this problem. You are essentially asking the questions "`cell_subset` _isa_ T cell (CL_0000084)?" or "`cell_subset` _isa_ B cell (CL_0000236)?" While you don't need to include the whole Cell Ontology structure, you probably at a minimum want to use the leukocyte (CL_0000738) sub-tree.

I think my question is more fundamental than that. This can be solved with Ontology via cell_subset. The question is, should that be the only way? From a minimal standard perspective, should there be a field that makes it easy to classify whether a repertoire is B-cell or T-cell? This seems like something that is pretty basic, so maybe shouldn't require a complex ontology look up to determine???

It sounds like, as @javh says, maybe pcr_target_locus is a candidate, as long as valid pcr_target_loci are limited to IGH and TRA and similar - that would imply that we are using pcr_target_locus incorrectly, but that is fine as long as we are agreed how it should be used 8-)

I do have one question around that, as this would imply that CDR3 is not a valid pcr_target_locus. We use this a lot in our metadata at the moment, so I would need to understand in these instances what the pcr_target_locus would be... Hopefully @bussec can clarify...

**Comment by javh** [comment]
Are you amplifying a specific CDR3 DNA sequence? In that case, the sequence probably has a name.  If you are instead try to selectively amplify any (unknown) CDR3 sequence, then I would guess your PCR primers target the conserved V and J sequences flanking the CDR3. (IIRC, this is what Adaptive's protocol does.)

**Comment by emilyvcbarr** [comment]
Generally, the CDR3s that we are annotating are unknown and the primers do target either V and J or V and C, but we've been treating that input as part of forward_pcr_primer_target_location and reverse_pcr_primer_target_location. We've been using pcr_target_locus to describe the area in between those two targets (So, CDR3, full V-D-J, V gene, etc.). If this is incorrect, how should we be defining pcr_target_locus? Would "TRBV-TRBC" be the correct input if the targeted area is the CDR3?

**Comment by schristley** [comment]
I believe the issue with `pcr_target_locus` is that it is for PCR-based experimental protocols only, thus it will not have a value for non-PCR based protocols.

A `locus` in the genetic sense is a position on a chromosome, and `pcr_target_locus` is asking what `locus` is being targeted by a specific PCR primer. In this case, a numerical position isn't being asked for but "according to standard gene nomenclature", so IGHV4, TRAV2, etc. The CDR3 sequence is generally not a valid target for a PCR primer and thus not a valid `pcr_target_locus`.

**Comment by emilyvcbarr** [comment]
@schristley So should all the input pertain to specific genes, or would a broad IGHV be allowable input, if you don't know which specific V genes are present?

**Comment by schristley** [comment]
> So should all the input pertain to specific genes, or would a broad IGHV be allowable input, if you don't know which specific V genes are present?

Maybe. I'll leave it to @bussec to be more precise for MiAIRR. My understanding though is a PCR primer is designed to bind to a specific (often unique) location so it should be possible to specify that exactly. I'm not sure why you would put IGHV if you knew that the primer specifically targets (say) IGHV4. You should be able to BLAST the sequence against the human genome to see what it targets if you don't know. Of course, if you don't have the primer sequences, then you cannot know, but then I'm not sure if Christian prefers putting in a broad IGHV or to leave `pcr_target_locus` as undefined.

**Comment by emilyvcbarr** [comment]
I suppose the problem I face personally is whether or not I list all the of specific genes being targeted. For example, I fill out this field before any processing is done on the sequences themselves. The primers that I'm provided are almost always specific for more than one gene, so that if a sample has multiple V genes to be captured, all of them would be matched with the different V primers. Would it be better to list all of the different V genes that could potentially be present (ex. TRBV1 TRBV2 TRBV3 TRBV4 TRBV5...), or broadly state that the V gene is what is being targeted for PCR? Or would it be better to fill this out after rearrangements are complete and then list the specific genes that were found in the sample? 

And again, if the author of a paper states that they are targeting the CDR3 for PCR and sequencing, do we state that they were targeting V gene for PCR, or is it acceptable to say TRBV-TRBJ? I think a problem with this is that the V gene is often not targeted and captured as a whole when someone is seeking to capture the CDR3- is it still technically correct to say that they target the V gene if it is not captured fully?

**Comment by javh** [comment]
In this context, I take "target" to mean where the primer binds, rather than the region of interest captured by amplification.  But I'm not sure. I think we need clarification on what is meant by "target".

The existence of the `forward_pcr_primer_target_location` and `reverse_pcr_primer_target_location` field sort of imply "target" is the region of interest. But, those coordinate fields also aren't meaningful for a region of interest that spans "genes". (Unless you instead had `forward_pcr_target_locus` and `reverse_pcr_target_locus`.)

**Comment by schristley** [comment]
> whether or not I list all the of specific genes being targeted.

This is diverging a little from the original question, but MiAIRR V1 only had a single `pcr_target_locus` while with #132 it was recognized that multiple loci might be targeted so those fields should really be a list (and are in the more recent metadata format). Note that these fields don't say which primers target what, just what's being targeted, so I'd interpret that as yes, you should list all of the specific genes being targeted. In my example, IGHV4 is actually a family of genes, so if the primer is designed to capture all of the IGHV4 genes then it seems reasonable to use the family name instead of listing each individual gene.

> targeting the CDR3 for PCR and sequencing

This is fairly loose language by the author. They likely don't mean they have a PCR primer that is targeting a specific CDR3 sequence, but instead mean they are sequencing to acquire the CDR3 sequence. If they are doing the former, it's hard to think of that as "repertoire sequencing" because they will only get rearrangements with a specific CDR3 sequence (that matches the primer).

But yours and Jason's point is valid, it is a little unclear what is meant by "target" so MiAIRR should specify that more precisely and indicate what values are acceptable.

**Comment by schristley** [comment]
getting back to the original question...

> I think my question is more fundamental than that. This can be solved with Ontology via cell_subset. The question is, should that be the only way? From a minimal standard perspective, should there be a field that makes it easy to classify whether a repertoire is B-cell or T-cell? This seems like something that is pretty basic, so maybe shouldn't require a complex ontology look up to determine???

One person's complex lookup is another person's simple solution ;-D

As I think about this more, I'm not sure your question is well-defined. Or to say another way, terminology like "B cell repertoire" is kinda of colloquialism that people use but I'm not sure if it is well-defined and precise (maybe I'm wrong on that?). So, are you asking what type of cells are in the repertoire? Or are you asking what genes are being targeted with the repertoire sequencing? If the former then `cell_subset` seems the most appropriate. If you are asking the latter then `pcr_target_locus` seems more appropriate.

**Comment by emilyvcbarr** [comment]
I think the original question definitely does pertain to the cells in the repertoire. Really, it's about displaying in the simplest way possible that something is either a T cell or a B cell. Based on that, I do agree with you, Scott, cell_subset seems like the more straight-forward solution over pcr_target_locus.

**Comment by bussec** [comment]
I think the core of our issue is bit further up in the hierarchy, but let me try to make some clarifications first:

* "target"/"targeting": In MiAIRR these terms are used from a biochemical point of view and are equal to "under the experimental conditions used, a primer is expected to hybridize to this region in a nucleic acid". Therefore, it should *not* be interpreted as "this is our region of interest in a sequence". Primers that are located in exon 2 of the V segment will often not report the complete mature sequence. The sequence will therefore be be `partial` (see definition of terms for `complete_sequences` key) but nevertheless the V segment is targeted. Please note that V segment primers nearly always cross-hybridize and in general it is rather challenging to design primers that will only amplify a given V segment or V family. In most applications this is behavior is of course desired, as it allows us to get a broader coverage. Finally, as @schristley already pointed out, you cannot target CDR3, unless you know the sequence beforehand, but in this case your are doing something else than AIRR-seq.

* `pcr_target_locus`: This field indicates the genetic locus, which in mammals one of _TRA_, _TRB_, _TRG_, _TRD_, _IGH_, _IGK_ or _IGL_ (unless you want to do hairsplitting regarding _TRAD_). This key is supposed to provide high-level information, not primer locations. One of the reasons why we did not try to get more specific here, is the problem with specific targeting (as elaborated above). Hence _IGHG1_ is not valid (as it is a specific gene) and neither would be _IGHV1_ (which is a V segment family and therefore rather ill-defined).

* `cell_subset`: This field indicates the isolated population and when defining this field MiniStd was clearly thinking of flow cytometry (FC) as main method, thus `cell_subset` being supposed to be complementary to `cell_phenotype`. The more recent decision to go for Cell Ontology (CL) and allow the use of its hierarchy (i.e. "is-subset-of" relations) by preserving the CL identifiers would allow to use the lowest common classifier in the hierarchy, i.e. the node that contains all isolated populations. However, I realize that we need to be more specific on this definition (as there are more ways to isolate cells than FC) and for reasons outlined below, `lymphocyte` is not necessarily the top node.

Now let's get to the more general issue. In my perception the problem we are dealing is a similar to the `is_single_cell` issue: MiAIRR was designed to describe how an experiment was conducted. This is reflected by the fields and how - in my opinion - we SHOULD use them. However, both the "Is this data set single-cell?" and the "Is this data set contain B cell sequences?" issues are about how to find data sets based on the MiAIRR metadata. Usually "describing" and "finding" should easily go along with each other, but sometimes it will be hard to grasp the logic behind the experimental setup. For example:

* Someone takes PBMCs (i.e. T cells, B cells and a whole bunch of myeloid populations) and performs a PCR for _IGH_. In this case `cell_subset` is not informative, but `pcr_target_locus` is.
* Someone sorts IgG+ memory B cells (CD19+CD27+IgG+) and performs whole RNA seq on it. In this case `pcr_target_locus` is not informative (actually `NULL` as no PCR was done), but `cell_subset` is.
* Someone takes a chunk of inflamed tissue, performs whole RNA seq on it and computationally filters for _TRB_ reads and... I think you get the idea.

Long story short: Unless someone is inclined to write an AI module that infers which type of sequences will be present in a data set and makes this classification available to a search interface, we need a solution based on (additional) fields and conventions.

While finalizing the MiAIRR fields and some of the associated keywords, we (in my subjective and _post hoc_ perception) tried to stick to the following guidelines:
1. Fields should be non-redundant. Redundancy can be justified by multiple existing classifications (e.g. `cell_subset` and `cell_phenotype`). In case of an overlap, it needs to be specified where overlapping information would go.
2. Data in fields must represent the reality of the experiment.
3. Information that can derived from multiple existing fields, does not get a field on its own.

As we discussed in the single-cell issue, there can be exceptions to (3) when the derivation procedure is computationally expensive. However, based on (2), existing fields MUST NOT be used to encode such derived information. As we control this standard, we should be hesitant to hack it unless there is no other option.

Therefore, there solution that I would like to propose is this introduction of a `keywords` field. We could also have multiple of these fields at the different hierarchy levels, but the main point is that these fields are used to make records findable *not* to annotate the experiment. The content of the fields would be a comma-separated list of controlled terms (e.g. `is_single_cell`, `is_B_cell`) to start with (we can design an AIRR experiment ontology later on).

**Comment by javh** [comment]
Thanks, @bussec. Very helpful.

Adding `keywords` to the Repertoire object seems like a straightforward solution, assuming I understand the need correctly here.

**Comment by bcorrie** [comment]
@bussec thanks for making it clear why we couldn't quite get to where we wanted to go with what we have today. I am just thankful that it wasn't because we were missing something simple 8-)

I have a devil's advocate question regarding this... If, when an experimenter is describing their experiment, they can classify their experiment (at whatever level) into a small number of very well defined classes, in particular biologically, shouldn't that be part of MiAIRR. In a way, this counters your clause 3) above, but if the fields required to derive the classification are not well defined given a specific experiment (the derivation fields would vary based on the experiment) AND the classification is important biologically, wouldn't you want to capture the classification in MiAIRR??? This seems to boil down to a tradeoff between how important the classification is versus how hard (and perhaps more importantly how error prone the derivation of the classification might be) that would determine whether a MiAIRR field is justified or not. 

It seems to me that B cell VS T cell is one of those cases, but as per usual, I have to have the disclaimer that I am not an expert here 8-)

I am sure that your keyword suggestion would provide a mechanism for solving this, but it doesn't help in making the above classification more well defined unless everyone classifies their data using this keyword. And if everyone is using this keyword for classification, then shouldn't it be in the standard 8-)

**Comment by bussec** [comment]
@bcorrie, I never said that the `keyword` field(s) should not become part of MiAIRR ;-). My point was that MiAIRR historically looked at data sets with a rather strict focus on experiment annotation. Therefore, during the major clean-up in spring 2017, we removed quite a number of fields, which did not match this or the non-redundancy criterium (1). However, given the recent issues (#169 and #174) it would IMO be justified to introduce additional fields to MiAIRR to facitilate indexing/tagging of data sets. While we are abandoning the focus on experiment annotation, this would be justified as it prevents abuse of existing fields (point 2) and substantially increases the findability of data (i.e. the "F" in FAIR), thereby staying in line with the central idea behind MiAIRR.

Thus, these fields should be included in MiAIRR along with a first set of keywords to promote their general use. I think it would be helpful to specifically comment on the experiment annotation vs. tagging distinction in the new manuscript.

I will put this on the next MiniStd agenda and try to push this for MiAIRR v2, but we should come to a conclusion how many keyword levels we need.

**Comment by bcorrie** [comment]
Should we close this issue given #185
