### ISSUE TITLE
More clear example for pcr_target_locus

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#175]
@bussec give the discussion in https://github.com/airr-community/airr-standards/issues/174 should we have a more precise example for pcr_target_locus in the standard documentation. In issue 174 you have:

* `pcr_target_locus`: This field indicates the genetic locus, which in mammals one of _TRA_, _TRB_, _TRG_, _TRD_, _IGH_, _IGK_ or _IGL_ (unless you want to do hairsplitting regarding _TRAD_). This key is supposed to provide high-level information, not primer locations. One of the reasons why we did not try to get more specific here, is the problem with specific targeting (as elaborated above). Hence _IGHG1_ is not valid (as it is a specific gene) and neither would be _IGHV1_ (which is a V segment family and therefore rather ill-defined).

The current spec/description states:
pcr_target_locus:
   miairr_set: 3
   miairr_subset: process (nucleic acid)
   miairr_name: Target locus for PCR
   format: free text
   example: Constant region vs. V region amplification

**Comment by bussec** [comment]
Yes, you are right. I would have changed it already, but I just realized that there is a potential merge conflict in PR #156. This PR (current `CRWG-API` branch) groups `pcr_target_locus`, `forward_pcr_primer_target_location` and `reverse_pcr_primer_target_location` in a new `pcr_target` object to allow for annotation of multiple target loci within a single experiment.

@schristley, I know we discussed this before, but I can't find the respective mails/issue: Would it be ok to add these changes to #156? In this case I would also fix the other merge conflicts between `master` and `CRWG-API` that came via PR #155.

**Comment by schristley** [comment]
> Would it be ok to add these changes to #156?

@bussec yes, earlier discussion is in #132.

**Comment by lgcowell** [comment]
I agree with Christian that valid entries are TRA, TRB, TRG, TRD, IGH, IGK or IGL. Should we then change the format from free text to structured?

— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Mack Dressler
Mack.Dressler@UTSouthwestern.edu<mailto:Mack.Dressler@UTSouthwestern.edu>
214-648-2558

**Comment by bussec** [comment]
See commit above. `pcr_target_locus` has now a controlled vocabulary containing `IGH`, `IGI`, `IGK`, `IGL`, `TRA`, `TRB`, `TRD` and `TRG`. I changed the description from "standard genetic nomenclature" to "IMGT nomenclature" as the former one might differ between species. Disclaimer: This is merely based on practicality and non-ambiguity, it does not imply that IMGT has any nomenclature authority for non-human species.
