### ISSUE TITLE
what capabilities to add to reference library for study metadata?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#176]
While we have been mainly discussing the structure and format of study metadata, we should also decide what capabilities we want to add to the reference library. Post ideas and we can discuss implementation. Here are some ideas I have:

- read/write metadata file
- merge metadata files, e.g. when merging rearrangement files
- validate metadata, i.e. basic schema checks like with rearrangements
- "attach" metadata to rearrangements? One idea is to pass a parameter to `read_rearrangement` that specifies the metadata file. Or don't worry about "attaching", users manage them separately. However, "attaching" should allow us to perform additional validation checks and functionality.
- How does code interact with a repertoire object? Unlike rearrangements which is just a list of fields together in a dictionary, the metadata is a nested structure. Does code traverse that structure directly, or do we provide an abstraction layer to hide it?

Here, for example, is one implementation issue. The `repertoire_ids` are not indexed in the metadata file, they are just a list, so looking up a `repertoire_id` would naively requiring iterating through the list to find it, which is expensive if doing that for every rearrangement record. Alternatively, the list is converted into a dictionary keyed by the `repertoire_id` to allow for quick lookup. We could consider the same thing for `study_id`, `subject_id`, etc.

**Comment by bcorrie** [comment]
Have we agreed on a file format for study metadata. In the lang/python/examples directory there is a YAML file with Florian's data in it, both flattened and normalized... Does this imply that YAML is the format of choice 8-)

For a flattened repertoire file format, would it make more sense to support a TSV file like we do for rearrangements? I think this would ease processing data (I think most people are familiar with handling TSV, not so sure about YAML) and would be consistent with the rearrangement file format. 

Thoughts? Not sure we have discussed this issue in great detail???

**Comment by schristley** [comment]
> Have we agreed on a file format for study metadata.

@laserson is the last person who needs to review and approve PR 156, he said he would do it before the next DRWG meeting.

> Not sure we have discussed this issue in great detail???

We've discussed the file format (and structure) for months in the DRWG. Most of the discussion has focused around the structure versus the actual file format. However, it was discussed that a TSV format was not possible because the structure contains an "array of objects" in a number of places, and these don't have a clean representation in TSV format. Thus we need a more sophisticated format like YAML or JSON. Please use #144 for that discussion so as not to digress the purpose of this issue.

> Thoughts?

You ignored the question and didn't say what capabilities you wanted. ;-D

**Comment by bcorrie** [comment]
@schristley I ignored the question because your list was so complete 8-)

I think a big question will be driven by the normalized VS de-normalized approach taken (I think this is your last bullet). Does the reference library support interactions for both approaches? I think it would be useful to allow someone to read a metadata file and ask for the value of a specific field for each record without having to know and interpret the structure of the metadata. 

metadata = readmetadata(filename)
for each record in metadata:
    cell_subset = record["cell_subset"]

rather than:

metadata = readmetadata(filename)
for each study in metadata:
    for each subject in study:
        for each sample in subject:
            for each cell_processing in sample:
                cell_subset = cell_processing["cell_subset"]

or the equivalent:

metadata = readmetadata(filename)
for each record in metadata:
    cell_subset = record.study.subject.sample.cell_processing.cell_subset

That is, can we hide the structure if someone doesn't care about it while at the same time exposing the structure if someone does care...

**Comment by schristley** [comment]
> Does the reference library support interactions for both approaches?

It could, and yes that's what I'm getting at with my last bullet. However, as I think about it more, we cannot really "hide" the structure, meaning users can ignore the reference library, load up the metadata file directly, and traverse the structure however they want. This is likely what will happen anyways for languages we don't support, e.g. JavaScript, PHP. So I guess my "hiding" is really about providing some convenience functions for interacting with the data.

```
metadata = readmetadata(filename)
for each record in metadata:
    cell_subset = record["cell_subset"]
```

I agree this would be nice but I don't think it will be possible, for much the same reason that we cannot put the metadata into a TSV, the structure cannot be flattened into a single dictionary object with unique keys.

For my use cases at least, I don't see my code traversing through the metadata records like with your example code. The more common case is that I'm traversing the rearrangements records and I need to lookup a metadata value for some logic:

```
# separate the boys and girls
reader = airr.read_rearrangement('input.tsv', metadata='meta.yaml')
for row in reader:
   rep = row.get_repertoire()
   if rep.subject.sex == 'male'
      # do some calculation
   elif rep.subject.sex == 'female'
      # do another calculation
```

That example also utilizes my "attach" bullet such that the library can get the appropriate repertoire object for that specific rearrangement row without the user having to manually do the lookup.

In my mind, replacing `rep.subject` with a convenience function like `get_subject()` doesn't really seem that useful:

```
# separate the boys and girls
reader = airr.read_rearrangement('input.tsv', metadata='meta.yaml')
for row in reader:
   rep = row.get_repertoire()
   subject = rep.get_subject()
   if subject.sex == 'male'
      # do some calculation
   elif subject.sex == 'female'
      # do another calculation
```

Yes, it "hides" the subject object within the structure but it also adds overhead...

**Comment by bcorrie** [comment]
I was thinking a comparison to your example:
```
# separate the boys and girls
reader = airr.read_metadata('meta.yaml')
for row in reader:
   rep = row.get_repertoire()
   if rep.subject.sex == 'male'
      # do some calculation
   elif rep.subject.sex == 'female'
      # do another calculation
```
Would be something more like this:
```
reader = airr.read_metadata('meta.yaml')
for row in reader:
    if row.get_metadata_value('sex') == 'male':
      # do some calculation
    if row.get_metadata_value('sex') == 'female':
      # do another calculation
```
This allows someone to do the same operation that you were doing (through a key/value pair lookup on a MiAIRR meta data term) without needing to know anything about the structure of the entities. That is we know there is a "sex" field in MiAIRR for each meta data record and we don't really care that it is in the object "repertoire.subject.sex"

**Comment by schristley** [comment]
> This allows someone to do the same operation that you were doing (through a key/value pair lookup on a MiAIRR meta data term) without needing to know anything about the structure of the entities.

This requires that all keys be unique, which means all field names among all the entities must be unique. While this is currently true for the MiAIRR fields, users are allowed to add their own custom fields outside of the spec (e.g. iReceptor does this with its `ir_` fields), and we don't have an easy way to enforce uniqueness.

We discussed this in DRWG as it was suggested why not a "flat" dictionary object, and throw away the structure? Besides the unique field name issue, having no structure means you don't know which fields belong with which entities (subject, sample, etc.) and thus UIs and other tools that try to organize/display/etc the metadata would have a hard time. It would be hard "normalize" the metadata.

**Comment by schristley** [comment]
> This allows someone to do the same operation that you were doing (through a key/value pair lookup on a MiAIRR meta data term) without needing to know anything about the structure of the entities.

Even though we are talking about the reference library here, it's good to mention that the CRWG API operates like this, but the field name is the "path" to the field within the structure, and we are guaranteed that "path" is unique for each field.

- subject.sex
- subject.age
- sample.tissue
- sample.cell_subset
