### ISSUE TITLE
Can we retire the XLS templates for NCBI submission?

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#177]
The XLS templates (in `NCBI_implementation/templates_XLS`) are a bit cumbersome to maintain and would require some additional work to implement automated validation versus the updated schema (#47). In addition, XLS is a proprietary format. Given that [CEDAR](https://cedar.metadatacenter.org) now has a MiAIRR submission template, should we deprecate these XLS files and recommend CEDAR (at least for low volume submissions)?

**Comment by bussec** [comment]
From today's MiniStd call:
* @ahmadchan mentions that a number of groups still prefer the "classical" submission workflow and therefore would need time to transition to CEDAR-based submission.

Current MiniStd consensus is to release a final and updated version of the XLS files along with the release of MiAIRR 2.0. Files will be maintained for another three months and will be deprecated and removed from the `master` branch afterwards.

**Comment by schristley** [comment]
I'm not opposed to recommended CEDAR, but if we promote one site, we should also have a mechanism to promote other sites (or reference them). I also feel it is vital that CEDAR must produce an AIRR-compliant metadata file before we can recommend it.

**Comment by skleinstein** [comment]
I also think that keeping the “classical” submission pipeline is important.

**Comment by bussec** [comment]
Ok. Any volunteers to take over the maintenance of these files?

**Comment by laserson** [comment]
Could we write a test to ensure consistency with the spec instead?

**Comment by bussec** [comment]
Sure. Any volunteers for that? :wink:

**Comment by bussec** [comment]
This issue has come up (again) in the context of the Meth Mol Biol "Dry lab" chapter. I would opt for one more update in the context of v1.4 combined with a deprecation note. Thought?

**Comment by schristley** [comment]
I have a submission to SRA that I need to do, so I can resolve any issues I run across.

**Comment by scharch** [comment]
@bussec @schristley still relevant?

**Comment by schristley** [comment]
The XLS is still useful for SRA submission, though could likely use an update.
