### ISSUE TITLE
Add support for .NORM file format

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#178]
Support for .NORM is obviously the next big thing for AIRR Standards:

![norm_normal_file_format](https://user-images.githubusercontent.com/11953022/53414230-8a6dab00-39ce-11e9-9504-616410033da2.png)
https://xkcd.com/2116/

**Comment by schristley** [comment]
You are prescient @bussec , I heard a few days later that Microsoft will supports this. I've assigned this to you so you can jump right on this after the parking log committee standard is finalized!

**Comment by scharch** [comment]
closed as 8-D
