### ISSUE TITLE
Documentation about rearrangement mappings between annotation tools

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#184]
In the AIRR Data Rep paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6173121/ there was a table of equivalent fields in the supplementary data for the paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6173121/bin/Table_1.xlsx). We maintain something similar for our data loading process where we import data from imgt, igblast, and mixcr. Should we formally try to support such a mapping table in the AIRR documentation. I think this would be a useful effort and am willing to build on the existing table and add a MiXCR column (which we already have).

Comments before I start??? 8-)

**Comment by javh** [comment]
Hrm. The mappings aren't always (often?) one-to-one.  My inclination would  be that this would be out of scope for the DataRep WG (ie, maintaining a mapping to previous standards rather than promoting the new one).

I think unless we get people outside the WG asking for it, then it's probably more trouble than it's worth.

**Comment by bcorrie** [comment]
@javh we need a mapping like this for iReceptor... We load rearrangement data into the iReceptor "AIRR compliant" repository. By this, I mean the repository essentially stores all of the DataRep defined rearrangement terms. We can load data from the common annotation tools, including IMGT HIGH-VQuest, igblast, and mixcr. We are working on a few other annotation tools as well, and of course we can also load an AIRR TSV file directly into the repository. As a result we need (and already have) such a mapping.

We (iReceptor) can't wait for the tools to adopt the standard, as we need to load this data now. And there is not guarantee that the tools will adopt the standard (we can hope, but)...  I was suggesting that we start with the existing table from the paper and refine it with our mappings and make it a public mapping through DataRep. I don't think this is a lot of work, as we already have a mapping, and I think this would be helpful for people translate from things they are familiar with to the AIRR TSV format.

**Comment by laserson** [comment]
I think this would definitely be great, but I am worried that it'll go stale pretty quickly. At least it should specify the versions of the tools that are being documented.

**Comment by bcorrie** [comment]
@laserson I agree... Would need to be version specific... I think that given that we need this, I can volunteer at least in the short term to maintain this. I also think it will help us sort out some definitions - the one that jumps to mind for me (since I revisited it recently) is duplicate_count #161  8-)

**Comment by bcorrie** [comment]
@javh I think your tool pipeline maps from IMGT to AIRR TSV as well, doesn't it (can't remember which tool). It would certainly be valuable for us to ensure that how we map to AIRR TSV and how you map to AIRR TSV are the same 8-)

**Comment by javh** [comment]
Maintenance is definitely my biggest concern (as always).

We do translate the IMGT/HighV-QUEST data into the AIRR TSV, but a few of the fields are not just renames and it'd be difficult (not impossible) to summarize the translations in a table.  The main parsing class is [here](https://bitbucket.org/kleinstein/changeo/src/tip/changeo/IO.py?at=default&fileviewer=file-view-default#IO.py-370). Some example:

+ `sequence_alignment` can be the `V-D-J-REGION`, `V-J-REGION` or `V-REGION` column of the `2_IMGT-gapped-nt-sequences`, depending upon which one(s) of these are empty
+ The `V-D-J-REGION` column in the `2_IMGT-gapped-nt-sequences` contains different information than the same column in the `3_Nt-sequences`.
+ Determining whether `stop_codon` should be true or false requires searching for the presence/absence of the string "stop codon" in the `V-DOMAIN Functionality comment` column of the `1_Summary` file
+ And so on...

So, in some cases it's easy to say how the two formats map, but in other cases it's not.

**Comment by bcorrie** [comment]
I see your point... Your mapping is much more extensive and complete than ours.

The approach we have taken thus far is to map the ones we can map clearly, with the main goal of trying to ensure that we have consistent mappings for those fields that span all of the annotation tools (MiXCR, igblast, IMGT HighV-QUEST) that we support. This means that we can at least have a well defined comparison between the fields that the those annotation tools share. MiXCR is the lowest common denominator here, as it produces the fewest number of fields in its output files. 

When I look at your problem fields, indeed, we don't have a mapping for them. I suspect for the same reason as you state, the mapping is unclear. 

I suppose what I am suggesting is that I think it would be helpful to have a mapping for those that we think are clear. What we do with the others is an interesting question...

I suppose now that I think of it, I suppose we could use Change-O to convert IMGT HighV-QUEST data to AIRR TSV and just load AIRR  TSV files 8-)

I suppose the most desirable outcome would be for IMGT to provide a mechanism to output and download AIRR TSV files directly from their HighV-QUEST tool, at least as an alternative to their current format. They would be the best ones to map the IMGT file format fields to the AIRR TSV format...

**Comment by javh** [comment]
The MiXCR group committed to provided support for the AIRR TSV, though probably just through a conversion script initially. We should followup with them and see if they've finished that (I haven't checked). That might be a better option. Then, you'll get native output from both IgBLAST and MiXCR and conversion of IMGT through Change-O.  

The 10X Cell Ranger output already has most of what is needed between the CSV and JSON files it outputs, but I think it's worth talking to them and seeing if they'd be willing to also output the AIRR Rearrangement TSV, because most of that is just renames/merges of existing output.

IMGT was non-committal when I asked about AIRR Rearrangement support. We should probably ask again, but I suspect it's a case where the answer will be either "no" or "partial support" in a way that is ultimately non-compliant. I obviously can't speak for them though, and this was before we had finalized or published the standard.

**Comment by bcorrie** [comment]
We should bring this up with Marie-Paul at the Genoa meeting, I am pretty sure she will be there. 

Pardon my ignorance around 10X Cell Ranger, does that produce rearrangement annotations like igblast/MiXCR/IMGT HighV-QUEST?

Bottom line is that if everyone supports AIRR TSV then we don't need a mapping file 8-)

Brian

**Comment by javh** [comment]
Yes, Cell Ranger outputs rearrangement annotations for their contigs. Here's a description of their annotation output ("Contig annotation CSV files" is the relevant one):
https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/output/annotation

Note, CDR3 is actually the junction (same with MiXCR).

And, yeah, let's do that. Let's just get everyone to use the AIRR TSV. :)

**Comment by bcorrie** [comment]
We have also been talking to some of the people at BGI/PIRD (some are coming to the AIRR Meeting). They have a pipeline for annotation called iMonitor and the mapping for their annotation fields to AIRR appear fairly straightforward. We can perhaps talk to them at the AIRR meeting about having them add an option to export annotations in AIRR TSV as well.

https://www.ncbi.nlm.nih.gov/pubmed/26297338
https://github.com/zhangwei2015/IMonitor/

**Comment by schristley** [comment]
@bcorrie Can this be closed?

**Comment by bcorrie** [comment]
Yes, I believe so... I think this boils down to our discussion about people self reporting compliance to AIRR TSV and using that as our mapping... We "strongly encourage" adherence to the standard.
