### ISSUE TITLE
Update docs regarding application support

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#187]
We should add a citation/link to the DR-WG paper at the landing page for the *AIRR Data Representations* section. 

Also, we should ping the authors in the `Supporting Applications` section and see if that table needs an update.

**Comment by bussec** [comment]
@javh I just opened a [branch](https://github.com/airr-community/airr-standards/tree/readme_update_1903) with an updated version of the main README.

**Comment by javh** [comment]
Thanks!  I can check on the application status and update your branch accordingly. I mostly just wanted to remind myself we need to do these things...

**Comment by bussec** [comment]
Citation was added via #198.

**Comment by scharch** [comment]
closed as done
