### ISSUE TITLE
airr-tools merge fails

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#189]
It looks like the command wasn't changed when we moved from handles to filenames.

**Comment by schristley** [comment]
@javh I'd like to create a v1.2.2 release with this bug fix, plus I think there are a couple other bug fixes that are relevant. Do you think I should create a `release-1.2` branch (according to our release process) as master has a bunch of v1.3 changes in it, or just tag master? I don't believe the python library has changed, except for the bug fixes, and one of the bug fixes is for the R library. However, the schema file has changed, Christian has fixed a bunch of errors, there's been a minor fix to Rearrangement object though most of the changes deal with the metadata stuff.

Unfortunately, I find it hard to figure out on github what commits are or are not in master compared to v1.2.1

**Comment by javh** [comment]
Hrm. Too bad GitHub doesn't seem to have the diff between tags/branches view that Bitbucket does... Might have to use a local tool like Meld. The Blame view is helpful-ish, I guess.

My opinion is to do a v1.2.2 tag on master if the schema changes are only bug fixes or clarifications to the description text of *released* standards (Rearrangement, MiAIRR).  If there's any kind of additions or changes that modify the definitions in the schema in a significant way, then I say do a v1.3.0 tag on master. I would ignore unreleased specs like the metadata in the versioning decision.

I would avoid a v1.2 maintenance branch if at all possible (which is not to say avoid entirely).

Maybe fill in `lang/python/NEWS.rst` and `lang/R/NEWS.md` and we can all see exactly whether a minor version number bump is appropriate. (Not necessarily you - whoever made the changes.)

If it does look like we need a v1.3, then I think we might want to scratch off some other open issues regarding the Rearrangement schema (eg, #161, #181, #183, #188, some of #139, etc). Just so we don't have to turn around and do a v1.4 in a month.

(Pinging @bussec and @ssnn-airr.)

**Comment by schristley** [comment]
yeah, maybe that is better, just go forward and do a v1.3 release.
