### ISSUE TITLE
Handle unknown for boolean fields

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#193]
This came from #190 where Jian indicated that some fields like `productive` may be unknown or undetermined, that is you cannot concretely say T or F because there isn't enough information to make the determination. The result is the field is blank/null in the TSV.

This causes an issue in code though because the data type is boolean. The reference library wants it to be either T or F otherwise it's considered a validation warning.

So the question is, do we explicitly allow blank/null values for boolean (the code would need to be changed to support this)? An alternative is to set give each field a default value (we can specify this in the schema with `default` attribute), and blank/null values are automatically set to the default value?

**Comment by javh** [comment]
I can't think of a situation where I'd want to do anything except treat `null` as equivalent to `F` in an analysis, but... seems like we should support missing values, as it's part of the schema.

We could introduce a little feature float and add flag for whether to fill null booleans with false. Not sure how I feel about that.

**Comment by laserson** [comment]
My understanding is that all fields are nullable. I'm not sure why that's a problem here.

**Comment by schristley** [comment]
> My understanding is that all fields are nullable. I'm not sure why that's a problem here.

I was getting validation warnings for these fields with blank/null, so there is likely a bug in the validation code. I think that we handle blank/null properly for reading/writing but need to verify to be positive.

**Comment by schristley** [comment]
not able to reproduce validation error, must have been using an older version
