### ISSUE TITLE
Should we revisit our examples???

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#194]
I notice that we have some examples in the AIRR specification that are somewhat cheeky (why do I want to think these came from @bussec??? 8-) And I think we have stumbled across some that aren't particularly accurate given our current thinking on some fields.

For example, we have: School of Medicine, Unseen University, Ankh-Morpork, Disk World - Someone is a Terry Pratchet fan... 8-)

And we have recently fixed a few others...

Should we take the time to revisit these somewhat carefully? The reason I ask is that we use these on the iReceptor Gateway, and they appear in our help documentation in various places (see attached)... 8-)

I would do it but I am not the best person to ensure that the scientific examples are accurate... And we should decide if SciFi/Fantasy references are OK or if we should be a bit more "dry" in our non-existing worlds. 8-)

![Untitled](https://user-images.githubusercontent.com/1105216/54858663-5e8ad000-4cc3-11e9-814b-b498eaafae9a.jpg)

![image](https://user-images.githubusercontent.com/1105216/54858700-8c701480-4cc3-11e9-9c5d-fec2cfdf04ae.png)

**Comment by bussec** [comment]
@bcorrie how did you guess? Or did you simply use `git blame`? ;-)

I'm ok with going through the examples again. I would favor examples that are neutral in terms of real-live entities, but we can take out the cheeky ones and do not necessarily have to resort to Terry Pratchet. Do we need a vote on which universe/alternate reality to use? ;-)

**Comment by schristley** [comment]
we can also use the `example` property in OpenAPI to provide more detailed examples too.

**Comment by laserson** [comment]
Is there an opportunity here to write some tests?

**Comment by schristley** [comment]
> do not necessarily have to resort to Terry Pratchet

Somewhat of a Douglas Adams fan myself, can we work this into an example somehow...

"We demand clearly defined boundaries of doubt and uncertainty!"

**Comment by schristley** [comment]
I'm fine with closing this generic issue, which implies going over all of the examples and yeah it's liable to never be "finished". Instead, open up an issue for any specific field/example which should be changed, and thus has a small, finite scope that can be easily completed.
