### ISSUE TITLE
Best practices for germline_alignment when full naive sequence is not calculated

### ISSUE THREAD

**Issue by scharch** [airr-community/airr-standards#196]
@javh @schristley Should I use VVVVV---DD---JJJJ or VVVVVnnnDDnnnJJJJ? Or some other convention? What if the germline D is not assigned?

**Comment by lgcowell** [comment]
The downside to using n is that this may suggest the nucleotide is known to be an n nucleotide (as opposed to p nucleotide) even though this is rarely known.

— ——————————————
Lindsay G. Cowell, PhD
Associate Professor
Division of Biomedical Informatics
Department of Population and Data Sciences
Department of Immunology
University of Texas Southwestern Medical Center
Lindsay.Cowell@utsouthwestern.edu<mailto:Lindsay.Cowell@utsouthwestern.edu>
214-648-2289

Administrative Assistant:
Renee King
Renee.King@UTSouthwestern.edu<mailto:Renee.King@UTSouthwestern.edu>
214-648-2012

**Comment by javh** [comment]
I think VVVVV**NNN**DD**NNN**JJJJ is more accurate (because it doesn't imply an indel).

If the D is not assigned, I would similarly mask the D with Ns. (We usually analyze data with the D masked regardless of whether it has been assigned, but using a separate `germline_alignment_d_mask` field.)

**Comment by scharch** [comment]
Thanks @javh. Follow-up: if part of the V region is missing (primers, bad sequencing...), should those also then be masked with Ns in `sequence_alignment`? Or perhaps in those cases the `germline_alignment` should be truncated to avoid implying anything either way?

**Comment by javh** [comment]
I think it depends on whether it's the head or tail that's missing (head=FWR1 end). If the head is missing, I would pad the front of `sequence_alignment` with `-`. If the tail is missing then, I'd just truncate the alignment. But, you could truncate in cases where the head is missing as well if you'd prefer the `*_alignment` fields to accurately represent the amplicon/sequencing length (though, you can't do this if you add IMGT gaps to the alignment). Either way, as long as `sequence_alignment` are `germline_alignment` are identical in length, you'll be in compliance with the standard.
