### ISSUE TITLE
handle $ref in schema

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#197]
The current Schema python class is based mainly on `Rearrangement` which has a flat structure. To load up `Repertoire`, we need to handle $ref as well as traversing a deeper structure.

So does anybody know of a package that will de-reference all of the `$ref` links? The basic yaml loader doesn't seem to do that as far as I know. This is needed for both JSON and YAML files.

**Comment by laserson** [comment]
Can you point to the yaml file that needs to be rep'd and where the code does this now? Perhaps we just need to write a custom function that traverses the loaded yaml object?

**Comment by schristley** [comment]
The file is airr-schema.yaml. All of the current $ref points to schema objects inside the same file. Actually maybe we need this only for yaml and not for JSON. The python code that loads up the schema file is [schema.py](https://github.com/airr-community/airr-standards/blob/master/lang/python/airr/schema.py#L55)

We could write our own de-referencer but it's more than just #including code as the referenced schema can be incorporated in different ways, so I'd prefer to use somebody else's well maintained code. For javascript and JSON in the repository API, I'm using [json-schema-ref-parser](https://www.npmjs.com/package/json-schema-ref-parser) which works well.

**Comment by schristley** [comment]
I manually handled this in `validate_object` for validating a repertoire metadata object. It's not totally general but good enough for our schema and should throw an internal error if the schema changes in a way that isn't supported yet. Users who wish to traverse the schema are on their own...
