### ISSUE TITLE
restructure docs at RTD

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#199]
At last DRWG meeting, it was mentioned that the docs should be restructured to integrate better and make it easier for users to navigate and find what they need. My initial crack at this for the table of contents.

This simplifies the top level entries.
```
Introduction to AIRR Standards
    AIRR Data Model
    AIRR Data Commons
    AIRR Curated Germline Sets
Getting Started
    Examples & Tutorials
    Templates
AIRR Standards
    Study Reporting (MiAIRR)
    Software guidelines
    AIRR Data Model
        Repertoire schema
        Rearrangement schema
        GermlineSet schema
    AIRR Data Commons
        Query Interface
        AIRR-compliant repositories
    AIRR Curated Germline Sets
        Homo sapiens
        Mus musculus
        Macaca mulatta
Software
    Python API
    R API
    CAIRR
    OGRE
    ADC API
Community
    Supporting Applications
    Resources
Glossary
```

I guess `Introduction` and `Getting Started` would be user-focused while `AIRR Data Model` and `Software` would be more reference info.

**Comment by javh** [comment]
Overall, I like it!  A few suggestions:

1. Introduction
2. Getting Started
    1.  Examples & Tutorials
    2. Templates
3. Standards
    1. Data Reporting (MiAIRR)
    2. Software guidelines
    3. Data Formats
        1. Annotation and Analysis (Rearrangement schema)
        2. Metadata (Repertoire schema)
        3. Germline Databases (GermlineSet schema)
5. Software & Databases
    1. Python API
    2. R API
    3. CAIRR
    4. OGRE
    5. ADC API
6. Community
    1. Supporting Applications
    2. Resources
7. Glossary

On this topic... sort of...

I tried this a while ago, and there was some difficulty I don't recall, but I think we should revisit switching the theme to [bootstrap](http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html).  We now have a lot of pages that are very long, and you very easily lose the navigation sidebar. We also have some tables, which could use the extra width.

**Comment by schristley** [comment]
That's good, I like the top-level standards. I modified my TOC in-place.

I want to make sure that the high-level concepts, like how all the schema are related to each other in the AIRR Data Model, or the architecture of the AIRR Data Commons, get described properly up-front instead of being hidden in reference doc, so I guess the introduction and getting started sections is the best for that.

OGRE and inferred allele submission seems kinda hidden, but not sure how to call it out more.

**Comment by scharch** [comment]
> OGRE and inferred allele submission seems kinda hidden, but not sure how to call it out more.

Is there a way to show the top two levels instead of just one? Or to make the second level visible on mouse-over?

**Comment by schristley** [comment]
> Is there a way to show the top two levels instead of just one? Or to make the second level visible on mouse-over?

When you click on a TOC link to go to that page, the TOC shows the next level down, so kinda... The front page currently shows the fully expanded TOC. I think if we add as a top-level topic in the Introduction then that might be good enough. I'm not sure about mouse-over, possible if we can grab some code from somewhere.

**Comment by ssnn-airr** [comment]
I like it! I would only add some short text to the `Software & Databases` items, similar to section `iii Data formats`. I think `Python API` and `R API` are self explanatory, but the other items aren't. Maybe `CAIRR data submission`, `OGRE inferred allele submission'. I would make it easier for new users to identify what can be done with the resources available.

**Comment by laserson** [comment]
Make sure to look at docs from the "metadata" branch

**Comment by schristley** [comment]
I've committed a rough restructuring of the top level, take a look.

http://docs.airr-community.org/en/metadata-docs/

**Comment by schristley** [comment]
metadata-docs branch is merged
