### ISSUE TITLE
Broken link in airr_swtools_standard.rst

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#202]
The link to WG `GitHub repository` in `airr-standards/docs/swtools/airr_swtools_standard.rst` doesn't work from the docs site. This is the sentence: "An example Docker container is provided on the Software WG GitHub repository". The rendered link is "https://docs.airr-community.org/en/latest/swtools/github-swwg"

**Comment by schristley** [comment]
Also, the two links in the first paragraph don't work.

**Comment by williamdlees** [comment]
Thanks Scott. Fixed now.
