### ISSUE TITLE
Synthetic antibodies and MiAIRR

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#204]
@bussec and I have been having a discussion with a colleague around synthetic antibiody data and which fields would be nullable (related to #96). I wanted to capture this in an AIRR issue rather than in the email thread. I think the nullable part has been agreed, it is more around the definition and examples where discussion is ongoing.

Currently, the fields being discussed (and in particular their meaning for synthetic antibody data) are: 
    synthetic:
    organism:
    sample_type:
    single_cell:
    cell_storage:
    template_class:
    library_generation_method:
    complete_sequences:
    physical_linkage:

Other than some example clarification, the current fields where discussion is ongoing are:
    sample_type
    physical linkage

@bussec I think that is where our email conversation had ended, correct me if I am wrong, and if you think you have closure on this then you can close the issue. I thought there were a couple of outstanding thinks on the last two that still needed clarification?

**Comment by bussec** [comment]
@bcorrie, IMO the remaining issues are only misunderstandings, not general problems that would prevent the annotation of phage library repertoire data. We would probably need the following additions/clarifications:

* `organism`: We assume that every phage library is somehow a derived from V and J segments that exist in some vertebrate species. This field should encode this species. Importantly, it MUST NOT encode the phage vector, the bacterial host or comparable biological components of the library system.

* `sample_type`: Our previous assumption was that this field describes  the mode of sampling from an `organism`. For phage libraries we need to include additional terms into the vocabulary, e.g. for whole culture, affinity-selected phages or flow-through.

* `physical_linkage`: Typically phage libraries use scFv format for display, i.e. constructs that encode both the IG heavy and light domains in a single polypeptide, separated by some type of Gly{3,4}Ser spacer. As this constitutes a physical linkage within the construct we need to introduce a term for this.

**Comment by bussec** [comment]
Closed via #319.
