### ISSUE TITLE
Single-cell expression data annotation/linkage

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#206]
One of the goals of MiniStd WG is to extended the current MiAIRR specificiation to provide mean for more detailed annotation on the single-cell level. We already discussed chain-pairing in #169 (now in PR #200). In addition to this, we also aim to provide marker expression and reactity data. However, the corresponding raw data sets usually contain data from a lot of events and partitioning can be complex. Therefore in analogy to the MiAIRR Set 6 annotation, two levels will be provided: First, a link to the raw data set along with a pointer to the record(s) in question. Second, the most relevant parts of the processed data to allow for fast search and compare operations.

This issue will only deals with marker expression, for single-cell reactivity data see #207.

The proposal is to add the following information to the cell-level of the schema:
* single-cell expression data:
  * keyword describing the methology used to assess expression. Controlled Vocabulary. Currently: {"flow cytometry", "single-cell transcriptome"}.
  * Reference to raw data
    * DOI of raw data set containing the current event
    * Index addressing the current event within the raw data set. Note that the index field is not necessarily numeric but can also hold a DNA barcode.
  * _n_ processed data records:
    * `value`: transformed and normalized expression level
    * `marker`: standardized designation of the transcript or epitope

Potential issues of the approach:
* `value`: Transformation is a not standardized procedure, especially for FC data. Also note that no gating information is provided as this often goes FUBAR after transformation.

* `marker`: To be interoperatable, this should come from an ontology. While this is simple for gene expression, flow cytometry markers are more difficult as there is BTMK no ontology for them. Also note that gene name != protein name != FC marker.

**Comment by frubelt** [comment]
Thanks Christian! Can we also include additional methods ("methology used to assess expression") or maybe just talking about protein and transcriptom? New methods don't use fluorescence labled methods for antigen detection (e.g. DNA labeled). The data can be presented in FCS files but they are based on a different detection method. You may address it in the "Reference to raw data" with "Index addressing the current event within the raw data set. Note that the index field is not necessarily numeric but can also hold a DNA barcode." already. Just wanted t mention it.

**Comment by bussec** [comment]
For clarification: We are not limited to flow cytometry (FC) and transcriptomes, I just took the two most obvious examples. The goal is to have a record design that is flexible enough to accommodate new platforms, too.
