### ISSUE TITLE
Integration tests for multiple software pipelines

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#208]
Develop CI tests that download latest versions of tools and check their input/outputs are AIRR-compliant. This is a bit related to software WG's sumrep bc it'll probably require checking that the actual results are sane too. @scharch

**Comment by scharch** [comment]
What's the thought here? Output should be easy enough using the validation function in the reference implementation, right?

**Comment by laserson** [comment]
There are many different projects all being developed separately. The idea is to try to make a system that will alert people when someone breaks something. That means either the standard changes and now everyone needs to be notified. Or a tool makes a change that brings things out of compliance.

**Comment by schristley** [comment]
In a datarep call we discussed how checking that all tools are AIRR-compliant is a heavy lift, and we are going to let tools self-validate.
