### ISSUE TITLE
CIGAR string documentation needs more clarification

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#209]
From a discussion with @williamdlees with regard to partis and OGRE

> The one area of the spec that I think really does need some amplification is the CIGAR string.  An example from the spec is 'CIGAR string for the J gene alignment.'  It should specify the two sequences that are to be aligned, and state which is the query and which is the reference. Partis has implemented the J-region as reference and the sequence_alignment as query, but the spec is ambiguous: it could be interpreted as an alignment between the J-region and the J- germline gene, or the J-germline gene and sequence_alignment, and query and reference could be either way around. The spec should also say what's expected if there are gaps in sequence_alignment (such as IMGT gaps), and in particular whether there are ever any circumstances in AIRR data in which the CIGAR could contain more than one matching region separated by non-matching regions.

**Comment by javh** [comment]
Good points. The reference for the `j_cigar` should be the J germline reference sequence. The query was intended to be `sequence` (the input) and not `sequence_alignment` (typically restricted to the V(D)J). 

As for the IMGT gaps, the ones in `sequence_alignment` shouldn't matter. But, we should look into how the alignment is done against IMGT gapped V reference sets in different tools. Depending upon whether you remove the gaps before alignment or convert them to gaps in the reference, you could get a different answer. (I think people just remove them, so it might be a non-issue.)

For a full-length cigar, by inclination would be to use a custom field like `sequence_cigar`.

**Comment by williamdlees** [comment]
Thanks Jason, Perhaps the reference should be the ungapped germline gene sequence and the query should be sequence (i.e., the input?) In that case there’s no specific need to address how gaps are handled.

**Comment by javh** [comment]
I definitely think the query should be the input. The CIGAR strings are suppose to contain the information used to derive `sequence_alignment` and `germline_alignment` (partially), so it'd be kind of circular otherwise. Ie, if the CIGAR lists a deletion in the query then there should be a corresponding gap in `sequence_alignment`.

I think in the vast majority of cases the reference will be the ungapped germline sequence. I don't imagine an alignment tool working well against gapped references anyway. Unless they remove the gaps for alignment and then have a post-processing step where they adjust the positional information based on the removed gaps so it matches the gapped reference.

(Pinging @psathyrella)

**Comment by psathyrella** [comment]
I'm a little confused by all the different possibilities listed above, but I don't think I chose on purpose which was which, so could swap them if folks decide that makes sense. I will get on my hobby horse for a moment and say that I think this ambiguity is an inherent (and serious) flaw in the cigar format in general. I think the object we're trying to represent is two gapped/aligned sequences, which is purely symmetric, and introducing an asymmetry between the two sequences which, if you swap it, gives the wrong result, isn't ideal.

**Comment by williamdlees** [comment]
Given that we've decided to go with CIGAR, I think we really need to spell out in detail what the CIGAR fields are intended for, and exactly how they should be implemented, in a way that does everything possible to ensure that the fields are used consistently across implementations. I very much hope we can avoid implementation choices that will come up with conflicting results.

**Comment by bcorrie** [comment]
Hi all, trying to wrap up v1.3 issues, has this been completed??? Is it a v1.3 issue?

**Comment by javh** [comment]
It is a v1.3 issue and it isn't finished.

**Comment by bcorrie** [comment]
Dohhh...

**Comment by javh** [comment]
Well, I am assigned... I'm just slow. I'll try to make it a priority next week.

**Comment by bcorrie** [comment]
I would offer to help, but I can't define them 8-)

**Comment by javh** [comment]
Updated docs in #389.
