### ISSUE TITLE
Does it make sense to merge airr-formats and airr-standards?

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#21]
Replicated at airr-community/airr-formats#44

We could publish a single set of versioned docs at docs.airr-community.org or something like that.

Thoughts?

**Comment by schristley** [comment]
It kinda makes sense as they are both cross-referencing each other. airr-formats essentially just pealed off the rearrangement annotations.

**Comment by laserson** [comment]
@BusseChristian, love to hear your thoughts on this.  I think @ahmadchan is on board, and the formats group is on board with this as well.

**Comment by bcorrie** [comment]
My take on this is that having a single source of truth would be extremely valuable, so merging the AIRR repositories makes a lot of sense. I think (???) this makes sense across all of the AIRR working groups (Common Repo as well)...

Erik raises a good point in that whether having a single group meeting (Minimal Standards + Formats) with many people will be able to advance both the standards and the more detailed technical components that the Formats group tends to deal with at the pace we would like... Different groups will have different rhythms for meetings, and they are unlikely to match up...

Perhaps a good structure would be that we have a single source of truth and common technologies (git repo, slack channels, issue tracking, etc) but still have a Formats working group that meets regularly to discuss the more technical details that some on the Minimal Standard group may not want to spend time on???

I also agree that we need to tie the groups together better. Using the same technology platforms will help with this, but it might help to have something a bit more formal (I hate to say it) in terms of communicating initiatives and milestones that each of the working groups is working on.

Brian

**Comment by BusseChristian** [comment]
`airr-formats` was merged into `airr-standards` in 707cd472e0c5e2f6c1356550015b0fb16d27afaa.
