### ISSUE TITLE
specification of required fields for ADC API

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#213]
The `fields` parameter to the API allows the caller to specify which fields to return. In the case of `/rearrangements`, with AIRR TSV format, this can produce output that would not pass validation checks, because required fields are missing. Should we enforce that `required` fields are always returned, which kind of defeats the purpose of `fields`.

A more reasonable scenario is that a user wants all of the required fields, so it pass validation, plus a few more they are interested in, but not the full set. In this case, the user has to know the full set of `required` fields to pass `fields`, which they may not easily know without looking it up. Maybe there is an easier way to handle this case.

**Comment by scharch** [comment]
I think I must be missing something, but are you sure that's right? [This](https://github.com/scharch/SONAR/blob/f7ebfe65ddcd8d73c2059eabf3c03a698e14c620/annotate/parse_blast.py#L138) produces a valid AIRR TSV with all the required fields...

**Comment by schristley** [comment]
I don't mean the python library but the [ADC API](https://github.com/airr-community/airr-standards/blob/master/specs/adc-api.yaml) where a query against a data repository uses the `fields` parameter to limit the fields returned.

**Comment by scharch** [comment]
Got it, sorry.
If the user doesn't actually want the rest of the required fields, it should be possible to pass the retrieved data through something like the datarep reference implementation to automatically add all those back in as `Null` and generate a valid TSV. Alternatively, would it be possible to do something like have the API expand `fields=[ 'all_required', ... ]` as a shortcut so the user doesn't have to remember the exact list?

**Comment by schristley** [comment]
> Alternatively, would it be possible to do something like have the API expand fields=[ 'all_required', ... ] as a shortcut so the user doesn't have to remember the exact list?

I tend to prefer this alternative method, as some clients may not be able to easily pass through a ref implementation like (say) a GUI, plus the `required` list may change over time so requiring users to dynamically figure out those fields seems a bit onerous. We could add a field keyword like you suggest, another idea is an additional parameter for the API e.g., `force_required=true`.

**Comment by schristley** [comment]
@bcorrie Now that I've implemented the validation function for repertoires, this has a bit more urgency. If ADC API doesn't return `null` fields, this will generate a lot of validation errors. Take a look at #215 for a description.

I think we need a simple way to tell the API service to return all of the required fields so that the user will be guaranteed that returned data will pass validation. These might be fields that don't actually exist in the study, but the API needs to stick them in with null values.

**Comment by bcorrie** [comment]
I wonder if the API should always return the required fields? No matter what is requested in the "fields" block?

I suppose I am suggesting that the API should always return required fields - which kind of makes sense...

It makes the behaviour of the "fields" attribute a bit odd, but if a field is required maybe the API should always return it. This might be more of a problem at the rearrangement level, but it shouldn't really cause too much of a data bloat at the repertoire level???

**Comment by schristley** [comment]
Except that kinda defeats the whole purpose of having `fields` in the first place, it's meant to be a way to restrict the amount of data transferred, which is useful. I think we just need a simple way to toggle between the two behavior.s

**Comment by bcorrie** [comment]
How about:
```
{
"filters" : {}
"required": True
"fields": {"study.study_title"}
}
```
Giving you all of the required fields plus study.study_title. Required = True or False by default???? Maybe False so
```
{
"filters" : {}
"fields": {"study.study_title"}
}
```
just gives you study.study_title?

**Comment by schristley** [comment]
Yep, though I'd suggest a key name different from `required` as that's used by OpenAPI and may cause confusion. I'd suggest either `include_required` or `exclude_required` depending upon what we want the default behavior to be.

- We want the default (for JSON) to return all of the fields. This is really the only way to discover custom fields in a study. So I think with that as the default, it makes sense to always return all of the MiAIRR (and API) `required` fields.
- When `fields` is specified, this generally implies that the client wants to restrict the data being sent, so let's honor that by default and send only what's requested. Then if they want to insure the required are included then pass `include_required:true`.

Note that we haven't defined which fields are required yet, #215 . While there is the set of MiAIRR fields that are required, there are also non-MiAIRR fields like `repertoire_id` that are required from an API perspective. So we need to decide how to annotate those fields.

**Comment by bcorrie** [comment]
I believe this is a grid of the possible options...

| Query parameters                    | AIRR required | AIRR Not Required | Extra fields | Requested fields|
|-----------------                         |+-------------+|+-------------------+|+----------+|+---+|
| None                                        | Y|Y|Y|N|
| fields=[,,,]                                  |N|N|N|Y|
|include_required:true,fields=[,,,]|Y|N|N|Y|
|include_required:true                 |Y|N|N|N|

Some options that aren't possible in this scenario are requesting just all of the AIRR fields (AIRR required, AIRR not required, but no extra fields) or just all of the extra fields. Is that OK?

**Comment by schristley** [comment]
> I believe this is a grid of the possible options...

that looks great!

Note that there is a difference between MiAIRR required and (ADC API?) required. For example, `repertoire_id` isn't in MiAIRR but I think you'd agree that `repertoire_id` should be one of the required fields returned by the API. Is your "AIRR required" just the MiAIRR ones or the larger set?

While we have an attribute for MiAIRR required, we don't have one for ADC API required...

> Some options that aren't possible in this scenario are requesting just all of the AIRR fields (AIRR required, AIRR not required, but no extra fields) or just all of the extra fields. Is that OK?

We could provide those options, as we know all of the AIRR fields from the schema... I'm not sure if it's useful enough to make the interface more complicated to support. How about we go with this design, and if we actually get people asking then we can consider to add for V2?

**Comment by bcorrie** [comment]
> We could provide those options, as we know all of the AIRR fields from the schema... I'm not sure if it's useful enough to make the interface more complicated to support. How about we go with this design, and if we actually get people asking then we can consider to add for V2?

Sounds good...

**Comment by schristley** [comment]
> Hadn't though of that subtle difference... 8-) I guess since this is an ADC API related flag in the API request, I would think this should apply to the MiAIRR + ADC API required fields???

Yes, that's seems reasonable to me. ADC API required would include MiAIRR required plus additional fields, so it is a larger set.

The reason I bring that up is there's no mechanism in the schema to specify those ADC API required fields. Though that is #215 versus this issue but they are related.

**Comment by bcorrie** [comment]
How do we specify which fields are required in the spec? Discussion at the CRWG suggests maybe we could use miairr=false, required=true?

There are layers of requirements, MiAIRR has requirements, AIRR TSV has requirements, and ADC API has requirements.

AIRR TSV uses OpenAPI required field capability.

**Comment by schristley** [comment]
Opening this back up, even though we have the required fields specified in the schema, need to implement this in the ADC API reference implementation as well as add some documentation.

**Comment by schristley** [comment]
@bcorrie I've been coding `include_required` in the reference implementation. It's a pain to code but I seem to having it working. Currently, I had just put `include_required` parameter on the two main query [endpoints](https://github.com/airr-community/airr-standards/blob/6acb7f2936ffafa141369e984229288518701bfc/specs/adc-api.yaml#L217), but then I realized that this might be needed for the single GET endpoints as well. We don't really have any parameters on those GET endpoints except for the id of the object, so you cannot restrict fields or etc, it just returns the object as is.

So my question is should we start adding such parameters to the GET endpoints? I kinda prefer not to keep the interface simple. I think we have a few options:

* Add `include_required` to the GET endpoints.
* The GET endpoints always returns all the required fields by default.
* Leave GET endpoints as is, clients that want `include_required` should use the POST endpoint.

What do you think?

**Comment by schristley** [comment]
[implemented](https://github.com/airr-community/adc-api-js-mongodb/commit/f226aa50fda6308f69884592b780b28d00eb0aea) in ADC API reference.

**Comment by bcorrie** [comment]
We do not yet have this implemented but it is in the works...

For GET, I would suggest that the endpoint return everything... Required + Extra fields. As you say, if you want a more complex query and/or restricted fields then users can us the POST endpoint

**Comment by schristley** [comment]
[implemented](https://github.com/airr-community/adc-api-js-mongodb/commit/af526f7a8570eb643bb164242d341a8187b2317d); GET endpoints always returns all AIRR required field by default.
