### ISSUE TITLE
better specification of error/success conditions for ADC API

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#214]
There some error/success conditions that are not well specified for the ADC API, and we should specify them better so that all clients can expect the same behavior. Some things we can put in the API spec itself but others are behaviors that will need to be documented. Here are a few things that came up but there are likely more:

- If a query returns no data, is that a success with an empty result or a 404 status code? The `/repertoire/:repertoire_id` entrypoint suggests 404 code, while the `/repertoire` entrypoint suggests success with an empty result.
- If a query requests a field that doesn't exist, is that an error or success. If it's a success do we put the field in with a null, `{field: null}`, when the API default is not to return or store null fields. There is the confounding issue that fields may exist in some studies but not others. How about if the field is specified as part of `facets`?
- If the API service is operational, e.g. `/info` returns success, but the back-end database is down and thus queries would fail, should `/info` actually return an error instead?
- Query JSON is valid JSON but isn't a valid query, how should that error be reported?

**Comment by bcorrie** [comment]
> * If a query returns no data, is that a success with an empty result or a 404 status code? The `/repertoire/:repertoire_id` entrypoint suggests 404 code, while the `/repertoire` entrypoint suggests success with an empty result.

I  think this is a success with no data. The query did not fail, it should not return an error I would think.

> * If a query requests a field that doesn't exist, is that an error or success. If it's a success do we put the field in with a null, `{field: null}`, when the API default is not to return or store null fields. There is the confounding issue that fields may exist in some studies but not others. How about if the field is specified as part of `facets`?

I think success, with a field null. Maybe not intuitive, but I think the best example is if the requested field is a valid MiAIRR or Rearrangement field, isn't a manadatory field, IS NOT in repository A but IS in repository B.

We don't want to fail this, because it is a valid field. I feel less strongly about whether the repository returns it as null, as we want to be supportive of missing fields. So either not returning a value or returning a value of null would be OK.

I think returning a null if it is asked for and you don't have it makes a bit more sense, but... 

> * If the API service is operational, e.g. `/info` returns success, but the back-end database is down and thus queries would fail, should `/info` actually return an error instead?
My vote would be it should return an error.

> * Query JSON is valid JSON but isn't a valid query, how should that error be reported?
This I think should be an error...

**Comment by schristley** [comment]
> I think this is a success with no data. The query did not fail, it should not return an error I would think.

I'm okay with that. I think had 404 code thinking about a REST API perspective as that seems to be what is returned, but ADC API isn't really compliant with REST.

> My vote would be it should return an error.

This sounds reasonable too. The reference implementation will need to be updated to test the database.

> This I think should be an error... I think the issuer of the query should be able to tell the difference between a valid query not finding data and an invalid query.

I agree. My point was less should it be an error, but how should the error be reported. For example, should we have a list of common error cases that can help the user debug the query instead of the generic `Invalid query`? I can think of a few:

- Data type mismatch. The field should be an integer, but a string was provided.
- Unknown operator. You tried to do the `&` operator which doesn't exist.
- Missing fields for an operator. You gave `and` operator but didn't provide the `contents` field.

**Comment by schristley** [comment]
> I think success, with a field null. Maybe not intuitive, but I think the best example is if the requested field is a valid MiAIRR or Rearrangement field, isn't a mandatory field, IS NOT in repository A but IS in repository B.

Thinking about this a little more, I guess maybe I wasn't thinking about a field in the `filters` query but a field in `fields`. Now imagine that they do a rearrangement request and ask for AIRR TSV. They might expect because they said they wanted that field, that they should get a column in the TSV for that field.

**Comment by schristley** [comment]
These have all been addressed in the reference implementation, my last comment about `fields` is addressed in #230 . We haven't agreed on error reporting but we can do that as part of the test suite.
