### ISSUE TITLE
required fields for repertoire metadata

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#215]
We have `required` specified for rearrangements, but we don't for the new repertoire metadata. According to MiAIRR, most of these fields are `required` but `nullable` so should we do the similar behavior in that we insure/validate those fields are always in the file format? This ties in with issue #213 on whether those required fields should always be returned from queries?

**Comment by bcorrie** [comment]
I think all MiAIRR fields are required (but nullable) are they not???

**Comment by schristley** [comment]
Most are. Boolean fields are generally not nullable, and some which may be marked as nullable, we would want to think about, for example like identifier fields like sample_id, subject_id, and there might be others. There are also the non-MiAIRR fields to think about.

**Comment by laserson** [comment]
I'd be super-cautious with declaring a field non-nullable in the format spec. Someone will have a use case where they don't need that particular field, but their data will technically be out of compliance. $0.02

**Comment by schristley** [comment]
I've written the validate_repertoire() function in the python library and it may have worked out differently than expected. Most of the MiAIRR fields are marked as

```
require:true
nullable:true
```

What that means in the actual data is that those keys need to actually exist in the data file, so take this snippet for `study_id`. This data is valid because the key `study_id` exists, but it allowed to be null.

```
study:
      study_id: null
      study_title: "My study"
```

This is fine as well as a blank string:

```
study:
      study_id: ""
      study_title: "My study"
```

But if you don't have the `study_id` key at all, then it is a validation error:

```
study:
      study_title: "My study"
```

```
validation error: MiAIRR required field study.study_id is missing
```

**Comment by bcorrie** [comment]
I think this would be correct behavior though, right? Is the different outcome that you mention a problem? Too many required/nullable fields?

**Comment by schristley** [comment]
Yeah, it's correct. It's many fields though as all MiAIRR fields are required.

**Comment by schristley** [comment]
consensus seems that the MiAIRR definitions are sufficient
