### ISSUE TITLE
additional documentation for library_generation_method

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#219]
MiAIRR field `library_generation_method` has a controlled vocabulary for acceptable values. These values are concise and use acronyms that users may not immediately recognize, e.g. `RT(specific)+TS+PCR`. We need additional documentation that explains each of the values in more detail.

**Comment by bussec** [comment]
The terms are explained in [`NCBI_implementation/mapping_MiAIRR_SRA_library_terms.rst`](https://github.com/airr-community/airr-standards/blob/master/NCBI_implementation/mapping_MiAIRR_SRA_library_terms.rst), but I agree that they might be better placed in the docs. Any specific location to which you would like this to move?

**Comment by schristley** [comment]
The rearrangement schema doc actually lists out all of the fields and puts them in a table. It does this by reading the schema file. We should do something similar for the repertoire metadata, in which case the explanation can go in one of two places:

- In the schema itself, like the `description` field
- In a `Definitions Clarification` section like the rearrangement schema has

**Comment by schristley** [comment]
@bussec I've put in some rough work to generate field tables for all of the metadata schema objects and their fields.

http://docs.airr-community.org/en/metadata-docs/datarep/metadata.html#repertoire-fields

We should think of a few things to enhance:

- How to signify ontology-based and controlled_vocabulary fields? For the controlled_vocabulary (enum) we should list the acceptable values in the doc.

- Is it okay to have a `Definitions Clarification` that is only in the docs, or should it also be in the schema somewhere?

- Some of the descriptions are quite long, e.g. `complete_sequences`. Maybe this should be shortened, and the extra detail added to `Definitions Clarification`?
