### ISSUE TITLE
"Freezing" a version of MiAIRR?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#22]
Hello All,

We are trying to use the MiAIRR spec to define the iReceptor API. The iReceptor API is used to access information from iReceptor Repositories and is used by the iReceptor Gateway to query individual repositories and federate responses across those repositories. By using MiAIRR, in principle any data repository that has MiAIRR data in it could be linked into the iReceptor network by implementing the iReceptor API.

We are currently using a number of the columns from the MiAIRR TSV file, primarily the MiAIRR field designation, the data type, the content type (to some degree), and the AIRR Format field names. Much of this is being done through use of the YAML file. Our problem is that we need something that is relatively stable (a v0.1 release) that we can develop against.

The Travis job will help to ensure the TSV and the YAML stay in sync, but the reality is that at some point we should probably freeze our master branch with a tagged release (probably linked to something around the MiAIRR manuscript) and limit changes on the development branch with considered merges back to master. Currently the master branch is changing faster than the development branch 8-)

Does it make sense to "freeze" a version of the MiAIRR spec (presumably the Master branch with a release tag), possibly linked to the MiAIRR manuscript, and move the development work into the development branch?

For us it would be better to have a frozen release ASAP do we can develop against it. We are targeting the December meeting for having the iReceptor repositories, APIs, and our Gateway implement a significant part of MiAIRR, but we need something stable to develop against... 

Thoughts on moving in this direction???

Brian

**Comment by schristley** [comment]
Agree. Ahmad has already created v1.0 and v1.1 tags though those are from before the definitions yaml was added. We might want to reorganize the tags, using v0.X for this prerelease work and v1.0 for the manuscript release.

**Comment by BusseChristian** [comment]
Also agree. We will probably still need until next week to sort #14 and realted NCBI<->MiAIRR mappings, but I agree that it would be good to have a _real_ `stable` and `devel` branch soon.

**Comment by schristley** [comment]
We should turn on branch protection for master, which will help us enforce a consistent dev process.

**Comment by bcorrie** [comment]
Great, thanks... If the time line for a stable release is a small number of weeks, then that is fine. If there are some important outstanding issues (I have one more to query about) we should try and resolve them properly rather than rush. As long as the plan is to freeze it soonish, that will be fine...

**Comment by laserson** [comment]
I would be strongly in favor of cutting a release, but I would strongly recommend *against* releasing a v1.0 any time soon (with or without a paper).  It seems many things are still in flux, and releasing a v1.0 implies that we are committing strongly to a particular interface.  There is nothing wrong with releasing a v0.x and using it.  (Major components of internet infrastructure are still on v0.x)

**Comment by bcorrie** [comment]
That is fine for me as well... I agree, things are very much in flux and it is probably wrong to send the message that this is an agreed v1.0 standard. Until things are more solid (things aren't changed daily/weekly 8-) having a v0.1 is probably fine... Have a v0.1 is important though, so we can have something to develop against. I think the trick is to answer the question what do we try to resolve for v0.1, which determines how long until v0.1 is frozen.

I would prefer sooner rather than later, as any change results in us having to adjust many components in our software stack. Until we have the generation of these specs automated, this is time consuming. Our critical path for December is starting to get to a point where we can't afford to waste time 8-)

Brian

**Comment by schristley** [comment]
pre-release candidate v0.1.0 is tagged!
