### ISSUE TITLE
Include cell_id, pair_id, and clone_id in ADC API queryable fields

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#224]
Just on an MinStd call, talking about single cell extensions to MiAIRR and the MinStd manuscript that is planned for next year... I notice that the cell_id, pair_id, and clone_id are not queryable in the current ADC API manuscript. Should they be...

I think we probably want to be able to do things on the /rearrangement entry point like:

{
"filters":{"op":"=","content": { "field":"cell_id","value":"W06_046_091"}},
"fields" :["repertoire_id","v_call","d_call","j_call","junction_aa"]
}

To get a list of rearrangements from a singe cell.

Similarly for pair_id to query for a heavy and light chain pair?

And if you are going there, do we add clone_id as well?

Brian

**Comment by schristley** [comment]
Yes, I think all identifiers should be queryable. Also `clone_id` and `sequence_id`. Though to be clear that these are not globally unique identifiers, so users should restrict their search within a specific repertoire and maybe even within a specific data processing:

```
{
"filters":{"op":"and","content":[
     {"op":"=","content": { "field":"repertoire_id","value":"my_rep_id"}},
     {"op":"=","content": { "field":"data_processing_id","value":"my_dp_id"}},
     {"op":"=","content": { "field":"cell_id","value":"W06_046_091"}}],
"fields" :["repertoire_id","v_call","d_call","j_call","junction_aa"]
}
```

**Comment by bcorrie** [comment]
@schristley I made this change to the recent manuscript doc and sent it to you, I think we can close this issue...

**Comment by schristley** [comment]
The reference implementation has been updated but I still need to update the docs.

**Comment by schristley** [comment]
Added section to the docs which lists these fields as well as some other generic limits.
