### ISSUE TITLE
ADC API query tests

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#237]
Hi All,

I am working on some query tests, essentially a set of JSON queries that will test the ADC API. I was wondering where the right place for them might be. I notice that the current query examples are in the lang/python/examples area.

I am wondering a couple of things:

1. Is /lang/python/examples the right place for JSON queries, in particular those that are being used in the documentation. Should the doc query examples be moved to the docs directory? Or should the doc query examples be moved to the functional testing directory discussed below?
2. The tests I am working on are functional test, not unit tests. That is, they aren't tests that would be used in confirming the source code is working when you push changes to git, they are tests that an operating repository could use to test that their API and repository is working. It appears to me that the "tests" directories that exist currently are focused on unit tests. Where would be a good place to store such tests?

**Comment by bcorrie** [comment]
For the moment, I am maintaining a set of queries and a set of scripts to test the ADC API here:

https://github.com/ireceptor-plus/WP2/tree/master/api-hackathon/adc-api/ADCTest

I will move these to the ADC API test github when @schristley  sets up the test github. @javh I agree that these should be linked to the documentation (your (1)) and we will probably do that as part of our AIRR Compliance for repositories docs discussed in #238

**Comment by schristley** [comment]
@bcorrie I've created adc-api-tests repository and put in a bunch of initial repertoire tests. Could you stick in your test driver to automate running them?

There are a few things we probably need to decide

- How to check returned data? For things like operators and such, we need to check that the correct data records are returned. The standard idea is to have a `gold` file which is compared against.

- For error cases, we can check the HTTP status code but should we also check the message? While we cannot enforce the exact message, we could do a regular expression to expect certain words to be present?

- If we check against a gold file, that means we have to have specific data loaded into the repository. Running it against random data will not tell you if the query was actually run properly.

- Do we need to define some sort of test definition file, like this example in yaml, which the test driver can use to automate checking the results? I'm not sure if we can make assumptions about return codes, gold file names, etc., or if we should explicitly define them for each test.

```
pass-equals-op:
    code: 200
    gold_file: something.gold.json

fail-missing-op:
    code: 400
```

**Comment by bcorrie** [comment]
> There are a few things we probably need to decide
> 
> * How to check returned data? For things like operators and such, we need to check that the correct data records are returned. The standard idea is to have a `gold` file which is compared against.
> * For error cases, we can check the HTTP status code but should we also check the message? While we cannot enforce the exact message, we could do a regular expression to expect certain words to be present?

Currently I check for correct structure of the response, for example, I check that the /airr/v1/repertoire response has an "Info" and a "Repertoire" block, but not much more than that.

I think checking the content based on comparison to a known data set is much more challenging and should probably be considered a separate set of tests.

**Comment by schristley** [comment]
I'm thinking of a test suite that verifies the functionality of the ADC API reference implementation as the first thing, as that needs to be correct as implementations will rely upon it. Re-using that test suite against existing implementations for AIRR compliance is the second thing, and yes that may require modifying the tests and/or require implementations to load up test datasets to test against.

**Comment by schristley** [comment]
> Currently I check for correct structure of the response, for example, I check that the /airr/v1/repertoire response has an "Info" and a "Repertoire" block, but not much more than that.

That's a good start, we can add more in as we go. I've used the naming convection`fail-*` for tests that expect an error status code and `pass-*` for ones that expect data to be returned, so maybe that is sufficient for now.

**Comment by bcorrie** [comment]
I added some tests yesterday, and added a new prefix to queries that test specific field characteristics (as opposed to operators working). I created a new pass-field-pcr_target_locus.json and moved the organism tests to have a pass-field-organism* structure.

**Comment by schristley** [comment]
@bcorrie Cool, but we need to be careful. I've constructed some of the test queries in a certain way so for example [this change](https://github.com/airr-community/adc-api-tests/commit/7ec95085ab7f33c8092713662adf44c35a029154) alters the semantics of the query.

I notice you are using `CDR3` but that is not a valid `pcr_target_locus`.

Also, with adding tests like pass-field-pcr_target_locus.json and pass-field-organism*, are you thinking that we should have tests for each field?

**Comment by bcorrie** [comment]
> @bcorrie Cool, but we need to be careful. I've constructed some of the test queries in a certain way so for example [this change](https://github.com/airr-community/adc-api-tests/commit/7ec95085ab7f33c8092713662adf44c35a029154) alters the semantics of the query.

I kind of did that on purpose 8-)  The reason I made the change was that the contains text was "absence of CD8" and that seemed very specific to the description used for a specific study. That is, one study might describe that characteristic with "absence of CD8" and another might use "lack of CD8". Since we don't have a controlled vocabulary for cell_phenotype it is a challenging search to find a cell phenotype that doesn't have CD8. The search would be unlikely to find all of the cell_phenotypes that had an absence of CD8 due to that ambiguity so I didn't think that was a great example. 

I thought it better to have a contains example query that wasn't so "challenging". Maybe a better example would be to search for "CD8+" since my simple "CD8" search would return things that were both "absence of CD8" and  "CD8+". It seems like CD8+ is a more common way of specifying the presence of CD8 so maybe that is a better example?

**Comment by schristley** [comment]
> so I didn't think that was a great example.

I understand but that's not the point of the test. It isn't an example, it's specific query to test specific functionality and expect a specific result. If you want to create example queries, my suggestion is to do them in the documentation.

**Comment by bcorrie** [comment]
> I notice you are using `CDR3` but that is not a valid `pcr_target_locus`.

That is my bad, we are using an old set of metadata on our test ADC API server, we have fixed that on our production repositories so no more pcr_targe_locus == CDR3 8-).

I have changed the queries back...

**Comment by bcorrie** [comment]
> > so I didn't think that was a great example.
> 
> I understand but that's not the point of the test. It isn't an example, it's specific query to test specific functionality and expect a specific result. If you want to create example queries, my suggestion is to do them in the documentation.

Ahh, so you are thinking towards testing these queries against known results, so you were specifically targeting that query at a specific study... 

I had been thinking that the large battery of tests that we have now would more be functional tests at the basic API response level that we can use to test any API. That was why I changed it to CD8, so it would find and return repertoires in "most" repositories. Your query returns an empty repertoire list on the iReceptor repository, so it is hard for me to tell if it is working or not. My query returns data that can check for the existence of the string CD8 in the response. So it is more useful as a general API check while yours is more useful to test for specific data.

I guess the question is, do we have a second set of tests where we actually check the return result for actual data consistency with known data or do we want to perform that check on all of these tests? I was assuming we would have a smaller set of deeper tests, but that isn't necessary I suppose.

**Comment by schristley** [comment]
> Ahh, so you are thinking towards testing these queries against known results, so you were specifically targeting that query at a specific study...

yeah, the datasets directory has one test dataset, which might be all that is needed. One thing I realized is that some tests might require putting special data into the test dataset, i.e. data which isn't really consistent with a true study. It's my intent to update your test driver so that it actually checks the contents of the data being returned.

My thought is that implementations will only need to load up the dataset once into a staging version of their repository, then they just run the test suite for their code changes. For example, for VDJServer, I will have a staging VM which has this dataset loaded up. When I make a change to the repository code, I push and test it on the staging VM, then if it's okay then I can push it out to production.

**Comment by schristley** [comment]
@bcorrie All of the `repertoire/*.json` tests are passing against the reference implementation except for three. One is invalid json and the other two are facets tests. These are actually bugs with the test driver.

How do you want to indicate so that the test driver knows the right operation, should we keep going with the filename approach?

- start file name with `fail-json` if it's invalid json?

- start file name `pass-facet` or `fail-facet` to indicate its a facet test?

**Comment by bcorrie** [comment]
I wonder if we should maybe use the file name to indicate a basic level of testing where you test the response basic constructs ("Info" + "Facet"|"Repertoire"|"Rearrangement") with just the file name. If we go any further than that we would use some sort of matching test output file (as you describe above) to test the content of the response -  things like the number of expected results, a content check on the expected results, etc.

For example, pass-facet*.json would check the repertoire endpoint and expect in the response an "Info" object and a "Facet" object. A pass-repertoire-*.json would check for an "Info" object and a "Repertoire" object. Similar for "Rearrangement". None of these would check the contents of the response blocks. Any content checks would be done according to the accompanying content check file. If a content check file doesn't exist, it just performs the structure check above.

For the fail tests are a bit more complicated to encode in the file name I think... Maybe encode the HTTP response code expected as well? fail-400-json*.json 

Then for fail-500*.json, we probably want to specify a further test in the "message" field. But maybe the checks for that could be left to an accompanying content check file?

**Comment by bcorrie** [comment]
I think that other than checking for the "Facet" object on facet queries, the above is how the current test script works. 

I guess the other difference is that the endpoint to use is specified as command line argument and is not part of the file name...

**Comment by schristley** [comment]
> If we go any further than that we would use some sort of matching test output file

I have the beginnings of this in my dev environment but still working on it.

> Maybe encode the HTTP response code expected as well? fail-400-json*.json

All the failed tests return 400, so I've modified the test driver to assume that for fail*.json, but that's not the most general.

It should not be possible to force an internal server error 500 from a query. However, in the future we might have 403 unauthorized return codes.

If we are really going to get any deeper than this, we should stop with filename conventions and go to a test definition file where we can handle any/all future complexity.

```
pass-equals-op:
    code: 200
    gold_file: something.gold.json

fail-missing-op:
    code: 400
 ```

**Comment by schristley** [comment]
> The tests I am working on are functional test, not unit tests. That is, they aren't tests that would be used in confirming the source code is working when you push changes to git, they are tests that an operating repository could use to test that their API and repository is working. It appears to me that the "tests" directories that exist currently are focused on unit tests. Where would be a good place to store such tests?

@bcorrie I realize I took over your issue and changed it from the tests you wanted to write, to the test suite I was intending for the ADC API reference implementation. Are you thinking of this as a AIRR compliance test? If it is only to test that a repository "is working" then you don't really need a test suite for that, just run some example queries.

But to answer your question, I think a functional test suite you are thinking about is useful, if it's purpose is made more clear. You could create a new repository, but then maybe that just adds more maintenance for two test suites. Maybe you can add these into `adc-api-tests` under a new directory (functional?, integration?, stress?, performance?), and we can enhance the test driver to support those tests as well.

**Comment by bcorrie** [comment]
> @bcorrie I realize I took over your issue and changed it from the tests you wanted to write, to the test suite I was intending for the ADC API reference implementation. Are you thinking of this as a AIRR compliance test? If it is only to test that a repository "is working" then you don't really need a test suite for that, just run some example queries.

I think there is a place for tests that test the functionality of a repositories API but that does not test the actual values returned (your gold.yaml). The main reason I think this is important is to be able to test active APIs to confirm they are functioning on all the standard operators without having to have the repositories contain the test data.

I think the tests we have now are fine for that, I think we should just make it such that the test code has an option to run without testing against the gold.yaml file.

**Comment by schristley** [comment]
> I think the tests we have now are fine for that, I think we should just make it such that the test code has an option to run without testing against the gold.yaml file.

That sounds good, that should be an easy switch to add to the test driver.

**Comment by bcorrie** [comment]
> > I think the tests we have now are fine for that, I think we should just make it such that the test code has an option to run without testing against the gold.yaml file.
> 
> That sounds good, that should be an easy switch to add to the test driver.

Done... https://github.com/airr-community/adc-api-tests/commit/7c22d340804841dd1451192d84dade15c3c2b3df

**Comment by bcorrie** [comment]
@schristley closing this issue, I think the topics in it are resolved, we can create new issues around improvements as required... 

Reopen if I have missed anything...
