### ISSUE TITLE
Update docs on AIRR Compliant repositories

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#238]
Notes from CRWG meeting 2019-08-29 on docs for ADC compliant repositories.

We want to maintain a list of AIRR Compliant repositories on the docs page.

http://docs.airr-community.org/en/metadata-docs/standards/data_submission.html

This can act as our initial registry. The plan is to keep it limited to ADC Compliant repositories, and refer to other AIRR-seq repositories on b-t.cr. Repositories should self validate and request being listed through the normal AIRR CRWG contact email.

We want to get more information for each of the compliant repositories, such as URLs and contact information. ADC Compliance comes from the AIRR CRWG recommendations.

**Comment by scharch** [comment]
Closing as it appears this is done: https://docs.airr-community.org/en/stable/api/adc.html
