### ISSUE TITLE
How to handle the query of novel fields for /repertoire endpoint

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#239]
This is related to #230 but in regards to queries on /repertoire rather than returning data in AIRR TSV. If a repository has a novel (non AIRR) fields in the repository, should the API be able to query on those fields?

{ "op":"=", "content": { "field":"my_important_field", "value":"my_important_value" }}

If this is allowed, what should the response be if a repository doesn't have that field. I assume the response would be the same as the response where a query is issued for a non-required field that a repository doesn't store. It has no data so it returns a successful (the query is valid) but empty (the repository doesn't have any data that meets the search criteria) result. 

Note that this does not apply to /rearrangement because the fields that can be queried upon in /rearrangement is limited.

**Comment by schristley** [comment]
One of the challenges for this is handling the data type properly. If the field is an integer but the query is performed as a string, then the data might not be found. With the AIRR schema, we know the data types of the AIRR fields so the repository can construct an appropriate query to its backend databases.

You can see how the reference implementation does that [here](https://github.com/airr-community/adc-api-js-mongodb/blob/master/app/api/controllers/repertoire.js#L79)

**Comment by bcorrie** [comment]
Hmmm, I think that if one sent a query for a field "my_important_field" that existed, but the there was a type error, then the API/service could return, assuming it knew what internal type the field was, a 500 error with a {"message":"Invalid type for query field 'my_important_field', query type 'integer' received, expecting type 'string'"}. This helps with use, as it gives a hint about what went wrong in case the user knew they wanted that field, but were confused about the type.

Similarly, a query on a non-AIRR term that didn't exist could either return

1. a 500 error with  {"message":"Unknown query field 'my_important_field'"} or
2. a 200 success response with no data.

The advantage of 2) is that you get a consistent response from all services, no matter whether they have the data or not. The problem is you can't tell whether there is no data because the field exists and there isn't any data or that the field doesn't exist. 1) solves that, but then the consumer needs to handle error responses appropriately - which probably is OK as the consume has to handle other error conditions...

I think I would lean towards 1) for the field existence case.

**Comment by schristley** [comment]
> The problem is you can't tell whether there is no data because the field exists and there isn't any data or that the field doesn't exist.

Yes you can, the "is" and "not" operators are to check if a field "is" missing or is "not" missing.

> assuming it knew what internal type

and how would the service know this? That was kinda my point about why it's a challenge because the service doesn't know the type. If it could just look it up (like it can for the schema fields) then it would be easy.

The Mongo database for example won't return an error if you do a query on an integer field with a string, it just returns no results.

> error with {"message":"Unknown query field 'my_important_field'"} 

Similarly, how would the service know this? I think 2) is the most consistent response for how the query language is designed.

**Comment by bcorrie** [comment]
> { "op":"=", "content": { "field":"my_important_field", "value":"my_important_value" }}

OK, so I think we are saying that it is valid for a service to return a 200 success response that is empty (contains no data) in the following cases:

1. "my_important_field" exists in the repository but doesn't contain data with the value "my_important_value" - query worked but didn't find anything.
2. "my_important_field" exists in the repository but the value sent in the query is the wrong type (say an integer) - query didn't find any data because it didn't find any data in the field that matched the query (because of a type mismatch) 
3. "my_important_field" does not exist in the repository - query didn't find any data because the field isn't in the repository.

**Comment by schristley** [comment]
@bcorrie Yep, that looks good. I think the only coding change that needs to be made to the ADC API reference implementation is handling the data type for the custom field instead of assuming it is a string.

**Comment by schristley** [comment]
[implemented](https://github.com/airr-community/adc-api-js-mongodb/commit/7d6c084d0d31449d5af0ca7e43be9260c77795d2) in ADC API reference.
