### ISSUE TITLE
Green box fields in BioSample?

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#24]
The NCBI submission template for BioSample contains fields from the green box "#3" section.  Where is this information supposed to go?  For the common repo API, we want to have identifiers that essentially correspond to a sequencing library (so we can pull out all the other minstd metadata), but it's not clear whether taht would correspond to a BioSample id or an SRA experiment id.

**Comment by BusseChristian** [comment]
Not sure whether I understand correctly: With "green box" you are referring to data set 3 as shown [here](http://airr.irmacs.sfu.ca/working_groups/minimal_standards)? Note that this figure is buggy (we are on it), as data set "3/ processing (cell/tissue)" is supposed to go to BioProject (hence the templates) not to SRA (as shown in the figure.

**Comment by laserson** [comment]
Perfect, that issue is exactly what was confusing us.

**Comment by BusseChristian** [comment]
We have produced a corrected version of the overview figure, which should be updated on the website shortly. It is now also included in the repo, see a30484619c223cac577d9ae973482a78b608614f.
