### ISSUE TITLE
Differences between MiAIRR TSV and airr_schema.yaml on metadata_docs branch

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#240]
There are some field definitions in the metadata_docs branch that are different between AIRR_Minimal_Standard_Data_Elements.tsv and specs/airr-schema.yaml

In particular I notice that the keywords_study was added to airr-schema.yaml and not to the AIRR_Minimal_Standard_Data_Elements.tsv. Should these not be consistent? 

I notice that there also appears to be a consistency check for this - tests/check-consistency-miairr.py

**Comment by javh** [comment]
They should be, because we should be generating the tsv from the yaml schema. See #29 

This was on my plate and I just haven't done it yet.

**Comment by bcorrie** [comment]
Should we update AIRR_Minimal_Standard_Data_Elements.tsv manually in the short term. The reason I discovered this was that we are building our API against the "emerging" spec, and I used AIRR_Minimal_Standard_Data_Elements.tsv and was expecting to find the new **keywords_study** field, but it is missing. 

I can add it... But not sure if there is anything else I am missing...

**Comment by javh** [comment]
Well, given how slow I've been at getting to this, it would probably make sense to update it manually if you notice a problem. I doubt it would be a good use of your time to try to find the things you are missing though.

**Comment by bcorrie** [comment]
Changed AIRR_Minimal_Standard_Data_Elements.tsv on metadata_docs branch and closing...
