### ISSUE TITLE
Different API interface for facets?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#241]
@schristley in noting the odd structure of the response when using facets as opposed to doing a "normal" query (see #236), it occurred to us that it might make sense to have a separate API entry point for this. These are actually two quite different functions that are currently implemented in a single API, and it is pretty clear that responses to the API entry points are very different...

The /repertoire search query returns a list of repertoires, the facets query returns a list of summary statistics that may or may not have anything to with a repertoire...

My proposal would be to have a new API entry point that performs counting like operations and drop the facets capability from /repertoire and /rearrangement. My understanding was that we inherited this from the GDC API (https://docs.gdc.cancer.gov/API/Users_Guide/Search_and_Retrieval/#facets) and thought it was useful, but I am not sure it completely makes sense.

Although not 100% sure what this would look like, I would anticipate that the interface to the /repertoire/facets interface would be very similar to /repertoire (it would still keep the query interface) but would only have the "facets" capability and not the fields, from, size.

Note that this fits quite nicely with the need for iReceptor Plus to provide summary statistics from ADC repositories.

**Comment by schristley** [comment]
@bcorrie Yep, we can consider this for V2. I always thought that `facets` in GDC was pretty weak. It almost seems like a QC check, a simple verify that the number of records are what you expect...

**Comment by bcorrie** [comment]
OK, will consider the iR+ work that I am doing along those lines much more closely in the context of extending the ADC API...

Wondering if we should remove the facets capability from v1 of the API (and the manuscript?), with the thought process that having something in v1 that we suspect we might remove in v2 is probably not good. Maybe we move the facets/counting interface into future work for the manuscript?

**Comment by schristley** [comment]
> Wondering if we should remove the facets capability from v1 of the API (and the manuscript?)

It's still useful to have a simple way to count without downloading all the data.

**Comment by bcorrie** [comment]
> > Wondering if we should remove the facets capability from v1 of the API (and the manuscript?)
> 
> It's still useful to have a simple way to count without downloading all the data.

Would we then remove this feature in a later version?

**Comment by schristley** [comment]
> Would we then remove this feature in a later version?

We would leave it in for GDC compatibility.

**Comment by bcorrie** [comment]
@schristley should we close this issue for now, since we aren't working on anything explicit at the moment, and then reopen an issue as required if/when we start working on this... Trying to help you with your issue cleanup and keep things tidy. 8-)

**Comment by schristley** [comment]
@bcorrie you opened it, is it resolved to your satisfaction? ;-D

I'm fine with leaving enhancement requests open as issues.

**Comment by javh** [comment]
You can just label it with the "enhancement" tag. Then it's easy to filter without having to remember that you closed an issue you might care about later.

**Comment by bcorrie** [comment]
I will close it as it is not critical with facets, and maybe come back with something after we do more iR+ work around stats...
