### ISSUE TITLE
Confusion around pcr_target_locus... 8-)

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#244]
In #132 we changed pcr_target to be an array of objects to capture having multiple loci for PCR targeting.

In #175 we have introduce a controlled vocabulary for pcr_target_locus (IGH, IGI, IGK, IGL, TRA, TRB, TRD and TRG).

So far, so good... Now the confusion:

In #174 (https://github.com/airr-community/airr-standards/issues/174#issuecomment-461981880) @schristley stated that one should use pcr_target_locus as follows "... you should list all of the specific genes being targeted. In my example, IGHV4 is actually a family of genes, so if the primer is designed to capture all of the IGHV4 genes then it seems reasonable to use the family name instead of listing each individual gene."

This seems to conflict with #175's controlled vocabulary. Is the gene specific target for PCR in the 
forward_pcr_primer_target_location and reverse_pcr_primer_target_location?

Comments?

**Comment by schristley** [comment]
> In #174 (#174 (comment)) @schristley stated that one should use pcr_target_locus as follows "... you should list all of the specific genes being targeted. In my example, IGHV4 is actually a family of genes, so if the primer is designed to capture all of the IGHV4 genes then it seems reasonable to use the family name instead of listing each individual gene."

my initial confusion was cleared up later in the comments by @bussec and he mentions why the controlled vocabulary is not more specific.

> pcr_target_locus: This field indicates the genetic locus, which in mammals one of TRA, TRB, TRG, TRD, IGH, IGK or IGL (unless you want to do hairsplitting regarding TRAD). This key is supposed to provide high-level information, not primer locations. One of the reasons why we did not try to get more specific here, is the problem with specific targeting (as elaborated above). Hence IGHG1 is not valid (as it is a specific gene) and neither would be IGHV1 (which is a V segment family and therefore rather ill-defined).

**Comment by schristley** [comment]
@bcorrie there's no conflict, my initial confusion was cleared up. Re-open if you think something is missing.
