### ISSUE TITLE
Should sequencing_files be an array?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#245]
@schristley I think the intent for this is to have an array of files here, is that correct? Currently it is only a single object.
```
        sequencing_files:
            $ref: '#/RawSequenceData'
            description: Set of sequencing files produced by the sequencing run
```

**Comment by schristley** [comment]
> Currently it is only a single object.

Yep, which may be two files in the case of pair-end sequencing.

**Comment by bcorrie** [comment]
> > Currently it is only a single object.
> 
> Yep, which may be two files in the case of pair-end sequencing.

Sorry @schristley , to be clear, are you saying this is correct as a single object that may contain either one file name (filename) or two (filename and paired_filename) if pair-end sequencing?

**Comment by schristley** [comment]
Correct as a single object.
