### ISSUE TITLE
Field deprecation protocol?

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#248]
Following up on discussion in #183, I think we need some rules for deprecating fields in the schema, particularly in the `Rearrangement` object as it has a published, official release.

To start the discussion, how does this sound?

* Add `x-airr-deprecated: true` to the field definition.
* Deprecation of fields requires a `MINOR` version number bump (`MAJOR.MINOR.PATCH`).
* Deprecated fields are retained in the schema for at least one `MINOR` version or a minimum of 6 months, whichever affords more time.
* Update R/python package validation tools to handle these cases.

When we update to OpenAPI V3, we'll switch to the official deprecation handling method of adding `deprecated: true`.

**Comment by javh** [comment]
@schristley, can you clear up some confusion for me? This sire implies to me that `deprecated: true` is supported by OpenAPI V2. Am I misunderstanding?

https://swagger.io/docs/specification/2-0/paths-and-operations/

**Comment by bcorrie** [comment]
@javh I think in 2.0 that flag is for URL entry points only, not for fields in the specification... This is commented on in this post, if you read a bit further on to the last answer...

https://stackoverflow.com/questions/49870109/how-to-annotate-a-field-as-deprecated-in-openapi-swagger-2-0

**Comment by schristley** [comment]
> how does this sound?

That sounds pretty good. Can't think of anything additional at the moment.

One slight change, instead of `x-airr-deprecated`, it would be the `deprecated` property in the `x-airr` extension object. (We combined all these flags and stuff into a single object).

**Comment by javh** [comment]
From the call:

Retain deprecated fields forever or at least until the next `MAJOR` version number.

**Comment by schristley** [comment]
I'm thinking a `deprecated-message` or `deprecated-description` field would be nice that tells the user what to do, for example with `age` it might have:

```
deprecated-message: Convert this data into the age_min, age_max and age_unit fields.
```

**Comment by bcorrie** [comment]
Do we want to suggest or specify a default for age_unit? If not, what does it mean to have an age_min or age_max without an age_unit?

**Comment by bussec** [comment]
From the last MiniStd call: Deprecation of a field will not only happen in the context of "deleting" a field, but also of "renaming" it. In this case, there should be a two-way reference between the deprecated field and the one replacing it, e.g., via `replaced-by` and `replacing` keys in `x-airr`.

**Comment by javh** [comment]
From the call:
* Can we push this back to v2.0?  Which will allow for use of the OpenAPI V3 rules.
* We need to add the appropriate text to CONTRIBUTING with the rules.

**Comment by javh** [comment]
There are current a small number of fields (`age` in Subset and `germline_database` in Rearrangement/Alignment) with:

```
x-airr:
    deprecated: true
```

So maybe we do want to include this in v1.3 now and update the protocol for v2.0.  Either that or what to deprecate these fields until v2.0.

**Comment by javh** [comment]
Deprecation attributes and rules have been added to #359.

**Comment by javh** [comment]
Finished in #342.
