### ISSUE TITLE
Which Sample does MiAIRR refer to?

### ISSUE THREAD

**Issue by ahmadchan** [airr-community/airr-standards#25]
Is the sample described in the BioSample submission the primary sample collected from a donor (e.g., blood)? Or is it the derived/processed sample from which sequencing template was extracted (e.g., after flow sorting)?

**Comment by ahmadchan** [comment]
It refers to the primary sample e.g blood and primary sample will link to BioSample ID

**Comment by BusseChristian** [comment]
This is a bit tricky:
I. In the MiAIRR standard, the primary and the processed sample are separate things, which are described in `set 2 / sample` and `set 3 / process (cell)`, respectively. These sets have an (implicit) 1:n relationship.
II. In the current NCBI implementation, a single record submitted to BioSample contains all the fields of `set 1 / subject`, `set 1 / diag. & intervent.`,  `set 2 / sample` and `set 3 / process (cell)`, thus linking them in a 1:1 relation.
As MiAIRR is rather clear about this (I) and @ahmadchan's comment, I assume that the uncertainty about what `set  2 / sample` refers to (primary or processed) originates from the fixed linkage described in (II). The assumption of the NCBI implementation is that the cartesian product of the four sets described in (II) will be used to serialize the 1:n relationships. Therefore, while each BioSample record will have a 1:1 relation, the overall study does not. Third party databases could implement routines to deduplicate the data.

**Comment by frubelt** [comment]
Hi Ahmad,

Does Christians answer your question? Not perfect, but I think we have to live with it for now.

Florian



On Oct 12, 2017, at 6:51 PM, Christian Busse <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a bit tricky:
I. In the MiAIRR standard, the primary and the processed sample are separate things, which are described in set 2 / sample and set 3 / process (cell), respectively. These sets have an (implicit) 1:n relationship.
II. In the current NCBI implementation, a single record submitted to BioSample contains all the fields of set 1 / subject, set 1 / diag. & intervent., set 2 / sample and set 3 / process (cell), thus linking them in a 1:1 relation.
As MiAIRR is rather clear about this (I) and @ahmadchan<https://github.com/ahmadchan>'s comment, I assume that the uncertainty about what set 2 / sample refers to (primary or processed) originates from the fixed linkage described in (II). The assumption of the NCBI implementation is that the cartesian product of the four sets described in (II) will be used to serialize the 1:n relationships. Therefore, while each BioSample record will have a 1:1 relation, the overall study does not. Third party databases could implement routines to deduplicate the data.

**Comment by BusseChristian** [comment]
We realized in today's call that there was a mistake in the figure depicting the mapping of MiAIRR elements to NCBI: The elements of `set 3 / process (cell)` appeared as mapped to SRA instead of BioSample. This was incorrect and has been fixed in commit dbadf8b9dcea444fab1d0a57f4478414fc7c9998.
