### ISSUE TITLE
HLA info for subjects

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#252]
If we have HLA information for subjects, any suggestion on how this should be recorded in the repertoire metadata?

**Comment by watsoc04** [comment]
﻿You wanna open that can of worms, huh?

**Comment by schristley** [comment]
> You wanna open that can of worms, huh?

lol, I got so many cans of worms open...

I was thinking of just adding an `hla` string field with a list of like `HLA-A*01, HLA-A*68, HLA-B*14, HLA-B*57` but I thought I might ask...

**Comment by schristley** [comment]
Actually made it an array of strings.

**Comment by bcorrie** [comment]
@schristley where did this get added???

**Comment by schristley** [comment]
@bcorrie it didn't get added anywhere. I just did something specifically for the analysis I was doing.

Nobody put forward a proposal so once there is a proposal for discussion and interest to do this, then re-open

**Comment by bcorrie** [comment]
Ahh, I interpreted the above as you having added an hla field to the spec and I couldn't find it...

**Comment by bussec** [comment]
In case we should revisit this issue, please note that "HLA" is human specific. If this is the intention, and you consider this metadata, we could e.g. include it in the #264 extension (I think it would fit there). Otherwise the field should be called "MHC".

**Comment by bcorrie** [comment]
A comment for posterity (since this issue is closed) but I would think it would make sense to track this as MHC since it exists across species and is not human specific??? My understanding is that if exists(MHC) and species == "Home Sapiens" then we are talking about HLA, but calling the field name MHC would not be confusing to users of the standard, no?

**Comment by bussec** [comment]
Yes, `MHC` is generic and would do the job. This was just thinking about a "MiAIRR Core" approach, as I am not sure from how many species we would realistically annotate this, i.e. whether we should have an `MHC` field in MiAIRR Core to start with...
