### ISSUE TITLE
physical_linkage has nullable=false

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#253]
The schema has `physical_linkage` as `nullable=false` with an enum value of `none` or `hetero_head-head`. Is it necessary to have the `none` string, or can we allow this field to be `nullable=true` and null is assumed to be `none`?

**Comment by bussec** [comment]
We set this key as non-nullable as the information should always be present for an experiment. But I agree that in real life, your proposed modification will convey the same information. Is there any special reason why you would like to get rid of `none`?

**Comment by schristley** [comment]
Not really, I was just writing some conversion scripts and that popped out in validation (nice to see that works!) as not having a value. I was thinking `null` would save space as that seems like it would be a really common value but `none` does make the information more explicit.

I suppose we are a bit ambiguous with some of our fields where we don't specify the difference between "not collected" versus "unknown" versus "none". Like `strain_name` where if the organism is human then a null value essentially means none, while if the organism is mouse then a null value is ambiguous.
