### ISSUE TITLE
Not clear how "Content format" is stored in the yaml file

### ISSUE THREAD

**Issue by franasa** [airr-community/airr-standards#255]
Hi all, as my first contribution I made this simple script to create a .tsv file from the airr-schema.yaml. It is not clear to me how the "Content format" column from AIRR_Minimal_Standard_Data_Elements.tsv was created, can anyone give me a hint?
I am also looking forward to any feedback (I hope I'm not breaking anything)

**Comment by bussec** [comment]
Thanks @franasa ! There was a glitch in the position of the commit in the tree, so I just rebased it to `master` (instead of `issue-192`). Please fetch again from `origin`.

**Comment by schristley** [comment]
Within `x-airr` there is a `format` field which has a controlled vocabulary defined [here](https://github.com/airr-community/airr-standards/blob/master/specs/airr-schema.yaml#L60). If the `format` field is not there, or is null then the full range of the data type is assumed, e.g. "free text" or "any number"

If it's `ontology` then there should be an `ontology` field in `x-airr` for the ontology. If it's `controlled_vocabulary` then the field should have an `enum` with the list of allowed values, and lastly `physical quantity` has a [physical quantity](https://en.wikipedia.org/wiki/Physical_quantity)

**Comment by schristley** [comment]
thanks @franasa ! Likely what we will do is integrate your code into the docs, specifically `conf.py` which can generate the TSV when the docs are generated, which I think the design laid out in #29

**Comment by javh** [comment]
Great, thanks @franasa.

You can see how the other tsv files are currently being generated from the yaml spec starting on [line 246](https://github.com/airr-community/airr-standards/blob/metadata-docs/docs/conf.py#L246) of `docs/conf.py` in `metadata-docs` branch. 

Just plug your code into that block after the other entries and add link to the new tsv in an appropriate place in the MiAIRR docs.

**Comment by franasa** [comment]
thanks for your comments!, I just integrated some lines at the bottom of `docs/conf.py` including your comments. @schristley, in #192 data `type` is number but in the master it is integer, will it be changed to number, should i include this in the future? 
@javh the file is saved as `AIRR_Minimal_Standard_Data_Elements.tsv`  in the same `_downloads` folder where the previous files are generated, is this fine? I was not sure what you exactly meant with _add link to the new tsv in an appropriate place in the MiAIRR docs_. could you please elaborate on that?  thanks a lot!

**Comment by schristley** [comment]
> in #192 data type is number but in the master it is integer, will it be changed to number, should i include this in the future?

yes, the spec in issue-192 branch is the most up-to-date for the age fields

**Comment by javh** [comment]
> I was not sure what you exactly meant with add link to the new tsv in an appropriate place in the MiAIRR docs. could you please elaborate on that? thanks a lot!

Oh, I meant update the link to the tsv in `docs/miairr/introduction_miairr.rst` to point to the new tsv in docs/_downloads. The link to the old tsv be elsewhere as well - I'm not sure.

**Comment by franasa** [comment]
> yes, the spec in issue-192 branch is the most up-to-date for the age fields
@schristley  Is it fine if I change it after its merged with master? 

> The link to the old tsv might be elsewhere in the docs as well - I'm not sure.

@javh I added it now as a download. For now I just left the link to the old file like [this](https://github.com/airr-community/airr-standards/commit/8d221ada34e93312f33fae4e852e528b5464e249#diff-3e977bd4bfbd0ac71439670716e3ce5d) but needs further review (@bussec?)

**Comment by javh** [comment]
Do we need to preserve the link to the old version?

**Comment by schristley** [comment]
> Do we need to preserve the link to the old version?

I suppose we could point to prior releases, v1.1, v1.2, etc., as a convenience. We don't have that TSV file as a specific downloadable file in the release, people would need to download the release tarball.

**Comment by javh** [comment]
We can also build the docs pointing at specific release tags, so that we have "stable" (latest version), "latest" (directly from master, like now) and various version tags. ReadTheDocs makes the first two easy all you need is semantic version numbered tags and it'll figure out "stable" for you.

**Comment by franasa** [comment]
[**1bc950b**](https://github.com/airr-community/airr-standards/commit/1bc950b6b5511d4809a46e42761ac7a745d2772b) is my latest commit.  @schristley is it good to be merged into the [`metadata-docs`](https://github.com/airr-community/airr-standards/tree/metadata-docs) branch as you discussed with Christian? the TSV is still created and linked as Jason pointed in https://github.com/airr-community/airr-standards/issues/255#issuecomment-536751919
