### ISSUE TITLE
Human Population Genetics Extension

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#264]
Background: MiAIRR currently contains a number of fields that do not necessarily meet the stringent definition for being "minimal", in the sense of being *independent* of the specifics of a study (e.g. human subjects). To increase the usability and acceptance of MiAIRR and prevent potentially erroneous or misleading annotation (for the sake of "standard compliance"), it seems appropriate to move such fields out of the "core" standard and into separate "extensions". These will then be required to be used in a modular fashion if certain conditions are met by a study. This will also solve (some) of the issues related to a single field requiring multiple ontologies, depending on the context.

Proposal: Move the following fields, which are primarily aimed at human populations, into a "Human Population Genetics" extension. The name represents that the involved fields focus on the information regrading the ancestry of a subject. Note that the fields will be **removed** from the MiAIRR v2 Core Standard.

* `ancestry_population`
* `ethnicity`
* `race`
* `country_birth` (defined in #265 )
* `collection_country` (defined in #265  )

**Comment by bcorrie** [comment]
@bussec I think I like this idea... In particular from a data management perspective, it is nice to have things blocked like this because it makes it easier to provide (or deny) access to sensitive data that might be human subject related.

**Comment by bussec** [comment]
As a potential ontology for some of the fields we should have a look at [HANCESTRO](https://bioportal.bioontology.org/ontologies/HANCESTRO).

**Comment by williamdlees** [comment]
I think this is a good approach. The 'Ancestry category' of HANCESTRO feels to me to be at the right level for general use - perhaps it would be worth having a free text field for more specific details where a study has focussed on them, but for broad general use the HANCESTRO category is at the right level, I think.

**Comment by bussec** [comment]
I think we are slowly converging on the ontologies for `ancestry_population`, `country_birth` and `collection_country` (see discussion in #265). However, if anyone has suggestions for *globally applicable* vocabularies for `ethnicity` and `race`, please share your ideas ;-)

Otherwise we need to discuss whether we implement a more complex annotation with variable ontologies or simply not include these fields in the HPG-XT (but yet remove them from MiAIRR2.0, which will effectively deprecate them).

**Comment by bussec** [comment]
From today's MiniStd call:
* Moving/Introducing the fields `ancestry_population`, `country_birth` and `collection_country` to/in an Extensions is *approved*.
* As `ethnicity` and `race` have neither a consistent scientific concept nor globally applicable ontologies, they are *removed* from MiAIRR and its extensions. Note that annotators would wish
to provide this information can still do so using these keywords as `optional` free text fields.

**Comment by watsoc04** [comment]
Heyo
Sorry, I missed…I had a lab crisis to deal with…I guess the call was productive?
Corey
