### ISSUE TITLE
Rename `organism` to `species`?

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#266]
Not keen to bring this up, but working on #260 I realized that the `organism` field should actually be termed `species`, see [species](https://en.wikipedia.org/wiki/Species) and [organism](https://en.wikipedia.org/wiki/Organism). The decision for `organism` was originally based on the use of the `/organism` qualifier by INSDC. The [INSDC FT docs](http://www.insdc.org/documents/feature-table) use an "organism is-a species" construct to justify the name of the qualifier. However, this is difficult to apply when the term should be used as a suffix (`cell_species` is rather obvious, `cell_organisms` IMO not).

Therefore I wanted to get an idea what peoples' opinion on the following options are:
1. rename `organism` to `species`
2. propagate the mislabeling to other fields encoding species
3. have inconsistent terms for the same information within the AIRR Schema

**Comment by scharch** [comment]
I lean toward 3, but it's a very soft lean...

**Comment by bcorrie** [comment]
I would lean towards fixing it if it is incorrect, but also a very soft lean... We are going to make a major release, if it needs to be fixed better to do it sooner rather than later IMHO.

If we don't fix it then I think what we do want to get right is the description of the AIRR term, as that is what the users will see. For organism we have:

```
            description: Binomial designation of subject's species
                name: Organism
```
So if the actual keyword doesn't change, I would suggest that we change "name: Organism" to "name: Species".

**Comment by bussec** [comment]
Ok, we'll discuss about the MiAIRR field name tomorrow.

**Comment by bussec** [comment]
We discussed this in the MiniStd call today and the general consensus was that we should change the name from "Organism" to "Species" for MiAIRR v2. Note that this is MiAIRR name of the field (i.e. the thing which is encoded in the `name` key - as in Brian's post), not the `organism` field itself. I have a soft lean toward 1 (i.e. also renaming the field), but I am biased as the required changes wouldn't create a substantial workload on my side.

**Comment by bussec** [comment]
Issue was discussed again in the MiniStd call on 2019-12-13 and the decision was made to rename the field in v2.0 of the schema.

**Comment by bcorrie** [comment]
Also discussed at DataRep 2020-03-09 and we agreed that this change made sense... Jump in anyone if they want to clarify...

**Comment by javh** [comment]
Field has been renamed in #359 for v1.3. We'll just need to change the `x-airr: name` tag in v2.0 to:

```
species:
    description: Binomial designation of subject's species
    x-airr:
        name: Species
```

**Comment by bcorrie** [comment]
I think this can be marked as Closed, no?
