### ISSUE TITLE
IMGT Support for AIRR Rearrangement Schema

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#268]
Veronique from IMGT has posted a review table of mappings for support of the AIRR Rearrangement schema here:
http://www.imgt.org/IMGT_vquest/vquest_airr

The main limitation they have with the current fields is the lack of support for additional D segments. They have a list of custom fields for these in the bottom of the table (yellow). Do we want to add these to the schema? (w/ or w/out modifications?)

These few stuck out to me as ones that we might want to take a closer at look at, as either needing to be renamed/remapped or excluded from the official schema (left as custom IMGT fields):

* `5prime_trimmed-n nb`
* `3prime_trimmed-n nb`
* `Sequence_analysis_category`
* `insertions`
* `deletions`

(See also #139 regarding D-D rearrangements.)

**Comment by scharch** [comment]
I would put `d_number` as an excluded field, as well. Also perhaps all of the `d3_X` fields, as this seems unique to IMGT and I'm not sure if there is biological evidence for such rearrangements.

**Comment by javh** [comment]
From the 2019-11-11 call:

* We will incorporate the proposed `d2_*` and `np3_*` fields into the spec, with any additions needed to complete the set of fields.
* The `d3_*` and `n_*` will remain IMGT custom fields for now at least. If more tools end up needing them, then we can add them later. 
* `d_number`, `5prime_trimmed-n nb` `3prime_trimmed-n nb` `Sequence_analysis_category, `insertions`, `deletions` will be IMGT custom fields.

**Comment by javh** [comment]
Added the agreed fields to the spec in #295.

**Comment by javh** [comment]
Resolved in #315.
