### ISSUE TITLE
  Addition of locus field in set 6

### ISSUE THREAD

**Issue by srlak** [airr-community/airr-standards#272]
From a single cell perspectives - v_call, d_call,c_call, j_call and cdr3 annotations are suitable for both heavy (H) and light chains (K, L). It is notable from the names of the genes ('VH10.1.86') if they are heavy or light but this will require user to hard-code the names in the query. So, I’m wondering if it might make sense to add a locus field that is a controlled vocabulary (H, K or L) in set 6 to distinguish between the V,D,J, CDR3 regions of heavy and light chains .

For instance for a single cell, information would look like
```
[
  {
    "Processed sequence with annotations": [
      {
        "c_call": "Igkc", 
        "d_call": NaN, 
        "j_call": "JK4", 
        "junction_aa": "LQSDNLPFT", 
        "locus": "K", 
        "v_call": "bt20"
      }, 
      {
        "c_call": "Ighm", 
        "d_call": NaN, 
        "j_call": "JH4", 
        "junction_aa": "ARSGSYYAMDY", 
        "locus": "H", 
        "v_call": "36-60.1.46"
      }
    ], 
    "cell_id": "1003", 
    "repertoire_id": "0f00cca2c93a21d25a2413b06bba3e81fd5ef3bd5b7ed407c7c189e3771dbf3d", 
    "tissue": "spleen"
  }
]



```

**Comment by bcorrie** [comment]
Hi Sri??? 

Are you talking MiAIRR or the Data Representation specificiation... Most of this is already in the Data Rep spec (https://github.com/airr-community/airr-standards/blob/master/specs/airr-schema.yaml). There is a locus in the spec, and we also have an issue where we are discussing different possible gene and family notations (see #258). 

None of these will probably make into into the MiAIRR minimal standard (https://github.com/airr-community/airr-standards/blob/master/AIRR_Minimal_Standard_Data_Elements.tsv) because I don't think they are considered "minimal", but they will likely be in the DataRep specificiation. Is that correct @bussec ?

Note the gene naming we use in the standard is different than the example you use above (if I am not misunderstanding what you are saying), where you use:

```
 "c_call": "Ighm", 
"locus": "H",
"v_call": "36-60.1.46"
```
the correct AIRR description would be (I think):

```
"c_call": "IGHM"
"locus": "IGH"
"v_call": "IGHV36-60*01"
```
with the discussion in #258 helping us deal with gene's that are not know in a specific germline gene DB such as IMGT...

In the extension from #258 we would also have:

```
"v_subgroup": "IGHV36"
"v_gene": "IGHV36-60"
"v_allele": "01"
```

**Comment by srlak** [comment]
Hi Brian,

My understanding was that only the fields defined in set 6 are represented/queryable in the rearrangement schema/endpoint. However, since the locus field is already being defined; Would it be safe to assume that the airr-schema yaml in rearrangement would solve this issue?. Pls correct my assumption if incorrect. 

However, this leads me to another question, I am now in the phase of creating a rearrangement schema for our single cell data. A snapshot of it is what I pasted above for one cell_id (Note : They are still in the preliminary phase). In our case, one cell will have two sequences for one rearrangement and in rare cases three or more sequences for a cell. Each row will be a cell information which then should have at-least two v_call, d_call, j_call, c_call, junction_aa columns for H and L or K. So I was wondering what would be the best way to distinguish/represent between the v,d,j calls of heavy and light chain for a certain cell_id ? Would it make sense to have fields such as igh_v_call, igk_v_call and igl_v_call.
Not sure how complex it would be? 

Regd the gene naming, the current example was for our data set from Scireptor but yes we still have to adapt Gene Names according to the given standards.
Thanks
Sri

**Comment by schristley** [comment]
> My understanding was that only the fields defined in set 6 are represented/queryable in the rearrangement schema/endpoint.

The ADC API is slightly more expansive than the MiAIRR standard. `locus` is one of the [fields](http://docs.airr-community.org/en/latest/api/adc_api.html#adc-api-limits-and-thresholds) that can be queried upon. If you wish to dynamically determine that set of fields, then you can check the AIRR extension property `adc-api-optional: false` in the AIRR Schema.

**Comment by bcorrie** [comment]
> My understanding was that only the fields defined in set 6 are represented/queryable in the rearrangement schema/endpoint. However, since the locus field is already being defined; Would it be safe to assume that the airr-schema yaml in rearrangement would solve this issue?. Pls correct my assumption if incorrect.

That is an interesting question... From an ADC API endpoint perspective, we have the following:

1. All rearrangement values in the spec can/should be returned if requested (using the fields parameter).
1. The ADC API paper specifies a limited set of fields that are queryable in the API
1. There are a number of x-airr flags on each field in the spec that have certain meanings
1. The adc-api-optional field specifies whether queries on a field is optional or not.

So if a field does not have adc-api-optional:true then it has to be supported as a query. "locus" as a field is not optional for a query.

@schristley is that correct?

**Comment by bcorrie** [comment]
Ahh, it looks like we both answered the question at the same time 8-)

**Comment by schristley** [comment]
> However, this leads me to another question, I am now in the phase of creating a rearrangement schema for our single cell data. A snapshot of it is what I pasted above for one cell_id (Note : They are still in the preliminary phase). In our case, one cell will have two sequences for one rearrangement and in rare cases three or more sequences for a cell. Each row will be a cell information which then should have at-least two v_call, d_call, j_call, c_call, junction_aa columns for H and L or K. So I was wondering what would be the best way to distinguish/represent between the v,d,j calls of heavy and light chain for a certain cell_id ? Would it make sense to have fields such as igh_v_call, igk_v_call and igl_v_call.

If I understand your question correctly, for the AIRR format, you would need to transform that single row with multiple sequences into multiple rows, each with a single sequence. Use `cell_id` to link those multiple rows to each other.

**Comment by bcorrie** [comment]
I think I agree with Scott here, at least at the rearrangement level... In our current rearrangement format, the correct thing to do is have two rearrangements having the same ```cell_id``` linking them. Whenever we have rearrangements that are connected in some way at the cell and chain pair level, we have a mechanism to do that in our current schema, and we should try to avoid adding new things.

I think the outstanding question for me at the moment is, what other information is important at the "cell" level that would be required that isn't associated with a rearrangement and/or a group of rearrangements (such as grouping rearrangements by cell or chain pair)? For example, if we want to annotate a cell or chain pair with some sort of antigen specificity, how would we do that??? 

This is getting a bit off topic for the discussion about locus, so perhaps we should take this discussion to either another new issue and/or the single cell extension pull request???

https://github.com/airr-community/airr-standards/pull/211

**Comment by bussec** [comment]
So thoughts given our recent discussions about how the fields in Set 6 should be governed. If we go along with the idea that these are `rearrangement` fields for which DataRep is responsible, and MiniStd simply defines them as part of MiAIRR Set 6, would the inclusion of `locus` in Set 6 have any impact on DataRep or the ADC API? To my current understanding no, please correct me if I am wrong.

**Comment by bcorrie** [comment]
I don't think so. ```locus``` is already a field in the rearrangements. The only change would be some of the ancillary x-airr fields to this in the spec so that it is noted as an MiAIRR set 6 field. It already exists as a field that should be queried (according to the documentation here http://docs.airr-community.org/en/latest/api/adc_api.html), although I notice that x-airr fields for this in the spec are not set.

**Comment by bussec** [comment]
MiniStd decided in its last call that to hand over the governance of the MiAIRR Set 6 fields to DataRep. MiniStd will only define the whether a given `rearrangement` key is considered "minimal", in which case it will be `miairr: true` and thus become part of Set 6. Setting this to automatically close when #282 is merged.
