### ISSUE TITLE
add repertoire_name and repertoire_description fields to repertoire?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#274]
The `repertoire_id` field is expected to be a computer generated identifier, and it will likely not be very meaningful (or easy to remember) for the user. A `repertoire_name` and `repertoire_description` will provide the user the ability to add a human-readable short name and long description.

**Comment by schristley** [comment]
unless somebody objects, I'd like to add these fields to `Repertoire` for v1.3

**Comment by javh** [comment]
No objection, but should these instead mirror what is in Study: `repertoire_title` and `repertoire_description`?

I prefer `repertoire_name` over `repertoire_title`, so maybe Study is what is off. If we were to add analogous fields in Subject and Sample, `_name` seems more appropriate there as well.

**Comment by schristley** [comment]
`study_title` seems right to me as it is often the paper title, but yeah for subject and sample, `_name` seems more appropriate. The probably don't need to mirror each other.

**Comment by bussec** [comment]
`study_title` was named this way to match the NCBI BioStudy XML `Project/ProjectDescr/Title` key. As we need a mapping for these things anyhow, you could change it to `_name` if you prefer to have consistent suffixes for the schema keys.
