### ISSUE TITLE
Incomplete data_processing in Florian example data?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#275]
@schristley I was just loading the Florian example data set and I notice that there is no information in the the "data_processing" section of the JSON file

https://github.com/airr-community/adc-api-tests/blob/master/datasets/florian/florian.airr.yaml

Should this not have some information about the annotation tool used (software_versions), the germline DB used for the annotation (germline_database), etc?

**Comment by schristley** [comment]
Sure, feel to add some data if you find it useful for testing.

**Comment by schristley** [comment]
Seeing as the test suite isn't going to check exact values, it is only checking the correct number of records are returned, we can add values without messing up the existing tests. You just have to be careful about fields where we do exact queries against.

**Comment by bcorrie** [comment]
> Sure, feel to add some data if you find it useful for testing.

Shouldn't this contain some metadata about how the rearrangements were produced? Which of course I don't know 8-) It doesn't really make sense for me to add some "artificial" data does it?

**Comment by schristley** [comment]
> Shouldn't this contain some metadata about how the rearrangements were produced? Which of course I don't know 8-) It doesn't really make sense for me to add some "artificial" data does it?

Are you asking about the _real_ Florian study, or the test data set used in the test suite for testing, which is based upon the Florian study but has now diverged...

Yes, the _real_ Florian study, obtainable from VDJServer, will have more information in the data processing section.

**Comment by bcorrie** [comment]
OK, because the test data is downloaded from VDJServer, I thought you were using the real Florian data and therefore had the real Florian metadata - just with the data-processing missing.

I don't feel the need to add that to the test data if it doesn't naturally exist. It would just diverge if you ever update the test data and that seems silly... I will close the issue...

**Comment by schristley** [comment]
> I thought you were using the real Florian data...

I was, then I needed to modify it for certain test cases because it didn't contain useful values for doing specific checks (in this case less/greater than operators on numbers) so they diverged.

The test data is pulling the rearrangements from VDJServer. I haven't had to modify those yet but then I've not written many rearrangement tests yet. In reality, we don't need all that data just to do some simple tests...so maybe that will change in the future.
