### ISSUE TITLE
Adding Decombinator to the Applications Supporting AIRR Standards list

### ISSUE THREAD

**Issue by TahelRonel** [airr-community/airr-standards#277]
Hello,

We have just released Decombinator Version 4.0.1 (https://github.com/innate2adaptive/Decombinator), the UCL Chain Lab's T cell repertoire analysis software suite (previously published in, for example, https://doi.org/10.3389/fimmu.2017.01267, https://doi.org/10.1007/978-1-4939-8885-3_2).

One of the key updates to the tool is that the new output is compliant with the AIRR Community schema. Could you please add Decombinator to your list of Applications Supporting AIRR Standards list? (https://docs.airr-community.org/en/latest/resources/support.html).

Thank you,
Tahel Ronel.

**Comment by javh** [comment]
That's great! Thanks, @TahelRonel. Yes, we'll certainly add Decombinator v4.0.1 to the table.

We're in the middle of a doc restructure, so it won't appear on the landing page (stable docs) until we do a new version release, but it'll be in the devel ([latest docs](http://docs.airr-community.org/en/latest/resources/support.html#applicationsupport)) as soon as I commit the change.

**Comment by javh** [comment]
Added here:
http://docs.airr-community.org/en/latest/resources/support.html#applicationsupport

Let me know if anything is correct or if you'd prefer a different primary citation.

**Comment by TahelRonel** [comment]
That’s great, thank you @javh !

**Comment by javh** [comment]
Added in 0c02017.
