### ISSUE TITLE
Should read_length be an array of integers?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#279]
Currently read_length is specified as a string of the format [300,300]

Computationally, this isn't very useful. I want to do a search for all read_lengths > 300 and there is no effective way to do this in the sense that the data is a string and could have odd formatting issues...

I suppose this might be a good time to confirm that there should be one field for this, with an array of either one element or two elements depending on if it was paired-read sequencing???

**Comment by bcorrie** [comment]
Hmm, given that we have a keyword based spec, maybe we keep read_length and add read_length_reverse of the reverse read exists, null if it isn't paired-read sequencing? Both as integers.

**Comment by bcorrie** [comment]
Double Hmmmmm. I see that we have another array in the spec, keywords_study. What does a query look like in the ADC API if I want to query for a study that "contains_ig"?

Are the correct semantics:
```
{"op":"=", "content": {"field":"keywords_study", "value":"contains_ig"}}
```
with this evaluating to true if one of the array elements evaluates to true?

**Comment by bcorrie** [comment]
> I suppose this might be a good time to confirm that there should be one field for this, with an array of either one element or two elements depending on if it was paired-read sequencing???

Related question, what is the "correct" or "definitive" way to determine if a SequencingRun uses paired reads given the spec we have now?

**Comment by bussec** [comment]
Introducing a second keyword for the reverse read length should be ok, as the array is not expected to contain more than two entries. This does of course not fix the general handling of JSON style arrays in string-type variables.
The least ambiguous way to distinguish single from paired read setups is `length(read_length)>1`. The information could also be deduced from `sequencing_kit` but as this is free-text it is only human-readable.

**Comment by schristley** [comment]
> Related question, what is the "correct" or "definitive" way to determine if a SequencingRun uses paired reads given the spec we have now?

Well, I don't know about "definitive", but I check if `paired_filename` has a value.

**Comment by schristley** [comment]
I tend to like the idea of having a second field instead of making `read_length` an array.

**Comment by bcorrie** [comment]
Simple change??? Sort out for ADC v1 and AIRR v1.3?

**Comment by schristley** [comment]
> Kind of begs the question as to whether this field should be in the RawSequenceData object rather than the SequencingRun object.

That seems reasonable to me.

> Simple change??? Sort out for ADC v1 and AIRR v1.3?

sure, seems simple enough to me.

**Comment by bcorrie** [comment]
Made changes on a new branch, created a pull request (#324) to finalize the changes...

**Comment by bcorrie** [comment]
Closing this as the actual implementation of the change is captures in #324
