### ISSUE TITLE
Inconsistent use of array in spec?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#280]
We have a couple of places where arrays are used to contain multiple values for a field. In the spec this is done inconsistently, and when one tries to map this to a query the semantics of the query are not clear.

We currently have:
- keywords_study - which is an array of strings
- pcr_target - which is an array of objects, where each object is a key/value pair with a key value of "pcr_target_locus" and value type of string.

In #279 I suggest changing read_length, which is a string that contains an array like string with two numbers to an array of integers using the "keywords_study" approach.

I got confused when trying to generate a query using either approach, as I don't think the semantics of the queries are clear in either case.

There is an example in the docs for pcr_target_locus:
```
                "op":"=",
                "content": {
                    "field":"sample.pcr_target.pcr_target_locus",
                    "value":"IGH"
                }
```
We are assuming that this means that the query clause evaluates to true if any of the "value" elements in the pcr_target array contain the element IGH??? So this is an "OR" operation for "=" across each array element???

One can assume the same for keywords_study, but in doing so we actually have the same query operating on two different data structures, which is weird.

BTW, in looking at the spec, it is unclear why there is a need for more than one PCR Target. This may be obvious to others, but I am a bit unclear. This might need a clarification in the description for the field?

**Comment by bussec** [comment]
> BTW, in looking at the spec, it is unclear why there is a need for more than one PCR Target. 

You can run multiplex PCRs on multiple loci at the same time. It is not the most frequently used protocol, but technically possible. In this case the resulting libraries would be mixed, which is what we tried to encode in this field.

**Comment by bcorrie** [comment]
> > BTW, in looking at the spec, it is unclear why there is a need for more than one PCR Target.
> 
> You can run multiplex PCRs on multiple loci at the same time. It is not the most frequently used protocol, but technically possible. In this case the resulting libraries would be mixed, which is what we tried to encode in this field.

Ah, lack of clarity - I blame it on working on GitHub issues while on a long flight 8-)

What I meant by this, more than clarifying for me, is that we should probably clarify this in the spec in the description for this field... So someone reading the spec would know what this might be???

**Comment by schristley** [comment]
> We are assuming that this means that the query clause evaluates to true if any of the "value" elements in the pcr_target array contain the element IGH??? So this is an "OR" operation for "=" across each array element???

Yes, that's my understanding of how the query works.

**Comment by schristley** [comment]
> I got confused when trying to generate a query using either approach, as I don't think the semantics of the queries are clear in either case.

You might want to review the Mongo docs on querying [arrays](https://docs.mongodb.com/manual/tutorial/query-arrays/) and [arrays of objects](https://docs.mongodb.com/manual/tutorial/query-array-of-documents/). I don't think the ADC API supports the full capability that Mongo provides.

**Comment by bcorrie** [comment]
> > We are assuming that this means that the query clause evaluates to true if any of the "value" elements in the pcr_target array contain the element IGH??? So this is an "OR" operation for "=" across each array element???
> 
> Yes, that's my understanding of how the query works.

My point is that I think we need to define the semantics of this query, at least in the documentation, don't we??? If we don't specify this, then the service could implement a "surprising" set of semantics. For example, although it doesn't seem quite as logical as the OR operation, if one was really testing for equality for an element (IGH) across an array (pcr_target.pcr_target_locus), true equality would mean that all array elements equaled the search element. If one service implements the OR semantics and a different service implements the AND we have a problem...

So I think we need to specify this in the documentation (as I don't think we can do it via the spec).

**Comment by schristley** [comment]
Yes, there's a need to document a number of query semantics. In some sense, that is part of the larger question of an AIRR-compliant repository, implementing the appropriate semantics as you are correct in that we cannot specify this in the API spec exactly.

**Comment by bussec** [comment]
A related point that I just realized: We have `pcr_target` as array, which is not marked a nullable, but all the variables in the `pcr_target_locus` object are nullable. Does this mean that I would have to create an object that only holds three keys with a `NULL` value?

**Comment by schristley** [comment]
> A related point that I just realized: We have pcr_target as array, which is not marked a nullable, but all the variables in the pcr_target_locus object are nullable. Does this mean that I would have to create an object that only holds three keys with a NULL value?

I think you should be able to just have `pcr_target: null`, I do this for `subject.diagnosis`, but I'm not sure if the validation routine is checking or allowing that. We might need to add `x-airr` to make it more explicit.

**Comment by bcorrie** [comment]
This came up in our implementation once again... Perhaps we can at least sort out the simple case of:

```What are the semantics of an operator on a field that is an array of strings"

We currently have two of these, ```keywords_study``` and ```data_processing_files```. Based on the discussion above, I think we are leaning towards something like this:

```
                "op":"OP",
                "content": {
                    "field":"study.keywords_study",
                    "value":"STRING"
                }
```
The semantics of this query are that for each element ```I``` in the array of N ```keywords_study``` the correct return value would be an ```OR``` operation on the results of N tests ```keywords_study[i] OP "STRING"```

If that is true, I will start a pull request to make that change, I think we need this resolved for the ADC API v1.3.

**Comment by bcorrie** [comment]
@bussec and @schristley can we close this issue assuming this is subsumed by #322 

Or do we want to create a new issue to take consider the situation where a schema object (such as subject.diagnosis or sample.pcr_target) are set to NULL? #322 is primarily an ADC API schema question, where this is more of a data representation thing (although we will need to test this functionality if it is allowed).

**Comment by bcorrie** [comment]
I created a new issue #328 to capture the nullable schema objects... Perhaps we can close this issue as I think #322 and #328 cover this issue.
