### ISSUE TITLE
Changelog for MiAIRR and schemas

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#286]
We agreed in the last DataRep call to have a changelog to document changes. Here are the bullet points from the discussion:

- We agreed on having a changelog to document standards changes.
- The suggestion on the table is to have a unified changelog for MiAIRR and DataRep schemas by documenting the changes of the spec files themselves (airr-schema.yaml, adc-api-yaml, future.yaml).
- We need some additional documentation to clarify the overlap/difference between minimal information (MiAIRR, study reporting) and required schema fields (Rearrangement schema, tool interoperability) to users. This is currently confusing.

We need to operationalize this. Is it is a RST file in github? Is it a file in the docs? What is the format for each of the entries?

I kinda like it being a file in github so it can be viewed directly without having to build the docs (though the docs can include it...). Presumably PRs that change the schema should have an entry added to this file.

**Comment by schristley** [comment]
and we should probably go back to v1.2.1 and document all the changes the best we can.

**Comment by javh** [comment]
My preference would be to have a `NEWS.rst` file at the root that logs changes, which we can then add as an include in the docs. 

Same thing we do for the software packages:
https://raw.githubusercontent.com/airr-community/airr-standards/master/docs/packages/airr-python/news.rst

**Comment by bcorrie** [comment]
> and we should probably go back to v1.2.1 and document all the changes the best we can.

Christians group (@franasa I think?) is working on doing this for the MiAIRR manuscript, so I am hoping we can leverage his extensive work for creating such a changelog... There is a pretty good list in the MiAIRR manuscript document, which we can share separately...

**Comment by bussec** [comment]
> Christian's group (@franasa I think?) is working on doing this for the MiAIRR manuscript

Yes, it shouldn't be a lot of work to transfer this. Just let us know once you have decided on the way of documentation (I like the news.rst, though).
