### ISSUE TITLE
Bug in python AIRR module?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#289]
Probably for @javh ?

I am using the python AIRR module to load Schema objects from the YAML spec file. Code that used to work in terms of doing something like:
```
>>> from airr.schema import Schema
>>> myschema = Schema('Repertoire')
```
used to work for all of the Schema objects in the YAML file. I just did a git pull on master, then did a ```python3 setup.py install --user```. Now some of the Schemas are failing to load as follows:
```
>>> myschema = Schema('Sample')
>>> myschema = Schema('SampleProcessing')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/airr/schema.py", line 59, in __init__
    self.definition = spec[definition]
KeyError: 'SampleProcessing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/airr/schema.py", line 61, in __init__
    raise KeyError('Schema definition %s cannot be found in the specifications' % definition)
KeyError: 'Schema definition SampleProcessing cannot be found in the specifications'
```
In this case the Sample schema loaded fine but the SampleProcessing one did not??? It does exist in the YAML file...

Any ideas???

**Comment by javh** [comment]
I just tried the same, I don't get an error:

```
> [airr-standards/lang/python]$ python3 setup.py develop --user
> python3
>>> from airr.schema import Schema
>>> myschema = Schema('SampleProcessing')
>>> myschema.info
OrderedDict([('title', 'AIRR Schema'), ('description', 'Schema definitions for AIRR standards objects'), ('version', 1.3), ('contact', OrderedDict([('name', 'AIRR Community'), ('url', 'https://github.com/airr-community')])), ('license', OrderedDict([('name', 'Creative Commons Attribution 4.0 International'), ('url', 'https://creativecommons.org/licenses/by/4.0/')]))])
```

Can you check that our version numbers match:
```
>>> import airr
>>> airr.__version__
'1.2.1+377.gc8e45a4'
```

**Comment by bcorrie** [comment]
Hmmm, did a bit more investigation... It looks to be a packaging conflict, with python being a bit confused as to what packages it should have been using... 

I did a ```sudo python3 setup.py install --user``` and it fixed the problem... This is probably what I had done before. When I did the ```python3 setup.py install --user``` in real user space, it looks like python was using a mixture of user space updated packages and root user non updated packages at the same time... Interesting that the user space packages did not over ride the system packages?

**Comment by bcorrie** [comment]
```
ubuntu@turnkey-test2:/data/src/sandbox/util$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import airr
>>> airr.__version__
'1.2.1+377.gc8e45a4'
```

**Comment by bcorrie** [comment]
So maybe resolved, although I don't quite understand why it broke when I did the install in user space without the sudo...

**Comment by javh** [comment]
It has to do with the default python search path for modules.  You can see what yours is set to via:

```
>>> import sys
>>> print(sys.path)
```

IIRC, local site-packages should precede the system site-packages paths by default. So the import order should be:

1. Built-in modules.
2. Current working directory.
3. sys.path, with user paths before system paths. If you set the PYTHONPATH environment variable it'll prefix sys.path, so the user/system locations get pushed down the list.

I *think* that's the right priority.  I would:

* Check your sys.path to make sure it's not screwed up somehow.
* Uninstall the airr library from the user and system locations, then reinstall it to the location you prefer.

**Comment by bcorrie** [comment]
This has been sorted, closing the issue...
