### ISSUE TITLE
Auto generate definitions.yaml from TSV?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#29]
Hi All,

I was wondering if it might make sense to auto generate the definitions.yaml file from the MiAIRR TSV file rather than have a consistency check???

There are a couple of reasons for this:

1) They won't ever be out of sync (assuming the generation is done automatically). Probably worth having the Travis job still to ensure this and catch bugs in the conversion 8-)

2) The definitions would be more complete. Currently the definitions.yaml file is very minimal with name and type. The YAML object spec accepts descriptions and examples for fields in the definition. The TSV file has both field descriptions and examples. It would be nice if these could be added to the definitions.yaml file. I was going to do it manually but thought that is a lot of mundane work and will make it even harder to keep the two consistent. The driver for this is that our API uses the definitions.yaml file. But the API description is pretty bare bones as it has no descriptions or examples. It would be nice if the definitions.yaml file had this information.

3) When using the MiAIRR definitions in a swagger API spec like we are, we need definition in multiple forms. For swagger API responses, we need swagger objects. For API parameters, we need a different YAML structure, essentially a list of single parameters and their types, descriptions, and examples. Similar to #2 above, it would be nice if we could automatically generate a parameters.yaml file from the TSV.

I am happy to work on the code snippets to do this... The consistency check that we have now is a good starting point.

Thoughts?

I can create a branch for this development...

Brian

**Comment by schristley** [comment]
If anything I think it should go the other way, generate the MiAIRR TSV file from definitions.yaml. Over time, the yaml file will be more inclusive of all AIRR objects, and MiAIRR can be a generated subset.

However, feel free to add the descriptions and examples to definitions.yaml.

**Comment by bcorrie** [comment]
I think it is  good idea to keep a 1:1 mapping between the TSV and the YAML. One can then say THIS is the MiAIRR TSV file and THAT is the MiAIRR YAML file. If there are other things that are outside of MiAIRR I think they should be defined in a separate YAML file. That way a repository or tool like iReceptor (or VDJServer) can take the MiAIRR YAML definiton and know that they are only getting the MiAIRR definition. If they want the MiAIRR extensions that you are talking about then they can get that by composing those objects from multiple YAML files. This is just like what we are doing now with MiAIRR defining all of the MiAIRR fields and then the Formats rearrangements.yaml defining the Formats extension. 

BTW, this isn't exactly what we have now as the rearrangement part of the MiAIRR spec isn't in the definitions.yaml file for MiAIRR. This should probably be fixed, and then the rearrangements.yaml file should contain only those fields that aren't in MiAIRR. At least that would be my suggestion 8-)

**Comment by laserson** [comment]
I second @schristley in that the TSV should be generated from the YAML rather than the other way. The YAML file is more flexible and can contain more information. Actually, given a YAML file, I'm not sure what the purpose of the TSV file is.

I don't feel strongly about whether there should be a single YAML file or not.  At least for now, I'd probably have slight preference for a single file.

**Comment by BusseChristian** [comment]
I think the TSV provides a better overview of the data elements than the YAML, thus we should keep it in the current central location. However, I agree that it could serve as a "read-only" file that is generated from the YAML.

**Comment by schristley** [comment]
Is there a way to automate this, maybe with travis? I'm not a fan of requiring the committer to run a program to generate because the local environment may not be conducive to that, for example, manually running the consistency checker is painful for me, have to setup a whole docker environment so not to pollute my local environment...

Maybe a better idea is not to have the TSV in the repository, but generated as part of the docs website?

**Comment by laserson** [comment]
I think @schristley's last suggestion is probably the best way to go about it. Most consumers of the spec should be viewing the docs site rather than the github repo, so we could have the table generated as part of the docs.

**Comment by javh** [comment]
We can put arbitrary python code in sphinx's conf.py that executes upon build. So we could convert the yaml to tsv that way, when the docs are built. Which would also allow us to add a download link above the table in the docs to download the table as a tsv.

Sound good?

(Ideally, this means not committing the tsv to the repo, because it's part of the docs build.)

**Comment by schristley** [comment]
I'm okay with that so long as all released/tagged versions of the TSV will be available on the docs website and not just the latest. If that's not assured then best to commit the TSV so that it gets tagged with a release.

**Comment by javh** [comment]
Yeah, it should just be a matter of switching the docs version and hence getting the build for the relevant tag.

Might be some hitch I'm not thinking of, but it's a chunk of work to implement so figured I'd ask before attempting...

**Comment by schristley** [comment]
The MiAIRR columns in the TSV with their values need to be added to the yaml spec.

**Comment by schristley** [comment]
> Might be some hitch I'm not thinking of, but it's a chunk of work to implement so figured I'd ask before attempting...

I also don't think that it needs to be completed for this release, as a stand-in the current docs can just point to the current TSV in the repository.

**Comment by bussec** [comment]
Ok from my side, however all the information currently in the TSV should be maintained, so the following four columns need to be moved into the YAML (or placed elsewhere):
* MiAIRR data set / subset
* MiAIRR field designation
* Content format
* Field value example

**Comment by javh** [comment]
Hrm. Okay, I'm not seeing a good way to do this without two files (2 yaml or 1 yaml + 1 tsv). Right now, everything in `definitions.yaml` has the same structure and I think that should be maintained.

We could redefine the `x-miairr` tag from a boolean to the corresponding `MiAIRR field designation` value, then just autopopulate what's currently in the `AIRR Formats WG field name` column using that. That's pretty much the same amount of maintenance as just filling in the MiAIRR TSV column manually though.

**Comment by bussec** [comment]
I would prefer a second YAML (easier to extend, better for `diff`), could do the conversion if you want.

**Comment by javh** [comment]
Okay, there's some code of questionable quality in the autobuild-tsv branch to make downloadable files when building the docs. Looks like this:

http://docs.airr-community.org/en/autobuild-tsv/formats/rearrangements.html

The `Download as TSV` link downloads the table (which should probably be built from the tsv if we want to go this route).

I think we just need some name mapping, searching, and joining between `definitions.yaml` and `miairr.yaml` to remake the current TSV.

**Comment by bussec** [comment]
Short question for @schristley and @javh : Where are things standing regarding this issue?

My current understanding is that
* the MiAIRR TSV in the base directory is not (yet) autogenerated from the YAML specs (#115)
* you would like to merge the content of the `miairr.yaml` in the general YAML (#158)

I can work on the latter one, as I would like to include in the `required` information (#96) into the specification, but wanted to make sure that this would not break any auto-generation code I am not aware of.

**Comment by schristley** [comment]
There is no auto-generation code that I'm aware of. I've been holding off on doing the merge (#158) until the metadata PR is finalized because of all the changes. I already partially messed up the PR by trying to resolve conflicts between the branches.

**Comment by javh** [comment]
The currently autogenerated TSV files are for the Rearrangement and Alignment schema. Adding to the MiAIRR object shouldn't impact that at all.

Once we merge the two files, I can setup the autogeneration of the TSV.

**Comment by bussec** [comment]
Ok, thanks. I will wait until PR #156 is merged in.
