### ISSUE TITLE
Age of >18 years

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#292]
Our current spec says:

        age_max:
            type: number
            description: Upper boundary of age range or equal to age_min for specific age. This field should only be null if age_min is null.

How would I capture the age range of a subject where the ages of the subjects are stratified as in
```age > 18``` or ```age <= 18```

The current spec says that age_max can't be null, which prevents one possibility - ```age_min = 18.001```, ```age_max = null```

Perhaps ```age_min = 18.001```, ```age_max = 999``` and ```age_min = 0```, ```age_max = 18``` assuming ```age_unit = 'year'```

**Comment by bussec** [comment]
I am not a big fan of requiring users to enter arbitrary data into fields just to ensure that a query succeeds. So how far can/should we deviate from what you [described before](https://github.com/airr-community/airr-standards/issues/192#issuecomment-528908688)? If we assume that `NULL` in the data indicates an unbounded interval, this could be represented by an additional
`OR data_(min|max) IS NULL` condition on both sides of the `AND` in your example.

And while we  are at it: `age_*` is a closed interval, yes?

**Comment by bcorrie** [comment]
> And while we are at it: `age_*` is a closed interval, yes?

Yes,  I would think so...

**Comment by bcorrie** [comment]
> I am not a big fan of requiring users to enter arbitrary data into fields just to ensure that a query succeeds. So how far can/should we deviate from what you [described before](https://github.com/airr-community/airr-standards/issues/192#issuecomment-528908688)? If we assume that `NULL` in the data indicates an unbounded interval, this could be represented by an additional `OR data_(min|max) IS NULL` condition on both sides of the `AND` in your example.

I prefer using NULL as an indicator of an unbounded limit as well, but our current spec doesn't allow this, in fact it explicitly says this is not allowed. Does anyone remember the reason for that, in particular the explicit statement that it is not allowed...

**Comment by schristley** [comment]
> Does anyone remember the reason for that, in particular the explicit statement that it is not allowed...

It is essentially implied by the queries. Because we decided to combine single point age with age intervals into the same fields, that introduces requirements so that this query (for both a single age and for an interval) works:

```
30 >= age_min && 30 <= age_max
```

> this could be represented by an additional
OR data_(min|max) IS NULL condition on both sides of the AND in your example

I think so.

```
30 >= age_min && (30 <= age_max || age_max is null)
```

**Comment by bcorrie** [comment]
This needs to ensure that we have the ability to check for null

**Comment by bcorrie** [comment]
> This needs to ensure that we have the ability to check for null - See [#298 (comment)](https://github.com/airr-community/airr-standards/issues/298#issuecomment-568137773)

Separate tests have been created for null fields, so closing this issue.
