### ISSUE TITLE
Representation of bispecific antibodies

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#293]
This was briefly mentioned by @javh in yesterday's DataRep call:

How can we represent immunoglobulins that consist of more than one heavy and one light chain species. Our current concept of `paired_id` assumes that we combine two chains into a single Ig.

This would most likely happen in things like bispecific constructs, but it could also apply to immunoglobulins produced by B cells with two productive light chains (although it is harder the verify the actual existence of the latter one).

**Comment by rspreafico** [comment]
Yes, this is an important issue that will become increasingly common as this type of biotechnology is more and more common. It would be great if AIRR formats could support bispecific Abs.
