### ISSUE TITLE
Functionality of is operator

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#298]
In looking at the implementation of the ADC API "is" operator in the ADC API on iReceptor, we have stumbled on an issue... I think this is probably an @schristley question 8-)

In the document, the "is" operator checks to see if a field is "missing". The question is, what is the definition of missing?

This was touched on here: https://github.com/airr-community/airr-standards/issues/239#issuecomment-531391095

The ADC API test for this is here (https://github.com/airr-community/adc-api-tests/blob/master/repertoire/pass-is-op.json):
```
{
  "filters": {
    "op":"is",
    "content": {
      "field":"sample.cell_number"
    }
  }
}
```
This returns a list of repertoires where the sample.cell_number field is missing. My understanding from #239 is missing in this case means that the field **is not in the repository** or the field **is in the repository** but is **null** for a given repertoire.

Put a different way, the above query would return the repertoire where "cell_number" == null

```{"repertoire_id":"1", ... , "sample" : { "cell_number":null, ... }, ... }```

I wanted to confirm, from my understanding of #239, that this interpretation is correct?

**Comment by bcorrie** [comment]
I would like to also revisit the question as to whether we should change these operators from:

"is" to "missing"
"not" to "notmissing"

or something similar... I find these are extremely confusing even when they are well documented 8-)

If I want to query as to whether a field has data in it or not for a given repertoire, the query below:
```
{
  "filters": {
    "op":"missing",
    "content": {
      "field":"sample.cell_number"
    }
  }
}
```
to be much more clear and intuitive than the query:
```
{
  "filters": {
    "op":"is",
    "content": {
      "field":"sample.cell_number"
    }
  }
}
```

**Comment by schristley** [comment]
> means that the field is not in the repository or the field is in the repository but is null for a given repertoire.

Mongo allows you to differentiate these but I don't think the API can, as there is no way to check for a `null` value, is that right? That might be something useful though... Anyways, The GDC [docs](https://docs.gdc.cancer.gov/API/Users_Guide/Search_and_Retrieval/#filters-specifying-the-query) doesn't give much help, so it's up to us to define. If we don't add a way to explicitly check for `null` then I agree with your definition, that it covers both cases.

**Comment by bzimonja** [comment]
Another question then is, what happens in fields that are defined as "N/A" - do they exist as 'not applicable/not available' and if so, is that different from them being 'null'?

**Comment by bussec** [comment]
@bzimonja We had some discussions about this in #96, you might want to start [here](https://github.com/airr-community/airr-standards/issues/96#issuecomment-386839733). However, this was more a MiAIRR/DataRep discussion, so the API requirements might differ.

**Comment by jeromejaglale** [comment]
> If we don't add a way to explicitly check for null then I agree with your definition, that it covers both cases.

`null` is a proper JSON value so it would make sense to support it but an API user would expect such a query to return both the results that have the value `null` for that field **and** the results that don't have that field. No?

In other words, shouldn't  `is field` and  `field=null`  mean the same thing?

**Comment by schristley** [comment]
> In other words, shouldn't is field and field=null mean the same thing?

We could treat them separately if we want, but I think with the current API the answer is yes, we should treat them the same.

**Comment by schristley** [comment]
> "is" to "missing"
"not" to "notmissing"

I'm fine with adding new operators "is missing" and "is not missing" but I'd still want to keep the original operators for GDC compatibility.

**Comment by jeromejaglale** [comment]
If we add a new operator, it can be simpler: only one operator, taking a boolean:
```
"op": "missing",
"content": {
	"field": "sample.cell_number",
	"value": true
}
```
 
Also, do we expect this operator to be used mostly to retrieve data with a given missing field? Or to retrieve data having that field for sure? In that last case, it would be more straightforward to have:

```
"op": "exists",
"content": {
	"field": "sample.cell_number",
	"value": true
}
```

**Comment by schristley** [comment]
I guess I shouldn't say "new" operators, I just mean we can have additional names that perform the same operations as `is` and `not`

**Comment by schristley** [comment]
@bcorrie Are we adding additional operators ("is missing" and "is not missing") that's equivalent to "is" and "not" to satisfy your naming issues? We would still keep the original operators for GDC compatibility.

**Comment by bcorrie** [comment]
I think that would be my preference, but I think we want to write some adc-api-tests for this to ensure it does what we expect before saying we are done.

Are you sure you want to keep the "is" and "not" for compatibility??? I think I would prefer to change them and document that they are different... I am not sure that we are that strict on compatibility anyway.

It is in many ways more confusing to have two operators that do the same thing but are named differently than having one poorly named operator...

**Comment by schristley** [comment]
> not sure that we are that strict on compatibility 

@bcorrie It wasn't one of the CRWG goals, but I don't want to unilaterally eliminate it without discussion. How about we add it to the agenda for the next CRWG meeting so we can get feedback from the group?

Having the bullet point, "compatible with GDC API" might not matter much to us, but it might be relevant for PIs, grants, and other [stuff](https://commonfund.nih.gov/commons).

**Comment by schristley** [comment]
From CRWG call, we will add the new operators but also keep the old GDC ones for now. Need to update the docs and the reference implementation.

**Comment by schristley** [comment]
[implemented](https://github.com/airr-community/adc-api-js-mongodb/commit/c211b7cd78fbd8b223f59ad891dc9e3b654ee606) in reference, [tests](https://github.com/airr-community/adc-api-tests/commit/be1735b46cdb4d8c195d67758ad457bc9a190291) added
