### ISSUE TITLE
cell_processing_id and nucleic_acid_processing_id???

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#301]
These two IDs are listed in the comments, but there is no field for them. I think these are artifacts from a past version when we has _id fields for each of these... Is that true? I think these comments should be deleted from the spec???

cell_processing_id: line 640 in the spec
nucleic_acid_processing_id: line 838 in the spec

**Comment by schristley** [comment]
Yes, please delete those comments, we debated having these id fields but decided against.
