### ISSUE TITLE
format parameter in ADC API should be an enum

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#303]
with the set of accepted formats, `json` for repertoire, `json` or `airr` for rearrangement. That's what's in the reference implementation but maybe change `airr` to `tsv`?

**Comment by schristley** [comment]
and set default to json for both.

**Comment by bcorrie** [comment]
> That's what's in the reference implementation but maybe change `airr` to `tsv`?

Wonder if `airr-tsv` might be better. I think it is worth making it clear that the the format is an AIRR specific TSV format??? `tsv` alone doesn't make it clear it is AIRR specific, and `airr` by itself doesn't say it is a TSV file 8-)

**Comment by schristley** [comment]
> Wonder if airr-tsv might be better.

I thought that too but then we should use `airr-json` because it is an AIRR specific JSON format?? I think the AIRR is presumed from the ADC API, especially as we don't offer any non-AIRR formats, so I think `json` and `tsv` are fine.

**Comment by schristley** [comment]
[committed](https://github.com/airr-community/airr-standards/commit/6acb7f2936ffafa141369e984229288518701bfc), [committed](https://github.com/airr-community/adc-api-js-mongodb/commit/a86c08b0d69cec4496624172da4cf3eb2a6785c8) and tested
