### ISSUE TITLE
FAIRsharing record for Data Representation Standard

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#306]
Background: [FAIRsharing](https://fairsharing.org) already has a record for [MiAIRR](https://fairsharing.org/bsg-s000689/), but not a separate one for the Data Representation (see #105). FAIRsharing also makes a distinction between "Formats" and "Reporting Standards", therefore we cannot simply expand the existing MiAIRR record.

Question: Should we create a separate Data Representation / AIRR Schema record (record can be linked?

**Comment by bcorrie** [comment]
Yes, I think this makes sense...

**Comment by schristley** [comment]
Sounds fine to me. Hopefully we can have a single entry to cover all the AIRR formats

**Comment by bussec** [comment]
FAIRsharing also supports "collections", i.e. we can create one "AIRR Community" collection that contains all standards, repositories and policies.

**Comment by bcorrie** [comment]
Initial version created here: https://fairsharing.org/bsg-s001474/

Not yet approved, let me know if anyone has any suggestions...

**Comment by bussec** [comment]
Looks good, I now removed the DataRep publication from the MiAIRR record.

**Comment by bcorrie** [comment]
@schristley do you want to create an ADC API Fairsharing record? I am happy to do this if you don't want to, but I think we probably should have one.

**Comment by schristley** [comment]
@bcorrie go for it.

**Comment by bcorrie** [comment]
Yet to be approved, but created... https://fairsharing.org/bsg-s001477/

**Comment by bcorrie** [comment]
This has been done and approved
