### ISSUE TITLE
Why is cell_storage not nullable?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#307]
In the current spec, cell_storage is not nullable... Is there a reason for that? Other boolean fields are nullable, is there a reason that cell_storage needs to have a value?

This is particularly problematic when curating data from a paper and the authors don't talk about cryo-preservation... We have a bunch of data where this is unknown but we are not within the AIRR spec if we have a NULL value (we don't know T or F)... Is this an oversight?

**Comment by bussec** [comment]
The decision whether a field is `nullable` or not is depends on whether we can expect the information to be available to the *primary* data depositor, and `cell_storage` fits the bill here.

I understand that this makes it hard to third-party annotators, if this information is not passed on in the original publication. We can discuss whether `nullable:false` should be reserved for those cases where that have an undeniable relevance for the interpretation of the study (i.e. `species`). The original list of non-nullable fields is in https://github.com/airr-community/airr-standards/issues/96#issuecomment-391165107 . We will discuss this in the next MiniStd call, all input welcome.

**Comment by bcorrie** [comment]
Closing as per #310 revisiting this question in general...
