### ISSUE TITLE
RearrangementReader only reads TSV - could we modify to include JSON? 

### ISSUE THREAD

**Issue by lfunderburk** [airr-community/airr-standards#314]
Have been using `airr.load_rearrangement` and `airr.load_repertoire` to load JSON and TSV results. 

There seem to be differences between the two modules - in particular the file format input each allows. 

We were able to successfully test that JSON response for repertoire metadata and flag missing fields. We want to do the same for JSON response for rearrangement data but noticed it only accepts TSV format using the `RearrangementReader` class.

Is airr-standards open to including loading and validating JSON format when dealing with rearrangements and if so, what is the best way to modify the code?  

Refer to python code 

https://github.com/airr-community/airr-standards/blob/master/lang/python/airr/io.py

for  `RearrangementReader`   class and

https://github.com/airr-community/airr-standards/blob/master/lang/python/airr/interface.py

for `load_repertoire` and `load_rearrangement` functions.

**Comment by javh** [comment]
IIRC, this is something we had planned to do at some point, if/when the need arose.  So I don't think there would be an objections to adding this functionality (someone please chime in if this is an issue).

I suspect the easiest way to add support would be to copy-paste-modify the read/write code from `airr.load_repertoire`/`airr_write_repertoire` into `airr.load_rearrangement`/`airr.dump_rearrangement`, with an if-else block to perform the appropriate operation based on the input/output type. This would require adding another argument to these functions for the input/output file type. For example, `format="auto"` to autodetect from the file extension, format="tsv" to force TSV, and format="yaml" and format="json" for the other two.

That's my thoughts anyway. Pinging @schristley, as he may have more insight (he wrote the Repertoire I/O code).

We're pushing to v1.3 release, so if you were to put in a PR we'd have to push it back to a later release. I tagged it as v2.0, but it might not be that long. (We just don't have a schedule for v1.4 right now.)

**Comment by bcorrie** [comment]
@javh was this addressed and can it be closed? Or if not, do we think it is important for v2.0?

**Comment by javh** [comment]
There have been a lot of changes to how schemas are loaded in the packages since this was opened. I think we can let this one go.
