### ISSUE TITLE
R package doesn't support Repertoire

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#316]
The python package has support for loading/writing Repertoire objects as json/yaml, but the R package is missing this functionality.

This might be too late to get into v1.3, but it'd be nice if we could.

**Comment by ssnn-airr** [comment]
FYI @javh , I am working on this. The error I mentioned yesterday

```
>         read_yaml(file)
Error in yaml.load(string, error.label = error.label, ...) : 
  (../R/tests/data-tests/good_repertoire.airr.yaml) Duplicate map key: 'cell_subset'
```
Comes from the test file I copied from the python tests folder being a good-but-actually-bad repertoire, as it has duplicated 'cell_subset' info for the same sample.
[good_repertoire.airr.yaml#L49](https://github.com/airr-community/airr-standards/blob/master/lang/python/tests/data/good_repertoire.airr.yaml#L49)

**Comment by ssnn-airr** [comment]
Here in the [schema](https://github.com/airr-community/airr-standards/blob/master/specs/airr-schema.yaml#L1280), are we missing this?:
```
    required:
        - repertoire_id
```
`airr::load_schema` doesn't like having no required fields. If `required` is `NULL` then:

```
>     return(new("Schema", required=required, optional=optional, properties=properties, info=info))
Error in validObject(.Object) : 
  invalid class “Schema” object: invalid object for slot "required" in class "Schema": got class "NULL", should be or extend class "character"
```

**Comment by javh** [comment]
I noticed a lot of the new objects haven't had a `required` property, but do have an `x-airr: / required: true`.

I'm honestly not sure when/why/if this changed. @schristley?

**Comment by schristley** [comment]
I remember with python that schema.py had some code specific to `Rearrangements` which needed to be altered, I assume the R code might be the same.

I didn't add a `required` property to the new objects because I wasn't sure in what circumstances it applies. For rearrangements, `required` is used to mean it's required in the AIRR TSV file, however that `required` is not relevant to the ADC API, which uses different criteria. For repertoire metadata, MiAIRR and the `x-airr` properties seem to cover all the possibilities.

**Comment by javh** [comment]
Okay, so this is directly related to #297.

I'd see if  `new("Schema", required=as.character(NA), ...)` gets past the error, but seems we have a larger issue...

**Comment by ssnn-airr** [comment]
`as.character` does the trick

**Comment by ssnn-airr** [comment]
I am back to working on this. Not sure this will be 'done' for v1.3. Did we decide a date?
I am now writing the validation function repertoire vs schema, and bumped into this.
The Repertoire spec includes references to other schemas. Example from [here](https://github.com/airr-community/airr-standards/blob/6acb7f2936ffafa141369e984229288518701bfc/specs/airr-schema.yaml#L1305):
```
        sample:
            type: array
            description: List of Sample objects
            items:
                allOf:
                    - $ref: '#/SampleProcessing'
                    - $ref: '#/Sample'
```
The current version of `load_schema` loads this referenced schemas in `$ref`, as strings:
```
> str(RepertoireSchema@properties[['study']])
List of 3
 $ $ref       : chr "#/Study"
 $ description: chr "Study object"
 $ type       : chr(0) 
```
So I need to either modify `load_schema` to load actual referenced schema objects, or write some code that when I find the `$ref` situation, will be smart to switch and use that particular schema to validate the fields. Do you (@javh ) have a preference?

**Comment by schristley** [comment]
> switch and use that particular schema to validate the fields.

This is what I do in the python [code](https://github.com/airr-community/airr-standards/blob/6acb7f2936ffafa141369e984229288518701bfc/lang/python/airr/schema.py#L360). Extract out the schema name from the `$ref` then recursively call the validate function.

**Comment by ssnn-airr** [comment]
Ok! I think I found an <whispering>easy</whispering> way to do it with `rapply`...

**Comment by javh** [comment]
Cool. Thanks, @ssnn. Sorry, I may not get a chance to look at this closely until the weekend, but the recursive approach in the python code sounds easier to implement, but slower (at least in the abstract).

Though, we can probably avoid most of the overhead in the recursive approach by adding calls to `load_schema` for all the supported objects in the package (R/Schema.R) so that they make it into the global namespace. Then you can storing those objects in the properties of the schema where they appear.  Ie, add stuff like:

```
SampleProcessingSchema <- load_schema("SampleProcessing")
```

Then you can check if a property is a Schema object and act accordingly with:
```
is(RearrangementSchema, "Schema")
```

Which would might be simpler if we just drop the "Schema" suffix so that the schema name and class name are the same (eg, "RearrangementSchema" -> "Rearrangement"). But, currently the names match the python package, so maybe not.

Anyway, I'll try to look closer later. Just tossing ideas out.

**Comment by ssnn-airr** [comment]
Thanks @javh What you just said is what I have done. I have loaded all Schemas, and now I am working on the recursion. I will push something when it is working and documented. I you don't hear from me, progress is being made! :+1:

**Comment by schristley** [comment]
> Though, we can probably avoid most of the overhead in the recursive approach by adding calls to load_schema for all the supported objects in the package (R/Schema.R) so that they make it into the global namespace.

Caching the schemas should definitely speed up the validation routine. I've been meaning to add that to the python code...

**Comment by bcorrie** [comment]
Hi all, I am trying to wrap up the v1.3 issues, wondering where this is at... 8-)

**Comment by javh** [comment]
@ssnn-airr, is there an active branch for this? I'm not seeing one. If not, could you please push the changes you have to-date?

**Comment by javh** [comment]
Pushing this back to the next release in the interest of releasing v1.3 ASAP.

**Comment by imkeller** [comment]
I just went through the code and the issues to familiarize with the R and python packages. Would it be useful if I started working on this issue #316 here or is there something more urgent? Is there someone else who is working on this currently? 
From what I understand, the R functions to read/write the Repertoire could be designed similar to those in the python package.

**Comment by ssnn-airr** [comment]
I started working on this before the world covid-collapsed, then stopped, and right now, I don't even recall what the status of that code is. It is not exactly as I wanted it, as I never pushed it. I was refactoring something, and think I had some issue with a part that was doing some recursive loading of schemas (eg https://github.com/airr-community/airr-standards/blob/master/specs/airr-schema.yaml#L1835)... I have not been following changes in the python package, so if you have already familiarized yourself with the python packages, and are available to tackle this issue, I would say go for it. What do you think @schristley  and @javh?

**Comment by javh** [comment]
Thanks, @imkeller. Sounds good to me. I think this issue (Repertoire support) and the bug fix for #475 are the most urgent R packages issues. 

#378 would probably be the next most important issue.

There's also the wish list items #314 and #433, but I don't think we've decided whether we want to implement that.

**Comment by imkeller** [comment]
I think there is something I am missing about the rearrangement and repertoire format. Maybe someone can help...
The repertoire.yaml contains several repertoire_ids, and all of them probably refer to multiple sequences. But the rearrangement.tsv does not contain any information on the repertoire_id. Does it mean that one repertoire file belongs to multiple rearrangement files? How does one specify the links?

**Comment by schristley** [comment]
> The repertoire.yaml contains several repertoire_ids, and all of them probably refer to multiple sequences. But the rearrangement.tsv does not contain any information on the repertoire_id. Does it mean that one repertoire file belongs to multiple rearrangement files? How does one specify the links?

`repertoire_id` is the link. It exists in both the `Repertoire` and `Rearrangement` [schema](https://docs.airr-community.org/en/stable/datarep/rearrangements.html). You may have missed it because it's near the bottom of the list.

**Comment by schristley** [comment]
> I think there is something I am missing about the rearrangement and repertoire format. Maybe someone can help...

Another point of confusion might be that `repertoire_id` isn't a required field for rearrangements. This is because repertoire metadata is fairly new, and few if any tools support it, and thus no tools assign a `repertoire_id`. For example, if you run the Immcantation suite to process sequence data, nowhere is a `repertoire_id` assigned by those tools (as far as I know).

Currently, the `repertoire_id` is mostly being assigned when studies are loaded into the AIRR Data Commons, and thus when data is downloaded from the ADC, that data must have `repertoire_id` in both repertoire and rearrangement data in order to form the link.

**Comment by imkeller** [comment]
Thanks! That makes sense. I was working with the test data that does not have the optional field repertoire_id.

**Comment by imkeller** [comment]
I have implemented functions for reading and writing repertoires in yaml format now (and the package is building :rocket: ). Code can be found in the branch [ r_package_repertoire](https://github.com/airr-community/airr-standards/tree/r_package_repertoire). I would appreciate your feedback on the overall structure.

For the cases where one entry in the Schema1 refers to another reference Schema2, the reference Schema2 is available in the `$ref` slot of the entry in Schema1. It also works for array-type fields. It is not yet suited to represent object-type entries such as `germline` in the `Subject` schema. Accessing `$ref` in all different levels of the Schema seems so easy in python... Probably because the python `yaml.load(f, Loader=yamlordereddictloader.Loader)` returns an object with a nicer structure than the R `yaml.load_file(spec_file)`? I was looking for other R functions but did not find any.
