### ISSUE TITLE
Do we need a MiAIRR v2 label?

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#321]
We currently have a `MiAIRR  v2` label that we are using to track MiAIRR changes for v2 of MiAIRR, which -- in my understanding -- would also be the v2 release of the schema. Therefore, `MiAIRR v2` would be functionally identical to `AIRR v2` AND `MiAIRR` and could be removed.

Opinions?

**Comment by schristley** [comment]
I don't see the need for both unless you really need to differentiate between MiAIRR as a standard, versus its specification/implementation in the AIRR library, we've been mostly keeping them in sync.

**Comment by javh** [comment]
Yeah, I think of them as the same thing. I don't mind it being called `MiAIRRv2`, because it does make it clear that it will be a MiAIRR release. Really, it's just `v2`... I was seeing `MiAIRR` and `AIRR` prefix as just descriptive context.

**Comment by bcorrie** [comment]
I think I might have been the guilty culprit there... I think I created one of them not realizing that there was already an AIRR v2.0 some time ago... I agree, I don't think there is a reason to have both...

**Comment by bussec** [comment]
Ok, I just removed `MiAIRR v2`. All respective issues are now labeled as `AIRRv2.0` && `MiAIRR`.
