### ISSUE TITLE
SampleProcessing object incomplete??

### ISSUE THREAD

**Issue by scharch** [airr-community/airr-standards#325]
Is it just me or is there stuff missing here? https://github.com/airr-community/airr-standards/blob/75456c32b3f967877045c8d07b5dfd0df1d79ed9/specs/airr-schema.yaml#L1259 --there is only a `sample_processing_id` field, even though the description makes it sound like there should be fields for `sample_id`, `cell_processing_id`, etc....

**Comment by schristley** [comment]
@bcorrie and I discovered this weird issue during #263 for how schema is processed. Apparently using the `allOf` as is done for the Repertoire's [samples](https://github.com/airr-community/airr-standards/blob/75456c32b3f967877045c8d07b5dfd0df1d79ed9/specs/airr-schema.yaml#L1301) cannot be combined with standard data types like we originally [tried](https://github.com/airr-community/airr-standards/pull/263/commits/13405818323f7ae3a65e6a84b64443f17dde68d0). We had to put the field into its own object to be included with `allOf`. All the fields are there though.

**Comment by schristley** [comment]
Actually `allOf` can be used, we just didn't get the syntax right. Should clean up the `SampleProcessing` object.

**Comment by bcorrie** [comment]
Is this required for v1.4 release? Doesn't seem like it.
