### ISSUE TITLE
Can schema objects be nullable

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#328]
Beginning discussion around this in #322 and #280.

https://github.com/airr-community/airr-standards/issues/280#issuecomment-564274272
https://github.com/airr-community/airr-standards/pull/322#issuecomment-584974815

The question is, should we allow a Schema object such as:

- `study`
- `subject.diagnosis`
- `sample.pcr_target`

to be `null` when they are compound objects in the schema?

**Comment by schristley** [comment]
Maybe yes for some, maybe no for others. For the objects that are arrays like `subject.diagnosis`, I think it's more appropriate for it to be `null` to indicate that the subject has no diagnosis entries. That seems more semantically correct than inserting a blank object into the array. Other objects like `study` should not be `null`.

**Comment by bcorrie** [comment]
Duplicate of my comment here: https://github.com/airr-community/airr-standards/pull/322#issuecomment-585336041

The below is more directly related to the ADC API queries, but I think this should probably be no in general - see below:

> > What I meant is performing a query on the field sample itself given that it is an array of objects.
> 
> I see. No, I don't think many operators/queries would make sense directly on `sample`. The exception is maybe to check if it does or does not exist.

I think this holds true of all Schema objects, correct, including `pcr_target` as @bussec was discussing? The bottom line here is that it is an error to try and apply an ADC API operator to a Schema object (AKA operators can only be applied to base types (not objects))

The one possible exception might be the "is missing" operator as per the discussion in #298 Does it make sense for us to allow for:
```
"op":"is missing", "content": {"field":"sample"}
```
or
```
"op":"is missing", "content": {"field":"sample.pcr_target"}
```
Personally, I think this is quite messy and potentially confusing... If a field is required but nullable, shouldn't it be present in the data as a null field? If you had a data set with 
```
{ ... "sample":[{ ... "pcr_target":null ... }] }
```
This would mean that the data was missing a required, nullable field (e.g. `sample.pcr_target.pcr_target_locus`) ... Doesn't that make it not AIRR compliant? I think it is an important part of the spec that these fields are required and should be provided (even as null) and we should avoid providing shortcuts to make it easy for researchers to leave things out...

**Comment by bcorrie** [comment]
> Maybe yes for some, maybe no for others. For the objects that are arrays like `subject.diagnosis`, I think it's more appropriate for it to be `null` to indicate that the subject has no diagnosis entries. That seems more semantically correct than inserting a blank object into the array. Other objects like `study` should not be `null`.

As per above, doesn't this break the AIRR required, AIRR nullable criteria for the spec/standard. My understanding of the rationale for that is that we want them to be ever present so they are always considered...

**Comment by schristley** [comment]
> As per above, doesn't this break the AIRR required, AIRR nullable criteria for the spec/standard. My understanding of the rationale for that is that we want them to be ever present so they are always considered...

That's easily resolved by updating the criteria to allow some of these objects to be null.

I understand you are strictly applying the rules. My suggestion is to think about the common sense interpretation of the data, then update the criteria appropriately. In my opinion, if a subject has no diagnosis data then it makes sense that there are no diagnosis objects.

**Comment by bcorrie** [comment]
> > As per above, doesn't this break the AIRR required, AIRR nullable criteria for the spec/standard. My understanding of the rationale for that is that we want them to be ever present so they are always considered...
> 
> That's easily resolved by updating the criteria to allow some of these objects to be null.
>
> I understand you are strictly applying the rules. My suggestion is to think about the common sense interpretation of the data, then update the criteria appropriately. In my opinion, if a subject has no diagnosis data then it makes sense that there are no diagnosis objects.

That may be true from a common sense perspective, but it goes against the statement from a MiAIRR perspective that a field is `required`, which I think is pretty fundamental. If we allow a parent object (say `diagnosis`) to be nullable, then do we not have to change it such that `diagnosis.disease_diagnosis` is not `required`? I don't think you can have both as the data will not have the field `diagnosis.disease_diagnosis` if `diagnosis` is null. You could state (through documentation - as I don't think this can be captured in the spec) a complex rule about nested objects and how nested objects/fields that are required are not required if their parent object is nullable (and that parent object is indeed null), but that is getting messy.

Perhaps this is another example of how our use of the `required` and `x-airr` attributes breaks down (#297)... 

Also there are some problems as to query semantics.

What would then be the semantics of QUERY1.
```"op":"is not missing", "content": {"field":"subject.diagnosis"}```
as compared to QUERY2
```"op":"is not missing", "content": {"field":"subject.diagnosis.disease_diagnosis"}```
Both of these are queries (kind of) for data sets that have a disease diagnosis.

Suppose I have data like DATA1
```
"disease":null
```
and DATA2
```
"disease": [
{
  "disease_diagnosis":null,
  "study_group_description":null,
  ...
  "medical_history":null
}
]
```
With your ability to have `"disease":null`, both are correct ways of describing data with no diagnosis, but the queries are now ambiguous. If you use QUERY1 on DATA2 it will not give you the expected results, nor will QUERY2 on DATA1 (this later one may work, depending on the query implementation).

**Comment by schristley** [comment]
> goes against the statement from a MiAIRR perspective

I cannot answer these things definitively, I'm just stating my thoughts. The MiAIRR WG will need to discuss these things and give us guidance.

> semantics of QUERY1

I interpret this as that subject has no diagnosis.

> compared to QUERY2

I interpret this as the subject has a diagnosis entry, but no disease (maybe because it isn't a disease study but an immunogen instead, or something else)

> both are correct ways of describing data with no diagnosis

I don't agree, just because `disease_diagnosis` is null does not mean the subject has no diagnosis.

I do agree that a single consistent way to know that subject has no diagnosis would be useful.

**Comment by bcorrie** [comment]
> > goes against the statement from a MiAIRR perspective
> 
> I cannot answer these things definitively, I'm just stating my thoughts. The MiAIRR WG will need to discuss these things and give us guidance.

We discussed this at the Minimal Std WG meeting this morning, and the consensus was that all required fields should be present in the file for it to be MiAIRR compliant (although some fields can be null if no data has been gathered or it is not known). So from this perspective, the MiAIRR compliant format would be:

```
"disease": [
{
  "disease_diagnosis":null,
  "study_group_description":null,
  ... [fields left our for brevity]
  "medical_history":null
}
]
```
This makes for more verbose files, but ensures that all files have all MiAIRR fields.

**Comment by bcorrie** [comment]
> > semantics of QUERY1
> 
> I interpret this as that subject has no diagnosis.
> 
> > compared to QUERY2
> 
> I interpret this as the subject has a diagnosis entry, but no disease (maybe because it isn't a disease study but an immunogen instead, or something else)
> 
> > both are correct ways of describing data with no diagnosis
> 
> I don't agree, just because `disease_diagnosis` is null does not mean the subject has no diagnosis.

To be clear, the description I used was meant to imply all fields in diagnosis were null, with ... implying that fields were left out for brevity. 

> I do agree that a single consistent way to know that subject has no diagnosis would be useful.

I think the Minimal Std position on this is that the following is the correct way to show no diagnosis...
```
"disease": [
{
  "disease_diagnosis":null,
  "study_group_description":null,
  ... [fields (all null) left our for brevity]
  "medical_history":null
}
]
```

**Comment by schristley** [comment]
> I think the Minimal Std position on this is that the following is the correct way to show no diagnosis...

Can you explain this in more detail? Does this mean that to determine if a subject has no diagnosis, this is the logic?

1. There is only a single entry in the `diagnosis` array.
2. All fields in that entry are null.

Okay, that's doable. The only unfortunate part is there won't be ADC API query that can effectively ask "are there any subjects with no diagnosis?" While you could devise a query that checks if all of the MiAIRR fields are null, that wouldn't be correct as there might be a custom field, for example:

```
"diagnosis": [{
  "disease_diagnosis":null,
  "study_group_description":null,
  ... [fields (all null) left out for brevity]
  "medical_history":null,
  "my_custom_field":"some custom data"
}]
```

**Comment by schristley** [comment]
@bcorrie Ok, so it sounds like nothing needs to be and we can close this? The [repertoire template](https://github.com/airr-community/airr-standards/blob/master/lang/python/airr/specs/blank.airr.yaml) has this already, as does the validation check. I guess we will just live with that there won't be an ADC API query that can effectively ask "are there any subjects with no diagnosis?"

**Comment by schristley** [comment]
@bcorrie Unless we want for the ADC API to state that the data repository should save `null` so that we can do queries, but when it returns the data, it has to stick in the blank object?

**Comment by bcorrie** [comment]
Sorry @schristley on being slow... For completeness, wanted to comment that at least from a response perspective the blank object should be returned. We could think about queries on null objects for the API, but we should consider that after 1.3 release I think.
