### ISSUE TITLE
Beta version of python AIRR v1.3 package on PyPl

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#332]
I think this is maybe a @javh question?

We are working on our production deployment of v1.3. Our iReceptor Turnkey uses docker images, and our data loading docker image relies on the AIRR library in PyPl. The current PyPl version is v1.2, which of course doesn't have a lot of the new features that we need, including Repertoire loading. 

I was wondering if it would be possible to load a v1.3aplha or v1.3beta version to PyPl of the AIRR Library so that those of us that are developing for the production environment can just do a pip install to get the new library?

Not sure how hard or practical that is, but thought I would raise the issue to see if it was easy?

I can always do a git clone and python install, but we are trying to develop for the production environment, so I would prefer to do a normal python module pull for the Docker container...

**Comment by javh** [comment]
I don't think we should do that. It'll make it so that the default `pip install` for users installs the unstable version. Plus, we'd have to deal with the R package, repo tags, and docs to do a release, even if it's beta one.

You can just do this to install from the tip of master via pip:

```
pip3 install -e "git+http://github.com/airr-community/airr-standards@master#egg=airr&subdirectory=lang/python"`
```

Should give you:

```
python3 -c "import airr; print(airr.__version__)"
1.2.1+439.g53be07b
```

**Comment by bcorrie** [comment]
OK, no worries... I did find another way around, almost the same as the solution you suggested... I didn't know pip could install from git that way - good to know... 8-)

Will mark this as closed...

**Comment by javh** [comment]
Cool. One thing we do is maintain separate devel and release docker images, with a few little changes in the Dockerfiles for each. Release installs packages from the tip and devel installs from a version tag. 

Easy way is using the same command, but swapping out `@master` for `@v1.2.1` in the pip git install. We keep all the package version numbers in a separate yaml file that is read upon building the docker image, but you could do the same thing in a much less complicated way by just setting something like `ARG AIRR_VERSION="master"` in your Dockerfile and doing `@${AIRR_VERSION}` in the pip command.

Anyway, food for thought.
