### ISSUE TITLE
Add deprecation of rearrangement_set_id to Rearrangement

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#346]
@bcorrie bought up the point in #340 that we hadn't properly deprecated `rearrangement_set_id` and indicated that it was replaced by `repertoire_id`.

**Comment by schristley** [comment]
> replaced by repertoire_id

and `data_processing_id` and `sample_processing_id`. Essentially that single grouping field got replaced by more specific fields as the repertoire metadata was better defined.
