### ISSUE TITLE
clean up branches

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#348]
@javh @bcorrie @bussec @williamdlees This isn't critical for the release, but we have a lot of dangling branches. I think some of this stuff is aborted work that will never be merged. If you could, please review your branches and delete the old cruft.

**Comment by schristley** [comment]
or branches that have already been merged with no real expectation that the branch will be used again.

**Comment by javh** [comment]
Will do. Give me a couple days?

**Comment by bcorrie** [comment]
Is there an easy way to see who the "owner" of a branch is???

**Comment by schristley** [comment]
If you click on the [Branches](https://github.com/airr-community/airr-standards/branches) link from Code, then there is a Yours button.

**Comment by javh** [comment]
I deleted the ones I contributed to that seemed safe to delete.  I left the `clones-and-trees` and `clones-and-trees-release` branches alive, because we had intended to revisit some of the content in their for the repertoire grouping discussion.

**Comment by schristley** [comment]
thanks everyone, looking much better
