### ISSUE TITLE
Remove spaces from directory names

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#36]
e.g., "NCBI Templates"

**Comment by BusseChristian** [comment]
Done in f37a4c607fa0577aa662ad11e8333076973aa9b9. Note that commit *breaks* the links to files and images linked by the README files, as those refer to the `master` branch, which is not yet updated. This will resolve once this commit is merged in.

**Comment by laserson** [comment]
Why not make the development branch the default on the landing page?

**Comment by BusseChristian** [comment]
The issue mentioned above was fixed with the recent merge of `development` into `master` (commit 790a8ea).
