### ISSUE TITLE
Cell and Repertoire definition

### ISSUE THREAD

**Issue by sharikrish** [airr-community/airr-standards#361]
In our previous discussion on cell object specification (issue : #320 ) and repertoire definition described [here](https://github.com/airr-community/airr-standards/issues/320#issuecomment-580513051) represents "actual" `Repertoire `and "virtual" `Repertoire`

Actual `repertoires `being the ones that contain each cell object only once and virtual `repertoire ` can contain them multiple times (either copied or linked).

From the previous call on MiniStd, there is a consensus that overlapping populations/`repertoires `need to be addressed and that two tiers of `Repertoire `objects could be a possible solution.

Any thoughts how we represent them in the schema?

**Comment by scharch** [comment]
Can we just add a boolean `virtual` field? Or maybe better would be list of `linked_repertoires` which would by its presence define a `Repertoire` as virtual

**Comment by javh** [comment]
I'm having trouble understanding the distinction. A Repertoire is an arbitrary collection of records, with the scope defined by whoever decided to label the collection as a Repertoire.  

What's the different between and "actual" and "virtual" collection? And what is the problem we want to solve? If it's data compression, by collapsing multiple Cell records into a single consensus Cell, then it may just be a matter of allowing `repertoire_id` and/or `sample_id` to be an array.

**Comment by lgcowell** [comment]
?I haven't been carefully following the thread, but it seems a virtual repertoire is what Jason is defining (arbitrary collection of records) while an actual repertoire is a biological entity and so is not composed of records and membership in the repertoire is not arbitrary but is based on a combination of cell type and anatomical location.


-------------------------------------------------------------------
Lindsay G. Cowell, PhD
Division of Biomedical Informatics
Department of Population and Data Sciences
University of Texas Southwestern Medical Center at Dallas
5323 Harry Hines Blvd.
Dallas, TX  75390-9066

F4.212b, MC9066

phone: 214-648-2289

fax: 214-648-2064
Lindsay.Cowell@utsouthwestern.edu
________________________________

**Comment by sharikrish** [comment]
> Can we just add a boolean `virtual` field? Or maybe better would be list of `linked_repertoires` which would by its presence define a `Repertoire` as virtual

Adding the 'virtual' flag makes sense and should be possible to implement. How to handle the meta-data associated with the linked repertoires?

**Comment by scharch** [comment]
> How to handle the meta-data associated with the linked repertoires?

The point of having a `linked_repertoires` field would be to get the metadata from the originals without needing to copy it. I haven't completely thought it through yet, though.

**Comment by bcorrie** [comment]
Not sure whether this is still a v2.0 task, @scharch ? This kind of feels like a `RepertoireGroup` type of issue - so maybe have this land wherever `RepertoireGroup` lands? See #578

**Comment by scharch** [comment]
Yes, I think this would ideally be solved by `RepertoireGroup`...

**Comment by bussec** [comment]
Re-reading this thread and parts of #320, I also think that `RepertoireGroup` is likely the second level we are looking for. We should save the previously mentioned [use case](https://github.com/airr-community/airr-standards/issues/320#issuecomment-580253923), but otherwise we can IMO close this.

**Comment by bcorrie** [comment]
I have create a Repertoire Group pull request (#748) and associated this issue with the pull request. So when we are comfortable the Repertoire Group addresses this we can close it.
