### ISSUE TITLE
/info ADC API entry point

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#367]
A couple of things... 

Is there a reason why the /info entry point doesn't respond with the info_object object in the schema? It currently response with two text strings a name and version, while the info_object has a much more informative set of information...

Also, I was wondering if we could consider adding a "last_update" field to the info_object in the ADC API schema. It would not need to be mandatory, but if present would indicate the last time the repository data had changed.  This would be useful to us as a client of the ADC API, as one could easily check if a repository had added any data since the last time one checked.

Thoughts?

**Comment by schristley** [comment]
The /info entry point should return information about the API service. However, I see the desire to want to know more, like what API version does it support? and what schema version does it support?

I actually expanded /info in the [Stats API](https://github.com/ireceptor-plus/specifications/blob/3dfdc12e1bd095973235748f94cb221c30a7a346/stats-api.yaml#L26) to try that out. Though there is adds info on the API version. We could also add info about the schema version.

**Comment by bcorrie** [comment]
My point is that we have two "info" responses in the current ADC API. We have:

```
definitions:
  # Info object
  info_object:
    type: object
    description: Provides information about the API response
    properties:
      title:
        type: string
      version:
        type: string
      description:
        type: string
      contact: 
        type: object
        properties:
          name:
            type: string
          url:
            type: string
          email:
            type: string
```
and then the actual response to the /info entry point, which seems to be a weak subset of the above:
```
          schema:
            type: object
            properties:
              name:
                type: string
              version:
                type: string
```
We already have an info_object defined in the ADC API yaml file that both /repertoire and /rearrangement use, is there a reason we aren't using it?

**Comment by schristley** [comment]
> We already have an info_object defined in the ADC API yaml file that both /repertoire and /rearrangement use, is there a reason we aren't using it?

Because that info_object is for the schema info, it's not for the API info. We should either create another info object for /info or merge the two somehow. We need to update anyways to include the documented [limits](https://docs.airr-community.org/en/latest/api/adc_api.html#adc-api-limits-and-thresholds)

**Comment by bcorrie** [comment]
My pull requests merge the two, but if they are going to diverge with limits as you say, that may not make sense. If the /info endpoint is returning repository specific information, then I would suggest adding a `last_update` field in addition to the limits that you mention. That way it is easy for a client to determine whether or not the repository is the same as at a previous visit.

**Comment by schristley** [comment]
Ok, I'll clean up the info objects and add `last_update` too

**Comment by bcorrie** [comment]
@schristley I added a service_info_object - have a look in #375
