### ISSUE TITLE
Add documentation for experimental lineage schema

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#368]
We needs docs for the Clone, Tree and Node schemas. I think skeletal docs like we have for Alignment should be fine at this stage:
https://docs.airr-community.org/en/latest/datarep/alignments.html

**Comment by bcorrie** [comment]
@javh should this be part of v1.3?

**Comment by bcorrie** [comment]
By that I mean it isn't tagged with v1.3 but is a Milestone in AIRR v1.3

**Comment by javh** [comment]
Yeah, it should. I just quit using the tags because they were redundant with the milestones.

**Comment by bcorrie** [comment]
I just tagged it, as I worry about overlooking things as I am not sure we all look at the Milestone as the mechanism for tracking these things...

**Comment by javh** [comment]
Cool. We should probably settle on one mechanism to avoid confusion, at some point. Maybe for the next release?
