### ISSUE TITLE
Verify and update new x-airr attributes

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#369]
Now that we've merged in the new `x-airr` tag structure (see #342, #364), we need to take a pass over all the fields and verify them. In particular, that `required` (top level) and `x-airr: nullable` are correct.

**Comment by bcorrie** [comment]
Ok, ran our mapping and the following came up for Repertoire fields - this means that these fields are not required in the file format (`required`) or the ADC response (`required` or `identifier`)...

- repertoire_name is not `required` or `identifier` but is `adc-query-support`
- repertoire_description is not `required` or `identifier` but is `adc-query-support`
- study_description is not `required` or `identifier` but is `adc-query-support`
- cell_species.id is not `required` or `identifier` but is `adc-query-support`
- cell_species.value is not `required` or `identifier` but is `adc-query-support`
- data_processing_files is not `required` or `identifier` but is `adc-query-support`
- analysis_provenance_id is not `required` or `identifier` but is `adc-query-support`

My suggestion is that all of these should be required - At the repertoire level I would suggest that if they are in the spec and require query support then they should be in the Repertoire file and be required by the query response like everything else...

If the argument is that the they are not needed in the Repertoire JSON file format, then we probably need a new x-airr attribute along the lines of adc-response-required unless we want to suggest that adc-query-support => adc-response-required?

I didn't check nullable fields to confirm that they match the miairr levels correctly.

**Comment by schristley** [comment]
These are all optional fields, so the settings seem correct to me. The certainly aren't `required`, nor are they an `identifier`. I think of them more like custom fields, and I think we should allow queries on custom/optional fields for `Repertoire`.

- repertoire_name is not `required` or `identifier` but is `adc-query-support`
- repertoire_description is not `required` or `identifier` but is `adc-query-support`
- study_description is not `required` or `identifier` but is `adc-query-support`
- data_processing_files is not `required` or `identifier` but is `adc-query-support`
- analysis_provenance_id is not `required` or `identifier` but is `adc-query-support`

These look like they are missing something, I think `cell_species` is a MiAIRR field?

- cell_species.id is not `required` or `identifier` but is `adc-query-support`
- cell_species.value is not `required` or `identifier` but is `adc-query-support`

**Comment by bcorrie** [comment]
If that is the case then I suspect only MiAIRR fields should be required at the Repertoire level. Currently in Repertoire, all MiAIRR fields are required and no non-MiAIRR fields are required (with one exception). This should be consistent. The one exception is primary_annotation - given the above it should probably be removed from the required fields.

**Comment by bcorrie** [comment]
I also noticed that the sample_processing_id and data_processing_id are required fields, and they shouldn't be should they??? They are identifier:true, but they shouldn't be required...

**Comment by bcorrie** [comment]
Made the _id field and primary_annotation changes on #371

**Comment by bcorrie** [comment]
Made the cell_species change, @bussec can you confirm this is MiAIRR?

**Comment by bussec** [comment]
@bcorrie Yes `cell_species` is `miairr:defined`, I am currently putting this in. Is there any other change to this field that I should be aware of (could not see anything in the #371 diffs).

**Comment by bussec** [comment]
I went through the schema one more and did not find any issues with x-airr attributes related to MiAIRR. There are some things that need to be addressed in the `Cell` object, but we will do this in a separate issue.

**Comment by bcorrie** [comment]
> @bcorrie Yes `cell_species` is `miairr:defined`, I am currently putting this in. Is there any other change to this field that I should be aware of (could not see anything in the #371 diffs).

@bussec I added cell_species to the `required` fields since it is `miairr:defined`. I believe that is correct, no? See https://github.com/airr-community/airr-standards/pull/371/commits/5ef50255e6f5dfcfb2b8cfbdc5664767b79d3708

**Comment by bcorrie** [comment]
@bussec based on our Ontology discussions it looks to me like we need to change the ontology examples to NCBITaxon:9606 rather than NCBITaxon_9606 8-)

Do we want to do that in a separate ontology branch?

**Comment by bcorrie** [comment]
@bussec also I notice that you removed `name` from x-airr attributes for `study_description`... Is there a reason for that, I would prefer that all fields in the spec have a name... 8-)

**Comment by bussec** [comment]
@bcorrie 

1. As I commented in #335, `x-airr:miairr=defined` does not make a field `required`. I admit that this is not explicitly mentioned, I thought it was implied by stating that the field MAY be provided. I can clarify this.

2. I understand that you would like to name fields, but the current definition of `x-airr:names` says "MiAIRR name", which is the propose for which the field was introduced. And as `study_description` is not part of MiAIRR it should not have a MiAIRR name. Therefore I removed
it.

3. Yes, lets do this in a separate branch and after we merge this one... I smell merge collisions...

**Comment by schristley** [comment]
> I would prefer that all fields in the spec have a name...

If you are wanting fields to decorate a UI, you should use `title` and `description` as described by the [JSON schema](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.1).

**Comment by bcorrie** [comment]
> > I would prefer that all fields in the spec have a name...
> 
> If you are wanting fields to decorate a UI, you should use `title` and `description` as described by the [JSON schema](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.1).

We already have a method for naming a field, from the MiAIRR standard - the `name` attribute. Would the same not hold true for the MiAIRR terms as well then? 

It doesn't make any sense to have the name/title of a field in two places, and makes even less sense for this to be defined in one place for some fields and another place for other fields... We should probably move all of the `name` fields from x-airr to the JSON schema `title` then.

**Comment by bcorrie** [comment]
> * I understand that you would like to name fields, but the current definition of `x-airr:names` says "MiAIRR name", which is the propose for which the field was introduced. And as `study_description` is not part of MiAIRR it should not have a MiAIRR name. Therefore I removed  it.

See my comment above... It doesn't make any sense to me to have a name/title in two different attributes for a field in a specification. I agree that the `name` field originated with MiAIRR, but that doesn't necessarily mean it should be exclusive for that purpose. I would suggest that we converge on a single attribute for a spec field's name/title. I have no particular opinion one way or the other, but I think it is a bad idea to have the name/title in two different attributes depending on the field...

**Comment by bcorrie** [comment]
If you want to move forward with this merge, I would prefer we put back the `name` field in study_description and open a separate issue to sort out the naming thing... Although I think it is pretty easy to resolve this, as we just need to decide which one to go with... It is easiest to just leave `name` as the attribute of choice, it is probably the most correct to use `title` given the JSON schema... I think we should just choose one (and only one).
