### ISSUE TITLE
Identifiers in NCBI templates should match schema exactly

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#37]
Currently in master, the AIRR_BioSample_v1.0.xls file has a column called "*sample_name" instead of "sample_name".

**Comment by laserson** [comment]
"won't fix"?

**Comment by ahmadchan** [comment]
I have pushed in development. I'll recheck.

**Comment by BusseChristian** [comment]
Per @ahmadchan and also according to my own tests, the asterisks prefixing the attributes/column headings required by BioSample are optional for submission. They have been removed in the current version of the AIRR_BioSample_v1.0.xls (commit 2cfaf9e85c325c34f6bba986d4daebe1cf1ee3f7).
