### ISSUE TITLE
Deprecate MiAIRR field name

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#380]
We have maintained a split between MiAIRR field names (which are human readable) and DataRep/Schema fields (which serve as unique and unambiguous keys) for the last two years. Given the recent decisions on Set 6/Rearrangement and the fact that everything is now represented in a single schema, this split appears unnecessary and potentially confusing. In addition, the `x-airr:name` property, which currently encodes the MiAIRR name, is used as short description for non-MiAIRR fields (e.g., `study_description`), which is illogical. As @schristley commented in [#369](https://github.com/airr-community/airr-standards/issues/369#issuecomment-614389193), this information should be in a property called `title`, the introduction of which would howver duplicate the information for MiAIRR fields. We should simply this.

Proposed changes:
* Move all `x-airr:name` properties to `title`
* Officially deprecate the MiAIRR field names. There are only Schema fields, which have a human-readable `title`. For MiAIRR fields, this title will initially be what is now the MiAIRR field name.

I think this should best go into v2.0, but open for discussion if there is a reason to push for v1.3.

**Comment by schristley** [comment]
@bussec if it's okay, I'm thinking of adding `title` for v1.3 while the deprecation of MiAIRR `name` can be for V2? I actually have a need for the title now.

**Comment by bcorrie** [comment]
Only problem with doing one without the other is that if I think we want to avoid having this in two places... So we should agree that we will be deprecating the `name` field and replacing it with `title` even if we don't actually do the deprecation until the v2.0 release.

**Comment by schristley** [comment]
> we should agree that we will be deprecating the name field

Well I agree. Based upon @bussec filing this ticket, I assume he agrees. Who else needs to agree? If @bcorrie agrees then we have a trifecta ;-D

**Comment by bcorrie** [comment]
Indeed... and I do agree... question is does anyone else have any thought/opinions other than the three of us 8-) Anybody??? going once, going twice, sold...

**Comment by schristley** [comment]
> I have created a new branch (title-spec), we want this for v1.3 correct?

@bcorrie yes, please, `title` is on the same level as `description`.

**Comment by bussec** [comment]
> We discussed at CRWG and decided to add the 'title' field now, leave name, and formally deprecate name in the v2.0 release. @bussec @schristley did I get that correct???

@bcorrie: Yes, or at least this was also how I understood it.

**Comment by franasa** [comment]
self-reminder: update `conf.py` once `name` is deprecated.
