### ISSUE TITLE
Pushing out the new docs site...

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#383]
Hi All,

I am involved in a number of COVID-19 related efforts, and am trying to refer to things that the AIRR Community has produced. These are guidelines for sharing from organizations like the Research Data Alliance's COVID-19 Omics working group (https://www.rd-alliance.org/groups/rda-covid19-omics), so this is relatively prominent and an excellent mechanism to advertise our standardization efforts, file formats, and API.

Unfortunately many of the things I am talking about don't exist on the current "stable" web site, so I have to put the "latest" tag in the URL, which will probably break down the line... Interestingly enough, I was unable to figure out what branch/tag on github maps to the various web site versions. What exactly is "stable" 8-)

We have been on this docs version for a long time, so the current docs site is quite out of date... Any chance we can merge them so the docs.airr-community.org site is a bit more up to date??? 

The RDA is about to release a guidelines for sharing COVID-19 data, and I would rather we have the main links in that doc rather than links to the non-production site...

**Comment by javh** [comment]
"Stable" builds from the most recent tag version (numerically, determined automatically by RTD). "Latest" builds from the tip of master.

So the solution is to tag the v1.3 release.

**Comment by bcorrie** [comment]
Damn, too late... https://www.rd-alliance.org/group/rda-covid19-rda-covid19-omics-rda-covid19-epidemiology-rda-covid19-clinical-rda-covid19-0

Next version...

**Comment by javh** [comment]
Okay, I'll close this then.
