### ISSUE TITLE
When to use `additionalProperties`?

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#386]
I couldn't readily find this in #251: Is there any reason why `Tree` uses `additionalProperties` in its `nodes` instead of `properties`? According to the [JSON schema object definition](https://json-schema.org/understanding-json-schema/reference/object.html) all `properties` are by default optional and `additionalProperties` to me seems to be mainly there to restrict undefined properties in various ways.

**Comment by schristley** [comment]
Yes, in this case, the node identifies are the keys (properties) of the object. As those identifiers aren't known ahead of time, they cannot be listed in the schema. `additionalProperties` is how that's indicated, not very intuitive in my opinion but there it is.
