### ISSUE TITLE
Inconsistency between Rearrangement and metadata field tables in docs

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#390]
Sorry I didn't catch this earlier, but the field tables aren't consistent across the Rearrangement, metadata (Repertoire), and experimental schema (Alignment, Clone, Tree, Node, Cell).

Rearrangement and Alignment have columns:  Name, Type, Priority, Description. I changed "Priority" to "Level" in #389. Where Level is either `required` (in top level `required`) or `optional` (not in top level `required`). 

Metadata objects and Clone, Tree, Node and Cell have "MiAIRR" instead of "Level".

The former also have a **Download as TSV** link and the latter do not.

I think these should be consistent. At the very least Clone, Tree, Node and Cell should follow whatever rules we use for Rearrangement and Alignment. I can see an argument for making the metadata field tables different. Though, I'm not certain "MiAIRR" is the right terminology to the convey the requirement levels. We can populated the column from the `x-miairr` tag, but I don't think the distinction between MiAIRR and not-MiAIRR is very useful.

Thoughts? I'm guessing this is partly due to us having some redundant code in `docs/conf.py` for building tables.

**Comment by schristley** [comment]
I agree that "MiAIRR" probably isn't the right terminology. I'd like the tables to provide the 4 main attributes for fields 1) MiAIRR level, 2) required, 3) nullable and 4) identifier. It's probably ok to pack them into a single column or we can consider splitting them out.

**Comment by javh** [comment]
From the call:
* Can link to the MiAIRR full table from the AIRR Data Model docs (https://docs.airr-community.org/en/latest/datarep/overview.html#airr-data-model).
* Try one column with requirement level, nullable and identifier tags.

**Comment by javh** [comment]
Working on this and a few other bits in the `docs-tables`  branch.  Should be done Soon(TM).
