### ISSUE TITLE
/rearrangement/ID returns an array

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#395]
@schristley the spec says this returns `rearrangement_response` which is an array. This will always return a single entity, is that what we want... Just wanted to check as we are returning a single object, which does not match the spec, but made more sense to us 8-)

This was raised in https://github.com/sfu-ireceptor/service-php-mongodb/issues/197

We are OK to change, just wanted to make sure that is what we wanted...

**Comment by schristley** [comment]
@bcorrie Yep, this is actually [your change](https://github.com/airr-community/airr-standards/commit/8fc46eb818d386fdd538fc7d5ab29267eda67b5e#diff-b3cdc707c41a3347f4f881ccc7ebeb08), the GET end points did only return the object, but I think you wanted the responses to be consistent (was a kingdom involved ;-D ). I guess I was fine with the change... The reference implementation follows the spec.
