### ISSUE TITLE
CSV dialect change

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#4]
Would it be possible to switch to tab-separated values with no quoted strings?  This tends to make things simpler to parse, and causes less confusion.

**Comment by BusseChristian** [comment]
Agreed. Fixed in commit [7a9636f](https://github.com/airr-community/airr-standards/commit/7a9636f7602a9c6cf12ed27e31c0d1aa6cd4dbd1).

**Comment by schristley** [comment]
It you switch then file extension should change to "tsv", that will make it "beautiful and searchable" as GitHub would say. That implies fixing any links to the file as well.

**Comment by schristley** [comment]
How come when I click on the file in GitHub, it doesn't show as a table?

**Comment by BusseChristian** [comment]
There no formatting error in the TSV, but GitHub parser seems to get confused with cells that contain commas AND short (i.e. 3-character long) pieces of text. Fixed in commit [8f6cb5d](https://github.com/airr-community/airr-standards/commit/8f6cb5dc5704c8db55e7720f86e03440afa01816).
