### ISSUE TITLE
AIRR schema with openapi V3 syntax

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#401]
I suppose one main question is do we keep V2 and V3 around indefinitely, or do we deprecate V2? The differences in the schema syntax are fairly minimal.

I'm all for deprecation, just need to decide on a time frame.

We need this because APIs being developed, using openapi V3, cannot directly include/reference the AIRR schema objects as it generates syntax errors.

**Comment by bcorrie** [comment]
Agree on deprecation once we have this working in OpenAPI v3

**Comment by schristley** [comment]
From discussion in recent CRWG call, we'd like to move forward with this. It sounds like we will need to support both a V2 and V3 for a while until we can properly deprecate V2.

From some early work, changing the schema to V3 is fairly minimal, it involves:

- change `discriminator`
- move `nullable` as property attribute

One slight difference is that V3 has default value of `false` for `nullable` while we have `true`

For the ADC API, the changes are much more substantial and likely requires a rewrite.

**Comment by schristley** [comment]
both the schema and ADC API have openapi3 versions now
