### ISSUE TITLE
Consider an API query on ontologies

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#407]
We currently have a set of ontologies in the specification (e.g. cell_subset). 

A very powerful query mechanism for the API to implement would be to implement an ISA operator that would search for ontological containment of a concept, such as `B cell`. Such a search would return all repertoires that contained `B cell` or any of its children in the ontology.

For example:

```
{
  "filters": {
    "op":"isa",
    "content": {
      "field":"sample.cell_subset.id",
      "value":"CL:0000236"
    }
  }
}
```
would return anything that is under node `CL:0000236` in the Cell Ontology.

This is a very difficult query to construct without this capability.

**Comment by schristley** [comment]
different from #234 ?

**Comment by bcorrie** [comment]
Nope, point taken... 8-)
