### ISSUE TITLE
Why isn't the sequence data part of 6 / data (proc. seq.)?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#41]
Isn't the sequence data needed for submission to GenBank?

**Comment by schristley** [comment]
This can be resolved after v0.1

**Comment by BusseChristian** [comment]
Yes, it is. So there are basically two parts to this question:
1. Can an implementation require more information than the standard? I think yes (as for #42)
2. Should the full sequence information be included in MiAIRR? This depends a lot on your interpretation of what set 6 is there for. If it is merely a search index to make raw data sets discoverable, then no. If it is a ready-to-use resource for processed sequences, then yes. I think it would be good to discuss this point in more general in December.

**Comment by schristley** [comment]
I see. I was interpreting the standard differently as the minimal information for repository deposition, but you are indicating it is the other way around, i.e. the minimal information that should be retrievable from a repository. That makes sense too.

Note that the manuscript is slightly ambiguous with "Finally, set 6 consists of the processed sequences with annotations" and "This MiAIRR set comprises the list of processed sequences, along with sequence-level annotations." Of course "processed sequence" isn't defined so its open to interpretation.

So if I publish a study, and I put the study metadata in BioProject/BioSample and raw data in SRA, do I have put in GenBank records? Can I just throw a file upon the web (such as journal supplemental data) with the MiAIRR fields?

**Comment by BusseChristian** [comment]
I think it works both ways: It is the minimal information that a repo has to provide, which requires that it receives this information in the first place.

Yes, the MiniStd WG is aware that "processed" is not clearly defined. Our current interpretation is that information from multiple reads can be used for error correction to produce the finished sequence. This means you are using information from _within_ your experiment to get closer to the ground truth, i.e. the actual nucleic acid sequence. In contrast to this, alignments with reference databases is a one-way road: It is used for gene segment call, but only the pre-alignment sequence will be reported. This dichotomy was done as INSDC repositories (e.g. GenBank) are very picky *not* to accept submissions that have undergone an inference step. However, I think that there is merit to this distinction also for other databases (e.g. Common Repo), but ultimately this comes back to the question above, "what is set 6 there for"?

Theoretically yes. However, while MiAIRR does not specify _where_ to deposit information, it does imply _how_ the information should be deposited (i.e. stable, free/open, retrievable and usable). So if you would upload the information as a GenBank format file onto Zenodo, this would clearly comply to the requirement. On the other hand a custom spreadsheet provided as PDF supplementary figure behind a publishers pay-wall will not.

**Comment by schristley** [comment]
The sequence data is part of the rearrangement schema, that should be sufficient especially as CRWG is using that schema for the underlying data repository.
