### ISSUE TITLE
Receptor, Cell and Rearrangement schema representations

### ISSUE THREAD

**Issue by sharikrish** [airr-community/airr-standards#410]
**Receptor**

A receptor represents two chains(i.e. one heavy and one light) of a cell, each with a antigen-binding site. However, an individual cells can also express multiple receptors, e.g. due to simultaneous expression of two TCR alpha chains. 

Aim of the ```Receptor``` object is to provide reactivity information for individual Ig/TCRs. 
```Receptor``` object which is currently available in the pull request #404. 

However, if the amino acid sequences of V-region of both receptor chains are identical and grouping them together will be considered as identical receptors and they would have identical reactivity information. So, the question was how to represent them in order to avoid redundancy of identical ```Receptor``` object?

**Relationship between Receptor, Cell and Rearrangement**

The current schema for ```Cell```, ```Rearrangement ```and ```Receptor``` is represented below  

![](https://pad.gwdg.de/uploads/upload_eeea5161cb8fd6ce4810e097d17415f3.png)

• ```Receptor``` has N: N with ```Cell``` – A cell would contain multiple receptors and a receptor can be from multiple cells

• ```Receptor``` has 1:2 with ```Rearrangement``` –Two rearrangement represents a receptor and a receptor contains only two rearrangements sequences.

However the current linkage between ```Receptor``` and ```Rearrangement``` breaks because the rearranged sequences associated with the receptor might be different as receptors are determined at amino acid level whereas rearranged sequences are determined at nucleotide level there by having any synonymous substitution would lead to identical V-region of both receptor chains but their rearrangements would not be identical. Hence, 2:1 ```Rearrangement```:```Receptor``` does not hold true.

Given the schema representations that allows N:N Cell:Receptor relationship we have come up with two schema proposals and would be good to get some suggestions/comments on the proposed schemas below. 

**Proposal 1:**

![](https://pad.gwdg.de/uploads/upload_e20b66ce5dc172c4ac79523b332cccb1.png)

In the proposed schema we define two ```Receptor``` objects i.e ```Intermediate``` and ```Observed Receptor``` where multiple ```Intermediate Receptor``` objects are related to a single ```Cell ``` object and a ```Observed Receptor``` object is linked to multiple ```Intermediate Receptor``` object and there are no direct linkage to ```Cell``` Object.  

The ```Observed Receptor``` object will then contain same properties as what we have defined currently in #409 but with addition of amino acid sequences of the receptor chains.

**Proposal 2:**

![](https://pad.gwdg.de/uploads/upload_2448ef5d959292a8c90e5aafa23c79ff.png)

• ```Receptor``` has N:1 with ```Cell``` – A cell would contain multiple receptors and a receptor can be present in single cell

Here we then do not link``` Receptor``` to ```Rearrangement``` but as proposed for ```Observed Receptor``` we should extend the current```Receptor``` object by addition of the protein sequences of both receptor chains

**Comment by scharch** [comment]
Looking at #404, it seems to me that "Proposal 2" is what currently exists, as I do not see a slot in the `Receptor` object for `Rearrangement`s. But, regardless, I don't see why a `Receptor` couldn't have the following fields allowing for a full linkage of N `Rearrangement`s:

```
heavy_chain_aa:
    type: string
heavy_chain_rearrangements:
    type: array
    items:
        type: string
light_chain_aa:
    type: string
light_chain_rearrangements:
    type: array
    items:
        type: string
```

I don't really see a need to preserve that nucleotide sequence H1 was observed in 5 cells, paired with nucleotide sequences {L1, L1, L2, L1, L4} etc, so I think this structure should suffice...

**Comment by javh** [comment]
I made a longer comment here: 
https://github.com/airr-community/airr-standards/issues/409#issuecomment-638965495

But, I'm not convinced Receptor needs to store links to Rearrangement or Cell records, or if that's even desirable because it ties a Receptor record to a specific experimental result. In which case, you just need to add a `receptor_id` column to Rearrangement.

If your questions are:
* Given an observed nucleotide sequence, what is it's antigen-affinity?
* Given a Receptor (affinity), what samples have corresponding sequences?

It seems like Rearrangement already meets these needs if you add a `receptor_id` column and a  Receptor record database.

**Comment by bussec** [comment]
As #574 included a `receptors` property of the `Cell` object, this issue will be closed with the complementary definition of the `Receptor` object in #404. To provide a brief summary of decisions we made regarding the original questions of this issue:

* `Receptor` is considered to be a global object, i.e., it describes the properties of an abstract receptor.
* `Receptor` is not directly linked to `Rearrangement`, as it requires two rearrangement to be properly defined. Linkage is instead provided by the `Cell` object.
