### ISSUE TITLE
Status of single-cell file format definition

### ISSUE THREAD

**Issue by grst** [airr-community/airr-standards#411]
Hi, 

I'm the author of [scirpy](https://github.com/icbi-lab/scirpy), a python software for analyzing single-cell TCR data. I would like to support AIRR-compliant input data and got some questions: 

 * Did I get that right that single-cell TCR (or BCR) data would be represented using the [Cell Schema](https://docs.airr-community.org/en/latest/datarep/cell.html)? 
 * On that page it says that the file format is not defined yet... Could you comment on what the status is? 
 * Are there maybe already preliminary sample files available? 

Thanks and best regards, 
Gregor 

CC @FFinotello

**Comment by javh** [comment]
Greetings @grst,

At this stage, the best way to add AIRR compliant support would be to support input of tab-delimited files meeting the [Rearrangement schema](https://docs.airr-community.org/en/latest/datarep/rearrangements.html), wherein cell associations are defined by the `cell_id` column.

This is structurally similar to the annotations csv output by cellranger-vdj. This would be the format you'd get by passing 10X data through [changeo(https://changeo.readthedocs.io/en/latest/examples/10x.html). Also, native output of the AIRR Rearrangement TSV is planned for cellranger-vdj (work in progress, no timeline).

I'll post an example TSV from single-cell data later today in this issue.

We are still working actively on the Cell Schema (progress here). Pinging @bussec and @sharikrish for further insight.

**Comment by javh** [comment]
Here are two example TSV files. One for Ig heavy chain and one for light. I just grabbed the example from here and ran the first step:
https://immcantation.readthedocs.io/en/latest/tutorials/10x_tutorial.html

[filtered_contig_heavy_productive-T.tsv.gz](https://github.com/airr-community/airr-standards/files/4704229/filtered_contig_heavy_productive-T.tsv.gz)
[filtered_contig_light_productive-T.tsv.gz](https://github.com/airr-community/airr-standards/files/4704230/filtered_contig_light_productive-T.tsv.gz)

We have a simple python library for read, write and validation of this format up on PyPI:
https://docs.airr-community.org/en/latest/packages/airr-python/overview.html

We're in the middle of releasing v1.3 of the schema and R/python libraries. I expect that to be finished sometime before Monday. But, the v1.2.1 release of the schema and libraries should be fine to work with. I don't think there's anything changing in Rearrangement that will impact you, except maybe the new optional `complete_vdj`, which maps to cellranger's `full_length` field.

**Comment by grst** [comment]
Hi @javh, 

thanks for the example files and the link. That helps a lot! 

Cheers, 
Gregor

**Comment by javh** [comment]
Sure thing. Let us know if you have any questions. I'll leave this issue open for a week or so, but feel free to reopen or make a new issue if you encounter problems.

Also, if you do add Rearrangement support, let us know and we'll add you to the list:
https://docs.airr-community.org/en/latest/resources/rearrangement_support.html

**Comment by grst** [comment]
The latest version of scirpy now supports to [`read_airr`](https://icbi-lab.github.io/scirpy/generated/scirpy.io.read_airr.html#scirpy.io.read_airr). Will be in the next release, end of this week. 

Thanks again for your help!

**Comment by javh** [comment]
@grst, I've added scirpy to the supporting applications list in #425. Please let me know if the version, citation or links are incorrect and I'll fix them.

**Comment by grst** [comment]
Hi @javh, 

thanks for adding us to the list. We are now published in Bioinformatics, I left a comment with the updated URL in the PR. 

Cheers, 
Gregor
