### ISSUE TITLE
Is the /v1/swagger endpoint deprecated?

### ISSUE THREAD

**Issue by Ross65536** [airr-community/airr-standards#415]
In the [API YAML schema](https://github.com/airr-community/airr-standards/blob/master/specs/adc-api.yaml) there is a `/v1/swagger` but in the [official documentation](https://docs.airr-community.org/en/v1.3.0/api/adc_api.html) that endpoint was removed

**Comment by schristley** [comment]
dang, missed that, thanks for pointing that out! Yes, the `/v1/swagger` endpoint was removed and it should have been removed from the API YAML schema.
