### ISSUE TITLE
Why does the ADC API use POST queries?

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#418]
This probably has been discussed before, but I couldn't find a clear answer in the docs and also #213 and #228 did not fully clarify this:

As far as I can see, the `GET /repertoire/:id` and `POST /repertoire` endpoints are performing very similar tasks. Both requests do not modify the state of the server and should be idempotent. Therefore, to my understanding of the HTTP specs, both should be `GET` queries. So why is the ADC API using `POST` for the latter query? The docs mentions few vs. many parameters, but this does IMO not change the "GET-ish" nature of the query.

**Comment by bcorrie** [comment]
GET is quite limited in the amount of information that can be provided as part of the request, where POST takes a request body that can be much more flexible and indeed fairly large... GET is too limiting for the types of queries that we the ADC API generates...

It is my understanding that the GET as read and POST as write are more REST specific and not HTTP specific... 

From the HTTP spec: https://tools.ietf.org/html/rfc7231#section-4.3.3
```
   The POST method requests that the target resource process the
   representation enclosed in the request according to the resource's
   own specific semantics.  For example, POST is used for the following
   functions (among others):

   o  Providing a block of data, such as the fields entered into an HTML
      form, to a data-handling process;
```
I don't believe the HTTP spec says anything about POST suggesting that this is incorrect behaviour...

**Comment by bcorrie** [comment]
@bussec asked and answered? I will close the issue, reopen if you want to continue the discussion. 

Yep, I am in issue cleanup mode...
