### ISSUE TITLE
Rearrangement TSV download with size parameter

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#419]
@schristley I think mostly a question for you... 

When one does a rearrangement TSV download with a size parameter, say to get 10 rearrangements, is it expected that when you ask for the next 10 you would get the same number of columns and the column order in the TSV would be the same? 

```
 curl -s --data '{"from":1, "size":10, "format":"tsv"}' https://ipa1.ireceptor.org/airr/v1/rearrangement >1.tsv
 curl -s --data '{"from":11, "size":10, "format":"tsv"}' https://ipa1.ireceptor.org/airr/v1/rearrangement > 11.tsv
```

This is not stated in the spec, it seems that this is an unreasonable restriction to put on a repository in general, and therefore one has to assume that this would not be the case. Unfortunately, I think this would mean that it is impossible to concatenate two files from an ADC API download from the same repertoire and the same repository if one was using the size parameter to incrementally download data.

This seems like a rather bad thing for something as numerous as rearrangements, as you would have to do a significant amount of processing for the files above to combine them into a single TSV file. 

I don't think  you can avoid this when combining TSV files from different repositories or possibly from even different repertoires from within the same study, but unfortunate for paging through a single repertoire...

**Comment by schristley** [comment]
That's interesting, I don't we discussed this at all. I know we talked about which headers for TSV, but we didn't say anything about the order of them. I looked at my API [example](https://github.com/airr-community/airr-standards/tree/master/docs/examples/api) and it doesn't retrieve using the TSV format, it is getting the JSON and using the python library to output a TSV.

You could also use `airr-tools merge` to concatenate the files for you. That will work regardless where the files came from, the order of the headers and/or what fields are there.

**Comment by bcorrie** [comment]
@schristley do you think we can close this issue? I think it is hard for the spec to enforce what I ask above, and since we have a tool to merge such files maybe we can just close this issue... If we do decide that this is fine the way it is, maybe we want to mention this explicitly in the documentation. That is, you should not assume that two different API calls to a repository will give you back the same fields and that there is a tool available for merging such files???

**Comment by schristley** [comment]
@bcorrie I'm fine with a doc mention, how about something like "A specific ordering of fields in the TSV format should not be assumed from one API request to another. Take care to properly merge AIRR TSV data from multiple API requests, e.g. such as with the airr-tools merge program"
