### ISSUE TITLE
Are coordinates needed for 6 / data (proc. seq.)?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#42]
When we prepare "6 / data (proc. seq.)" for submission to GenBank, it requires coordinates on the sequence for the [vdjc] features. Shouldn't those coordinates be part of MiARIRR then?

**Comment by schristley** [comment]
This can be resolved after v0.1

**Comment by BusseChristian** [comment]
In my interpretation the implementation (NCBI) has to cover the standard (MiAIRR) completely, but it does not have to be identical with it, i.e. it can require additional information. So the answer would be no. Also see my comment on #41.
