### ISSUE TITLE
time unit for `collection_time_point_relative`

### ISSUE THREAD

**Issue by franasa** [airr-community/airr-standards#420]
The MiAIRR property `collection_time_point_relative` is a time value (the current example for it is _14 d_). 
Should a **`collection_time_point_unit`** ontology property be defined as it was done for age with `age_unit` in https://github.com/airr-community/airr-standards/issues/192?.

**Comment by bcorrie** [comment]
Hi @franasa - I agree - I think this should be fixed as well. @kbhoehn was just asking about this as well, wanting to query for data that follows a time course, and without such an ontology this is very "challenging" 8-)

Is there any reason not to do this...

**Comment by bcorrie** [comment]
To be clear, I am suggesting making collection_time_point_relative to be a number and adding collection_time_point_relative_unit to use the UO ontology.

**Comment by franasa** [comment]
I wasn't sure about the `adc-query-support` so you might want to review it. I also added `template_amount_unit` and it's ontology, seemed appropriate to me too.
