### ISSUE TITLE
Define a manifest mechanism

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#426]
We need a way to link related files together on the file system. The immediate need is to link Rearrangement TSVs Cell JSON, and expression matrix files (#409), but applies equally to metadata and Clone/Tree/Node files.

Some notes from the 2020-06-29 call:
* The file manifest should live in the metadata file, which will be the "primary" file for the data set.
* We could define a top-level `Manifest` object to store file relations (has the advantage of clarity).
* We could put file links in `DataProcessing`, like the fastq file links (similar to an existing mechanism).
* We could extend the `Info` object with a file manifest (similar to an existing mechanism).

Random thoughts:
* Does the manifest need to define which identifier fields are present in the individual files?
* Do we need URIs and/or checksums to ensure a collection of files is correct/unchanged?
* Do we need metadata for the files themselves (format, creation date, etc)?

**Comment by franasa** [comment]
coming back to the manifest issue, we have some specific questions regarding the properties `filename` and `file_type` that define the file formats for the raw reads or sequences:
 
1) Are these properties to be included on the manifest?
 
both are `miairr: important` but in our case, we don't store unprocessed data files in our db, instead we do import the raw sequences of those files and scireptor performs some pre-processing on them. 

2) Is it expected for such a use case to also export the fastq files together with the files to be defined in the manifest?
 
there is also the property `data_processing_files` which is
an array of file names for data produced by this data processing. 

3) Are these files different to, for example, the TSV, YAML, or the files that we are defining for single cell in #409?

4) Does the definition of the manifest will include both the  RawSequenceData- and DataProcessing-files or would these be part of custom fields that you mention in [#478](https://github.com/airr-community/airr-standards/pull/478#issuecomment-728282251)?

**Comment by bcorrie** [comment]
> coming back to the manifest issue, we have some specific questions regarding the properties `filename` and `file_type` that define the file formats for the raw reads or sequences:
> 
> 1. Are these properties to be included on the manifest?

To be defined as to what goes in the manifest I think - see my comment here: https://github.com/airr-community/airr-standards/pull/478#issuecomment-735263668
> 
> both are `miairr: important` but in our case, we don't store unprocessed data files in our db, instead we do import the raw sequences of those files and scireptor performs some pre-processing on them.

The intent of these fields I believe is to capture the filename and file formant but _NOT_ to store the file. For us, this is a data provenance thing - so that the researcher can track the fastq file that the annotated data came from. In #435 we are also talking about having a more direct relationship, where possible, back to files that one might have gotten from SRA. Again, linking to the files for data provenance and scientific reproducibility.

> 1. Is it expected for such a use case to also export the fastq files together with the files to be defined in the manifest?

So I would say no - since we don't store them 8-)

> there is also the property `data_processing_files` which is
> an array of file names for data produced by this data processing.
> 
> 1. Are these files different to, for example, the TSV, YAML, or the files that we are defining for single cell in #409?
> 2. Does the definition of the manifest will include both the  RawSequenceData- and DataProcessing-files or would these be part of custom fields that you mention in [#478](https://github.com/airr-community/airr-standards/pull/478#issuecomment-728282251)?

Would be good to get others to weigh in, but again, for us, these are the file names that were produced by the annotation tool and that would be the output files that were produced by the software described in `software_versions` and `data_processing_protocols`. They are there for provenance and reproducibility, but the files themselves are not stored.

So we have things like this in these fields (see http://covid19-1.ireceptor.org/airr/v1/repertoire):

```
                    "sequencing_files": {
                        "file_type": "fasta",
                        "filename": "SRR11610494.fasta"
                    }

                    "software_versions": "fastx-toolkit/0.0.14, IgBLAST/1.16.0",
                    "data_processing_protocols": "Adaptors and primers removed by authors. Igblast annotation using imgt germline of the downloaded sequences was performed (igblastn -germline_db_V $GERMLINE/ig_heavy/igh_v -germline_db_J $GERMLINE/ig_heavy/igh_j -germline_db_D $GERMLINE/ig_heavy/igh_d -organism human -domain_system imgt -query $DATA/fasta_files/$SAMPLE\\ -auxiliary_data $EBROOTIGBLAST/optional_file/human_gl.aux -show_translation -outfmt 19 -out $SAMPLE.fmt19). Quality filtering was performed as per the paper: productive reads with a CDR-H3 region, and minimum V-gene alignment score of 200",
                    "data_processing_files": [
                        "SRR11610494.fasta.fmt19-filtered.fmt19"
                    ],
                    "germline_database": "IMGT",
```
Ideally, what you want to be able to do is take the files in `file_name`, hopefully found in SRA as per the extensions in #435, apply the data processing in `data_processing_protocols` using the software versions described in `software_versions` to reproduce the annotations in the repertoire being described...

**Comment by scharch** [comment]
@franasa The most basic function of `Manifest` is as an index. So while it certainly wouldn't be standard, if you wanted to package the raw fastqs, you could/would list them in the `Manifest`. But it doesn't create any new requirements/expectations that weren't already in the schema. Quite the opposite, in fact: it's partially a way to disambiguate the presence/absence of optional files like those containing `Cell`s, `Receptor`s, `Clone`s, etc

WRT #478: I do think the "custom" fields come here. The way I see it is that the schema in #478 tells you how to formally represent a `Repertoire` (etc) in File X, but I could still use the same schema to represent the `DataProcessing` in File Y and `Clone`s in File Z, with no automated way for a software tool to figure out they went together. That's what `Manifest` is for.

**Comment by bcorrie** [comment]
In my recollections, I thought we had started a `Manifest` object, but it looks like we defined a `DataFile` object but we do not yet have a `Manifest`. Am I missing this somewhere... If not, I will start this, as I would like to be able to represent iReceptor Gateway download information in a more formal and rigorous fashion.

Example downloads from the iReceptor Gateway were discussed here:

- https://github.com/airr-community/airr-standards/pull/478#issuecomment-728314405
- https://github.com/airr-community/airr-standards/pull/478#issuecomment-728321040

I want to be able to compute on these without relying on this custom iReceptor file format...

**Comment by schristley** [comment]
> In my recollections, I thought we had started a `Manifest` object, but it looks like we defined a `DataFile` object but we do not yet have a `Manifest`. Am I missing this somewhere... If not, I will start this, as I would like to be able to represent iReceptor Gateway download information in a more formal and rigorous fashion.

The two are complementary. I think Chaim was meaning to start the manifest but hasn't had the chance. Definitely give it a first pass. I was thinking to take a pass but haven't had a chance either...

**Comment by scharch** [comment]
Yeah, I've made a couple of abortive starts, but nothing that I was happy enough with to put here. Happy to work collaboratively/provide feedback/whatever.

**Comment by bcorrie** [comment]
OK, will use our "iReceptor Gateway Downloads" info.txt as a starting point... 8-)

Stay tuned...

**Comment by bcorrie** [comment]
Created a manifest branch for these changes: https://github.com/airr-community/airr-standards/tree/manifest

**Comment by bcorrie** [comment]
@scharch I made a very simple first attempt - shall we move the discussion to the pull request so we can discuss changes explicitly?
