### ISSUE TITLE
Is it safe to remove asterisks from keywords in NCBI BioSample templates?

### ISSUE THREAD

**Issue by BusseChristian** [airr-community/airr-standards#43]
The mandatory keywords/column headings in the NCBI BioSample template are usually prefixed with an asterisk. Those were removed in 5d75d77af9aa33ed8d83e9dc568507809ae69c67. @ahmadchan is it save to do this or could this break the submission process?

**Comment by ahmadchan** [comment]
No, it will not disturb the regular submission process. Here are the example that I have tested and these are without *   https://github.com/airr-community/airr-standards/tree/master/NCBI_implementation/Filled_NCBI_Templates. Moreover, I have added new examples in the NCBI filled templates in the development branch.
