### ISSUE TITLE
load_rearrangements from stdin

### ISSUE THREAD

**Issue by scharch** [airr-community/airr-standards#432]
Is this something that's possible or that could be added relatively easily? I want to enable streaming between analysis scripts...

**Comment by scharch** [comment]
Oh, it looks like I should be able to do this by creating a `RearrangementReader` object directly.

**Comment by javh** [comment]
Yeah, that was the goal. If you have trouble getting `io.StringIO` to work with the reader/writer classes, let me know. It should.

**Comment by scharch** [comment]
I used `fileinput.input('-')` and it works fine. :)
