### ISSUE TITLE
Update ontology docs to mention CURIEs?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#436]
Our current main ontology documentation page does not have any mention of the need for users to use CURIEs when referring to ontology terms.

https://docs.airr-community.org/en/stable/ontovoc/introduction_ontovoc.html

I think this should be changed, as it not very clear that the data within a AIRR compliant file should be a CURIE with an uppercase prefix (as per the spec) and the ontology ID (e.g. NCBITAXON:9606).

I would suggest having the following headers for this page:

- Summary
- Using CURIEs
- Approved Ontologies
- Sprint Reports

Also, in the approved ontologies section, should we mention the AIRR CURIE prefix explicitly (probably with an example), as this it what is expected to be in the AIRR files?

@bussec thoughts?

**Comment by bussec** [comment]
I agree that it should be mentioned on the main page for ontologies. Just not sure whether it is the only principle that should be mentioned there. But the text is all in the sprint reports, we just would need to condense it into one or two paragraphs.

And yes, the CURIE prefix should be listed in the Approved Ontologies list. If anyone has ideas how to present this list in a more appealing way, I would be open to change the current layout.

**Comment by bcorrie** [comment]
> I agree that it should be mentioned on the main page for ontologies. Just not sure whether it is the only principle that should be mentioned there. But the text is all in the sprint reports, we just would need to condense it into one or two paragraphs.
> 
> And yes, the CURIE prefix should be listed in the Approved Ontologies list. If anyone has ideas how to present this list in a more appealing way, I would be open to change the current layout.

I will take a stab at making some changes on the https://github.com/airr-community/airr-standards/tree/doc-fixes branch and get you to review... I have had two questions about this in the last week or two, so I think we need something...

**Comment by bcorrie** [comment]
@bussec have a look at the new docs: https://github.com/airr-community/airr-standards/blob/doc-fixes/docs/ontovoc/introduction_ontovoc.rst

**Comment by bussec** [comment]
Looks good. Did some minor changes (`doc-fixes` branch) and created a PR (#443).
