### ISSUE TITLE
ADC API query limit documentation is unclear

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#437]
I had question from a user about the ADC API query limits. It seems the documentation about this is misleading:
https://docs.airr-community.org/en/stable/api/adc_api.html#adc-api-limits-and-thresholds

The implication from the docs seems to be that there is a universal 16MB query limit that is part of the API spec. Was the intent here to say that specific repositories may have implementation-dependent limitations?

Can we reword this section to make it more clear to the user when a query limit applies and how they can discern that?

**Comment by schristley** [comment]
@javh I believe @bcorrie already [updated](https://github.com/airr-community/airr-standards/commit/8a089772b1c4210fdd1b6ede26f89be098a25fee) the docs.

**Comment by javh** [comment]
Oh, cool. @bcorrie is on the ball!

**Comment by schristley** [comment]
@javh just out of curiousity, how did you get the question? Did it come to you directly, through an AIRR email address, or somewhere else?

**Comment by javh** [comment]
It came to me directly from someone at work wanting to download the COVID-19 data from iReceptor. So not the typical route.

**Comment by bcorrie** [comment]
@javh I am going to close this issue, as the doc fixes are in #443
