### ISSUE TITLE
Info object in metadata

### ISSUE THREAD

**Issue by scharch** [airr-community/airr-standards#440]
Can someone please explain to me what the purpose of the `Info` object in the metadata file is supposed to be? I am thinking about proposing some changes, but don't want to break something I don't understand... TIA

**Comment by schristley** [comment]
It's metadata about the schema, analogous to the [info object in openapi](http://spec.openapis.org/oas/v3.0.3#info-object)

**Comment by schristley** [comment]
or hmm, maybe I should read about what you actually asked... In the metadata file, it acts as info about the schema, in particular the version of the schema for the objects in the file. You can also use it to put in information about the tool that generated the file.

**Comment by scharch** [comment]
@schristley thanks!
