### ISSUE TITLE
So what about pub_authors or contact_person

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#444]
We have contact information fields for who collected the data and who deposited the data, but we don't have a field to capture the contact person for the study. This has always seemed quite odd to me, but I understand the focus on MiAIRR as a standard to describe a study. But shouldn't there be a principal contact for the study - which in most cases would probably be the corresponding author on the relevant publication for the study?

As I say, this has always seemed odd to me, but with all of the traffic we are seeing on the iReceptor Gateway with the COVID-19 data, people are looking for studies based on authors and are expressing "frustration" that they can't find this. So this seems problematic.

We have hijacked the collected_by and deposited_by fields to capture relevant information about people, but you know that when you start to do that there is a flaw in the model...

So how do people feel about having one or both of pub_authors (to accompany pub_ids) or contact_person as the principal contact for the Study?

**Comment by bussec** [comment]
The reason why there is no `pub_authors` field is because MiniStd considered it out of scope. If a repository wants to allow searches for authors (which are not identical to `collected_by` or `submitted_by`), it needs to fetch the author lists of the publications annotated under `pub_ids` from a third-party (e.g., Pubmed).

Also, the general assumption was that the corresponding author is usually the person listed in `collected_by`, although this might not necessarily be the case. Furthermore, the `collected_by` person is rarely mentioned explicitly mentioned in academic publication. How often do you encounter this problem?

**Comment by bcorrie** [comment]
@bussec I think the main problem is that as you mention there is rarely information for `collected_by` so we have essentially hijacked it to capture the `contact_person` for the study. From my perspective, `contact_person` for a study is probably more important than `collected_by`, since `collected_by` might be a lab member who is "transient" while `contact_person` for a study would be much more persistent. For lack of anything more explicit, it is very easy to map the "Contact Person" for a publication (which all publications typically have) to a `contact_person` field.

If nothing else, I would suggest we add a `contact_person` or `study_contact` field...

**Comment by bussec** [comment]
> since `collected_by` might be a lab member who is "transient" while `contact_person` for a study would be much more persistent.

The schema currently describes `collected_by` as "[...] the person who is legally responsible for data collection and release". IMO this would typically be the PI, not someone "transient" (`<philosophy>Are we not all transient?</philosophy>`). But I understand the problem that to third-party curators this information might not be readily available, while the corresponding author usually is. Thus I would not oppose the introduction of a `study_contact` field, but I think for v2.0 we should consolidate the whole `[collected_by,lab_name,lab_address,submitted_by,study_contact]` complex, as these are all persons with a role and a affiliation, so we could use a more structured approach here (i.e., a `Person` object with the respective properties).
