### ISSUE TITLE
Study type to use for mouse studies

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#449]
The study ontology is not particularly rich in studies. There is an "Animal Study" which one could use if studying Mus musculus but there are not study types under that, so you can't denote whether it is a Case/Control study.

We are tempted to use "Case Control Study" rather than "Animal Study" because we have a rich species ontology to search for species. I see the @schristley on VDJServer is using "Animal Study".

Any thoughts, feedback on this. It seems more powerful in describing what the study is doing to use Case/Control but I don't run experiments...

**Comment by bussec** [comment]
We are using "Animal Study" (`NCIT:C93130`) for our mouse experiments. I would not use "Case-Control Study" (`NCIT:C15197`) as the definition in NCIT states that such studies "compare[s] groups of people", i.e. always deal with humans.

Having said this, with hindsight NCIT might not be the best ontology to use for Study type, as it is very focused on human and has potentially overlapping concepts ("Genetic Study", "Liver Study", "Animal Study"). Maybe something for OntoVoc to review...

**Comment by bcorrie** [comment]
Closing this issue. I will leave to you @bussec if you want to open another issue to consider another ontology for study.
