### ISSUE TITLE
Create Fairsharing.org records for Software Guidelines and AIRR Repertoire

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#450]
This has been done, awaiting approval. Probably of relevance to @scharch @schristley @javh @bussec ?

I have also created an AIRR Data Commons collection for grouping all of the AIRR Standards.

https://fairsharing.org/bsg-s001518/

https://fairsharing.org/bsg-s001517/

https://fairsharing.org/collection/AIRRDataCommons

All are awaiting approval to the creation or changes I just made...

If anyone wants to review and have me make changes let me know.

**Comment by bussec** [comment]
I always end up on https://fairsharing.org/collections/ so I assume that the records are not only yet?

**Comment by bcorrie** [comment]
Hmmm, if you search for AIRR it is there: https://fairsharing.org/search/?q=AIRR

But if you click on it it says it is missing...

**Comment by bcorrie** [comment]
These are all working now, they made the updates so now the links are working... Closing this issue.

**Comment by bcorrie** [comment]
Hmm, in reading their answer, I noticed that they removed the AIRR API as a standard, as they state:

"Currently, FAIRsharing has a strict definition for the type of standards that we accept. These must be metadata or data standards, i.e. models/formats, reporting guidelines, terminology artefacts, or identifier schema. As it stands therefore, an API specification falls outside this remit."

Although they admit this caused a fair bit of discussion 8-)

"However, our discussion has raised the issue that perhaps we should consider API specifications as standards. This isn't something we can do right now, but is something we are going to consider for the future. Given this, I unfortunately have to remove the AIRR API record from FAIRsharing."

Now we have an AIRR Data Commons record, so we will need to use that now.
