### ISSUE TITLE
Naming of the AIRR Rrarrangement Schema

### ISSUE THREAD

**Issue by williamdlees** [airr-community/airr-standards#452]
At the top of the page in which it is described (https://docs.airr-community.org/en/stable/datarep/rearrangements.html) this is referred to as the AIRR Rearrangement Schema, however in the overall standards index it is called V(D)J Representation. Please can one name be used consistently? At the moment I am unsure how to refer to it ina publication.

**Comment by javh** [comment]
AIRR Rearrangement Schema or AIRR Rearrangement Standard. The
