### ISSUE TITLE
airr-tools rearrangement validation error

### ISSUE THREAD

**Issue by uubram** [airr-community/airr-standards#457]
It seems that validating a rearrangement file with airr-tools produces the following error if the header has fewer fields than the record proceeding it:

> Error occurred while validating AIRR rearrangement files: 'NoneType' object has no attribute 'endswith'

For example [my_airr.txt](https://github.com/airr-community/airr-standards/files/5188691/my_airr.txt) produces this error when provided to airr-tools (version 1.3.0).

    airr-tools validate rearrangement -a  my_airr.txt

**Comment by javh** [comment]
Thanks for the report. We'll take a look at it.
