### ISSUE TITLE
FAIRsharing should point to GitHub

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#46]
The [FAIRsharing](https://fairsharing.org/bsg-s000689) entry referenced in the manuscript should point to the versioned released of the spreadsheet and not to a google doc.

**Comment by BusseChristian** [comment]
Agree, it would also be good if the term "MiAIRR" could show up in the General Information or even the Abbreviation (in case it can still be changed).

In addition it would be nice if the "Developed in" field could represent the international nature of this effort 😉.

**Comment by BusseChristian** [comment]
The link now points to the TSV on Github, thanks @skleinstein.
