### ISSUE TITLE
Have fields refer to Persistent IDs as often as possible

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#464]
It seems fairly obvious, but on review we don't actually specify this is the spec. For example, no mention of DOIs/Pubmed ID for papers (other than in the example), no mention of something like ORCID for people (submitted_by, collected_by), and only a brief mention of using an NCBI BioProject ID or similar value in a field like study_id. 

Should we be stronger in suggesting more rigour around this? I think we can do this without being overly prescriptive/restrictive.

I think probably in an ideal world, we might have a separate field for some of these (e.g. submited_by_pid, collected_by_pid, pub_ids_pid) so that using external information would be clear, but at a minimum it seems like we should be saying that for pub_ids you should refer to a known persistent identifier like a DOI or Pubmed ID...

This is related to both #444 and #435 in terms of being explicit about referring to external PIDs like ORCID and SRA run ids or similar.

**Comment by bussec** [comment]
I would support this. In general, I am wondering whether `*_pid` fields would be anything else than a "low-carb" version of an ontology controlled field. But I we shy away from the `id`/`value` record that this would imply, I would be ok with the convention that `*_pid` fields hold a CURIE (e.g., `ORCID:0000-0012-3456-789X`).

**Comment by bussec** [comment]
#### Table of keys for which PID would be avaiable
*(**not** including keys that are or should be ontology-controlled)*

| Group | Keys | PID |
|---------|------|---------|
| Researcher | `study_contact`, `collected_by`, `submitted_by` | ORCID |
| Research organization | `lab_address` | ROR |
| Publications | `pub_ids` | DOI |
| Raw data | `expression_raw_doi` | DOI |

#### List of keys which are PID candidates, but no PID has been identified so far
* `biomaterial_provider`: ROR would not cover commercial tissue banks 
* `sequencing_run_id`: Current definition in the schema does not fit PID criteria
* `sequencing_facility`: ROR would not cover commercial sequencing services
* `germline_database`

**Comment by bcorrie** [comment]
For the "people" category, do we consider the PID (ORCID) adequate to acquire contact details like email etc. I think we want to avoid adding a bunch of fields (like email) for each contact, but we could have a more complicated Person object??? Not really suggesting we should, but if we don't wanted to explicitly confirm that we don't want this. 

If we don't want it, we are saying that the PID is sufficient and we don't need anything else - which I think is correct...

**Comment by bcorrie** [comment]
BTW, I was looking at ORCID and I couldn't find a simple API to query to get the public fields for an ORCID ID in a simple JSON API response.  The ORCID API seems very convoluted... Am I missing something?

**Comment by bussec** [comment]
Have you seen this? https://pub.orcid.org/v2.0/

**Comment by bussec** [comment]
> For the "people" category, do we consider the PID (ORCID) adequate to acquire contact details like email [...]

I would prefer if we could tap into a central "source of truth", especially if it is one that it kept up-to-date by someone else :-)
There is one caveat however: As ORCID allows rather fine-granular privacy settings, users could block access to these fields later on (or not grant it in the first place). So we would need to decide whether this is something we can live with or whether we want to keep a "last-seen-version".

**Comment by bcorrie** [comment]
> > Am I missing something?
> 
> Have you seen this? https://pub.orcid.org/v2.0/
> This seems to be pretty straight-forward to me, I could `GET` my complete public information using `curl`. There is a lot of documentation on the authenticated parts of their API (which is ORCID members-only), but apparently you do not need this.

Duhh.... I was sure I tried that - but I guess not... 8-) That worked for me, thanks.

**Comment by bcorrie** [comment]
> > For the "people" category, do we consider the PID (ORCID) adequate to acquire contact details like email [...]
> 
> I would prefer if we could tap into a central "source of truth", especially if it is one that it kept up-to-date by someone else :-)
> There is one caveat however: As ORCID allows rather fine-granular privacy settings, users could block access to these fields later on (or not grant it in the first place). So we would need to decide whether this is something we can live with or whether we want to keep a "last-seen-version".

I think I agree... Best not to replicate something that is being done more completely elsewhere.  I think there might be a concern about not giving access to email, but in reality, if someone doesn't want to give out their email, we should respect that...

**Comment by schristley** [comment]
> For the "people" category, do we consider the PID (ORCID) adequate to acquire contact details like email etc. I think we want to avoid adding a bunch of fields (like email) for each contact, but we could have a more complicated Person object??? Not really suggesting we should, but if we don't want this I wanted to explicitly confirm that we don't want it. 8-)
> 
> If we don't want it, we are saying that the PID is sufficient and we don't need anything else - which I think is correct...

The PID may be adequate but I don't think we should eliminate the text fields and only have a PID. I think of the same issue as with the ontology fields, we kept `label` so that it can be displayed (queried) without having to perform ontology lookups. If anything, I think we should have a more structured and complete `Person` object.

**Comment by bcorrie** [comment]
Agree, but it probably doesn't have to be "extensive" if we have an ORCID to point to. `Person` might have a `name` and a `pid` field. What else would we need - keeping in mind the @bussec minimalism and our need to do stuff useful 8-)

**Comment by schristley** [comment]
> Agree, but it probably doesn't have to be "extensive" if we have an ORCID to point to. `Person` might have a `name` and a `pid` field. What else would we need - keeping in mind the @bussec minimalism and our need to do stuff useful 8-)

At least the data specified in MiAIRR like name, email, affiliation, address. We can also have `Person` contain additional optional fields.

**Comment by bcorrie** [comment]
For the record, @schristley pointed out this should we need to generate globally unique, internally created PIDs.

W3C spec for decentralized identifiers: https://www.w3.org/TR/did-core/

**Comment by bussec** [comment]
Also for the record: Digital Science will cease to make public versions of its GRID (Global Research ID) database available at the end of the year and recommends its users to switch to ROR (Research Organization Registry, https://ror.org). See https://ror.org/blog/2021-07-12-ror-grid-the-way-forward/

Unless anyone objects, this would make ROR IDs the first choice for an open affiliation PID.

**Comment by bcorrie** [comment]
Hopefully `germline_database` will be resolved through #530???

**Comment by bussec** [comment]
Maybe relevant for curators: ROR uses Github to track record creation/updates
https://github.com/ror-community/ror-updates

**Comment by schristley** [comment]
`study_id` should be CURIE with BioProject, like `BIOPROJECT:PRJNA578389`? Also need to decide how to handle studies that cannot be put into SRA, for example Adaptive studies, but that need a unique study_id. We could try to make them CURIEs too like `ADAPTIVE:robins-bcell-2016` so that they can resolve to the immuneAccess [page](https://clients.adaptivebiotech.com/pub/robins-bcell-2016)? Though not all of them are on immuneAccess. Does each repository create their own like `VDJSERVER:123` or do we do something generic like `AIRR:123`? We probably want something where we can easily detect duplicate studies across repositories.

**Comment by bcorrie** [comment]
Doesn't Adaptive have an identifier for its studies? This is what you get when you log in:

https://clients.adaptivebiotech.com/manageImmuneaccess?projectId=1c7ce2e3-808e-44da-b1e9-c44914719828

That is the ID you use/get when you use their API I believe...

They also appear to mint DOIs for their studies: http://doi.org/10.21417/B71018

So either of those would work, the DOI being preferred I would think.

**Comment by schristley** [comment]
> Doesn't Adaptive have an identifier for its studies?

Sure, it's just that not all studies that use Adaptive technology are on the Adaptive website...

**Comment by bcorrie** [comment]
> We probably want something where we can easily detect duplicate studies across repositories.

The AIRR Standard says `study_id` should be "Unique ID assigned by study registry". 

So I think we should have a CURIE prefix for known study registries but NOT for ADC repositories (except in exceptional circumstances - see below). These should be listed in the Spec like other CURIE prefixes IMO. Limiting and defining (in the spec) the number of "study registries" means we have a decent change at telling whether two studies are the same... 

If data is not stored in any other public registry (e.g. Not on Adatpive's web site but processed by Adaptive) then in those cases the data steward for the repository would need to come up with a mechanism for creating a unique ID (if that is the Unique place that identifies the data from that study). We should come up with a recommended mechanism for that (e.g. VDJSERVER:42) and the process should state that name conflicts for prefixes must be avoided etc. We might also provide a mechanism for specifying that if a CURIE prefix is not one of the ones listed in the Spec then this is clear (e.g. EXT_VDJSERVER:42). This indicates that it is a special case to indicate it is not a "Study Registry" that would typically be used, but still makes it possible to list a study_id.

We also have similar instances in the iReceptor repository. For example the Schomuradova COVID paper's annotated data was stored in the iReceptor repository only (to my knowledge the annotations have not been published elsewhere), and we have assigned an accession number ourselves (IR-EFIMOV-00001 and IR-EFIMOV-00002). So this could be referred to EXT_IRECPETOR:IR-EFIMOV-00001) as an "exceptional" case.

**Comment by bcorrie** [comment]
> * `sequencing_run_id`: Current definition in the schema does not fit PID criteria

Note from above comment. In #435 we are talking about extending the sequencing info to include a `sequencing_run_pid` which would fill this role by pointing to an SRA/ENA file such as "SRA:SRR11610494"

See https://github.com/airr-community/airr-standards/issues/435#issuecomment-804489785

**Comment by schristley** [comment]
The requirements for IDs when doing file-based analysis (presumably working within a single data set) is much looser than the requirements (#347) for IDs in the ADC and for published studies (to be FAIR). Much of the spec and current documentation has a local data, file-based approach to IDs. We need to resolve and document this properly. It is likely overly cumbersome to required tools (and users) to conform to strict ID requirements when working with local data, but the IDs need to be brought up to FAIR complaince when the data is inserted into an ADC repository and queried/downloaded from the ADC.

**Comment by schristley** [comment]
[the ten lessons](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2001414)

**Comment by bcorrie** [comment]
> #### Table of keys for which PID would be avaiable
> _(**not** including keys that are or should be ontology-controlled)_
> 
> Group	Keys	PID
> Researcher	`study_contact`, `collected_by`, `submitted_by`	ORCID
> Research organization	`lab_address`	ROR
> Publications	`pub_ids`	DOI
> Raw data	`expression_raw_doi`	DOI
> #### List of keys which are PID candidates, but no PID has been identified so far
> * `biomaterial_provider`: ROR would not cover commercial tissue banks
> * `sequencing_run_id`: Current definition in the schema does not fit PID criteria
> * `sequencing_facility`: ROR would not cover commercial sequencing services
> * `germline_database`

@bussec trying to get some closure on various issues. 

Would this make sense:

- study_contact, study_contact_pid (CURIE/ORCID)
- collected_by, collected_by_pid (CURIE/ORCID)
- submitted_by, submitted_by_pid (CURIE/ORCID)
- pub_ids (CURIE/DOI)
- expression_raw_doi -> expresions_raw_pid (CURIE/DOI)

This has the benefit of being backward compatible (study_contact is a string as we have it today, but the ORCID is in study_contact_pid)

We could refine the pub_ids definition to become a CURIE string only. The fact that this is plural implies that we thought perhaps there might be more than one - is that true?

expression_raw_pid can just be changed in name so it is consistent with our other PIDs.

**Comment by schristley** [comment]
> * study_contact, study_contact_pid (CURIE/ORCID)
> * collected_by, collected_by_pid (CURIE/ORCID)
> * submitted_by, submitted_by_pid (CURIE/ORCID)
> * pub_ids (CURIE/DOI)
> * expression_raw_doi -> expresions_raw_pid (CURIE/DOI)

I'm not a fan of embedding relationships/semantics into the field names, i.e. something and something_pid. We avoided this with the ontology-backed fields, and as these are ontology-like (ID's to external objects), I think we should treat them the same. However, we never resolved how to represent this in TSV. We might be able to use `oneOf` to define multiple structures.

> We could refine the pub_ids definition to become a CURIE string only. The fact that this is plural implies that we thought perhaps there might be more than one - is that true?

Yes, separated by commas. We should convert to an array to be explicit.
