### ISSUE TITLE
Referring to the AIRR YAML spec in the docs???

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#468]
In updating the AIRR records on FAIRsharing recently (#450) I noticed that nowhere (at least that I could find) do we point to the YAML spec itself. Now I know that the web pages are generated from the spec in many cases, but we don't seem to actually point to the YAML spec as the actual place where these data values are defined...

It seems like we should be more explicit in making this link, no?

**Comment by scharch** [comment]
done
