### ISSUE TITLE
Is clone_id like sequence_id?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#469]
This is mostly relevant to the `Clone` definition and it's `clone_id`. Both `sequence_id` and `clone_id` have a uniqueness qualification (although clone_id's is not particularly well defined). In #340 we determined that when analysis tools and repositories are working with sequence_id's they have to be unique in the context of the repository or analysis. This means that the actual sequence_id can (and needs) to change depending on the context and tools are free to change the sequence_id when they are combining and processing data sets to ensure this uniqueness.

Is the same true for clone_id in the `Clone` object? 

For example, if I am loading a MiXCR clone file into a database, and MiXCR has assigned it a clone_id of "0" am I free to change that to a unique clone_id within my repository?

The challenges of changing sequence_id and clone_id across and between analyses are alluded to in this comment on the issue.

https://github.com/airr-community/airr-standards/issues/340#issuecomment-596056400

Currently, I am throwing out the clone_id = "0" given by MiXCR and assigning it an internal unique clone_id for the repository.

Is that allowed? 8-)

**Comment by javh** [comment]
Yeah, `clone_id` is just a label. You can change it freely (at least according to the schema).
