### ISSUE TITLE
Consistency checks need to be written for NCBI XML

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#47]

**Comment by schristley** [comment]
never implemented and will be deprecated.

**Comment by bussec** [comment]
As long a we want to support the direct submission route to NCBI, we also need to support the XML templates. There is currently no consensus on deprecating them (#177).

**Comment by schristley** [comment]
Ok, I thought XML wasn't implemented, just the XLS templates.

**Comment by scharch** [comment]
@bussec close or add to 2.0?
