### ISSUE TITLE
Clone's germline_alignment and MiXCR

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#470]
`germline_alignment` is a required field in the AIRR `Clone` object. Does anyone know what this would map to in the output of MIXCR's "exportClones" option?

**Comment by scharch** [comment]
I think it would have to be a concatenation of `vAlignment`, `dAlignment`, and `jAlignment`, although you would probably also have to manually add back any nontemplated bases.

FWIW, technically `germline_alignment` is supposed to use the inferred ancestor, which MiXCR does not do. I don't think that's a (big) problem, but worth noting the data you are curating is going to be compared to `Clone`s where it _is_ the UCA... Maybe this is something we need to look at in finalizing the schema.

**Comment by bcorrie** [comment]
Is the intention that this can be interpreted as required but nullable - which according to the spec, it is at the moment.

In particular, because germline_alignment and sequence_alignment are required but nullable in rearrangement, I assume that that is the case for germline_alignment in Clone as well?

**Comment by scharch** [comment]
> Is the intention that this can be interpreted as required but nullable

I think so, yes

**Comment by bcorrie** [comment]
Closing this issue...
