### ISSUE TITLE
abundance value and other counts for a clone?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#471]
Some experimental protocols utilize controls that account for PCR amplification bias and other biases, thus allowing abundance between clones to be relatively compared within a repertoire sample. Should we have a field to hold this abundance value?

Furthermore, should we have a count field for the multiplicity (`duplicate_count`) of rearrangements? We have `sequence_count` but is that meant to be the number of rearrangement records, or the sum of `duplicate_count`? If an abundance value is not available for the clone, this count offer some notion of abundance even though it's potentially biased.

**Comment by bcorrie** [comment]
MiXCR has a cloneFraction field that seems to map to abundance... Currently this field is not mapped to an AIRR field when loading a clone into the iReceptor Turnkey. This seems reasonable to me...

**Comment by scharch** [comment]
> We have `sequence_count` but is that meant to be the number of rearrangement records, or the sum of `duplicate_count`?

Number of records. I am fine with adding an `abundance` field, but not keen on what you call multiplicity. If the analyst believes multiplicity is accurate enough, s/he can store it in `abundance`. If not, then it's not probably not meaningful to keep.

**Comment by scharch** [comment]
> MiXCR has a cloneFraction field that seems to map to abundance

Relatedly, I think we should define the field as a fraction --so maybe it should be `frequency` instead of `abundance`??

**Comment by schristley** [comment]
> I am fine with adding an `abundance` field, but not keen on what you call multiplicity. If the analyst believes multiplicity is accurate enough, s/he can store it in `abundance`. If not, then it's not probably not meaningful to keep.

That makes sense. I was thinking a downstream user would want to decide for themselves, and one field over the other would indicate confidence without digging through the experimental protocols, but I see that enforcing that would be problematic.

> so maybe it should be frequency instead of abundance??

sure.

**Comment by schristley** [comment]
> Relatedly, I think we should define the field as a fraction --so maybe it should be `frequency` instead of `abundance`??

Actually, after giving this a second thought, having `frequency` can be an issue if any tools want to "renormalize" for some reason. With just a frequency, you need a total to change that frequency back into an absolute count.
