### ISSUE TITLE
publish date for a study in an ADC repository

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#472]
As the ADC gets larger, a nice facility for the ADC to provide is the ability to show the user the newest or latest studies that have been added. Right now there isn't a date for when a study is added to a repository in the ADC. While there are dates associated with publications and/or a BioProject, they could be very different from when the study actually gets annotated and added into an ADC repository. My suggest is to add an `adc_publish_date` field in `Study` that a repository sets when that study has been made available in the repository for query and download. This should be a retro-active field, that is all existing studies should be given a date, even if it's an estimate.

**Comment by bcorrie** [comment]
I would also suggest having a `adc_update_date` as well. That way you can tell if the data you have downloaded at a specific time T1 (with a `adc_publish_date` and an `adc_update_date`) is different from the data you download at time T2 by looking at `adc_update_date` for the two downloads.

**Comment by schristley** [comment]
Yes, that makes sense. Do we still need two fields or combine together into `adc_update_date`?

**Comment by bcorrie** [comment]
I would suggest two fields?

**Comment by schristley** [comment]
@bcorrie @williamdlees  Should we also consider a timestamp for individual repertoires? In discussions about integration with OGRDB/VDJbase, is the study level too coarse, will they want to know when individual repertoires (and its associated rearrangement, clone, etc objects) have been modified/updated?

**Comment by williamdlees** [comment]
If we're anticipating OGRDB auto-annotating new repertoires as they appear in the repo, a date per repertoire would be useful.

**Comment by bcorrie** [comment]
Probably makes the most sense for a date to be attached to a `DataProcessing`??? That is the data that was processed with this `DataProcessing` process (e.g. annotation) was loaded into the ADC repository on this date. That way a date could be related to every rearrangement/clone that came from that DataProcessing without having a date in each rearrangement record.

I think the question then becomes do we need a date for a study, as that can be computed based on the latest update date of all the repertoires in a study...

**Comment by schristley** [comment]
> If we're anticipating OGRDB auto-annotating new repertoires as they appear in the repo, a date per repertoire would be useful.

Right, though I think in general, new repertoires appear because new studies appear, so I think the study publish date satisfies that. I was meaning more specifically when repertoires change (modified/updated) and thus there might be an evaluation to determine if the change is important. For example, fix a curation error, add new metadata that was missing before, and so on. Those might be fixes to individual repertoires versus all repertoires in the study. I'm just not sure if the granularity is needed.

**Comment by bcorrie** [comment]
Good point... Question of granularity is important I think. What is valuable to clients of the repository to know? We tend to track changes at the study level on our provenance page: http://www.ireceptor.org/repositories/provenance

**Comment by williamdlees** [comment]
If I, or someone else, wanted to update some analysis on each repertoire whenever the repertoire changed, how would they do that, based on a study date alone? Just assume that every repertoire has been updated every time the study date changes? It feels to me that's baking in some assumptions about how updates are released.

Beyond the revision date, do you provide details of the toolchain - software versions and germline set version, for example?

**Comment by schristley** [comment]
> If I, or someone else, wanted to update some analysis on each repertoire whenever the repertoire changed, how would they do that, based on a study date alone? Just assume that every repertoire has been updated every time the study date changes? It feels to me that's baking in some assumptions about how updates are released.

Valid points and questions, pretty much what I was thinking when I asked the question. Though this just addresses "what" has changed, it soon leads us to ask "how" it changed, which leads to questions about data versioning and provenance... But I don't want the scope of this issue to grows out of bounds, as the original issue is more mundane.

As the other major repository provider, if @bcorrie is okay with also adding an `adc_update_date` to individual repertoires, then I'm also good with it. Side point...we are going to need to start documenting best practices for repositories, as having this info buried in a field description is easy to miss...

> Beyond the revision date, do you provide details of the toolchain - software versions and germline set version, for example?

Technically, yes, with `DataProcessing` though we know there issues with reproducibility there...

**Comment by bcorrie** [comment]
For @williamdlees case, I think the date of interest would actually be a date attached to `DataProcessing` wouldn't it. I think @williamdlees you are talking about triggering an analysis if the rearrangement annotation data for a repertoire have changed, correct?

In `DataProcessing` we store the tool chains, versions of annotation tools, germline set used for annotation, and logically might store a date (say `adc_dataprocessing_update_date`) when the annotations were loaded. 

If you then decided to replace those rearrangements with a new annotation with a new germline set, you would delete the rearrangements, reannotate, reload, and then change the `DataProcessing` to store the new germline set and have a new  `adc_dataprocessing_update_date`.

You could then trigger a downstream analysis on those rearrangements - e.g. trigger a new computation of an inferred germline based on the new annotation.

**Comment by bcorrie** [comment]
I think I would think of a Repertoire change date (e.g. adc_repertoire_update_date) would be set when something in the Repertoire changes, including Repertoire metadata. Opps, I made a mistake and got the age of a subject wrong. I fixed it, and update the `adc_repertoire_update_date`.

**Comment by schristley** [comment]
> I would think a Repertoire change date (e.g. adc_repertoire_update_date) would be set when something in the Repertoire changes, including Repertoire metadata. Opps, I made a mistake and got the age of a subject wrong. I fixed it, and update the `adc_repertoire_update_date`.

Yes, exactly. Or we added race/ethnicity info or diagnosis info to a subject, so now you might need to update your genotype/haplotype maps in VDJbase.

**Comment by williamdlees** [comment]
All good points.

**Comment by schristley** [comment]
> I think the date of interest would actually be a date attached to `DataProcessing` wouldn't it.

What concerns me here is that it becomes a rabbit hole. `DataProcessing` isn't just for rearrangements but also many other objects (cells, clones, trees, etc.). The same questions apply, there could be updates to one of those objects that OGRDB/VDJbase doesn't care about, yet the granularity level of the date at `DataProcessing` doesn't provide.

I'm fine if we want to discuss and pursue that, but in another issue. If we constrain this issue to just repertoire metadata, then I think we have solution ready to go.

**Comment by williamdlees** [comment]
Sure, I’m happy to wait until/if we do pursue OGRDB integration, at which point perhaps we could talk about a more elegant and tailored solution, I am not wild about polling dates across all the repertoires.
