### ISSUE TITLE
read_rearrangement in the R package is vulnerable to confusion about column types from readr::read_tsv

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#475]
I have a file that is giving the following warning from `airr:read_rearrangement`, which is from `readr::read_tsv`:

```
Warning: 84610 parsing failures.
row    col             expected               actual
7570   d_call_10x      1/0/T/F/TRUE/FALSE     IGHD1-1
7591   vjl_group       1/0/T/F/TRUE/FALSE     G21 
```
Leading to all `NA` values in those columns.  Using `guess_max=10000` with `readr::read_tsv` avoids the error.
Those aren't AIRR columns, but we should still be loading them honestly somehow. Maybe by adding a `guess_max` argument to pass through to `read_tsv` or by defaulting unrecognized fields to type `character`.

**Comment by scharch** [comment]
Is this related to #433?

**Comment by javh** [comment]
No... But, that's one way we could fix it.

**Comment by ustervbo** [comment]
I guess setting `.default = col_character()` is a safer because the behavior will be the same irrespective of the number of lines in the tsv.

#433 is more elegant, though

**Comment by javh** [comment]
From the call:
1. Default to `character`, but allow user to specify a named vector that defines column type and pass this to `readr::read_tsv`
2. Add unit test for this case.
3. @javh should provide example data file that reproduces the issue.
