### ISSUE TITLE
duplicate_count vs number of rearrangements (ADC API query)

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#480]
@schristley we ran into a somewhat interesting problem... As far as I can tell, in the ADC API there is no way to ask a repository to count the number of total sequences in a Repertoire if the identical sequences have been collapsed using duplicate_count. So currently we can get one of two things:

1. We can facet on repertoire_id and get the total number of rearrangements (when there is no collapsing identical sequences - ie. no duplictate_count).
2. We can facet on repertoire_id and get the total number of unique sequences (when unique sequences have been collapsed using duplicate_count).

In the case of data that has unique sequences collapsed with duplicate_count, there is no way with the ADC API to get the total number of rearrangements that produced the collapsed counts (essentially the sum of the duplicate_counts). Am I missing something? From a UI perspective, we would ideally be able to show both, but we can't...

**Comment by bcorrie** [comment]
Note the same will hold true for clone and clone_count as well...

**Comment by schristley** [comment]
> As far as I can tell, in the ADC API there is no way to ask a repository to count the number of total sequences in a Repertoire if the identical sequences have been collapsed using duplicate_count.

That's correct. I think CWRG has had some old discussions about this. I seem to remember that using `duplicate_count` is on the borderline between being a query versus being an analysis.

**Comment by schristley** [comment]
@bcorrie Shall we consider extending the facets capability to also provide sums? I'm skeptical with the size of VDJServer that this could be done quick enough for interactivity. Also, I'm unclear of the utility except for a few fields. Or should we consider making the Stats API an ADC extension? It offers the count and sums that you want.

**Comment by bcorrie** [comment]
I like the Stats API as an ADC extension. We have discussed this at CRWG in passing, but I think it would be worth agreeing that this would be useful.

**Comment by bcorrie** [comment]
Moving this to ADC API v2.0

**Comment by bcorrie** [comment]
Closing this issue - superseded by #753
