### ISSUE TITLE
Next steps for Germline developments

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#482]
Further to the discussion in #416 and the pull request in #438 where we created the first germline implementation, I wanted to capture a new issue with the outstanding "next steps" as discussed here: https://github.com/airr-community/airr-standards/pull/438#issuecomment-716825784. 

The list from the comment above includes:

- Finalize GeneDescription
- Finalize how we will normalize germline gene sets
- Discuss if we want/need repositories that store germline gene sets
- Come up with an API to query germline gene sets

**Comment by bcorrie** [comment]
Related information:

- Using CURIEs for germline annotation: https://github.com/airr-community/airr-standards/issues/416#issuecomment-639611583
- Germline set pervious work: #157 
- GermlineSet object (previously added and then removed) that we want to develop further: https://github.com/airr-community/airr-standards/pull/438/commits/ef4bb0bbcaac9f1e91768ea9ae2d76addb4afb67

**Comment by williamdlees** [comment]
Closing this following the pull request and merge
