### ISSUE TITLE
Switch over to GitHub Actions

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#484]
I just learned [here](https://ropensci.org/technotes/2020/11/19/moving-away-travis/?s=09) that Travis is shutting down travis-ci.org.

[From Travis](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom): 

> We encourage you to migrate your existing repositories that are currently on travis-ci.org over to travis-ci.com as soon as possible, enabling you to identify any additional changes required to your code or configuration well in advance of the December 31st deadline.

**Comment by schristley** [comment]
I've migrated us to the free plan on travis-ci.com so we can keep builds.

**Comment by bussec** [comment]
Re-opening as our supply of credits at travis-ci.com is limited. We either need to register as an Open Source project, switch to a paided plan or switch to another CI provider.

**Comment by schristley** [comment]
@bussec Worthwhile to pursue having the Antibody society pay for travis plan? It's pricy though @ $759 / year

**Comment by bussec** [comment]
@javh IIRC you recently turned of Travis for good, so can we close this?

**Comment by javh** [comment]
Yeah, I did.
