### ISSUE TITLE
Should ADC API have more explicit error messages?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#487]
Currently we have 200 and 500 as http responses. There are a number of error messages that one might expect from the ADC API based on the spec, such as a "Timeout" when the server gives up because the query is to complex or a "Too much data" error when the user asks for more data at a time than the server can provide. I suspect there might be others...

**Comment by schristley** [comment]
Sounds good, I suppose some [codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) are immediately appropriate like "408" for timeout.  Can you propose which ones that should be added?

**Comment by bcorrie** [comment]
Moving this to ADC API v2.0 as the question is still relevant.

**Comment by bcorrie** [comment]
@schristley I suggest we add some docs to the limits section, and add the following error messages that should be returned when limits are not adhered to:

- 408 when a server time out has expired https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408
- 413 when max_size or max_query_size are exceeded - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413

I think we should suggest that other codes are returned as deemed appropriate - obvious I suppose, but worth stating.

**Comment by schristley** [comment]
> @schristley I suggest we add some docs to the limits section, and add the following error messages that should be returned when limits are not adhered to:

Yes, I agree but let's also put them in the API spec as responses.

> * 408 when a server time out has expired https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408

VDJServer should be returning this already.

> * 413 when max_size or max_query_size are exceeded - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413

Not sure if VDJServer returns this, I think it returns generic 400 for query error but I'm good with using a more specific error code.

**Comment by bcorrie** [comment]
Added some docs:
https://github.com/airr-community/airr-standards/pull/752/commits/ab2b8ce470fcfe72840236ab58f35dd746058a68

Updated the specs:
https://github.com/airr-community/airr-standards/pull/752/commits/f88b357286a90287325a362360cc63831b0b60a2
https://github.com/airr-community/airr-standards/pull/752/commits/65e7ab2abc3f5c015d61693ba857e9c7b21f8b80

I think we can close this.
