### ISSUE TITLE
Python AIRR validation tool Error

### ISSUE THREAD

**Issue by franasa** [airr-community/airr-standards#488]
:tada: HNY :two::zero::two::one: :tada:

Validating a rearrangements TSV file with the python AIRR validation tool raises an error when these fields are missing from a rearrangements TSV:

`rev_comp`,` sequence_alignment`, `germline_alignment`, `v_cigar`, `d_cigar`, `j_cigar`

Since they are not labeled with the `miairr:` flag they weren't parsed by our tool, but just adding them as empty columns was sufficient to pass the validation. 
Is this expected? and if so, shouldn't those properties also include a `miairr` label in the airr schema?

Additionally, the validation tool also raises these warnings for repertoire YAML files generated in our export routine:

```
Warning: Object has non-AIRR field that cannot be validated (study.study_contact).

[...] validation error: Field sample.collection_time_point_relative does not have string type: 16
````
Could this be due to the recent changes in the schema when we introduced `collection_time_point_relative_unit` (and `collection_time_point_relative` should be now number instead of string) and the `study_contact` fields?

**Comment by schristley** [comment]
> 🎉 HNY 2️⃣0️⃣2️⃣1️⃣ 🎉
> 
> Validating a rearrangements TSV file with the python AIRR validation tool raises an error when these fields are missing from a rearrangements TSV:
> 
> `rev_comp`,` sequence_alignment`, `germline_alignment`, `v_cigar`, `d_cigar`, `j_cigar`
> 
> Since they are not labeled with the `miairr:` flag they weren't parsed by our tool, but just adding them as empty columns was sufficient to pass the validation.
> Is this expected? and if so, shouldn't those properties also include a `miairr` label in the airr schema?

🎉🎉 Hi @franasa , that is correct. Though they aren't MiAIRR fields, they are tagged as `required` in the schema file, so those fields should exist in the TSV even if values are null.

**Comment by schristley** [comment]
> Additionally, the validation tool also raises these warnings for repertoire YAML files generated in our export routine:
> 
> ```
> Warning: Object has non-AIRR field that cannot be validated (study.study_contact).
> 
> [...] validation error: Field sample.collection_time_point_relative does not have string type: 16
> ```
> 
> Could this be due to the recent changes in the schema when we introduced `collection_time_point_relative_unit` (and `collection_time_point_relative` should be now number instead of string) and the `study_contact` fields?

That sounds right. `collection_time_point_relative` is defined as `number` in the latest schema so I'm not sure why it's complaining about not being string type. Is it possible that the python library that you are using for validation has an old schema?

**Comment by franasa** [comment]
> Though they aren't MiAIRR fields, they are tagged as required in the schema file, so those fields should exist in the TSV even if values are null.

I see,  wouldn't these properties then need to have a `miairr:` defined flag? As you mention,  If I would rely solely on the miairr flags from the schema I then have a TSV that is MiAIRR compliant but still fails the validation;  Or is it expected that a tool checks for both the `miairr ` and the `required` array together? 

btw, and as I also told Jason by email, I'd be glad to help anytime with the python package features, just let me know how could I best jump in (:.

**Comment by schristley** [comment]
> I see, wouldn't these properties then need to have a `miairr:` defined flag? As you mention, If I would rely solely on the miairr flags from the schema I then have a TSV that is MiAIRR compliant but still fails the validation; Or is it expected that a tool checks for both the `miairr ` and the `required` array together?

You need to check both, or really I think just `required` is sufficient to check. The `required` flag is a requirement beyond MiAIRR. It's separate because `required` is the correct OpenAPI schema way to indicate required fields, thus all tools should recognize it. The `x-airr` object and `miairr` flag are extensions, so really only AIRR tools recognize it.

**Comment by javh** [comment]
Yeah, just to echo what @schristley said, the validation tool is for validating compliance with the Rearrangement schema, not MiAIRR, and the Rearrangement schema has requirements beyond MiAIRR.

As for python package help, that would be very much appreciated. I think #195 is probably the most important issue, followed by #378.  We haven't made any decisions on #314 or #433, so maybe if we can decide on those they might be nice to tackle as well.

Also, it's not python issue, but we need to address the Travis-CI issue #484.

**Comment by franasa** [comment]
Closing this since #195 is in progress,  #484 is closed, and the remaining issues have been moved into the project tracking. Also the main questions were clarified:

>... that is correct. Though they aren't MiAIRR fields, they are tagged as required in the schema file, so those fields should exist in the TSV even if values are null.

&
>... the validation tool is for validating compliance with the Rearrangement schema, not MiAIRR, and the Rearrangement schema has requirements beyond MiAIRR
