### ISSUE TITLE
asynchronous API extension for the AIRR Data Commons

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#490]
The current ADC API (v1.0) is synchronous, which is simple but presents challenges for service implementors, especially as the data increases in scale. For example, it's possible for a malicious client to overload a server if that server doesn't have safeguards in place. Services can make different choices about how to implement the API in order to mitigate such service attacks, but then this may introduce inefficiencies and/or tradeoffs. The CRWG didn't want to "force" any particular design on service implementors, and thus the API allows for services to have safeguards (e.g. limited data transfer, timeouts, etc.)

I think the simplest way to describe the issue is, how to balance interactivity (small, fast queries) versus downloads (large, slow queries)?

This can also be a concern for clients as they 1) might not know if any particular query is fast or slow, and 2) even if they did know, there's no way to inform the server of their intent.

The small, fast queries aren't the problem, it is the large, slow queries. This API extension will provide for asynchronous query capability which allows services to "scale-up" to handle many large, slow queries without sacrificing performance for interactivity. Essentially, services can decide how many of these queries are being performed concurrently (e.g. to manage load on their backend database) without being "forced" to respond as expected with the synchronous API.

**Comment by bcorrie** [comment]
My main question around such an extension would be the tradeoff between simplicity and capability. One of the drivers for having our current simple, synchronous API is its ease of implementation, which hopefully translates to adoption by repository developers. Asynchronous APIs are quite complex to implement, and if we burden repository developers with such an implementation I would worry that we would limit adoption of the API and therefore fewer repositories becoming AIRR compliant. 

Are you thinking of this as a required API to be AIRR compliant, or as an "optional" API that we could specify and implementers could choose to support to add capability? We haven't really talked about the possibility of API extensions, but that seems like it could be attractive. One could think of our Stats API capabilities along a similar line. Not something we would necessarily require for AIRR compliance, but something that adds a significant capability to the repository...

**Comment by bcorrie** [comment]
> I think the simplest way to describe the issue is, how to balance interactivity (small, fast queries) versus downloads (large, slow queries)?

Are you thinking of this primarily for downloads (which can take a long time), or also for long running queries (which can be arbitrarily complex and therefore take a long time)?

**Comment by schristley** [comment]
> Are you thinking of this as a required API to be AIRR compliant, or as an "optional" API that we could specify and implementers could choose to support to add capability?

Optional, or an extension.

> Are you thinking of this primarily for downloads (which can take a long time), or also for long running queries (which can be arbitrarily complex and therefore take a long time)?

I think it applies to both. In the short term, I'm mainly thinking about downloads.
