### ISSUE TITLE
Add an AIRR TSV file split capability to python AIRR Utilities

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#492]
The ADC API makes it very easy to download large data sets into a single AIRR TSV file. One of the most common use cases would be for someone to process that data on a per repertoire basis. It would be nice if we had this capability in the python AIRR utility code. It looks like this should be easy to add. I am thinking splitting on the triple <repertoire_id, sample_processing_id, data_processing_id> although it might be nice to be able to split on a subset of these.

I have had several requests for this capability - although it isn't hard to do with some average bash/awk/grep magic, it might be nice to have this as a utility function in the AIRR library.

**Comment by javh** [comment]
You could point people here in the meantime:
https://changeo.readthedocs.io/en/stable/tools/ParseDb.html#parsedb-split

**Comment by schristley** [comment]
ParseDB has pretty extensive support, no need to replicate all that in the AIRR library.
