### ISSUE TITLE
Need to specify an AIRR Data Commons Registry API

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#495]
We need to create a registry API for the AIRR Data Commons so that it is possible to query the registry and discover all of the repositories in the AIRR Data Commons.

Once we have a registry spec, we can then figure who will implement it and how and where we run it.

This is related to the old CRWG issue https://github.com/airr-community/common-repo-wg/issues/18 which I have closed so we can move the discussion here.

**Comment by bcorrie** [comment]
Looking at Global Alliance for Global Health (GA4GH) APIs for service info (https://github.com/ga4gh-discovery/ga4gh-service-info) and service registry (https://github.com/ga4gh-discovery/ga4gh-service-registry) and they seem to look like they might be useful. We might want to consider implementing this as our service registry and the service_info endpoint to our services...

**Comment by schristley** [comment]
Earlier, CWRG looked at [DataMed](https://datamed.org) which seems to be a pretty standard repository registry. It looks like they have all the main repositories, and they have a search API.

**Comment by schristley** [comment]
Alternatively, the openapi3 version has a `servers` object that we could use it to list all of repositories, though there isn't an easy mechanism currently for programs to "find/load" the ADC API yaml file. The file isn't installed when the R or python packages are installed.

One bonus is we can use it to dynamically generate the documentation page.

**Comment by bcorrie** [comment]
> Alternatively, the openapi3 version has a `servers` object that we could use it to list all of repositories, though there isn't an easy mechanism currently for programs to "find/load" the ADC API yaml file. The file isn't installed when the R or python packages are installed.
> 
> One bonus is we can use it to dynamically generate the documentation page.

Certainly a good starting point.

**Comment by bcorrie** [comment]
Moving this issue to the adc_registry github repository. https://github.com/airr-community/adc-registry/issues/1
