### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by franasa** [airr-community/airr-standards#496]
Since January 1, 2020, there is no official support for Python 2.7 anymore, meaning that no more bug fixes or security updates will be released. I couldn't find any discussion about this, so I'm opening this one to ask whether a complete switch to python 3.6+ is planned for the python library, or if there are any reasons not to do it?

**Comment by javh** [comment]
No objections from me. Though, I think we should wait until AIRR v2 before dropping Python 2 support, because it's a major change.

**Comment by schristley** [comment]
It's going to take some time to update workflows (on VDJServer) that use python2. The AIRR v2 timeframe seems reasonable to me.

**Comment by javh** [comment]
From the call: Agreed to convert to Python 3 in v2.

**Comment by schristley** [comment]
While I don't have VDJServer completely converted yet, it's going quicker than the AIRR V1.4 release, so we might want to consider dropping for V1.4 instead.

**Comment by javh** [comment]
All right, swapped the milestone. We can decide once we approach v1.4. Sound good?

**Comment by javh** [comment]
From the call:
* We can drop python support in v1.4 to enable the Germline schema.
