### ISSUE TITLE
Revisit `date` format

### ISSUE THREAD

**Issue by franasa** [airr-community/airr-standards#499]
Related to #498 but to be solved independently.  

There is one appearance of `format: date` in `sequencing_run_date` (with `date` being not defined on the `Attributes` object)

Should `date` be added to the  the `format`  enum? of `Attributes` (instead of `physical quantity`?,  see #498) ?

**Comment by schristley** [comment]
`format: date` is coming from the [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#data-types). Note that `Attributes` only defines the properties in `x-airr` while everything else is from JSON Schema or OpenAPI.

**Comment by franasa** [comment]
That clarifies this issue, thanks @schristley
