### ISSUE TITLE
Harmonize data types with airr-formats

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#5]
I'd propose harmonizing the data types between the two repos.  In the airr-formats group, we specify the types as `string`, `boolean`, `float`, and `integer`.  Any objections to a PR that would make them the same?

**Comment by BusseChristian** [comment]
No, please go ahead.

**Comment by schristley** [comment]
In definitions.yaml I'm using the canonical JSON types as suggested by Uri, plus `enum`.

**Comment by BusseChristian** [comment]
@schristley : Will `enum` allow for `NULL` values?

**Comment by schristley** [comment]
Not exactly, so for NucleicAcidProcessing if the service tried to return

```
{ "library_source": null}
```

then it would throw a schema validation error (I tested this with code). There are two ways to handle this:

1. If the value is null then don't return that field in the response.
2. Define a "null" value with the enum.

Generally services do 1 as clients need to generally check if the field exists first before accessing its value. The issue is if the field is a required field, then you would need to do 2.

Note this issue also applies to boolean, as null isn't a valid value, and maybe some other data types.

**Comment by BusseChristian** [comment]
Well, for items like `library_source` this information will be available and unambiguous. But we should think about medical items like `sex` where a controlled vocabulary would make sense, but the information might not be available and ambiguous.

**Comment by schristley** [comment]
I agree and providing additional enum values like "N/A", "Unknown", "Not specified", and so on can document those cases.

**Comment by laserson** [comment]
Where will the definitions.yaml file most likely be consumed?

In general, I'd say that all fields should be nullable.

**Comment by schristley** [comment]
Right now it is being referenced by the [iReceptor API work](https://github.com/sfu-ireceptor/api/tree/AIRR-compliance) and the common repository WG [example API](https://github.com/airr-community/common-repo-wg/tree/issue-13/specs). I also expect that the formats WG will reference these definitions for tools to access study metadata.

**Comment by schristley** [comment]
@BusseChristian 
Jason makes a good point about GenBank submission, maybe [vdj]_allele needs to be split out into two fields?

https://github.com/airr-community/airr-formats/issues/45

**Comment by BusseChristian** [comment]
See my comment there. I think the best solution for now is to rename the fields to `[vdjc]_call`, although parsing tends to be difficult. If the subcomponents are required by downstream processes, we should discuss the most likely scenarios to see what to include where.

**Comment by schristley** [comment]
Actually we should follow the [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) for primitive types which are `string`, `boolean`, `number` and `integer`. We can use `format` to be more specific.
