### ISSUE TITLE
Add clone and rearrangement keywords to keywords_study

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#515]
I think for completeness we may want to add a couple of keywords to our controlled vocabulary for `keywords_study`

Currently we have:

- contains_ig
- contains_tcr
- contains_single_cell
- contains_paired_chain

I am suggesting we add

- contains_clone
- contains_rearrangement

I think it would be useful to know if a `Study` has clones just like it is useful to know if a study contains paired or single cell data. For completeness it makes sense that we note whether a study has rearrangements or not.

**Comment by javh** [comment]
What about addressing this in the manifest instead?

**Comment by bcorrie** [comment]
For the record, manifest issue is here: #426 

> What about addressing this in the manifest instead?

As I understand it, the manifest is more about managing inter-related files. I suppose it is a bit unclear to me how the MiAIRR description of the study is related to how the manifest captures the structure of the study in terms of files.

For me, this is a mechanism to provide an easy way to find out if a study has data of a certain type, and fits well with the `study_keywords` field at the moment.

**Comment by scharch** [comment]
> I suppose it is a bit unclear to me how the MiAIRR description of the study is related to how the manifest captures the structure of the study in terms of files.

I think the question is whether this is properly part of the MiAIRR description or whether it is something more technical about the format of the data. Given that `Manifest` is (in my understanding) envisioned as the entry point of a `Study`, you could get the information you want by looking for a property like (eg) `path_to_clone_file` and whether it is null or not. That would be a step faster than looking up `path_to_repertoire_file` and then parsing the metadata for a `contains_clone` property (after which you'd _still_ need `path_to_clone_file` to acutally retrieve that data anyway). Might need some nuance for Ig vs TCR, though.

On a separate note, shouldn't `contains_paired_chain` be deprecated??

**Comment by bcorrie** [comment]
> I think the question is whether this is properly part of the MiAIRR description or whether it is something more technical about the format of the data.

Agreed... That is why I pinged @bussec... The reason I thought it made sense as a `keywords_study` is that is where we have other such things like `contains_single_cell`. It made sense to me that this field contains keywords about what kind of objects from the AIRR spec that the study collected.

**Comment by bussec** [comment]
@bcorrie In general, I don't have strong opinions for or against adding specific keywords, if it simplifies usage. The one difference -- if I understand your proposal correctly -- between the current and the proposed terms is that the former ones were introduced to flag properties of the `rearrangement` object, which would be time-consuming to parse out otherwise, while the latter ones signify the existence of individual object in the data schema. Admittedly, `contains_single_cell` by now could be replaced with a test for the existence of a `cell` object, but for this we would need to decided that this object (and the associated file) become mandatory for single cell experiments.

Would it be meaningful to distinguish between "features of" and "objects in" a study, or would this only complicate things?

**Comment by bcorrie** [comment]
For me it makes sense to describe, as part of your study description, the types of data that are in your study. Given that the AIRR data model is getting quite complex (Repertoire, Rearrangement, Clone, Cell, Tree, ...) it seems like we want to have an easy way for the researcher to specify if a study contains a specific type of data as well make it easy for the user of the data to determine if 
a specific type of data of interest exists in a study. `keywords_study` provides a simple, single place to discover this.

Testing for the existence of objects means you need to know which types of objects there are and how to test for their existence. This is quite messy, cumbersome, and possibly error prone.

I would rather search for a keyword base controlled vocabulary rather than looking for files of a certain type (or the equivalent querying API entry points of a certain type in the ADC world). A manifest will help with this, but it just seems logical to me to have a place where at a glance the user can see that a study contains clones while another one doesn't.

**Comment by javh** [comment]
From the call:
* Maybe `contains_clone_data` and `contains_rearrangement_data` to denote object presence rather than the experimental protocol.
* Maybe put this in DataProcessing in the future (consider during object redesign)?

**Comment by bcorrie** [comment]
Hi all, any chance we can try and close this out - fairly straightforward, but with single cell and clones on the horizon, it would be good to get closure on this.

Currently:

- contains_ig
- contains_tcr
- contains_single_cell
- contains_paired_chain

I think we are here:

Add:

- contains_clone_data
- contains_rearrangement_data

Do we change contains_single_cell to contains_single_cell_data?

Those are the high level objects (Rearrangement, Clone, Cell) with Cell => Expression data?

Do we leave the others as is:

- contains_ig
- contains_tcr
- contains_paired_chain

**Comment by javh** [comment]
Suggestions from the call:
