### ISSUE TITLE
characterize the schema objects in OGRDB

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#517]
Determine which objects are "core" to an interoperability standard for germline gene reference sets.

**Comment by williamdlees** [comment]
See https://github.com/airr-community/airr-standards/pull/295#issuecomment-812854376

**Comment by schristley** [comment]
The [gldb schema](https://github.com/airr-community/gldb-wg/blob/master/germline_schema/schema/receptor_germline_schema.yaml) and the [germline schema](https://github.com/airr-community/airr-standards/blob/9b914790a0a61840e9e93c4b6716ea5d6385aa8f/specs/airr-schema.yaml#L142) currently in airr-schema.yaml
