### ISSUE TITLE
Add Immcantation to docs of software with badge on master branch?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#519]
@scharch Immcantation has been awarded the software badge, correct? Can we add it to the tools that have such a badge so this appears on the docs site on the "latest" branch (which is master I believe). We are referring to the AIRR software compliance and the applications that have passed the compliance test in a grant application, and we want to talk about Immcantation - but it doesn't appear yet. I am happy to make the change, but thought I would check in and confirm that it was ok (and what version to list).

**Comment by scharch** [comment]
Yes, Immcantation should be on the list of certified tools. There's a table somewhere that allows the updated list to appear on `stable` even without a version change... @williamdlees usually takes care of this but I can dig the instructions out of my email later this week...

**Comment by williamdlees** [comment]
Apologies, it’s there now.


William
