### ISSUE TITLE
Where did Rearrangement quality and quality_alignment come from?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#525]
I am in the process of updating the iReceptor AIRR Mapping to take into account the germline and cell fields, and these appeared without my recollection of them being added. A git blame says they were added as part of the OpenAPI v2 - v3 merge that Scott did, which doesn't really make sense since they are field additions.

The git blame also has a typo introduced, which was later fixed and a weird cell_id comment, so I wanted to make sure this was not some git conflict resolution that got weird???

**Comment by bcorrie** [comment]
@schristley can you have a look at this? Just checking that these are how we expect them to be...

**Comment by schristley** [comment]
@bcorrie #479 #481 part of @franasa work. I'm not sure why it isn't showing in the commit history, maybe with how the  commit was merged.

**Comment by franasa** [comment]
@bcorrie that is correct,` quality` and `quality_alignment` were added to close **479**. The cell_id comment must come from the introduction of the Cell object by Sri on #388. I believe it was part of an internal discussion and can be safely deleted. I am not sure about the typo, that one I couldn't trace back (:
