### ISSUE TITLE
AIRR file validation inconsistent between R and Python libraries

### ISSUE THREAD

**Issue by swemeshy** [airr-community/airr-standards#527]
I've been working with several AIRR TSV files. In Python, I added a column to each of these files, and then using `merge_rearrangement`, I merged and wrote the output to a file. I made sure to validate the output file using `validate_rearrangement`. Then, I proceeded to open this file in R using `read_airr`, however I get a warning about non-unique values in the `sequence_id` column, and checking validity using `validate_airr` gives me `FALSE`, i.e. it is not valid.

Not sure if this is an error on my end, or something that needs to be fixed. Let me know, thanks!

**Comment by scharch** [comment]
@swemeshy if this is still relevant, please submit example data for reproducing the issue.

**Comment by javh** [comment]
Likely merged files had duplicate IDs, so failing validate is expected.
