### ISSUE TITLE
Field names for the deletion count from the V 3’, 5’ and 3’ D, and 5’J

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#536]
We are looking for field names for the deletion count from the V 3’, 5’ and 3’ D, and 5’J. This is related to issue #139 and [alakazam issue 96](https://bitbucket.org/kleinstein/alakazam/issues/96/use-airr-ish-names-for-output-fields-of). We would like to use names that are decided by the community and can be standard names. Let us know what your preference is, or if you have additional options.

Description | Option 1 | Option 2
------------ | ------------- | ---------------
Number of 3' V germline nucleotides deleted  |  v_germline_deleted_3  |  d3v_length
Number of 5' D germline nucleotides deleted | d_germline_deleted_5 | d5d_length
Number of 3' D germline nucleotides deleted | d_germline_deleted_3 | d3d_length
Number # of 5' J germline nucleotides deleted | j_germline_deleted_5 | d5j_length

**Comment by javh** [comment]
Option 3: `e3v_length`, ...
Option 4: `e3v_deletion`, ...

"e" for excision/exonuclease.

**Comment by ustervbo** [comment]
If suggestions are possible:

nd_3v (number deleted 3' V)
nd_5d (number deleted 5' D)
nd_3d (number deleted 3' D)
nd_5j (number deleted 5' J)

I find length of deleted nt conceptually difficult.

**Comment by bussec** [comment]
My two cents:

1. What ever the naming scheme is, we need 6 fields in total: 1x V, 2x D, **2x D2**, 1x J
2. While I agree that @ssnn-airr's Option 2 is the most consistent with our current naming, I would find it confusing to have names like `d3d2_length`.
3. Do we agree that the values of these field have be integers >= 0?
4. Is the statement "length(`np1`) = `np1_length` = `n1_length` + `p3v_length` + `p5d_length`" always true, irrespective of the inferrence tool?

**Comment by javh** [comment]
> While I agree that @ssnn-airr's Option 2 is the most consistent with our current naming, I would find it confusing to have names like `d3d2_length`.

Yeah, that's kinda why I'm leaning towards something like "e", "ex", etc.

Just for references, the other detailed junction alignment fields are:

- n1_length
- n2_length
- n3_length
- p3v_length
- p5d_length
- p3d_length
- p5d2_length
- p3d2_length
- p5j_length

**Comment by javh** [comment]
> Do we agree that the values of these field have be integers >= 0?

I do, if we include `null`.

> Is the statement "length(np1) = np1_length = n1_length + p3v_length + p5d_length" always true, irrespective of the inferrence tool?

This seems right to me, for heavy chains at least; light being `np1_length` = `n1_length` + `p3v_length` + `p5j_length`.

**Comment by ssnn-airr** [comment]
Is there a way to "vote" here?

Options:

- Option 1: `v_germline_deleted_3`
- Option 2: `d3v_length` ("d" for deletion, confusing if 2 d_calls: `d3d2_length`)
- Option 3: `e3v_length` ("e" for excision/exonuclease)
- Option 4: `e3v_deletion` ("e" for excision/exonuclease)
- Option 5: `nd_3v` ("nd" for number deleted)

I liked 1, but given that "Option 2 is the most consistent with our current naming"... my vote goes for Option 3 :)

**Comment by schristley** [comment]
> 2. While I agree that @ssnn-airr's Option 2 is the most consistent with our current naming, I would find it confusing to have names like `d3d2_length`.

It isn't necessary that we use prefixes and make the names short and obtuse. I wouldn't mind seeing some options that make the names more self-documenting.
