### ISSUE TITLE
Should a version number be associated with repository submissions?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#54]
Not sure if it necessary but worthwhile to think about. We have the situation where the minimal standards will likely undergo refinements, yet we should soon expect that studies will be submitted to repositories following MiAIRR. How to handle if incompatible changes are introduced? Should a spec version number be associated with repository submissions? This might also be important for APIs that repositories expose. How could this be implemented?

I can see how tools that perform automated submission could insure that a version number is attached, not sure how to do that for manual submissions.

**Comment by laserson** [comment]
Good point.  We could simply add a field that lists the AIRR version number. If done manually, I imagine the user would have some NCBI-related templates to fill out.  Since these are versioned, they can include their version string for the field.

**Comment by scharch** [comment]
Closing as moot since MiAIRR is now in maintenance mode
