### ISSUE TITLE
Should Clone have a c_call?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#542]
Currently the AIRR spec does not have a c_call in the Clone object (along with other accompanying C gene fields). Should it?

**Comment by bussec** [comment]
The constant region is not a defining part of the clone, i.e., an IGHG1 sequence can be part of a cluster that also contains other isotypes. Assuming that `Clone` is used to define the grouping criterions for individual `Rearrangements`, the latter ones would still contain the `c_call` information.

**Comment by bcorrie** [comment]
@bussec if I understand correctly, the answer is no, a clone shouldn't have c_call - so we can close this?

**Comment by bussec** [comment]
@bcorrie yes, we can.
