### ISSUE TITLE
Clean up docs RE: YAML/JSON

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#547]
We talk about YAML/JSON and file formats for specific objects in various places (e.g. `Rearrangement` and `Repertoire`). For primarily historical reasons they talk about each other and their relationships. We should probably:

- Just talk about the formats for objects in their specific section
- Talk about how the objects and their file formats are related in a new "Manifest" section - #426

E.g. This page on `Rearrangements` talks about `Repertoire` formats, which should probably be removed as it is out of date: https://docs.airr-community.org/en/stable/datarep/rearrangements.html#file-format-specification

**Comment by javh** [comment]
From the call:
* Manifest docs are a separate task.
