### ISSUE TITLE
What's needed to complete for V1.1.0 software release?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#55]
While staying in an alpha version is ok, it means we do not take advantage of semantic versioning, so I'd like us to plan for features we should finish. Here's what I'd like to see:

- integrate airr-formats (i.e. the current python reference library).
- have the doc website generated from GitHub
- NCBI/SRA XML operational and tested

Some other ideas but maybe not v1.0...

- initial API for common repository
- tools for performing NCBI/SRA submission, and extracting NCBI/SRA data back into AIRR objects.

Please post your thoughts.

**Comment by laserson** [comment]
Oops, that was an artifact of the merge.

**Comment by javh** [comment]
API documentation for the reference library. 

I'm partial to inline documentation using the napoleon Sphinx extension and [Google style](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings.

For the R package, I should be able to adapt my [markr](https://bitbucket.org/javh/markr) documentation package for Sphinx builds. It's a bit of work, but I don't know if there's a better option. (I need to work on the package anyway.)

**Comment by javh** [comment]
Here's the list of things I think we need to decide/do for an initial release of the Python library. I'm thinking as v1.1.0 of the repo:

1. Should we make the code compliant with [PEP8](https://www.python.org/dev/peps/pep-0008/)?
2. Should split the `RearrangementsFile` class into separate reader and writer class? It works fine as is, but it has a more C++ feel than a Python feel? Not a big deal either way.
3. Similarly with using a filename/handle override strategy on the `__init__` method, instead of always requiring a handle?
4. Fill in docstrings with API docs and add them to the Sphinx build.
5. Comment out the metadata code for the initial release.
6. Should we add a NEWS file? In general, how do we want to manage our changelog?

**Comment by schristley** [comment]
> Should we split the RearrangementsFile class into separate reader and writer class? It works fine as is, but it has a more C++ feel than a Python feel. Not a big deal either way.

One feature I have is to create a derivative file, with the idea that you open an existing file to read, and then write out a new file with some additional annotations. The create derivative function handles copy the metadata, columns, and etc. from the input to the output file for you. How would this be handled with the separate reader writer classes?

**Comment by schristley** [comment]
> Similarly with using a filename/handle override strategy on the __init__ method, instead of always requiring a handle?

Not sure I understand this, can you explain more? The __init__ methods allow either a filename or handle to be specified, how should this be changed?

**Comment by javh** [comment]
> Not sure I understand this, can you explain more? The __init__ methods allow either a filename or handle to be specified, how should this be changed?

Usually, you wouldn't have a function/method accept both a filename and handle as a valid argument in Python. You'd just pick one. A handle is more standard, because then it can be any open file like object (eg, a string buffer). 

Overriding with different types for arguments isn't something Python does. So you have to do something like what we have now, catch it inside the function and open the file if given a filename, or do a small wrapper that opens a file by name and calls the method/function primary function with the open handle.

**Comment by javh** [comment]
> One feature I have is to create a derivative file, with the idea that you open an existing file to read, and then write out a new file with some additional annotations. The create derivative function handles copy the metadata, columns, and etc. from the input to the output file for you. How would this be handled with the separate reader writer classes? Actually I should ask is there a pythonic style for doing that?

Let me think about it, but initial inclination is by simply exposing the relevant information as attributes of the reader class. Ie, if you need to specify `fields` and `metadata` as arguments to initialize the writer class, then the reader would have attributes `fields` and `metadata` that are populated when the reader is initialized.

**Comment by javh** [comment]
Oh, forgot my opinions. :)

1. Slight preference for disobeying PEP8 and leaving the style as is. It means we could use the same style for R and Python. It's not official, but it's not weird either (some of the original python standard library is still in that C++/Java-esque style).
2. No real opinion.
3. Preference for taking only a file handle.
4. I'm willing to be responsible for this.
5. Yes.
6.  I prefer a `NEWS.rst` at the top level that we manually update, but that is automatically included in the sphinx docs.

**Comment by schristley** [comment]
1. No opinion.
2. Leave for now.
3. Only file handle.
4. It's all Jason.
5. Yes.
6. What Jason opined.

**Comment by javh** [comment]
Most of this is now done for the python API. I think at this point we just need:

1. A NEWS.rst file linked to the docs.
2. Some sort of getting started docs. Boilerplate stuff like how to install the package and how to read/write a file.
3. Some very minor code cleanup. Like moving the functions in the top level `__init__.py` to a submodule and using `__all__` instead. Maybe some future proofing, like renaming `airr.read` to `airr.read_rearrangement` (man, that's long), etc.
4. @schristley, do you want to add any of the commandline tools to the initial release?

The R package is maybe half done, so we could target v1.2.0 for that, though it might be done quick enough to include in v1.1.0 (see issue #101).

**Comment by bcorrie** [comment]
If we are talking about documentation that points to tools that support the TSV format, one of the hot button items on our list is to provide the ability to download AIRR TSV files from iReceptor. If we are talking about finalizing things like referencing tools (as opposed to the internal libraries) then I think we might be able to have this completed, depending on when the v1.1 release was targeted at...

**Comment by javh** [comment]
Yeah, just the reference library. Ie, when are comfortable posting what's currently in `lang/python` to PyPI? It'd be awesome if iReceptor could export the AIRR TSVs, and it'd be nice to have a docs page pointing to tools that use the format, but I wasn't thinking we'll need that for an initial release.

**Comment by schristley** [comment]
> do you want to add any of the commandline tools to the initial release?

Yeah, would be nice but not critical.

**Comment by javh** [comment]
Done in #110 for the python package:

1. A NEWS.rst file linked to the docs.
2. Code cleanup. 
3. Finished commandline tools.
4. All API and commandline docs.

Leaving only:

1. Decide if we want to future-proof the names in `interface.py`. Eg, `airr.read` to `airr.read_rearrangement`.
2. Flesh out the README.

**Comment by javh** [comment]
Last two things (readme and name future-proofing) are done in #118.
