### ISSUE TITLE
Genotype documented_allele VS delete_gene

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#554]
I notice that

- `documented_alleles` used to have `gene_symbol` and now it has `label`. 
- `undocumented_genes` has `gene_symbol`

@williamdlees it looks like you made the change in `documented_alleles`, should this be consistent with `undocumented_genes`

https://github.com/airr-community/airr-standards/blame/8e07bd75736c3c32e926f08b6042709940794ded/specs/airr-schema.yaml#L975

**Comment by williamdlees** [comment]
Yes it should be label in both cases. Do I fix this in the germline branch and make a pull request, or does it need a new branch?

**Comment by schristley** [comment]
> Yes it should be label in both cases. Do I fix this in the germline branch and make a pull request, or does it need a new branch?

@williamdlees It's best to create a new branch from master with a new PR; that usually makes it easier to review and merge. You can probably use the germline branch but you need to make sure that you bring it up to date with master, but then you still need to create a PR so it can be merged. I forget if github re-opens the old PR or makes a new one.
