### ISSUE TITLE
how to know if a repository supports an ADC extension?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#555]
I was thinking we could add an `extensions` array into the info object, which might be an easy way to programmatically determine if a repository supports an ADC extension. While we only have one extension now with the async API, CRWG has been considering adding the stats API, and we might have more in the future. It could be a simple keyword array like this:

```
extensions:
  - asynchronous
  - statistics
```

**Comment by bcorrie** [comment]
Moving this to ADC API v2.0

**Comment by bcorrie** [comment]
@schristley do you want to add this? It seems trivial.
