### ISSUE TITLE
How will versioning work for AlleleDescription?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#559]
The AlleleDescription schema supports a `release_version` which is important as curation/updating of germline genes will be an ongoing process for many species. However, some open questions remain regarding how to manage that provenance, and what that implies for AIRR objects that may reference or use the germline genes. Here are some questions that should be resolved and documented:

- [x] Can a germline set contain allele descriptions for multiple versions of an allele?
- [x] What should be recorded in rearrangements fields `v_call`, `d_call`, `j_call`? I believe the answer is `gene_symbol` except in the case when it is empty (hasn't been assigned yet), and then `coding_sequence_identifier` should be used.
- [x] Who is allowed/what is the process to increment the version number? If two researchers working independently, update the allele description, increment the version then publish a germline set, how to detect/handle the conflicting versions?

Depending upon the answers, we might add validation rules to enforce our decisions.

**Comment by williamdlees** [comment]
The germline set should contain one `AlleleDescription `for each allele. Mention in the description

The rearrangement calls should reflect the `label `field in the AlleleDescriontion

The version number is updated under the control of the repository hosting the germline set. reflect discussion into airr standards coc: if someone copies a germline set they should put their own number on it, if they change it

Add validation code - >1 definiton of an allele in R and Python libraries

**Comment by williamdlees** [comment]
(closed in error)

**Comment by williamdlees** [comment]
Closed now the documentation is updated.
