### ISSUE TITLE
Some MiAIRR data elements are "write-only" in BioProject

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#57]
This issue was brought up by Christian on the mailing list...

While finishing up on the MiAIRR-to-BioProject mapping, I came across 
the issue that I was unable to retrieve information on the submitter 
and corresponding person. So I asked NCBI: 

>> I am trying to use your eutils interface to retrieve BioProject 
>> information about various related sequencing studies. 
>> However, I have noticed that when I fetch a record (like this 
>> one from the Kleinstein lab) 
>> 
>> https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=bioproject&id=PRJNA209947 
>> 
>> the submitter and contact information is missing. This is also 
>> true in the"bioproject.xml"export file on your FTP site. Am I 
>> doing something wrong or can this information simply not be 
>> retrieved from the database (the Submission.xsd does specify 
>> these fields as mandatory, so they should be there)? 

To which they replied: 

> You are not doing anything wrong as this information can not be 
> retrieved from the database. The submitter info and contact info 
> are only used during the submission process and removed from 
> the XML once public. Only the Submitter Organization info is 
> available - which is seen in the example (PRJNA209947) you provided. 

Which means that in our current NCBI implementation these fields 
are "write-only", which I assume was not our intention.

**Comment by BusseChristian** [comment]
I am in contact with NCBI about this. This seems to be a privacy protection / anti-spam "feature". Will try to find out whether a submitter can turn it off.

**Comment by schristley** [comment]
Yep, that makes sense, otherwise a bot will slurp up all the emails. We should keep this in mind for any "public" interfaces we provide.

An alternative is to move to id's, I guess [ORCID](url) is becoming popular.

**Comment by BusseChristian** [comment]
The BioProject help desk has responded back to me:

> The individual submitter information is not shown in *any* public display option for BioProject.

However, they pointed me towards BioSample, which does contain the submitter - but not the corresponding author - information. I did not find a complete XML scheme for BioSample, but the
following keys/attributes have been used in the past:

```
BioSample/Owner/Name
BioSample/Owner/Name/abbreviation
BioSample/Owner/Contacts/Contact/Name/First
BioSample/Owner/Contacts/Contact/Name/Middle
BioSample/Owner/Contacts/Contact/Name/Last
BioSample/Owner/Contacts/Contact/Address/Street
BioSample/Owner/Contacts/Contact/email
BioSample/Owner/Contacts/Contact/fax
BioSample/Owner/Contacts/Contact/phone
BioSample/Owner/Contacts/Contact/lab
```
So at least we could change the mapping of the submitter field to these ones.

**Comment by schristley** [comment]
The AIRR data model has the necessary MiAIRR information, we cannot control if any specific data repository throws away or restricts access to it.
