### ISSUE TITLE
make 1.3.2 release

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#570]
Attempting to use the openapi V3 version of the ADC API was pulling in the 1.4 AIRR schema, thus breaking backward compatibility. The plan was that openapi V3 would be available with 1.4 but 1.4 has taken longer to release, so I've backported the openapi V3 specs to the 1.3 schema and put them on the `release-1.3` branch. Should tag a 1.3.2 release.

**Comment by scharch** [comment]
closed as stale
