### ISSUE TITLE
Define J gene donor splice site

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#571]
`AlleleDescription.j_donor_splice` aims to define the donor splice site 3' of a J gene. However, as the actual splicing occurs between two nucleotides, it needs to be defined whether the referenced position is the last exonic or first intronix nucleotide.

**Comment by williamdlees** [comment]
Changed the description to: Co-ordinate (in the sequence field) of the final 3' nucleotide of the J-REGION (J-genes only)
