### ISSUE TITLE
Make ADC V1.2 release

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#579]
We need to decide what we want to put in the ADC V1.2 release. This issue is to keep track of all of the decisions we make as we need to decide what AIRR Schema version and what entry points to support. These decisions might imply additional tasks to be performed with the release.

- [x] AIRR Schema V1.4
- [x] What entry points to support?
- [x] Any new operators/parameters that will be supported?
- [x] Documentation for any new functionality.
- [x] Schema change management

**Comment by schristley** [comment]
> AIRR Schema V1.4 or V1.3?

This is important because it implies additional tasks we need to consider. With V1.4, we can include new entry points for the new draft AIRR objects, but this also implies that we have significant schema changes that will affect queries. The queries for V1.3 schema will not necessarily work against V1.4 schema. Will clients be required to support both V1.3 and V1.4 schemas? In theory, this is possible, because the info endpoint indicates the schema version, and the client could adjust queries appropriately.

If we stick with V1.3, this simplifies many things, and we can release the ADC API V1.1 before waiting for the V1.4 schema to be finished, but it also means we cannot take advantage of the new stuff in V1.4.

**Comment by schristley** [comment]
A newer VDJServer ADC API service is based upon the OpenAPI V3 spec, and also has the async API. In order to do this properly, I needed to backport the changes to the ADC API V1 and V1.3 schema, so #570 is to make a V1.3.2 release with those changes.

**Comment by schristley** [comment]
Actually, looking back at the tags, we sorta already made a V1.1 release with Schema V1.3.1, as the clone object and entry point was added, though documentation was never added. So I guess this should be V1.2 or stick with V1.1?

**Comment by bcorrie** [comment]
I would go with v1.2. And it should probably be linked to v1.4 of the schema since we have API v1.1 -> Spec v1.3.1?

**Comment by schristley** [comment]
> I would go with v1.2. And it should probably be linked to v1.4 of the schema since we have API v1.1 -> Spec v1.3.1?

That seems reasonable. I'm thinking the openapiv3 and async API will be V1.1.1 then.

What do you think about using ADC specific tags for the repository (e.g. adc-v1.0.0, adc-v1.1.0, etc)? These are primarily convenience, but it does let us (and users) track changes a bit easier versus having to remember the associated schema version.

**Comment by schristley** [comment]
I've made a separate issue #583  for V1.1 release and changed this to be V1.2

**Comment by bcorrie** [comment]
@schristley WRT new operators/parameters - I don't believe we have any other than what is in the spec - new fields from v1.4 of course, but nothing other than that?

Unless perhaps you are talking about the adc_ fields?

**Comment by bussec** [comment]
@bcorrie Hoping that we can merge #404 rather soon, so including a `/receptor` endpoint would be good.

**Comment by bcorrie** [comment]
@bussec I thought `Receptor` was a v2.0 release (not v1.4). The ADC v1.2 API is in sync with the v1.4 release, with endpoints for the objects in the v1.4 release. 

So based on that, we would not have a /receptor endpoint in ADC v1.2 API.

**Comment by schristley** [comment]
> WRT new operators/parameters - I don't believe we have any other than what is in the spec - new fields from v1.4 of course, but nothing other than that?

No new operators/parameters that I'm aware of.

**Comment by bcorrie** [comment]
In discussions with @bussec (see #404) I think we can add the /receptor endpoint, assuming it is merged in to the v1.4 AIRR Spec.

**Comment by bcorrie** [comment]
> > WRT new operators/parameters - I don't believe we have any other than what is in the spec - new fields from v1.4 of course, but nothing other than that?
> 
> No new operators/parameters that I'm aware of.

Checked off Task 3 above.

**Comment by bcorrie** [comment]
@schristley any objection to marking this issue as closed - as Task 5 above is subsumed by #607 - and this can't be completed until we have a v1.4 version of the Spec tagged. But we don't need both open...

**Comment by bcorrie** [comment]
Closing - need to resolve #612 once we have a v1.4 tag, but the tasks here are done
