### ISSUE TITLE
Update docs for keywords_study

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#580]
Need to reflect the changes and in particular how _schema_ objects are data related while other keywords are study design related.

**Comment by scharch** [comment]
@bcorrie has this been done? Can you describe in more detail what you're looking for?

**Comment by bcorrie** [comment]
This has been done... 

https://github.com/airr-community/airr-standards/commit/dcb91b3c46f2e8040c7efd7038dcee554c247b5a
