### ISSUE TITLE
Python language support - Treatment of json objects in Python 2

### ISSUE THREAD

**Issue by williamdlees** [airr-community/airr-standards#584]
In python 2, the json parser reads strings into Unicode objects. On the other hand, the validator expects strings to be str. This means that under python 2, validation of any objects against the schema will fail in the current library. Not an issue with Python 3 as strings are all Unicode.

Possible solutions:
- make the validator accept Unicode where the schema specifies string. Not ideal, because the yaml parser returns strings, so objects will be different, depending on whether they are read from json or yaml.
- Under Python 2, run through an object read from json, converting any Unicode attributes to str
- stop supporting Python 2, on the grounds that formal support for Python 2 ended over a year ago.

**Comment by schristley** [comment]
We'd previously decided #496 that python 2 support would be dropped with AIRR V2. However, V1.4 has been taking much longer to solidify and release, so we might consider dropping with V1.4.

**Comment by scharch** [comment]
@javh if we aren't already dropping python2 with 1.5, maybe we should?

**Comment by javh** [comment]
Yes, dropping python 2 for v1.5 makes sense to me.

**Comment by javh** [comment]
Should remove python 2 support code from the python library.
Update setup.py, if necessary to remove python 2 support

**Comment by javh** [comment]
setup.py is already set to python>=3. There's some future imports still in the code, but if they aren't breaking anything, then I think it's fine to leave them for now.
