### ISSUE TITLE
collection_time_point_relative and units

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#587]
From a group that is trying to curate a data set - a question about `collection_time_point_relative`

Related to but not the same as #504 

This group has a time series (subject sampled at multiple times), but doesn't actually have a duration between visits. So it isn't "day 1", "day 30", and "day 60", it is "visit 1", "visit 2", and "visit 3". The need is to group samples that are taken at specific "visits" (e.g. on "visit 2").

I think we want something like this:
```
collection_time_point_reference = 'subject enrollment'
collection_time_point_relative = 2
collection_time_point_relative_unit = 'visit'
collection_time_point_relative_unit_id = 'UO:????????' - an ontology ID that represents relative time.
```
It seems like it might be a common use case to require an ordinal scale for this data.

It seems like one way to represent this is:
```
collection_time_point_reference = 'subject enrollment'
collection_time_point_relative = 2
```
with no units?

**Comment by bussec** [comment]
How about the "count unit" (`UO:0000189`): "A dimensionless unit which denotes a simple count of things."?

**Comment by scharch** [comment]
@bcorrie ok to close?
