### ISSUE TITLE
Agenda items for Dec. AIRR meeting

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#59]
We have a good chunk of Sunday on the [agenda](https://www.regonline.com/custImages/490000/494014/Draft2017AIRRAgendaDecember3-620170803.pdf) for the WGs to meet. I know many of us are on multiple WGs, which makes it hard to do it all concurrently. Apparently the whole Tools and Resource WG only gets a 1/2 hour to present.

We should plan ahead of time, ya know, set a good example for the other WGs who you know will scrap it together at the last minute, or is it, we are so on top of things that we can whip it up on the fly, I tend to forget ;-D

Do we want to meet as a group? What do we want to present?

**Comment by BusseChristian** [comment]
Best to my knowledge, this schedule is not finalized yet. As of 2017-11-07, Tools & Resource was supposed to have 45' overall presentation time, which would mean that Formats would get 10'+5' (as GLDB has a separate slot earlier in the afternoon).
