### ISSUE TITLE
Update tools authors on relevant v1.4 changes

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#604]
We should contact authors about major v1.4 changes that will impact them. All that occurs to me off the top of my head is:

- [ ] Let 10x know about the `duplicate_count` to `umi_count` switch for their data. (#586)

Need to review the changes for others. To be updated.

**Comment by scharch** [comment]
@williamdlees we should look at the list of certified tools and see who we want to ask for updates to maintain compliance...

**Comment by javh** [comment]
This is process, not documentation. And I dropped the ball on it. :(

Closing this as we are well beyond the relevant version.
