### ISSUE TITLE
Error in adc-api.yaml (operationId is not unique)

### ISSUE THREAD

**Issue by marcoamarooliveira** [airr-community/airr-standards#615]
In https://github.com/airr-community/airr-standards/blob/master/specs/adc-api.yaml.

Value of 'operationId' repeated in lines 1002 and 826 (value: queryCells). Value on line 1002 should be 'queryReceptors'. 

'operationId' values should be unique in the document.

**Comment by bcorrie** [comment]
Thanks @marcoamarooliveira, fixed...
