### ISSUE TITLE
Missing sample object structure in the adc-api.yaml

### ISSUE THREAD

**Issue by marcoamarooliveira** [airr-community/airr-standards#616]
In the repertoire/ endpoint the 'sample' object structure is not defined.
It only has : "sample": [ "string" ] .

https://raw.githubusercontent.com/airr-community/airr-standards/master/specs/adc-api.yaml

**Comment by bcorrie** [comment]
I believe this is an oddity in how the Swagger editor displays fields in the response. I believe the YAML is correct.

I am marking this as closed since we have released v1.2 (a long time ago).
