### ISSUE TITLE
Genbank structured comments

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#62]
Continuing from original airr-standards repo.  This is the original prompt (from @javh).

>We should also discuss whether we can/should design these fields with the intention of using them in GenBank structured comments. This is one of the things that came up when working through the AIRR minimal information GenBank submission process. It's something we can add to the submissions, if we want, but we need to have a clearly defined vocabulary to give NCBI so that they can parse it and tag the data as AIRR.

See some additional comments at the original issue: airr-community/airr-formats#51

**Comment by javh** [comment]
Stale.
