### ISSUE TITLE
Embedding AIRR annotations in scanpy/scverse objects

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#620]
Hi All, after the AIRR Meeting I found this rather interesting discussion going on in the scverse (scanpy/scirpy) world around single cell file formats (https://github.com/scverse/scirpy/issues/327). II thought I would link the two discussions in case anyone here is interested in contributing to the discussion. Now seems to be the time to try and get this correct with AIRR v1.4 and the Cell/Expression specs being released.

**Comment by javh** [comment]
Initial release of the scirpy structure is released. We can discuss further in those repos.
