### ISSUE TITLE
IGHD reading frame in AIRR format IgBlast output

### ISSUE THREAD

**Issue by chunleya** [airr-community/airr-standards#625]
Hello, I would like to use IgBlast with AIRR output as part of my VH sequence analysis pipeline but would really like to know the D reading frame, as is available from IMGT/HighV-QUEST. Can anyone help? Is this an IgBlast issue?

**Comment by javh** [comment]
Yes, `d_frame` is an optional field that IMGT/HighV-QUEST provides. It's up the IgBLAST developers whether they want to provide that information.

That said, you should be able to derive the field from either `d_cigar` or `d_germline_start` easily.
