### ISSUE TITLE
IGHD reading frame in AIRR format IgBlast output

### ISSUE THREAD

**Issue by chunleya** [airr-community/airr-standards#626]
Jason, thank you for your time addressing this issue. I don't want to clutter up this channel with these questions so will make this the last.

I don't see how you can extract the D-reading frame from the D_germline_start without knowledge of the 3' junction. Perhaps D_CIGAR would help although i don't recognise its annotation from IgBlast. I'm sure i can write an R script to work RFs out but not sure which info to use from the IgBlast output. It would be easier if all the J-germline sequences started in the same frame but they don't.

Any pointers from anyone would be much appreciated

Regards

Harry White, Babraham Institute, Cambridge, UK

**Comment by scharch** [comment]
`d_frame` was added as an optional field in v1.4.1
WRT IgBlast specifically, it appears to have been added in release 1.23.0
