### ISSUE TITLE
Merge cleanup

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#63]
Tracking some issues related to merging airr-formats in airr-standards.

- [x] Change subtitle from "MiAIRR: AIRR Community Minimal Standards WG" to something more inclusive, perhaps "AIRR Community Data Standards"
- [x] Change URL to point to docs.airr-community.org
- [x] Add docs for MiAIRR to the RTD docs
- [x] Merge the testing code into a single Travis job
- [x] Convert reference library to use airr-standards spec file
- [x] Switch to Sphinx documentation gen (with Markdown support) for more flexibility

**Comment by laserson** [comment]
- [ ] Merge the testing code into a single Travis job

**Comment by schristley** [comment]
- [ ] Convert reference library to use airr-standards spec file

**Comment by BusseChristian** [comment]
I will bring up the first point on the next MiniStd call. IMO it would be best if all documentation moves to Sphinx, so we would only leave a single README.md in the repo. Any opinions on this?

**Comment by javh** [comment]
Agreed. I think it makes sense to use only one markup language for all documentation. Github should render `.rst` files too, so we could convert the README to reStructuredText as well. Which makes it easy to do things like having top level README.rst, CONTRIBUTING.rst and NEWS.rst files which are embedded in the documentation via include directives. Eg, `.. include:: ../README.rst`.

pRESTO example:
https://bitbucket.org/kleinstein/presto/raw/tip/docs/install.rst

Renders the content as a single page:
http://immcantation.readthedocs.io/projects/presto/en/latest/install.html

**Comment by BusseChristian** [comment]
Ok, the MiniStd people are happy with the name change and with moving all remaining documentation elements from the two README.md to Sphinx.
I might do this sometime in April, if anyone wants this change to happen fast, please go ahead ;-)

**Comment by bussec** [comment]
Working on this in branch markdown-to-RST, should be a PR by tomorrow.

**Comment by javh** [comment]
Everything looks done.
