### ISSUE TITLE
Where did the Manifest object go???

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#634]
I thought this was just overlooked in the Release Notes, but it is also gone from the Spec??? When did this happen?

We use this when you do a download from the iReceptor Gateway.

**Comment by javh** [comment]
Are you sure it was ever in the spec?

#548

**Comment by bcorrie** [comment]
Damn, I thought it was... Oh well, we will use a future looking not yet in the spec Experimental Schema in our production Gateway I guess 8-)

**Comment by javh** [comment]
Okay. Skimming over #548 and having such messed with `DataFile`, I expect the final `Manifest` object will look different, so I'd suggest implementing around that expectation. We'll need to sort out the relationship/overlap between `DataFile`, `Manifest` and `RepertoireGroup/Set` at some point.

**Comment by scharch** [comment]
Looks like I missed this flash mob....

**Comment by javh** [comment]
lol. Sorry, seemed resolved.
