### ISSUE TITLE
exclude deprecated fields from template

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#636]
```
import airr
r = airr.schema.RepertoireSchema.template()
print(json.dumps(r, indent=2))

[snip]
    "age_event": null,
    "age": null,
    "ancestry_population": null,
[snip]
```

`age` is deprecated. This should be easy fix.

**Comment by javh** [comment]
I hit the wrong button and accidentally pushed this fix to master in 9f572ef instead of making a PR. Can you test in master, please?

**Comment by schristley** [comment]
looks good! Generating a template for DataFile is interesting, I like it

**Comment by javh** [comment]
Oh, I didn't think about trying it on `DataFile`. That works pretty well!
