### ISSUE TITLE
info in python's API reference doesn't look up to date

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#640]
I noticed the python library [API reference](https://docs.airr-community.org/en/latest/packages/airr-python/api.html) doc doesn't mention `read_airr` and friends.

**Comment by schristley** [comment]
Might also want to add the deprecation message within the description for the function so it shows in this doc, unless there's a special way to mark deprecated stuff...

**Comment by javh** [comment]
Both are now fixed in #633. 

(There is indeed a special way to mark [deprecation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated).)
