### ISSUE TITLE
How to represent range for collection_time_point_relative

### ISSUE THREAD

**Issue by kira-neller** [airr-community/airr-standards#646]
With v1.4 of the AIRR Standards, we now represent timepoint collection like so:
collection_time_point_relative (number)
collection_time_point_relative_unit (ontology)
collection_time_point_reference (string)

This works fine for something with a discrete collection timepoint, e.g. "2 days post-vaccination". 

We have a study that has a timepoint collection range for two groups (early and late COVID recovery). Early samples were taken _less than 7 days after the first negative COVID-19 test_, while late samples were taken _more than 14 days after the first negative COVID-19 test_. Currently, we're representing this like:
collection_time_point_relative = 7
collection_time_point_relative_unit = day
collection_time_point_reference = Less than N days after first negative COVID-19 test

Should we consider introducing a collection_time_point_relative_min and collection_time_point_relative_max to handle cases such as these?

Thanks!
Kira

**Comment by bussec** [comment]
My 2 cents: If you think that this would address a relevant fractions of studies that we could currently not accurately annotate, we should discuss adding these properties. However, we should ensure that we do not end up with 40+ `cellection_time_*` properties, if we are already aware that the appropriate step would be to adopt a more comprehensive annotation standard (I don't have anything in mind, but I am sure that people have tried to address the problem before).

**Comment by schristley** [comment]
Can take a general approach as suggested in #551 so any physical quantity field can either be a point value or an interval.

**Comment by bcorrie** [comment]
Yes, I think for v2.0 we should look to the #551 approach and have an "Interval" capability for numeric fields when we think that is appropriate.

**Comment by bcorrie** [comment]
Revisiting this. `collection_time_point_relative` is now a `TimePoint`. Should we make it a `TimeInterval`?

This does solve the problem if we use TimeInterval as an open interval. For one study arm it would be min = 0, max = 7 
and for the other min = 14, max = null?

For most cases we would have min = max indicating it was a single TimePoint.
