### ISSUE TITLE
Bug: Adding `subject.genotype' to a subject dict causes validation to fail unexpectedly.

### ISSUE THREAD

**Issue by jday1** [airr-community/airr-standards#652]
Steps to reproduce:

1) Add in a genotype to a subject entry. For example, in `lang/python/tests/data/good_combined_airr.json`  I added a simple entry

![image](https://user-images.githubusercontent.com/45389553/198016555-5c4d93d6-55bf-4c7c-aa6d-20775984f28f.png)

2) Run the python test `test_interface.TestInferface.test_read_airr()` 

3) Failure: `Repertoire at array position 0 with validation error: Internal error: field "subject.genotype" in schema not handled by validation. File a bug report.`

The schema suggests that I should be able to add a genotype in here:
![image](https://user-images.githubusercontent.com/45389553/198017283-2759c7b9-6b92-47b3-b485-116e36348cac.png)

If so this is a bug. However, I think this could potentially be left over from a previous release when GenotypeSet became it's own root-level array:

![image](https://user-images.githubusercontent.com/45389553/198017572-5a6a3ba0-e84f-481c-966b-30f45df90be7.png)

In this case, there is no place to add MHCGenotypeSet. This is solved by PR: https://github.com/airr-community/airr-standards/pull/651

**Comment by schristley** [comment]
The quick fix is to create a schema object for it:

```
diff --git a/lang/python/airr/specs/airr-schema.yaml b/lang/python/airr/specs/airr-schema.yaml
index 788d815..129a6c2 100644
--- a/lang/python/airr/specs/airr-schema.yaml
+++ b/lang/python/airr/specs/airr-schema.yaml
@@ -1326,6 +1326,21 @@ MHCGenotype:
                 nullable: true
                 adc-query-support: true
 
+SubjectGenotype:
+    discriminator:
+        propertyName: AIRR
+    type: object
+    properties:
+        receptor_genotype_set:
+            nullable: true
+            $ref: '#/GenotypeSet'
+            description: Immune receptor genotype set for this subject.
+        mhc_genotype_set:
+            nullable: true
+            $ref: '#/MHCGenotypeSet'
+            description: MHC genotype set for this subject.
+
+
 #
 # Repertoire metadata schema
 #
@@ -1801,15 +1816,10 @@ Subject:
                 nullable: false
                 adc-query-support: true
         genotype:
-            type: object
+            $ref: '#/SubjectGenotype'
             description: Genotype for this subject, if known
-            properties:
-                receptor_genotype_set:
-                    $ref: '#/GenotypeSet'
-                    description: Immune receptor genotype set for this subject.
-                mhc_genotype_set:
-                    $ref: '#/MHCGenotypeSet'
-                    description: MHC genotype set for this subject.
+            x-airr:
+                nullable: true
```

Though with that, a blank template repertoire stills fails validation because now it will complain about the identifiers which are not defined correctly #656 

```
Repertoire at array position 1 with validation error: Non-nullable field "subject.genotype.receptor_genotype_set.receptor_genotype_set_id" is null or missing
```

**Comment by javh** [comment]
Thanks for the report and sorry for the delay. We'll review soon so we can get out a patch.

**Comment by javh** [comment]
Finally getting to this... I see a couple other things going on here:

**1.** The various MHC schemas didn't make it into the DataFile schema, validation routine cached schema, and unit tests for v1.4.1. Mostly because they were very new, but I think we can add them now.

**2.** `Subject.genotype` seems overly nested to me. Any reason we can't have `Subject.receptor_genotype` and `Subject.mhc_genotype` properties instead? Ie:

```
Subject:
    receptor_genotype:
        $ref: '#/GenotypeSet'
    mhc_genotype:
        $ref: '#/MHCGenotypeSet'
```

**Comment by javh** [comment]
From the call:
+ Would SubjectGenotype be something that should be queryable? If so, it would need an `_id`. If not, then it's an unnecessary object for what is only two properties.

**Comment by schristley** [comment]
It may be incorrect to have `GenotypeSet` in `DataFile`, i.e. defined as a top-level object. Are we expecting a GenotypeSet and a MHCGenotypeSet to be essentially unique to the subject? So they won't really be shared except for repertoires with the same subject? If yes, then they should live within `Subject` like they do now, denormalized inside `Repertoire` essentially. If not, then these fields should be switched to ids and objects are stored at top-level `DataFile`.

**Comment by schristley** [comment]
> From the call:
> 
> * Would SubjectGenotype be something that should be queryable? If so, it would need an `_id`. If not, then it's an unnecessary object for what is only two properties.

That's a good point, and you can even apply it to the next level down with `GenotypeSet`, it has an `_id` but is it queryable as you're defining it? It looks like a wrapper around a list. Those could be moved all the way up to `Subject`

```
Subject:
  properties:
    receptor_genotype:
            type: array
            items:
                $ref: '#/Genotype'
    mhc_genotype:
            type: array
            items:
                $ref: '#/MHCGenotype'
```
