### ISSUE TITLE
AIRR output format in igblast 1.19.0 is not consistent

### ISSUE THREAD

**Issue by aerijman** [airr-community/airr-standards#653]
I hope someone can help here!

run igblast with `outfmt 19`, for AIRR-format table. The number of fields is not the same for all hits... Igblast might not be writing the field if it didn't find it. However, the number of fields should be the same as in the header for ALL queries.

Thank you for your help!

**Comment by bussec** [comment]
@aerijman this seems to be an issue of the implementation by IgBLAST, not of the AIRR format specification. Please direct this issue to the IgBLAST developers.
