### ISSUE TITLE
what category for extension fields?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#655]
ADC API v1.2 introduced extension fields which are in the API schema but not in the core AIRR schema. For the API endpoints, the `include_fields` parameter defines three categories (sets) of fields. Are the extension fields included in any of these categories, or in a new category?

**Comment by bcorrie** [comment]
@schristley in reading our docs, we have:

"By default all fields (AIRR and non-AIRR) stored in the data repository are returned." So in this case, you would get the extension fields.

I suppose I would group these extension fields in the "airr-schema" category. It doesn't make sense to me to have a separate "include_fields" category for these?

I would suggest we change the Docs in the table here:

https://docs.airr-community.org/en/stable/api/adc_api.html#components-of-a-request

to have the right most column read "Other AIRR and ADC Extension fields"

The alternative is to add another includes category of "adc-extension"

**Comment by schristley** [comment]
Hmm, I guess I can see arguments for either side. Having a separate category seems more "precise" but I also feel like the general use case is that those fields will be almost always be wanted. If that's true, it is simpler to put them in the "airr-schema" category and not complicate things with a new one. So my vote is for simpler and change the column text in the docs as you suggest.

Regardless, at least for VDJServer, support for that won't be immediate. That's because my code is going through the AIRR spec to pick the fields, and to support the extension fields, I need to add code to walk through the API spec.

**Comment by bcorrie** [comment]
I have added this on #628 closing this issue.
