### ISSUE TITLE
contains_single_cell is no longer a study keyword?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#660]
I didn't see this mentioned in the release notes. Was it removed because it's redundant with something else, or was it replaced by a different keyword?

**Comment by javh** [comment]
Replaced by `contains_schema_cell`. Need to update patch notes.

**Comment by schristley** [comment]
Ok, so there are two concepts here, one is what the experimental protocol was attempting, that is the `single_cell` flag in the sample processing. When `contains_single_cell` was removed, I was thinking it was ok, it's redundant because you can just iterate over the repertoires and test the `single_cell` flag.

But the second is if the study contains AIRR `Cell` objects, is that the intent of `contains_schema_cell`? Will it be invalid to have a repertoire with `single_cell: true` but no `Cell` objects?

**Comment by scharch** [comment]
> Will it be invalid to have a repertoire with `single_cell: true` but no `Cell` objects?

I think it should at least be strongly discouraged, but I guess making it invalid might go against our general strategy of allowing people to be jerks if they so insist...

**Comment by schristley** [comment]
> > Will it be invalid to have a repertoire with `single_cell: true` but no `Cell` objects?
> 
> I think it should at least be strongly discouraged, but I guess making it invalid might go against our general strategy of allowing people to be jerks if they so insist...

I'm fine with it being invalid, though this is a form a validation that we aren't performing yet, i.e. cross-object validation. Users probably won't check the `single_cell: true` flag anyways then, they'll just look for `contains_schema_cell` flag to see if there is single cell data.

**Comment by javh** [comment]
Looks like the changes to Study.keywords_study are already in the v1.4.1 Study Schema patch notes. Are we okay to close this?
