### ISSUE TITLE
Ontology fields use "value" rather than "label"

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#662]
See here: https://docs.airr-community.org/en/stable/miairr/data_elements.html
for at least `collection_time_point_relative_unit` but I think this is all fields.

This:
"Ontology: { top_node: { id: NCIT:C63536, value: Study}}"
should read
"Ontology: { top_node: { id: NCIT:C63536, label: Study}}"

**Comment by javh** [comment]
Bug. Find and fix.
