### ISSUE TITLE
Remove functional NULL values from `subject`.`sex`

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#670]
`subject`.`sex` is the only property that still defines the terms `not collected` and `not applicable` in its enum list. This seems to be a leftover from the days when this field was still considered to be what is now "essential". As it is now only considered to be "important" and is `nullable: true`, the use for the two enum terms above is rather limited. Should we remove them?

**Comment by javh** [comment]
`not applicable` seems potentially informative. `not collected` seems redundant with `null`.

**Comment by javh** [comment]
From the call:
+ Remove both `not collected` and `not applicable`.

**Comment by javh** [comment]
From the call:
* Seems v1.5 as it changes enum values.
