### ISSUE TITLE
Consistent list of possible Ig/TCR loci throughout the schema

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#671]
Field that encode Ig/TCR loci are implemented as controlled vocabularies (i.e., `enum`) throughout the schema. However, the list of available values differs between `Rearrangement`.`locus`, `PCRTarget`.`pcr_target_locus`, `AlleleDescription`.`locus` and `GermlineSet`.`locus`, as the former two contain `IGI` as additional option (which is an additional Ig light chain locus in bony fish).
Whether by addition or removal, the enum lists should be consistent throughout the schema.

**Comment by javh** [comment]
Addressed in #674.
