### ISSUE TITLE
x-airr tags need to be added to germline objects

### ISSUE THREAD

**Issue by williamdlees** [airr-community/airr-standards#675]
see comment from @javh below.

---
Because this will initially be an experimental release we might be able to push back sorting out the proper x-airr tags. But, to answer your question, if you look at Rearrangement:sequence_id you will see:

sequence_id:
  x-airr:
    adc-query-support: true
    identifier: true

Denoting whether the field is required and what its purpose is in the AIRR Data Model and ADC contexts. We'll need to sort that our for the various _id fields at some point. Maybe _ref too, but I don't know how they'll fit in.

**Comment by bcorrie** [comment]
@williamdlees has this been done? I haven't checked, feels like this might have been addressed already and can be closed?

**Comment by javh** [comment]
This was done. I'm sure we'll need to give everything a pass over for v2.0, but we can close this.
