### ISSUE TITLE
Include co-ordinates of CDRs explicitly

### ISSUE THREAD

**Issue by williamdlees** [airr-community/airr-standards#676]

**Comment by williamdlees** [comment]
This removes reliance on the IMGT alignment to place them. Change "IMGT alignment" to "sequence alignment" and make it clear that this alignment places the CDR3s at specific locations in the aligned sequence (There are cases where this does not happen in IMGT's alignment, e.g. inserted codons in macaque IG sets).

**Comment by javh** [comment]
This looks done. @williamdlees ?

**Comment by williamdlees** [comment]
It's done.
