### ISSUE TITLE
Add ability to test `mhc_genotype_set` and `receptor_genotype_set`.

### ISSUE THREAD

**Issue by jday1** [airr-community/airr-standards#684]
Currently, the fields `mhc_genotype_set` and `receptor_genotype_set` are nested such that they cannot be tested because they exist in an object.

I have introduced `GenotypeSets` which allows this functionality and added a test.

I am aware of issue https://github.com/airr-community/airr-standards/issues/667. From what I understand, this issue will not resolved in the immediate future, so under the current schema this functionality should be added.  This will also make it easier to test the change outlined in the aforementioned issue.

I have introduced this change in PR https://github.com/airr-community/airr-standards/pull/685.

In addition, there are two further minor changes.
- Making the yaml indentation consistent: There are several cases where there is an indentation of 2 is used instead of 4. This lack of consistency can cause some validation to fail. For example, in the case of the MHC enum on line 1273. A long term solution is to enforce yamls are written consistently in the github action checks to prevent this.
- Small formatting changes for readability/consistency which were done by my IDE. These are non-functional and I have highlighted these with an 'Ignore' comment.

**Comment by scharch** [comment]
closed via #695
