### ISSUE TITLE
`discriminator` keyword is being used improperly in the schema

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#686]
I discovered this when using a JSON validator. We have a `discriminator` keyword on all of our objects, however its usage is not correct. It's meant to be used with `oneOf` where the `propertyName` in the `discriminator` indicates what property can be used to distinguish the appropriate object in the `oneOf` union.

Because we aren't using `oneOf` anywhere, we should essentially delete all of the discriminators.

**Comment by schristley** [comment]
@javh This is an easy fix, I can add to #674 if you agree.

**Comment by javh** [comment]
@schristley, works for me to add it to #674.
