### ISSUE TITLE
Why are dependencies not getting installed on when on readthedocs?

### ISSUE THREAD

**Issue by grst** [airr-community/airr-standards#692]
Hi, 

what's the reason for this check to exist? 
https://github.com/airr-community/airr-standards/blob/2520bbd28d0a9696a24efe7a05a91d73482546e2/lang/python/setup.py#L17-L19

The issue I have with that is that it does not only affect the airr package itself on readthedocs, but also all packages that depend on it (in my case [scirpy](https://scirpy.readthedocs.io/en/latest/)). I wasted an entire evening figuring out why my documentation builds in a clean environment locally, but not on readthedocs -- it turned out that, well, dependencies were missing. 

Cheers, 
Gregor

**Comment by javh** [comment]
It's a workaround for ReadTheDocs not allowing installation of packages requiring C compilation in virtual environments. Ie, bypassing attempts to install dependencies like numpy that would cause the build to fail.

That reason it exists anyway... I suspect this is no longer necessary as binaries should be available on pypi for all this stuff now.  It has been many years.  Let me test.
