### ISSUE TITLE
Provenance of samples

### ISSUE THREAD

**Issue by ahmadchan** [airr-community/airr-standards#7]
Problem:

To indicate the provenance of samples, MiAIRR currently only defines a single
data item "commercial source". It is therefore unclear how to describe the
source of samples from other sources. BioSample has a mandatory
"biomaterial_provider" field, but according to NCBI's documentation
[https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/] this is distinct
from the "biospecimen_repository", which indicates registered commercial
providers (controlled vocabulary). We have introduced "source_commercial" as
an AIRR-specific field in the BioSample submission template, which is likely
redundant with "biospecimen_repository".

Proposed solutions are either:

1) *Replace* "commercial source" in MiAIRR with "biomaterial provider" as the
sole and mandatory field to indicate sample provenance (free text format). All
providers will be entered into this field, irrespective of their status.
*Remove* "commercial source" in all downstream documents in which it would be
redundant with "biomaterial provider" and/or "biospecimen_repository".

or

2) *Rename* "commercial source" to "biospecimen repository" and fix downstream
mappings accordingly. This field is optional (applies only to commercially
obtained samples) and contains text from a controlled vocabulary (see above).
*Add* "biomaterial provider" as an new mandatory item to MiAIRR (free text
format).

Dependencies:
mapping table, *figures*

**Comment by BusseChristian** [comment]
Fix in line with solution 1.
