### ISSUE TITLE
CellReactivity object is missing from the Docs

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#732]
In the current version of the Docs, the page for the [`Receptor` object](https://docs.airr-community.org/en/stable/datarep/receptor.html) mentions the `ReceptorReactivity` object, but there is no documentation for that object.

**Comment by bcorrie** [comment]
I think this should be AIRR 2.0 not ADC 2.0???

**Comment by bussec** [comment]
@bcorrie Yes, sorry.

**Comment by bcorrie** [comment]
This is now CellReactivity, updated the title
