### ISSUE TITLE
Change CellExpression proprty_type to enum?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#733]
In #699 we added the property_type field to CellExpression as a string with documented preferred values.

We noted that we probably should change this to an enum.

**Comment by bcorrie** [comment]
Currently we have this:
```
               Keyword describing the property type and detection method used to measure the property value.
                The following keywords are recommended, but custom property types are also valid:
                "mrna_expression_by_read_count",
                "protein_expression_by_fluorescence_intensity", "antigen_bait_binding_by_fluorescence_intensity",
                "protein_expression_by_dna_barcode_count" and "antigen_bait_binding_by_dna_barcode_count".
```

**Comment by bcorrie** [comment]
Can we come up with a set of enum values for this? Outside of my area of expertise... 8-)

**Comment by bcorrie** [comment]
@bussec @javh any objections to leaving this as a string with "suggested values". If no objections I will close this issue.

**Comment by bussec** [comment]
@schristley I would also prefer to have an ontology, but then we would have to split the field again, as I doubt that there is an ontology that would capture both components of our keywords (i.e., what was measured and how it was measured) and we decided a while ago, that having two components is potentially confusing to curators.

**Comment by bussec** [comment]
For the call: Leave the field as it is, i.e. free text with suggested keywords. This is clearly not perfect, but better than having a solution that is more formalized but less flexible.
