### ISSUE TITLE
Do we want to use the wiki on GitHub?

### ISSUE THREAD

**Issue by schristley** [airr-community/airr-standards#74]
It currently is enabled and has some info that Ahmad wrote, but I think we've decided to centralize at docs.airr-community.org?

**Comment by javh** [comment]
We could transition to using the wiki for project management and development guides. 

Code style details, how to build/update the docs, release process, roadmap, etc. Though.  most of that we can probably use issues or `CONTRIBUTING.md` for.

**Comment by laserson** [comment]
I'd vote against the wiki, since it *another* place to look.  I'd vote for putting anything someone would want to read into the Sphinx docs published at docs.airr-community.org.

**Comment by BusseChristian** [comment]
I do not see a good reason to use the wiki if the information can also be in the default place for documentation.

**Comment by schristley** [comment]
Ahmad has backup of all the data. Wiki is now off.
