### ISSUE TITLE
Make Study.pub_ids an array of strings

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#740]
Currently `Study`.`pub_ids` is a single string and it is unclear how multiple references would be separated (probably by comma, but is this documented). It seems appropriate to change this into an array of strings.

**Comment by bcorrie** [comment]
Agree, and I also think we should make this an array of CURIEs - or CURIE like objects (e.g. DOI:10.1016/j.retram.2024.103439, PMID:29944754)

This is already how we curate our data, and on the iReceptor Gateway if it sees a CURIE like object it interprets the object like a CURIE with a set of internally defined CURIE prefix mappings. So it translates both DOI: and PMID: to the relevant web sites so one can directly look up the paper.

I would also suggest that the docs suggest that if there is a primary publication for the study, it should be first in the array. Adding a bit of semantics to the Array to get predictable behaviour is useful.
