### ISSUE TITLE
Review docs for queries against array objects

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#751]
This needs to be done for the v2.0 release.

Fixing the query functionality will be a v2.1 release task as per #623

**Comment by bcorrie** [comment]
I have updated the docs. There were formally two sections that discussed this issue. I combined them and moved them to the end of the section, where other issues and caveats are listed.

@bussec do you want to look one more time? 8-) Otherwise I will close the issue.

**Comment by bussec** [comment]
Ok, looks good. Thanks!
