### ISSUE TITLE
Change of license (again)

### ISSUE THREAD

**Issue by BusseChristian** [airr-community/airr-standards#76]
When we switched from Apache 2.0 to CC-BY-4.0 in September, the assumption was that this repository would primarily hold documentation and table but only minor amounts of code. Given the changes since then, do people think that we should switch back to a more classical software license? If yes, is everyone ok with Apache 2.0?

On a related note, should we include a CLA (contributor license agreement) in the CONTRIBUTING.md?

**Comment by schristley** [comment]
I'm fine with Apache 2.0. I'm not sure what you mean by CLA, is that something beyond just the license? We should also keep a list of authors as everyone maintains their copyright.

**Comment by BusseChristian** [comment]
Yes, it is basically about granting the AIRR Community more permissive rights, including to change the license at a later point. The Apache CLA can be found [here](https://www.apache.org/licenses/#clas).

I already have a list of contributors for everything concerning MiAIRR, but it is still on my ToDo list to make a copyright note out of it...

**Comment by javh** [comment]
So we use CC-BY-SA 4.0 (international) for our tools and CRAN considers it a valid FOSS license:
https://www.r-project.org/Licenses/

However, Creative Commons recommends against their licenses for software:
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

But:

> Version 4.0 of CC's Attribution-ShareAlike (BY-SA) license is one-way compatible with the GNU General Public License version 3.0 (GPLv3). This compatibility mechanism is designed for situations in which content is integrated into software code in a way that makes it difficult or impossible to distinguish the two.

FSF's thoughts on CC licenses: 
https://www.fsf.org/blogs/licensing/cc-by-4-0-and-cc-by-sa-4-0-added-to-our-list-of-free-licenses

Given that we have a mix of software and other content, my inclination would be to stick with CC-BY-4.0. I get the impression the problematic part for CC software license compatibility is really the ShareAlike (copy left) part, because CC0 is perfectly valid for software.

**Comment by schristley** [comment]
> granting the AIRR Community more permissive rights

That opens a can of worms, on both ends, as the AIRR Community is not a legal entity, and on the other side contributors don't necessarily have the legal authority to sign. I suppose we will have to deal with this at some point, but I'm content to leave it unspecified for now.

I'm also fine with leaving the license as CC-BY-SA 4.0

**Comment by laserson** [comment]
If I understand correctly, CC-BY-SA 4.0 is only compatible with a GPL license, which is highly restrictive. I'd vote to use Apache 2 license or equivalent.

**Comment by javh** [comment]
CC-BY 4.0 doesn't have the copy left (ShareAlike) requirement, whereas CC-BY-SA 4.0 does (like the GPL).

**Comment by laserson** [comment]
Ah, didn't read them closely enough.  On a separate note, the LICENSE file currently in there might be corrupted, since it has `<<<<<<< HEAD` so there may have been a messed up merge that affected it.

**Comment by javh** [comment]
Yeah, CC license are module, so you pick the elements you want: Attribution (BY), Share Alike (SA), No Derivatives (ND), non-commerical (NC). 

CC-BY is:

> This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials.

**Comment by BusseChristian** [comment]
Ok, thanks everyone for the input. To sum it up: Everyone is happy to leave the license at CC-BY 4.0 and right now there doesn't seem to be any advantage of switching to Apache 2.0. Therefore I'll close this issue for now.
