### ISSUE TITLE
Add consistency checks to make sure unit test data are identical between R and python

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#775]
The unit test data sets seems to have gotten out of sync:

* Copy-paste to fix this.
* Should we add consistency checks to GitHub Actions to avoid this in the future?

**Comment by schristley** [comment]
> * Should we add consistency checks to GitHub Actions to avoid this in the future?

PR #767 has those consistency checks.

**Comment by javh** [comment]
Ahhh... Thanks, @schristley. If we swap the `NA` for an empty string then that should work.

**Comment by javh** [comment]
I think this was resolved. @schristley ?

**Comment by schristley** [comment]
@javh still to be resolved in PR #767

**Comment by schristley** [comment]
PR #767 has been merged
