### ISSUE TITLE
Refactor/reenable formats consistency checks

### ISSUE THREAD

**Issue by laserson** [airr-community/airr-standards#79]

**Comment by javh** [comment]
Also, should we move all the associated files/scripts (TSV, .sh, etc) into `/tests`?

**Comment by javh** [comment]
In the call we discussed maybe delete the AIRR_Minimal_Standard_Data_Elements.tsv file entirely and replacing it with appropriate auto-generated tables in the docs.

**Comment by javh** [comment]
R package consistency checks added in #103.

**Comment by schristley** [comment]
I'd leave AIRR_Minimal_Standard_Data_Elements.tsv in for now, but mark it deprecated. I use that table all the time as a reference. Marked as deprecated, we can remove it for the next release. Yes, definitely auto-generate tables in the docs.

**Comment by javh** [comment]
Unit tests added to the travis job for both the python and R packages in #112. And I split the consistency checks into a separate build matrix item.

Also see #29.

**Comment by javh** [comment]
This done. Remain related task in #29.
