### ISSUE TITLE
Docs for "latest" tag not building on docs.airr-community.org.

### ISSUE THREAD

**Issue by bcorrie** [airr-community/airr-standards#793]
The versioned tags seem to be working but latest is generating a 404 error.

Now sure how this works, maybe something for @javh

**Comment by javh** [comment]
This latest?

**Comment by bcorrie** [comment]
Weird, so can I now... I was getting a 404 error before.

**Comment by bcorrie** [comment]
@javh when I click on "latest" here:

<img width="233" alt="image" src="https://github.com/user-attachments/assets/e358bff9-5c80-4ebb-87da-214199915fff">

I get this:

<img width="1019" alt="image" src="https://github.com/user-attachments/assets/a12f5eec-2a3e-4f3c-9a9b-bf61956b55e7">

Last week this happened as well, but it started working later...

So it is intermittent or maybe something to do with my browser????

**Comment by bcorrie** [comment]
Ahh, I figured it out. It is the page that I am on when I switch that is the problem. The adc_api.html page does not exist on latest because we re-structured that documentation on the master branch.

Re-closing, sorry 8-)
