### ISSUE TITLE
Rearrangement::cell_index should not be mandatory

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#83]
A `cell_index`  is unique to studies with paired heavy:light chain data. It's not universal, so this field should be optional instead of required.

Also, it should be `type: string` instead of `type: integer`, as the index may be a number, a nucleotide barcode, a well identifier, etc.

**Comment by BusseChristian** [comment]
Agree.

**Comment by schristley** [comment]
Agree.

**Comment by javh** [comment]
Resolved in #89.
