### ISSUE TITLE
MiAIRR Zombie - CDR3 / junction amino acid sequence

### ISSUE THREAD

**Issue by ahmadchan** [airr-community/airr-standards#9]
Problem:
If I remember correctly, we have decided *against* including the amino acid
sequence of CDR3 / JUNCTION as part of the minimal standard at least twice (as
it is redundant to the DNA sequence). Nevertheless this field is still in the
current table.
Our current NCBI implementation has no mapping for this field, as there is no
clean way to annotate it in Genbank.

Proposed solution:
Drop "JUNCTION amino acid sequence" as part of MiAIRR, keep the "junction_aa"
key as field name of Formats WG (as non-minimal implementations might want to
provide this data).

Dependencies:
mapping table, *figures*

Please let me know what you think until the call next Tuesday.

**Comment by skleinstein** [comment]
Yes, this is what I recall.  -Steve...

**Comment by frubelt** [comment]
I also thought (like Uri) that we will leave it in.  For many people that is the most important part of the sequences and they want to be able to find an see the sequences without any translation- even it is redundant with the other field.

**Comment by BusseChristian** [comment]
Personally I consider `cdr3_aa` redundant and thus would prefer to handle this on the side of the database, not on the side of the minimal standard. I do understand why people would like to include this, but I am not convinced that this will make any perceivable change in real life. My thoughts on this:
1. The information is already present in `cdr3_dna`, so we are talking about a question of encoding.
2. Including `cdr3_aa` will require consistiency checks against `cdr3_dna`. As the DNA -> AA translation is non-ambiguous, this can be avoided by not implementing `cdr3_aa`.
3. I consider it realistic to assume that any AIRR-focused DB can and will simply translate `cdr3_dna`, thereby allowing searches against the peptide sequence. The computational cost for this is minimal.
4. Considering the searchability of the sequences in general purpose databases: Will Google really have an easier time in finding the string "ARYGSSWVSY" when it is marked up in a custom `/note` identifier followed by a `/function:CDR3` tag one line below? Will the result be any different than the string being part of the automated "/translation" of the complete `V_region`?

**Comment by BusseChristian** [comment]
Discussed in today's call. Decision was made to keep cdr3_aa for this version of MiAIRR. Will reconsider once there are AIRR-specific repositories online that will automatically convert the cdr3_dna tag information.
