### ISSUE TITLE
Add geographical location field to biosample

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#91]
We do not have an explicit field to record the geographical location where the sample was collected, do we? I don't see it here https://github.com/airr-community/airr-standards/blob/master/AIRR_Minimal_Standard_Data_Elements.tsv

This seems a relevant information for potential epidemiological studies using AIRR-seq data.

**Comment by lgcowell** [comment]
The BRCs that collect surveillance info have this.  We should probably use their approach for consistency


-------------------------------------------------------------------
Lindsay G. Cowell, PhD
Division of Biomedical Informatics
Department of Clinical Sciences
University of Texas Southwestern Medical Center at Dallas
5323 Harry Hines Blvd.
Dallas, TX  75390-9066

F4.212b, MC9066

phone: 214-648-2289

fax: 214-648-2064
Lindsay.Cowell@utsouthwestern.edu
________________________________

**Comment by ssnn-airr** [comment]
@ahmadchan told me this was already discussed long ago and the decision was to not include 'location' in the minimal standards

**Comment by BusseChristian** [comment]
Yes, we decided that this information is not *minimal*, which does not imply that we would not consider it useful. For the NCBI implementation, you can use the [BioSample attribute](https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/) `geo_loc_name` to annotate this information.
