### ISSUE TITLE
'lab_name' description and example are ambiguous

### ISSUE THREAD

**Issue by ssnn-airr** [airr-community/airr-standards#92]
Description for the field 'lab_name' is 'Department of corresponding author' but the example value is a lab name 'Stibbons Lab'. It is not clear what is expected, if a Department name or a Lab name.

https://github.com/airr-community/airr-standards/blob/master/AIRR_Minimal_Standard_Data_Elements.tsv#L8

**Comment by BusseChristian** [comment]
Sorry, the example value is a bit sloppy, something along the lines of "Dept. of Quantum Immunology" would be more appropriate.

Please note that these field have been bugging us for a while now (#13) and that the issue how to get them into NCBI BioProject is still open (#57).

**Comment by ssnn-airr** [comment]
Is this on the agenda for next call? (ping @ahmadchan ) I have data ready to submit with CAIRR, if we could make a decission on this soon, the would be able to update the data submission templates.

**Comment by bussec** [comment]
Is this this an open issue after we moved to `specs\miairr.yaml`?

**Comment by bussec** [comment]
The description text for `lab_name` was clarified in commit ed4c486, along with other issues regarding submitter/collector information.
