### ISSUE TITLE
API docs and Python API refactor

### ISSUE THREAD

**Issue by javh** [airr-community/airr-standards#95]
A skeleton of the python API docs are now in the `api-docs` branch. As this also requires some configuration changes to the ReadTheDocs site, I've setup a temporary docs build at the old [airr-formats url](http://airr-formats.readthedocs.io/en/api-docs/index.html).

There's still a lot of missing information, especially w.r.t. the metadata methods/arguments, and the TOC needs work, but it's more or less what it will look like. So I'm soliciting feedback. Holler if anything looks wrong.

Also, we currently have both read/write for the TSV and metadata going through the same class (`airr.formats.RearrangementsFile`) with a writable `state` and some metadata arguments, rather than separate reader/writer classes. It'd be a chunk of work to do, but it's probably more clear to have separate reader/writer classes for both (we could drop alot of items from the `Attributes` docs in `airr.formats.RearrangementFile`).

Do we want to restructure at all? If we're going to make any changes to the structure, I think we should decide now so we don't have to rewrite the docs.

**Comment by javh** [comment]
Talked with @schristley a bit and went ahead with the refactor.

1. API docs are now in a finished state.
2. Metadata code remains in the package, but has been removed from the docs and split into a separate class for future work.
3. We could probably move the `definitions.yaml` import into the `formats.RearrangementSchema` class, but that won't impact the docs.

On another note... Is anyone attached to the Alabaster theme? It, most vexingly, won't let me configure the toctree depth for pages and the sidebar separately.  I assume we want a white theme?  Any objections to experimenting with [bootstrap](https://github.com/ryan-roemer/sphinx-bootstrap-theme)?

Updated doc preview is here:
http://airr-formats.readthedocs.io/en/api-docs/index.html

If there are no objections by Thursday, then I'll initiate a PR with the API docs and refactor.

**Comment by BusseChristian** [comment]
> Any objections to experimenting with bootstrap?

Nope. Looks good for me.

**Comment by schristley** [comment]
Looks good. Only question is `external_fields`. Should it be `externalFields` to match the case style of the rest of the code?

**Comment by javh** [comment]
> Looks good. Only question is external_fields. Should it be externalFields to match the case style of the rest of the code?

I just autopiloted `functionName` and `variable_name`, with the `@property` methods  following `variable_name`.

If we want to be [PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) compliant it should be `function_name`.  I feel like we talked about PEP8 at some point, but can't recall what we decided...

**Comment by schristley** [comment]
Okay, if that's what PEP8 specifies then that's good. We have PEP8 listed in our CONTRIBUTING.md

**Comment by javh** [comment]
Ah, okay. Then I need to change the method names.
