### ISSUE TITLE
How do we approach ontologies

### ISSUE THREAD

**Issue by bussec** [airr-community/airr-standards#97]
For finding ontologies for the MiAIRR data items, should we try to do this for all fields in a single concerted action or do we agree on matching ontologies for one/a few fields at a time as the need arises. Typically, I would prefer the concerted way, but right now our group needs an ontology for the `linked_subject` and `link_type` fields and it would be nice I could start to use it before the next annual meeting ;-)

**Comment by schristley** [comment]
@lgcowell might have some comments. The CRWG has a short list of fields for ontology consideration, and it seems like each field needs to be considered separately. I think it's worthwhile to propose an ontology for one/few fields as the needs arises, to help move things along. We need to be confident when we decide because change it later can be costly.

**Comment by bcorrie** [comment]
Agree, identifying low hanging fruit and deciding for those better than trying to resolve all at once. Even deciding what "all" means will probably be too difficult. It would be nice to get some easy ones agreed (e.g. organism???) and out of the way...

**Comment by bussec** [comment]
Ok, so there are currently eight MiAIRR fields that should contain a string coming from a controlled vocabulary (CV), which are all listed in the table below under they AIRR Formats keyword. While there are some that will only hold a very limited set of values, which we can define ourselves (listed as "custom" CV source), there are also those where IMO it would be good to tap into an existing ontology ("external").

I had a closer look at the ontologies offered by BioPortal and found a couple of them that we could use for MiAIRR. In general, I focused on comprehensive ontologies that seem to be actively maintained and have a "Production" state. However, as they are all quite large, the list below contains the top node within the ontology that would contain all the stuff we would need for a given keyword.

BioPortal offers a [REST API](https://data.bioontology.org/documentation), however it does require an API key.

Feedback welcome!

keyword|CV source|ontology|top node|current definition
----|----|----|----|----
study_description|external|NCIT|`Study Design`|https://bioportal.bioontology.org/ontologies/NCIT
organism|external|NCBITAXON|`Gnathostomata`|https://bioportal.bioontology.org/ontologies/NCBITAXON
sex|external|SNOMEDCT|`Finding related to biological sex`|https://bioportal.bioontology.org/ontologies/SNOMEDCT
cell_subset|external|CL|`lymphocyte`|https://bioportal.bioontology.org/ontologies/CL
template_class|custom|n/a|n/a|`/(DNA\|RNA)/`
library_generation_method|custom|n/a|n/a|pending
complete_sequences|custom|n/a|n/a|`/(partial\|complete\|complete+untemplated)/`
physical_linkage|custom|n/a|n/a|pending

**Comment by ahmadchan** [comment]
In addition to, we can constraint the Tissue field with UBERON or BTO (Brenda Tissue Ontology), Disease with DOID (Human Disease ontology). Authenticity and race are defined in NCBITAXON.

**Comment by bussec** [comment]
Thanks @ahmadchan! My two cents:
* Tissue
  * UBERON seems reasonable, but we need a mechanism to split the records onto `tissue` and the `anatomic_site` keywords.
  * BTO looks pretty chaotic to me as they mix tissue, cell types and cell lines...
* Disease: DOID looks good, do we have any comments on this from "real life" MDs?
* Authenticity is not a MiAIRR field
* I could not find a "race" node in NCBITAXON.

**Comment by schristley** [comment]
the AIRR schema has a model for specifying ontology-based fields, which are being used for a few fields now.
